### ISSUE TITLE
what about Linux

### ISSUE THREAD

**Issue by efernbach** [veyon/veyon#1]
I just received an e-mail about the great news that iTalk will be upgraded and improved. When I tried to download the alpha version I found  Windows versions and source code. Will there be a .deb package or do I have to compile myself?

**Comment by tobydox** [comment]
Linux is (and will be) fully supported as well - you can download the source tarball and build Veyon for your distribution. Like before we don't provide any binaries however any efforts to set up build infrastructures  and support auto-builds for various Linux distributions are welcome.
