### ISSUE TITLE
Issue: UNC Screenshot path update.

### ISSUE THREAD

**Issue by PatCahill77** [veyon/veyon#101]
Veyon RC3 3.99.7
Windows 7 x64 Master
Windows 7 & 8.1 Clients

Issue with using a unc path in Configurator - Screenshots
eg Screenshots: "\\server\Veyon$\Screenshots\"
When you open the Screenshot area in Veyon Master, it correctly displays any screenshots in the unc folder.
When you take a screenshot it immediately creates the file in the unc folder, however it does not show in the Veyon Screenshots area until Veyon is closed and reopened.
If you delete a screenshot in the Veyon Screenshots area, it immediately deletes the file from the unc share but it does not update the Veyon Screenshots area until you close and repopen Veyon.

**Comment by tobydox** [comment]
Thanks for reporting! I can reproduce this but unluckily this seems to be an issue within the Qt framework. We're using a filesystem watcher model which updates automatically on changes but obviously it doesn't work with UNC paths. Maybe an optional reload button would be a solution?

**Comment by PatCahill77** [comment]
A refresh button would work especially if the refresh function also fired when you opened the screenshots tab (since I'd guess most people work with it closed).

**Comment by tobydox** [comment]
This has been refactored via 463bc2868bfbde8fa263019bdb070eca95d9ddac and is part of recent Veyon releases.
