### ISSUE TITLE
Can the source be built on OSX?

### ISSUE THREAD

**Issue by jlyle29** [veyon/veyon#102]
[This](http://blog.capterra.com/the-top-free-digital-classroom-management-software-and-classroom-collaboration-tools/) blog entry seems to suggest that Veyon runs on OSX, however your page mentions only Linux and Windows. I just wondered whether it is possible to build Veyon from source on Mac?

**Comment by tobydox** [comment]
OS X is currently not supported, I'm sorry. Building from source will probably fail due to platform-specific code. However we're working on factoring out all platform-specific code into dedicated plugins so one day it will be possible to develop other platform plugins easily :-)

**Comment by tobydox** [comment]
Find news regarding multi-platform support here: http://veyon.io/blog/2018/02/20/platform-abstraction/

**Comment by vintalorian** [comment]
I want to get this 100% clear; now that there is no platform-specific code in the app, is it now possible to build from source on macOS? I realize there's no official support for macOS at this time, but is it now possible? I've seen/heard no updates on this that I can see online, and as an IT head that loves and uses Veyon on a daily basis, I'd really love to see this gain some steam. I have a lab that is considering moving to Macs and I really _really_ don't want to have to find a different program, espeically when most of the only options are proprietary and paid.
