### ISSUE TITLE
Enabling the computer over a network

### ISSUE THREAD

**Issue by mrkaban** [veyon/veyon#104]
Hello, I'm sorry, the topic has already been raised. On the Internet there are articles about the inclusion of computers on the network, and that you need to enable "Wake On Lan" in the BIOS, but I still do not get it.

Please, explain what needs to be done? I have a lot of teachers ask how it can be done?

**Comment by ideamk** [comment]
WOL is not stable. If computer power off and unplug powercable, after plugin cable WOL is not work. If use Windows, in device manager (with admin rights) select you network card, and enable wake on magic packet in Properties.

**Comment by mrkaban** [comment]
I found the "enable wake on magic packet" option, it is almost always enabled by default. In Veyon Configurator entered the MAC address, and tried to turn on the computer, but it did not work. The power cable is naturally connected and networked too. A network cable is a twisted pair with four cores.

Help please understand. Very many teachers ask.

**Comment by Haelito** [comment]
Hello, are the all computers in the same LAN, Master and clients?

**Comment by mrkaban** [comment]
Hello, yes, all the computers in one local network. I'm testing within a home network, three computers. Two fixed computers that are connected by cable. The third computer is a laptop that is connected via wi-fi.

Thanks for the answer. Help or assist please, and that very much many teachers ask.

**Comment by bacsom** [comment]
Try different drivers. Years ago, in my case, changing the default driver to the one from the website of the manufacturer helped.

**Comment by mrkaban** [comment]
I tried with two computers, the first is a regular system unit with the operating system Windows 10 x64, and the second is a laptop with Windows 7 x64. Tried, did not help = (

**Comment by mrkaban** [comment]
Thank you for trying to help! Does anyone have this functionality?

**Comment by tobydox** [comment]
This has been fixed via e675dfc21eaaeee1710bded4504f1b9408cddbf4 and will be fixed in upcoming 4.0.8 release :-)
