### ISSUE TITLE
Remote Control Issues

### ISSUE THREAD

**Issue by rubycrayons** [veyon/veyon#105]
Hi,
I am having trouble when taking remote control of a different computer. On the actual computer everything looks fine, but on the master the mouse is very slow, and will only work in a box small than the screen in the top left corner. Meaning on the master I am unable to click the red 'exit' button on a window, but on the computer being remote controlled I am able to click it, using the mouse from the master computer. any ideas?

**Comment by sbaecker** [comment]
Did you try to set the scaling to 100% in the monitor settings on the controlled computer? I have similar problems with a remote controlled laptop with fullHD display and the scaling set to 150%.

**Comment by tobydox** [comment]
Should be fixed in upcoming 4.0.3 release :-)
