### ISSUE TITLE
Problem with Displayed monitors screen position in Veyon master 4.0.0

### ISSUE THREAD

**Issue by orion777** [veyon/veyon#108]
Hello
I added some computers in Veyon configurator but i can't adjust the monitors position screen in the Veyon master window. Look the capture i send you. Monitors screen are displayed vertically so it's not possible to control all the monitors in the same screen. With Italc all the monitors screen were automatically resized depending the monitor number ans it was horizontally displayed. 
Tested on Windows 10 
Thanks you for your help

![veyon capture](https://user-images.githubusercontent.com/29846901/30455960-16963706-99a2-11e7-8f18-8d813b5bfade.JPG)

**Comment by ideamk** [comment]
![default](https://user-images.githubusercontent.com/7419359/30471106-de425ac8-9a10-11e7-9c50-0c4ac7874b9e.png)
In green square area show current zoom (you zoom is maximum). In red squared area button for fit to window all computers. Use bar for change zoom, and button for fit to screen.

**Comment by orion777** [comment]
Hi,

Thanks you very much for the info. It's ok now.

**Comment by tobydox** [comment]
@ideamk: thanks for helping out!
