### ISSUE TITLE
Master app option to hide not logged in/hide not accessible

### ISSUE THREAD

**Issue by aiwo-kw** [veyon/veyon#109]
It would be very handy to have checkbox(es) or button(s) in Master app for
- hiding computers on which no users are logged on,
- hiding computers not accessible (powered off, not authenticated, no accessible via network)

**Comment by bacsom** [comment]
I think you can do it manually. Just click on computer rooms and uncheck the PCs you don't want to see.

**Comment by tobydox** [comment]
Thank you very much for your suggestions! Unfortunately this does not work with the current implementation as it only tries to connect to computers which are shown in the main area.
