### ISSUE TITLE
LDAP configuration and settings?

### ISSUE THREAD

**Issue by orion777** [veyon/veyon#111]
Hello 

i have only tested the key authentification with Veyon and it works perfectly.
Now i would want to test the authentification LDAP but i don't know how to configure this with Veyon configurator. We are working in a school with samba domain and LDAP authentification for users.
Is it possible to get a screen capture with correct LDAP settings like exemple? 
I would want that screen monitors are automatically authentified in Veyon when students are logged in computers of the classroom.
Is it possible? Thanks you very much for your help

**Comment by tobydox** [comment]
I'm sorry but LDAP can't be used for authentication with Veyon. You can use logon authentication which tries to authenticate the accessing user on the client computers. If your computers are part of a domain, it will work with domain users automatically so there's no need to set up LDAP integration (unless you want to populate computers from LDAP/AD automatically). Comment if you want me to re-open the issue :-)
