### ISSUE TITLE
Even schoolkids bypass Veyon!

### ISSUE THREAD

**Issue by mushketer888** [veyon/veyon#113]
Even schoolkids bypass Veyon!
Even in first lesson schoolkids(13 yo) realize that you can press Power button (power off) then Windows starts to shut down and close applications. They have time to press Cancel so only Veyon is closed.
What to do?

**Comment by tobydox** [comment]
Hi, of course Veyon can't prevent physical access to a computer ;-) However you can enable the option "Enforce selected mode for client computers" in Veyon Configurator which makes Veyon Master enable the selected mode (such as screen lock or fullscreen demo) on reconnect again.

**Comment by Avaryan** [comment]
@tobydox I know of another application that has a secondary service whose only task is to relaunch the primary service in case it crashes, gets closed, etc...

**Comment by dmoorse** [comment]
How can my student avoid veyon seeing his computer even though its connected to the network and how can this be remedied?

**Comment by t3kkm0tt** [comment]
Well, there is something called Veyon antispy on github that simply makes the screen blank for recording etc. also, you could activate the WDAGUtilityAccount and change its password and then use it as a local account with .\WDAGUtilityAccount as username. So no, Veyon isnt really secure.

**Comment by tobydox** [comment]
There will always be ways to bypass software like Veyon, with varying degrees of effort. We cannot offer 100% protection. Ultimately, it must be made clear to students that deliberately circumventing security measures—as well as any other misconduct—will be subject to appropriate disciplinary action.
