### ISSUE TITLE
Current classroom not automatically displayed and checked when starting veyon master on Linuxmint18 xfce

### ISSUE THREAD

**Issue by orion777** [veyon/veyon#114]
Hello

I started installing the veyon master and client on Linuxmint in our school but there is a problem with the veyon master. 
In veyon configurator i checked "automatically switch to current room at start"  and i added the veyon master / teacher computer and enabled the option "hide local computer" but the classroom is no even displayed. I send you the screen capture there
![capture d ecran_2017-09-18_18-24-39](https://user-images.githubusercontent.com/29846901/30566105-f7487c2a-9cca-11e7-9193-edeecac9b014.png)

**Comment by orion777** [comment]
When veyon master is running it is necessary to click the computer rooms tab to display the classroom and then to check the classroom box to get the monitors screen. 
I think the "automatically switch to current room at start" is not working with the Linuxmint veyon master.
Will you fix this issue with updating the current Veyon stable release? Would be great to have this option working with Linuxmint in our school.
Thanks you for you help

**Comment by orion777** [comment]
Hello Tobias,

Any new concerning this issue?

Thanks you again for your help

**Comment by orion777** [comment]
Hello
No news for this issue ?
We have this problem in our schools with veyon on linuxmint , we need your help
Regarde

**Comment by orion777** [comment]
Hello

Did you check this issue on Linuxmint  xfce?
Thanx again

**Comment by tobydox** [comment]
Did you add the IP address or hostname of the master computer to the corresponding room? Try use the opposite type of host address so Veyon identifies your local computer as master computer properly

**Comment by orion777** [comment]
Hello and thanks you very much for your message but i already added the ip adress and hostname of the master computer in veyon-configurator. But the current room  isn't automatically displayed and the master computer isn't hidden.
One of my friend tested with Linuxmint xfce and same problem for him. Something doesn't work with veyon configurator and veyon master with linuxmint xfce.
Hope you will find a solution
Thanx again for your help

**Comment by orion777** [comment]
Hope you will find the fix for this issue.
Regards

**Comment by orion777** [comment]
This is a screenshot showing what i get when i run veyon-master and then clicking on the computer rooms tab

![capture d ecran_2017-09-25_15-54-41](https://user-images.githubusercontent.com/29846901/30812089-31b2b15c-a20a-11e7-8f49-718180e6b68f.png)

**Comment by orion777** [comment]
Here are the informations concerning ip and hostname of the veyon master.
![capture d ecran_2017-09-25_15-58-07](https://user-images.githubusercontent.com/29846901/30812236-85aeb4ae-a20a-11e7-8000-7a4c233d0ee1.png)

**Comment by orion777** [comment]
Here the veyon configurator configuration

![capture d ecran_2017-09-25_16-00-24](https://user-images.githubusercontent.com/29846901/30812304-b7408ef2-a20a-11e7-988d-35181716e875.png)

**Comment by orion777** [comment]
And this is what is displayed when i check the monitors box
The master computer is displayed despite the fact it is checked hidden in the veyon configurator
![capture d ecran_2017-09-25_16-05-32](https://user-images.githubusercontent.com/29846901/30812810-10204e4e-a20c-11e7-9b93-74cf7540ff68.png)

**Comment by tobydox** [comment]
The problem is that Veyon does not recognize one of the computers as the master computer. Does the local computer "Linuxmint" resolve to the IP address 172.16.29.48? Can you enter "Linuxmint" or "linuxmint" instead? Also try to set log level to "Debug" (page "General") and look at VeyonMaster.log? You should then see lines like "excluding local computer via ....", "initializing rooms for host name...." and "initializing rooms for host name....". Please make sure the printed names/IPs match the information you enter in Veyon Configurator.

**Comment by orion777** [comment]
Thanks you i found the solution.
here are the lines in the veyonmaster.log
017-09-25T16:40:57.708: [DEBUG] ComputerManager::initRooms(): initializing rooms for host name "linuxmint"
2017-09-25T16:40:57.708: [DEBUG] ComputerManager::initRooms(): initializing rooms for host name "linuxmint.arenoleau.lan"
2017-09-25T16:40:57.708: [DEBUG] ComputerManager::initRooms(): initializing rooms for host address "127.0.1.1"
2017-09-25T16:40:57.708: [DEBUG] ComputerManager::initRooms(): found local rooms ("")

So i changed the network ip adress with the localhost adress 127.0.0.1 and it works now!
So with the linuxmint master it is not possible to enter the network IP, only the localhost ip?

Thanks you for your help
