### ISSUE TITLE
Veyon service not running when user logout and then login to his session on Linuxmint 18 xfce

### ISSUE THREAD

**Issue by orion777** [veyon/veyon#115]
I noticed this issue on the Linuxmint client. When starting the system and running the loggin session the first time veyon-service is running but then when the session is logging out and login again then the veyon-service isn't running again. This is a big problem because our students just close their session and then another students run a new session.  Note that i enabled veyon-service on autostart session 
Thanks you if you can fix this isssue.
I remember with italc the client was running for each sessions.

**Comment by orion777** [comment]
Any solution concerning this issue?

**Comment by orion777** [comment]
Hello
This is really a problem with our classrooms because veyon-service doesn't run when a session is disconnected and another student is logging on.
Veyon-service works only when the computer is power off and then power on.
Veyon-service command (usr/bin/local/veyon-service) is copied  in autostart session.
Any solution to fix this problem?
Thanks you for your help

**Comment by tobydox** [comment]
In Veyon 4.1 we have full systemd support which should also fix your issue. You can try 4.1 Alpha or wait for 4.1 Beta (recommended). Please re-open the issue if upgrading to 4.1 won't help.
