### ISSUE TITLE
All LDAP integration tests pass but no computer rooms are visible in Veyon Master

### ISSUE THREAD

**Issue by g-kostov** [veyon/veyon#116]
Hi. I'm new to Veyon. I tested it with local data and it works ok. Now I want to use LDAp integration. I configured everything and all Integration test pass successfully but no computer rooms show up in Veyon Master. I tried all possible options (Group, OU, Common attribute) - it's all the same - nothing is visible in Veyon Master. I'm using version 4.0.0. I suppose I'm missing something general, but can't guess what is it?

**Comment by tobydox** [comment]
Did you change the network object directoy backend (page "General") to "LDAP"? This is something most people miss ;-)

**Comment by g-kostov** [comment]
Yep, I really forgot that, but just changed it to LDAP, applied config, restarted master and "Computer Rooms" is still empty in Master...

**Comment by tobydox** [comment]
Thanks for reporting back!
