### ISSUE TITLE
Leap 42.2 rpm not connecting

### ISSUE THREAD

**Issue by vincentvije** [veyon/veyon#118]
Hello Tobias,

In the same time I try to compile from source and correct some QCA problem in another thread, I write you here the problem I have with your Leap 42.2 rpm.

I just saw you release the version 4 of Veyon.
And you wrote you corrected the problems with Qt5.5 and the lag when locking/unlocking screen.

I spent some time to try to make work Veyon 4.0.0 with your Opensuse Leap 42.2 rmp on Leap 42.2 :

    Master : Windows 10
    Client : Opensuse Leap 42.2 with your rpm

I tried all possibilities, really. No way.
It worked in june with version 3.99.7 I compiled (but with the lock screen very big lag).
I tried my certificates that worked in june (I actived only the auth with certificates, and replicated the certificates in both client and master, with the good paths.)
I tried new certificates.
I tried auth with logon, or with certificates.
I installed a new fresh Leap 42.2.
But now way to connect.

Here is the "loop error" a have with old or new certificates, or logon, when I start veyon-service on the Leap client and then veyon master on windows 10 :
![ciceonbcjgidaopc](https://user-images.githubusercontent.com/15954198/30686587-0c779bfe-9eb9-11e7-91c6-df0196939e3a.png)

And I get this error :
![afooeanldacoddho](https://user-images.githubusercontent.com/15954198/30686580-0520f9ae-9eb9-11e7-8584-94493b2a3a30.png)

I hope you can help.
Thanks in advance,

Vincent

**Comment by vincentvije** [comment]
This issue could be closed saying : The Leap 42.2 rpm doesn't work... better upgrade to Leap 42.3 or install Tumbleweed.

**Comment by tobydox** [comment]
Did you set  log levels to debug on both sides and found some further information? Especially VeyonMaster.log would be interesting.

**Comment by vincentvije** [comment]
Thanks Tobias,

I will try that asap.

But I decided to switch to Tumbleweed.
The problem with Leap 42.2 if compiling Veyon is that it need some dependencies that I cannot satify (more than 700 to upgrade to gcc6) without breaking older software...
So, now that 42.3 is out, and Tumbleweed that seems to be working well, it's better to upgrade.

Maybe your rpm has some dependencies that my system do not satisfay.

About the logs, I try asap some further test. But now my tests computer is with Tumbleweed.
Veyon work like a charm with it and your recent modification.

Thanks again for Veyon !
Kind regards,
Vincent

**Comment by tobydox** [comment]
Is this still an issue?

**Comment by vincentvije** [comment]
Hello Tobias,
For the version of the rpm that generated this issue, 4.0.0, no, then 
you can close this issue.
For the beta of the 4.1 you just added few days ago, I will report 
directly to you when I try it. I hope to do it this week.
Thanks a lot.
Kind regards,
Vincent

**Comment by tobydox** [comment]
Thanks for the feedback!
