### ISSUE TITLE
Lock / Unlock do not work, and freeze the client forever, Monitoring do not work.

### ISSUE THREAD

**Issue by vincentvije** [veyon/veyon#119]
Hello Tobias,

I installed Veyon on a fresh Tumbleweed.
It compiles and install fine.
On the Tumbleweed Client, the service start fine.

On the W10 master, I can see the screen, but when I whant to monitor (Remote View), a popup ask me the IP, it's not the way it should work.

WORSE : when I click "Lock", the Tumbleweed Client freeze (and don't show the Lock image).
Just say "Running worker for feature "Lock", and stay frozen.
When I click Unlock, it remain frozen some minutes !

So Veyon can't be used for monitoring nor for locking screen...

Thanks for your work.
I hope all these can be fixed soon.

Kind regards,
Vincent

**Comment by vincentvije** [comment]
I add I used this file : veyon-4.0.0-src.tar.bz2
More tests : Client takes some minutes (maybe 3 min) to show locked screen, and some minutes to unlock.
I confirm, Monitoring ask for IP, it's of no use.

**Comment by vincentvije** [comment]
Tobias,
In the release log, you said you solved the lag problem, but it's far worse.
And Monitoring is broken.
Please, do you plan a working solution ?
Thanks for your work,
Best regards,
Vincent

**Comment by vincentvije** [comment]
Tobias,

The computer I used hed some problem with it's graphic card.

NEVERTHELESS :
I made the same test in a fresh new computer with a fresh install of Tumbleweed.
There is always the lag of about 12 to 15 seconds on both lock and unlock.

Then, nothing is solved with the lock / unlock lag since june with version 3.99.6.
You said in the release note og 3.99.7 that it was solved, but it seems not.

Please Tobias, sorry to insist but do you think you can solve this ?

Thanks in advance.
Kind regards,

Vincent

**Comment by vincentvije** [comment]
Please Tobias, do you think you forgot to apply the correction about the lag to 4.0.0 ?

**Comment by tobydox** [comment]
I got a report about this problem on opensuse from another user. However this seems to be opensuse-specific where xmodmap makes some problems and/or takes very long time to execute. I currently do not know a better approach, I'm sorry :-(

**Comment by tobydox** [comment]
Seems to be a known problem: https://unix.stackexchange.com/questions/94336/xmodmap-hanging-the-system-for-20-secs-and-not-sticking

**Comment by tobydox** [comment]
Maybe we can call XChangeKeyboardMapping directly and skip using xmodmap.

**Comment by vincentvije** [comment]
Hello Tobias,

Thanks a lot !
I checked your link.
I'm not good at programming.
If you can try to make the change in the code, in github, or in a source tar that you send me by email, I can make the test and say you if it solved.

I will use the 3rd party software of your tar.bz2.

Thanks again for Veyon.

Kind regards,
Vincent
