### ISSUE TITLE
Can't upgrade Veyon 4.0.0 to Veyon 4.0.1 by cloning git repository on Linuxmint

### ISSUE THREAD

**Issue by orion777** [veyon/veyon#120]
Hello again

I tried to upgrade veyon 4.0.0 to veyon 4.0.1by cloning the Git repository and fetching all submodules with the command 
git clone https://github.com/veyon/veyon.git
cd veyon
git submodule update --init      
and then cmake .. and make install as usually, but it doesn't work, when i run veyon-configurator it is noted veyon 4.0.0-21and same thing for veyon master.
It worked fine when i upgraded from Veyon 4 RC3 to veyon 4.0.0
Thanks again for your help

**Comment by orion777** [comment]
Any info about this?

**Comment by tobydox** [comment]
Please do a fresh clone and build and you should have a proper 4.0.1 installation. It's definitely working :-) I also recommend using the precompiled binaries so you don't have to worry about building Veyon manually every time.

**Comment by orion777** [comment]
Hello

I installed the veyon_4.0.1-ubuntu-xenial_amd64.deb but same problem, it didn't upgrade the compiled installation i did with veyon 4.0.0 using the clone and build.
When i run the veyon master or veyon configurator it is not displayed veyon 4.0.1 but veyon 4.0.0 with linux mint.
