### ISSUE TITLE
Not displaying classroom

### ISSUE THREAD

**Issue by Avaryan** [veyon/veyon#121]
I'm 100% sure this is because I have it configured wrong.

When I log into the master client the only thing I can see is my own computer. When I go to add a classroom it treats each individual computer as it's own classroom.

I don't have anything entered under Advanced settings --> Filter for computer containers

objectClass=container or objectClass=organizationalUnit don't work for me.

**Comment by Avaryan** [comment]
Each classroom is in its own OU. I have added my laptop to that OU for testing.

**Comment by tobydox** [comment]
Can you please add screenshots of your LDAP configuration?

**Comment by Avaryan** [comment]
![image](https://user-images.githubusercontent.com/1270366/30815444-3ab998a2-a1e1-11e7-9491-152cfeab5adf.png)

**Comment by Avaryan** [comment]
Is there anything specific that you need?

**Comment by Avaryan** [comment]
I added "name" to Computer room name attribute. After adding that I was able to add objectClass=organizationalUnit to the computer containers filter.

Application takes a long time to load after authenticating and is very laggy, often not responsive.

**Comment by Avaryan** [comment]
Corrected the issue as described in previous post. Closing issue.
