### ISSUE TITLE
Mouse cursor is movable/visible in Fullscreen demo

### ISSUE THREAD

**Issue by teotwawki16** [veyon/veyon#122]
I'm not sure if I did something wrong but if the master computer entered Fullscreen demo, client computers can use the mouse and move the cursor around (but can do nothing).

The keyboard is disabled, though. But the description says:
"In this mode your screen is being displayed in fullscreen mode on all computers while **input devices** of the users are locked."

Locking the client computers doesn't show the mouse cursor. And I want Fullscreen demo to be like that, too.

**Comment by tobydox** [comment]
Which version are you using? This should be fixed in 4.0.1.

**Comment by teotwawki16** [comment]
Ohh. Thanks. Will update now. Should I install directly or uninstall the older version first?

**Comment by tobydox** [comment]
You can perform an in-place upgrade. Don't forget to reboot clients afterwards.

**Comment by teotwawki16** [comment]
Alright! Thanks a lot!

**Comment by teotwawki16** [comment]
I've already tried it and it works! But is there any workaround to hide the clients' mouse cursor?
