### ISSUE TITLE
How to reduce latency when we take control of a computer ?

### ISSUE THREAD

**Issue by tech62** [veyon/veyon#123]
Can we reduce the time of refresh to render more smoothly when we take control of a computer ?

**Comment by SilveryGod** [comment]
I think that using external UVNC instead of using the integrated one help

**Comment by tobydox** [comment]
In Veyon 4.1 Alpha there are improvements to the VNC server - feel free to check it out or wait for 4.1 Beta. Besides that there's no solution I can provide here, I'm sorry...
