### ISSUE TITLE
Inconsistent Classrooms 

### ISSUE THREAD

**Issue by Avaryan** [veyon/veyon#124]
Hello,

I now believe I have my classroom settings correct. Most of the time, when I open Veyon, it opens the correct classroom. Occasionally it will open OU's higher up. Most recently it opened the entire domain group with about 3,000 computers in it into one window (talk about lag).

Example:
Domain Computers ---> High School --> Room 100
Instead of opening Room 100 it will occasionally open the entire High School or even entire Domain Computers OU (this includes several other schools) and show ALL of the objects inside. 

Not only is this extremely laggy, but it's a security issue as we can't have people outside the designated teachers station viewing other classrooms.

**Comment by trevelyanuk** [comment]
I'm noticing this too. I can't figure out what the reason would be other than that, in my situation, it appears to be "third level" room within an OU hierarchy.

**Comment by Avaryan** [comment]
@tobydox Any thoughts?

**Comment by Avaryan** [comment]
Updated to 4.0.2. Same issue.

Example:
My PC is located here in AD.
Domain --> High School --> HS IT

When I open Veyon Master it's taking me to:
Domain --> High School

And it's showing me everything in the High School, and all sub OU's within HS.

**Comment by trevelyanuk** [comment]
How are the OUs named?

The problem I had was like this:

Only able to see PCs in the room you're in
Don't show empty OUs
Filter for |(A0*)(B0*)
Computer room attribute based on OU

- Computers
  - A001
     - A001Desktops
     - A001Servers
  - B001
  - B002


A PC in B001 will not see a PC in B002 and vice versa.
A PC in A001Servers will only see A001Servers the first time Veyon loads
But a PC in A001Servers will see ALL PCs in A001Servers, A001Desktops and A001. 

It seems - in our case - as though the first instance of a filter match is taken to be a positive "this is the room you're in", or perhaps that's only the case if it is populated with PCs.

I'll dig in the code if I get a chance and see if I can figure out where this all happens. I've been wanting to get involved but just haven't had the time yet!

**Comment by Avaryan** [comment]
Closing issue. No longer using this product.
