### ISSUE TITLE
No Full/Window-Demo with Linux Master and Windows Client

### ISSUE THREAD

**Issue by lebowski42** [veyon/veyon#125]
Hi,
i've an ubuntu 16.04 computer with veyon master and a computer with Windows 7 an veyon client. Everything works fine, except window and fullscreen demo. I append the error report created with veyon-configurator

> {

    "Configuration": {
        "AccessControl": {
            "AccessRestrictedToUserGroups": "false",
            "AuthorizedUserGroups": null
        },
        "Authentication": {
            "KeyAuthenticationEnabled": "false",
            "LogonAuthenticationEnabled": "true",
            "PrivateKeyBaseDir": "$GLOBALAPPDATA/keys/private",
            "PublicKeyBaseDir": "$GLOBALAPPDATA/keys/public"
        },
        "Demo": {
            "FramebufferUpdateInterval": "100",
            "KeyFrameInterval": "10",
            "MemoryLimit": "128"
        },
        "Directories": {
            "Screenshots": "$APPDATA/Screenshots",
            "UserConfiguration": "$APPDATA/Config"
        },
        "ExternalVncServer": {
            "ServerPort": "5900"
        },
        "LDAP": {
            "ServerPort": "389"
        },
        "LocalData": {
            "NetworkObjects": {
                "JsonStoreArray": [
                    {
                        "Name": "Lernwerkstatt",
                        "Type": 2,
                        "Uid": "{e09140cd-3fe3-4946-9333-01412dc0d143}"
                    },
                    {
                        "HostAddress": "10.0.2.96",
                        "Name": "static46",
                        "ParentUid": "{e09140cd-3fe3-4946-9333-01412dc0d143}",
                        "Type": 3,
                        "Uid": "{4cb0187e-368c-4915-801c-2ef9baab1bda}"
                    },
                    {
                        "HostAddress": "10.0.2.95",
                        "Name": "static45",
                        "ParentUid": "{e09140cd-3fe3-4946-9333-01412dc0d143}",
                        "Type": 3,
                        "Uid": "{883fad83-8521-425d-ba99-3bf2339743a3}"
                    }
                ]
            }
        },
        "Logging": {
            "LogFileDirectory": "$TEMP",
            "LogFileRotationCount": "10",
            "LogFileRotationEnabled": "false",
            "LogFileSizeLimit": "100",
            "LogFileSizeLimitEnabled": "false",
            "LogLevel": 5,
            "LogToStdErr": "true",
            "LogToWindowsEventLog": "false"
        },
        "Master": {
            "AccessControlForMasterEnabled": "false",
            "ManualRoomAdditionAllowed": "true",
            "OnlyCurrentRoomVisible": "true",
            "OpenComputerManagementAtStart": "false"
        },
        "Network": {
            "DemoServerPort": "11400",
            "FeatureWorkerManagerPort": "11300",
            "FirewallExceptionEnabled": "true",
            "PrimaryServicePort": "11100",
            "VncServerPort": "11200"
        },
        "NetworkObjectDirectory": {
            "UpdateInterval": "60"
        },
        "Service": {
            "Arguments": "",
            "Autostart": "true",
            "HideTrayIcon": "false",
            "SoftwareSASEnabled": "true"
        },
        "UI": {
            "ApplicationName": "",
            "EnableHighDPIScaling": "false",
            "Language": ""
        },
        "VncServer": {
            "Plugin": "{67dfc1c1-8f37-4539-a298-16e74e34fd8b}"
        }
    },
    "General": {
        "BuildType": "x86_64",
        "MachineInfo": "Linux static30.intern 4.10.0-33-generic #37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux",
        "OS": "Linux\nDISTRIB_ID=Ubuntu\nDISTRIB_RELEASE=16.04\nDISTRIB_CODENAME=xenial\nDISTRIB_DESCRIPTION=\"Ubuntu 16.04.3 LTS\"",
        "Version": "3.99.7-38-g0f5657f"
    },
    "LogFiles": {
        "VeyonConfigurator": "AAAB8niclY/BSsNAEIbvPsXQk4LdJtsmaffW2goqVGlFD9LDJjtJ1qY7YXcr+mKevPXF3IqIFg8KAzMM3///MzyKs2406vL0Ns5EnAg+ZGk6EPAwWyxWcEWm1NXWSq/JgNFF7cEVtUWd59KCgKl0MJHFGo2CcvdmQWmEhtaywQNxLT1UuMFGoT8FJZ37YH9LyPFbhnaewUR7j/uAsDawDDoV+h2+BM3ZlwNZ2GgP9e61xj13Y/WTbrDSYZZbx474z28zwTOWZFn49mJ+fr2Ccduy2TMWByCPRBwx3v8LmAzZIIkCeD9ezFdw6cgsw2EoRENSHZ8IKGjbKDDkgdpwWKdniXxvim7tqe1VZR2KPQZd59Cdi2TEeNL/v7vCDX16vgOEgJ5r"
    }
}

**Comment by tobydox** [comment]
Thank you for your bug report! Can you please first update both sides to the latest version? Which host address is shown on the client computer after starting a demo? Is it an IPv6 address?

**Comment by lebowski42** [comment]
Problem still exists after updating.

Is an IPv4 adress
