### ISSUE TITLE
Sorting of Clients on Master

### ISSUE THREAD

**Issue by SimonSchmittMecadat** [veyon/veyon#126]
Hi,

is there still a possibility to sort the clients (shown as displays) in the master app?
We are missing this nice feature, which was available in iTalc.

Thank you very much in advance.
Best regards.

Simon Schmitt

**Comment by bacsom** [comment]
We are also missing this feature. It is a huge time saver to be able to arrange the small screens in the way how the real computers are placed in the classroom.

**Comment by SlrG** [comment]
Our school is missing this feature desperately, too. Without it, I can't fully migrate to veyon. But I follow the development closely and am very happy about the constant fixes and improvements happening at the moment. :+1:

**Comment by fenixconnektion** [comment]
I have to chime in here and agree with everyone above.  Our classrooms don't have arranged seating so the ability to shuffle the screens to match the actual seating layout would be a real help and time saver.  Please add this functionality back to the master app!

**Comment by cheshireshane** [comment]
As with all above comments, I too am having the same issue. An update would be most helpful.

**Comment by tobydox** [comment]
Veyon 4.1 Alpha will be released next week which will support freely arrangeable computers :-)

**Comment by patdu59** [comment]
Hi !
Can you tell us where we can download alpha or beta versions please ?
Thanks :)

**Comment by tobydox** [comment]
Next week at the official download page.

**Comment by patdu59** [comment]
OK :)
Thanks 👍

**Comment by tobydox** [comment]
The master branch now contains support for custom computer placements. The new implementation provides a better usability compared to iTALC. You can now switch between custom placements and the auto-sorted placement so you don't lose your computer placement when switching between the two modes.

If you build Veyon from source, you can already try it. All other users will have to stay patient for 1-2 more days ;-)

**Comment by shanequinn001** [comment]
Hi i was wondering if i am missing something but i do see there are custom computer placements but i still don't see an ability to sort by logged in computer which iTalc used to have and was extremely useful?
thanks in advance for your help
S

**Comment by tobydox** [comment]
@shanequinn001 The computer sort order is fully configurable in Veyon 4.2 and newer: https://docs.veyon.io/en/latest/admin/reference.html#basic-settings
