### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by SRANTECH** [veyon/veyon#129]
Hello I am new to using veyon it is a great product thank you and I was wondering from what I have seen of the code and the program so far the student computers are able to broadcast their screen to the teacher and also the opposite. I was wondering would it be possible for a chrome extension to broadcast images of their screen? I was able to build two basic chrome extensions for sending and receiving images to and from the two extensions so I am hopping that veyon would be able to support chromebooks in the future as we have a lot of chromebooks and your app is perfect for the classroom.

**Comment by richardsenior1986** [comment]
Here, here.  Please, can we have Chromebook support?

**Comment by tobydox** [comment]
We don't have chromebook support ATM, I'm sorry. It might come with Veyon 5 in 2019, stay tuned!

**Comment by pjkool** [comment]
https://github.com/veyon/veyon/wiki/Roadmap
Sorry this is not on roadmap, so this is deprecated?
