### ISSUE TITLE
Can I add computers only with MAC address, for DHCP case?

### ISSUE THREAD

**Issue by aguadopd** [veyon/veyon#131]
Is it possible to avoid using an IP for each computer defined in a room, and just use the MAC address?

**Comment by Avaryan** [comment]
Not sure about MAC, but Hostname is what I previously used (with iTalc). Now using LDAP.

**Comment by tobydox** [comment]
Unfortunately this is not possible. Try to use hostnames as suggested by Avaryan ;-)
