### ISSUE TITLE
Make monitored screens refresh faster?

### ISSUE THREAD

**Issue by ghost** [veyon/veyon#132]
When in the Monitoring section of Veyon Master it shows the screens of the client computers. But for me the client screens refresh too slowly (~8 second delay). Is it possible to make it faster, or live? Thanks

**Comment by o71** [comment]
Hello,

I would also like to be able to reduce the refresh time. With Italc it was possible to reduce it enormously. 

![image](https://user-images.githubusercontent.com/2280629/31650272-def33f86-b316-11e7-9cc2-492fed54c818.png)


Thank you very much.

**Comment by tobydox** [comment]
In Veyon 4.1 you can configure the update interval in Veyon Configurator (+substantial improvements regarding the refresh rate). Feel free to checkout Veyon 4.1 Alpha or newer.
