### ISSUE TITLE
IDE?

### ISSUE THREAD

**Issue by matteke-games** [veyon/veyon#133]
Hi,

I wanted to contribute to this awesome project but when reading through the files it seemed like a qt creator project to me. But it doesnt have project files, only the cmake files. So I was wondering if you officially support an IDE or not?

Thanks

**Comment by tobydox** [comment]
Thanks for your interest in Veyon development! I use Qt Creator all the time and use the builtin CMake support. On Windows you'll have to obtain the required external libraries and put them into the Qt environment.

**Comment by matteke-games** [comment]
Okay, thank you :)
