### ISSUE TITLE
Continuous Screen Duplicate

### ISSUE THREAD

**Issue by ngajugodwin** [veyon/veyon#136]
Please, i notice that whenever i connect to a system and when viewing the system remotely, the screen flickers and make a continuous duplicates of the screen.

How do i resolve this please??

**Comment by tobydox** [comment]
Does this happen inside the remote control window or locally at the remote controlled computer? Try to alter the VNC server settings on the client, i.e. disable capturing of layered windows.

**Comment by tobydox** [comment]
Closing due to missing feedback. Please respond if you have new information.
