### ISSUE TITLE
Computer Lock doesn't work with windows 10

### ISSUE THREAD

**Issue by tyaoning** [veyon/veyon#138]
I am using window 10 Enterprise 1073 version. When I lock the student PC from the master. Student computer display the lock screen but all keys are working, the student can use windows key to call start menu, use Alt+Tab to switch program, or call Ctrl+Alt+Del.

Another suggestion, when we do demo, can we lock the student PC at same time, or make this as an option?

Thanks for your great project.

**Comment by tobydox** [comment]
With Veyon 4.0.7 this should work. If not, please respond and re-open the issue.
