### ISSUE TITLE
Feature Request: Enable/Disable Internet connection button

### ISSUE THREAD

**Issue by karamazov451** [veyon/veyon#139]
Hi,
Is it possible to create a feature where you can disable & enable the students' internet connection, either by disabling the network adapter or changing the proxy settings? Thanks

**Comment by bacsom** [comment]
On Windows we use Microsoft FamilySafety feature for this. It has whitelist/blacklist option as well. To have all this built in would be a great idea though!

**Comment by Treeek** [comment]
What you could do is to step up the proxy global variable to a unused port.
And then roll back, to the older state.

**Comment by Treeek** [comment]
By disabling the network adapter you are also terminating the connection with the rest of the network, including veyon itself

**Comment by tobydox** [comment]
There's ongoing work to provide a plugin with this functionality, stay tuned :-)

**Comment by tobydox** [comment]
The requested functionality is implemented in the commercial Internet Access Control add-on - see https://veyon.io/en/addons/ for details :-)
