### ISSUE TITLE
Fullscreen/Window Demo Not Working

### ISSUE THREAD

**Issue by ArtChick** [veyon/veyon#141]
My school's IT admin just installed Veyon in our computer lab. Every feature is working except for the Fullscreen/Window demo. When we try to run it we get this message: "Establishing connection to : :ffff : 10.55.11.177...;  And then it just stalls there. We have Version 4.0.1.

**Comment by joacliba** [comment]
It's happening the same in my case. I use ubuntu for all the computers (clients and master) and I can't use the demo feature. I tried changing ports, configuring another VNC server but without luck.

**Comment by oleg153** [comment]
The same is for me - "Every feature is working except for the Fullscreen/Window demo". Both master and client computers are Win7 x64.  Veyon is of version 4.0.1 x64. 

Is there any hope for correcting this bug? This pretty software is almost useless without demo feature.

**Comment by petrost8** [comment]
I had the same problem.
So, I put the MAC addresses of the clients at Veyon Configurator -> Rooms & Computers and somehow it stopped. But it still occurs sometimes, especially when I move my mouse and change windows immediately after I hit the Fullscreen/Window demo. So, after I press the demo, I wait for all the clients to connect and then I begin my demonstration

**Comment by joacliba** [comment]
I tried to add the MAC addresses without luck. It keeps on "Establishing connection to : :ffff : X.X.X.X".

**Comment by tobydox** [comment]
Fixed via 98ee19f1cd6f58e483b90eb7543d03ed133343a4

**Comment by stephanvaningen** [comment]
I see no connection between 98ee19f and this.

I have here a Veyon-installation, all clients (with public key) are Ubuntu/Linux, all Masters using the private key are Windows 10: same issue.
If I - within the same constellation - create a Linux Master with that private key: there the demo server works...
Windows 10: does not seem to be a Firewall-issue: same situation when Firewall in Windows is completely shut down.

telnet to Windows' 11100 produces the expected result as described in the documentation (RFB 003.008 response), telnet to 11400 gives no connection.
