### ISSUE TITLE
LDAP + "Computer in the same room" option don't work

### ISSUE THREAD

**Issue by ebugnet** [veyon/veyon#143]
Hi,
I test again Veyon with LDAP config.
I made advanced rules for authentification.

When a teacher user on master start veyon he can see student screens.
If I add the "computer in the same room" option on student client : teacher can't view his screen.
I got "can't authenticate on computer" (something like this).

All this computers are in the same OU of my AD LDAP, and I use OU classroom type.

Perhaps it's linked to this issue : [issue 130](https://github.com/veyon/veyon/issues/130).
I can avoid this issue by specifing my complete room OU in config file : it works, but not ideal.

If you got an idea...
Éric

**Comment by tobydox** [comment]
Could you solve this problem in the meantime?

**Comment by ebugnet** [comment]
Hi, I tested it.
Now on 4.7 it works !
Thanks.
Éric
