### ISSUE TITLE
See students computers from netwoek

### ISSUE THREAD

**Issue by fran-m** [veyon/veyon#145]
Hi,
How can I see all the students computers on my network authomatically?
Thanks

**Comment by jamj2000** [comment]
Hello, first you must use veyon-configurator for registering those computers

**Comment by fran-m** [comment]
Is not possible that veyon scans the network to find computers? As epoptes does for example.

**Comment by jamj2000** [comment]
I think that functionallity is not available. It may be a proposal for next releases.

**Comment by tobydox** [comment]
You either have to add computers manually or setup LDAP/ActiveDirectory integration so computer information are retrieved from your network directory. There's currently no scan method even though it would be possible to provide such a functionality as a plugin - any development contributions are welcome ;-)
