### ISSUE TITLE
Having trouble downloading Veyon

### ISSUE THREAD

**Issue by mbeauregard71** [veyon/veyon#147]
I am new to Github but Veyon seems like a great program. I am having trouble getting the installer to run. I am running windows 10 if that helps. Any assistance would be much appreciated thanks!

**Comment by jamj2000** [comment]
What does it really means "having trouble getting the installer to run"?

**Comment by mbeauregard71** [comment]
I downloaded the Win64bit setup file, Ran it and get this message: 
![capture](https://user-images.githubusercontent.com/32493823/31495737-ba97669c-af26-11e7-8eec-91f1afb0ed2b.PNG)

**Comment by tobydox** [comment]
Did you run the installer as administrator? Do you have a previous version of Veyon running? If so, stop all Veyon applications before.

**Comment by mbeauregard71** [comment]
Running as an admin worked Thank you so much... Do you guys know how I would add the computers in the lab to my view? thanks again for your help.

**Comment by Galforg** [comment]
@mbeauregard71 Depends on what config you want going. Veyon can be done in two ways, AD/LDAP or Auth Keys.
Details on how to get it working are found here:
https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=http%3A%2F%2Fdocs.veyon.io%2Fde%2Flatest%2Fuser%2Findex.html

**Comment by tobydox** [comment]
I'm closing this now due to inactivity. Feel free to join our community forum if you still have questions regarding the installation and setup of Veyon.
