### ISSUE TITLE
Connecting to client computers 

### ISSUE THREAD

**Issue by mbeauregard71** [veyon/veyon#148]
I am having trouble connecting the Client computers to my computers. Do I need to download the program on all of them or do I download something else? thanks for your help

**Comment by farmeunit** [comment]
Same program for both.  When running it, just deselect Master option.

**Comment by tobydox** [comment]
Please follow our trouble shooting guide at https://docs.veyon.io/en/latest/admin/troubleshooting.html - feel free to join our community forum if you still have questions or problems.
