### ISSUE TITLE
AD computers appear but no rooms

### ISSUE THREAD

**Issue by fr0d0scious** [veyon/veyon#149]
I'm struggling to add computers. Server 2012 AD Domain.

When I select "add room" a list of computers appears and I can't open them.

The examples in the selection boxes in the configuration utility aren't helping. I could do with some guidance.

My OU structure:

Domain
> Computers
>>Rooms
>>>Room 1
>>>>Computer name
>>>Room 2
>>>>Computer name
>Users
>>Pupils
>>>Year group
>>>>Pupil name

**Comment by fr0d0scious** [comment]
Domain
>Users
>>Year group
>>>Pupil name

**Comment by mnurulfahmi** [comment]
i managed to configure veyon with ldap.

- this is my veyon config, at environment tab:
![veyon config](https://user-images.githubusercontent.com/24728620/31599099-1c8dddb6-b27b-11e7-8323-04c34fbe0ecf.png)

- this is my AD structure:
![untitled](https://user-images.githubusercontent.com/24728620/31599006-c18b7cf2-b27a-11e7-8ded-e0d2dec450f4.png)

- this is the result:
![master](https://user-images.githubusercontent.com/24728620/31599205-90c0e78c-b27b-11e7-8839-6199b0a4e0b8.png)

**Comment by fr0d0scious** [comment]
That fixed it! Many thanks
