### ISSUE TITLE
Teacher is the only available role for key authentication

### ISSUE THREAD

**Issue by hunterd** [veyon/veyon#150]
When I try to create a new authentication keypair the only available role in the dropdown is "Teacher"
Even when I try to create by command line it's impossible : 
`"E:\Program Files\Veyon\veyon-configurator.exe" -CreateKeypair "E:\Program Files\Veyon\keys" -role "admin"`
This creates "teacher" folders in "E:\Program Files\Veyon\keys\public" and "E:\Program Files\Veyon\keys\private"
I'm using Veyon 4.0.1 x64 on Windows 7 Pro x64

**Comment by tobydox** [comment]
I'm sorry but we dropped support for multiple roles in Veyon in favour of access control rules. Please try to make use of this feature which allows to you configure computer access permissions in a very detailled manner.

**Comment by hunterd** [comment]
I see. I'll try access control rules then. Thank you for your answer.
