### ISSUE TITLE
big ldap issues

### ISSUE THREAD

**Issue by Pat-iut** [veyon/veyon#151]
Hi,

Great job on Veyon.
Testing worked fine but production environment is a complete failure for me. Using ldap authentification is so slow that either Veyon crash or it never respond.
I have 77 000 users and more than 2400 groups in our ldap ... as soon as i have enough time i'll send you more technical details but network activity is HUGE to and from our ldap server.
Each teacher or student may be member of up to 40 groups
i don't and won't store computers and rooms in ldap, is it what slow down Veyon ?

Can you please optimise ldap access (when computer are not stored on ldap) ?
To simplify, just chek on the admin station if the user belongs to a group that can launch the dashboard et retrieve the names of the students on each station ?
I'd like to avoid key athentication to have the name of the students on the dashboard.

I may not be "crystal clear", i'll be more specific in my next post

Thx for all

**Comment by tobydox** [comment]
Thanks for your feedback! That's indeed a huge environment and I didn't have the chance to test Veyon in such an environment. You can of course omit LDAP/AD integration and add computers manually. You can also use domain users without LDAP/AD integration as logon authentication does not rely on it.
