### ISSUE TITLE
Feature request : remove client popups

### ISSUE THREAD

**Issue by johne5s** [veyon/veyon#152]
I work for a school, with 6 computer labs.  I've installed Veyon in 1 lab for testing it out before rolling it out to all labs.
I'm getting reports that the client computer gets a popup.  I personally have never seen it.  They tell me that it says "username is now monitoring this computer".  something along that line.  I've only seen the "username tried to monitor but the authentication failed".

So my request is to have an option to suppress these messages via the configurator.

Thank you for this great program.

**Comment by tobydox** [comment]
Thank you for your bug report! Veyon only reports about failed authentication attempts. There's definitely no such message "is now monitoring this computer" - this has to be a special feature of a 3rdparty solution. In case this is still an issue please try to get more information on this issue such as log file entries and screenshots.
