### ISSUE TITLE
Mouse stop working!

### ISSUE THREAD

**Issue by knapper** [veyon/veyon#154]
Hi. I hope anyone can help me.

We installed Veyon version 3.99 on student and manager computer to test it, but after a while the mouse stop working, it's just the mouse, because keyboard works fine, and if we switch the mouse for another one, is keep the same problem, so we have to restart the computer, and everything goes normal.

The thing is we wait for a new version and install it (last version is 4.0.1) and it is the same. 

I think probably there is a problem with the remote control service... i'm not sure. 

Thanks for your help.

**Comment by alsho** [comment]
Hello everybody!

I have the same issue here. Sometimes, mouse & keyboard stop working, but with remote control its possible to access and control the terminal, and restart it. After restart system, all inputs working fine.

I don't know what provoke it, I have does a lot of tests to try to make this issue again, but unsuccessful.

@knapper When it occour again, try to open the veyon configuration and restart the service (stop and start) and reply us here if was solved (temporarily), if it occour again here to me I'll do it to see the reaction too.

Good lucky~

**Comment by tobydox** [comment]
Does it still happen with 4.0.7? Can you also try 4.1 alpha?

**Comment by dxdemetriou** [comment]
It's happening with 4.1.1 too, I had a whole room with unable to start PS2 Keyboard & USB Mouse, and I had to uninstall Veyon & reboot for fixing it. This happens during boot loader from boot logo (in BIOS everything is OK).
![screenshot from 2018-08-23 16-13-15](https://user-images.githubusercontent.com/41939421/44527455-86936000-a6ef-11e8-9019-a4c5877d27e8.png)

**Comment by tobydox** [comment]
When using Veyon in remote desktop server environments, it's recommended to enable multi session mode on Windows which will automatically uninstall the Interception driver. It's also possible to disable the Interception driver usage in the Veyon Configurator, so it doesn't get installed automatically on boot.
