### ISSUE TITLE
Mac OS X build? Not an issue

### ISSUE THREAD

**Issue by olesolo** [veyon/veyon#155]
I would be grateful if anyone could share a build for a OS X 10.7+? Thanks

**Comment by tobydox** [comment]
Unfortunately OS X is currently not supported. This might change after Veyon 4.1 (where we plan to separate all remaining platform-specific code into platform plugins) if someone writes a platform plugin for OS X.

**Comment by fritzlim** [comment]
I would like a MacOS version too.

Our school currently uses Windows laptops, but we'll be using MacBooks soon when we teach iOS app development.

**Comment by Lrobben52** [comment]
Don't forget the android version for the tablets.

**Comment by tobydox** [comment]
Find news regarding multi-platform support here: http://veyon.io/blog/2018/02/20/platform-abstraction/

**Comment by olesolo** [comment]
Great news! Can't wait to see 4.1 version. When do you plan to make a
release?

2018-02-21 12:35 GMT+02:00 Tobias Junghans <notifications@github.com>:

**Comment by tobydox** [comment]
Please note that 4.1 will *not* have macOS support - we just laid the foundation for possible future implementations. Feel free to invite developers who are familiar with macOS to join the Veyon project :-)
