### ISSUE TITLE
questionning ldap rights for users

### ISSUE THREAD

**Issue by stevy44** [veyon/veyon#157]
Hi,
i have last version of veyon (4.0.1), i use ldap integration, login authentification and Access control with Allow authenticated user access. I have one concern about the users rights.
If i log with a domain admin, i have access to class room and i can add anothers class or computers.
But if i log with a teacher (a user domain), there is no computers, and nothing to add.
Is that normal ?

**Comment by tobydox** [comment]
There's a difference between LDAP credentials and those used for authenticating for accessing computers. For LDAP to work you have to enter credentials of a user who is allowed to read all objects. For accessing computers you have to login with a user who is allowed to access the computer depending on your access control settings (these settings have to be made on both master and client computers!).
