### ISSUE TITLE
TWO teacher computers

### ISSUE THREAD

**Issue by cceegg** [veyon/veyon#158]
I have two computers "Teacher" and I need to be able to be Manager in both, is this possible ?, I have not found documentation and options to be able to do it.

**Comment by farmeunit** [comment]
In older version (iTalc), you could just make a second master, but copy the key from the 1st.  Not sure it's possible in this version.

**Comment by Galforg** [comment]
It is possible, I have done this for 3 teacher stations. How to do it though is completely dependent on what kind of setup you have going (if you're using Keys or AD/LDAP).

We have set our system up by using Auth Keys to avoid the security issue with AD/LDAP config files. You need to have one teacher PC to generate the Public and Private key sets then you simply copy the Private key and put it on the second teacher PC, that allows both of the teacher stations to manage the Veyon network.

**Comment by farmeunit** [comment]
I tried this using keys, but it just showed the machines that I tried on in red and wouldn't monitor them.  I set the back to use logon authentication, the issue is a normal teacher doesn't have access to the Logon Authtentication, so kind of stuck.  I tried disabling both and I got error about the keys.

Not sure exactly what I'm doing wrong.  I exported the keys to a network drive, then copied them over the workstations.  I'll try again later this week when I have more time.

**Comment by Galforg** [comment]
If you're having issues about teachers having issues with signing in using LDAP then it may be a config issue that is causing an issue with communication with your AD server, we've had many issues with implementing LDAP successfully so you're not alone.

If keys authentication isn't working then I'd advise to completely reset your config and do it again from the ground up (that includes creating a new public key). In order for you to see computers using key authentication you will have to manually add PCs using IP/MAC addresses into the configurator, this can be a little time consuming depending on how many PCs you have but we don't have that many, plus if you make IP reservations for the PCs in DHCP then its a one-time configuration that you hopefully wont have to do again.

Here are some screenshots of the config I have which may be of some help, this is the one we're using to get key authentication working.

https://user-images.githubusercontent.com/33317331/32727328-1a1387c0-c874-11e7-9ad1-71a24f863cad.PNG

https://user-images.githubusercontent.com/33317331/32727329-1a269cb6-c874-11e7-923c-83d42f842ae9.PNG

https://user-images.githubusercontent.com/33317331/32727330-1a38c8dc-c874-11e7-8864-111a64ef3dc6.PNG

https://user-images.githubusercontent.com/33317331/32727331-1a4a7ef6-c874-11e7-9385-1c85a96bad01.PNG

https://user-images.githubusercontent.com/33317331/32727332-1a692018-c874-11e7-836c-a1c450ef17a7.PNG

https://user-images.githubusercontent.com/33317331/32727333-1a7b24f2-c874-11e7-816e-e66e847b6983.PNG

https://user-images.githubusercontent.com/33317331/32727334-1a9aabc4-c874-11e7-8773-2b9826fbc063.PNG

**Comment by tobydox** [comment]
@farmeunit please proceed as described by @Galforg ;-) Copying the private key (or the whole keys directory at all) from one master computer to the other one is the solution in your case.
