### ISSUE TITLE
Authentication Failed / Access Denied

### ISSUE THREAD

**Issue by 02nielzkie** [veyon/veyon#159]
How come that i encounter this error on 2 PC while i successfully configure the 10 other pc with the same procedure please help me 
![image](https://user-images.githubusercontent.com/33147069/32092789-8547d3c0-bb2c-11e7-8902-0f29768987b9.png)
![veyon error](https://user-images.githubusercontent.com/33147069/32092811-9b4d3a2a-bb2c-11e7-9130-0a4ae51c0ac6.jpg)

**Comment by 02nielzkie** [comment]
![image](https://user-images.githubusercontent.com/33147069/32095089-7910a08e-bb34-11e7-9490-17ec3e4c4a18.png)
This is the computer i trying to access

**Comment by tobydox** [comment]
That's strange! Did you manage to fix the issue?

**Comment by 02nielzkie** [comment]
Yeah u recreate new master key and import it to all 50 pc

**Comment by tobydox** [comment]
Is this still an issue? Can you try with 4.1 Alpha?

**Comment by matydelomas** [comment]
Hello

I was using version 4.0.7.0 and everything worked perfect.

update all the PCs to version 4.1.7.1 and in several the authentication error occurred. I can not solve. Please help!
![veyon 1111](https://user-images.githubusercontent.com/47567509/52645756-28864f00-2ec0-11e9-813a-13b2ab744732.JPG)

**Comment by tobydox** [comment]
All we can recommend here is to update to the latest Veyon releases since they have many bugs fixed. If you still encounter isues, please follow the troubleshooting guide at https://docs.veyon.io/en/latest/admin/troubleshooting.html
