### ISSUE TITLE
 New project, as a suggestion.

### ISSUE THREAD

**Issue by MS-PC** [veyon/veyon#160]
I ask you with all due respect if you can create a Software to time control in PC or Cyber ​​Cafe, since in "Latin America" ​​we use in our Cyber ​​Café premises.

"I ask you since you are a great Programmer". : )

I ask you since all the time control software on PC or Cyber ​​Café in "Latin America" ​​has a very high cost.

For my part, I could only contribute with the translation if I would accept it.

**Comment by tobydox** [comment]
Thank you very much for sharing your idea! It definitely would be possible to write a plugin for Veyon which accomplishes some kind of time control and/or time accounting for both master and client computers. However our developer ressources are very limited and unless there's a volunteer for this task, I don't know how to realize this.
