### ISSUE TITLE
Can't use monitoring

### ISSUE THREAD

**Issue by Jschroeder146** [veyon/veyon#163]
I am able to use "lock" and "open website," but I cannot see the students' monitors. When I select "monitoring," nothing happens. When I try to share my screen with the clients, the clients keep saying connecting, but never display the master screen. How can I resolve this so I can monitor clients' screens and share the master screen?

![image](https://user-images.githubusercontent.com/33193477/32142057-884244d2-bca0-11e7-81d7-fbe84b11bb08.png)

**Comment by royvs33** [comment]
It helped for me to use the zoom bar (right bottom) and move it a tiny bit, this problem only seems to occur on first use. This could be a bug

**Comment by Jschroeder146** [comment]
Great! That worked perfectly for monitoring client computers! Thank you very much!

However, I still cannot get the Fullscreen Demo or Window Demo to work. When I try to share my screen, the client computers turn black and only say "Establishing connection to..."
