### ISSUE TITLE
Duplicated Clients from Multiple Classrooms

### ISSUE THREAD

**Issue by lincdeckard** [veyon/veyon#165]
Hello,
My AD config goes as follows:

6 classrooms with around 15 machines each. 
12 different users: one for each room (student) and one for each room (teacher) so, every student on room 1, logs in with the same account. I'm using logon auth and default data backend. (AD/LDAP isn't working/can't find machines/configure for AD machine discovering)

I've tried creating the user lists for local data network object management with and without MAC addresses included, for purposes of WOL (which isn't working correctly either/successful WOL happens randomly but fails almost everytime).

A lot of times, as shown in the picture, Clients from a certain room get shown/duplicated in another room, even though they have a unique name and IP address. Every computer in the classrooms has a unique AD name and DHCP enabled. 
It gets even more confusing if students by mistake log onto one classroom machine with an account from another room. As shown in the picture, a student from room 2 logging on as a student from room 3 on that machine appears on my admin veyon duplicated on both rooms, even though the logged account should not interfere. As an admin, my veyon master client should be monitoring machines by their unique ID on the network, not the account that is logged on those machines. 
This leads to another problem which is me not being able to actually access through veyon to the machine that is being duplicated over. For example: If the Room 2 computer 3 gets duplicated and starts showing the preview from a computer on Room 3 (happens regularly) I cannot access that particular computer on room 3 because It will remote control the machine on Room 2. 

![capture](https://user-images.githubusercontent.com/31446430/32223891-20461b86-be37-11e7-8adb-0085397ad5f8.PNG)

Anyone having similar issues? Any suggestions?

Cheers,
Carlos

**Comment by lincdeckard** [comment]
bumping this thread... 

Anyone having similar issues? 

![capture](https://user-images.githubusercontent.com/31446430/37458257-6837fdb4-283c-11e8-962c-0f7c2cd35894.PNG)

On the picture, a desktop from a a computer on room 3 being shown on a listing from room 2. 
Again, this presents an issue also because If I do a global action on a room and there is a computer from another room showing up on the list instead, it will also be affected. 

Since I'm using host names on the config and even MAC addresses for each machine as shown in the picture below, it seems that Veyon is using some other method to identify the machines, one that eventually changes on the server unlike the host name or MAC address.

![capture2](https://user-images.githubusercontent.com/31446430/37458434-f27664fc-283c-11e8-8220-c6f81b898c8b.PNG)

scratching my head here...

**Comment by tobydox** [comment]
Issue should be fixed in v4.1.1 - please try as soon as it is released. If the problem still persists, please check that each object has a unique ID via the CLI tool:

``
veyon-ctl networkobjects dump
``

Tell me if you need more help on this.
