### ISSUE TITLE
Cannot Share Screen (neither Fullscreen Demo nor Window Demo)

### ISSUE THREAD

**Issue by Jschroeder146** [veyon/veyon#166]
I have been able to get everything else to work, but am unable to share my screen with client computers. When I select Fullscreen Demo or Window Demo, the screen on the client computer turns black and says "Establishing connection to :: ffff;192.168... [IP address]." 

How can I get this to work?

![image](https://user-images.githubusercontent.com/33193477/32234516-1633da0c-be6e-11e7-8b58-89629ac82b1a.png)

**Comment by joacliba** [comment]
This, theoretically is fixed in 4.0.2 but I'm still getting the black screen on linux with that version. The only difference is that now, the message is "Establishing connection to 192.168.X.X" , without the :ffff:

**Comment by tobydox** [comment]
It should work in 4.0.2 - can you try to disable the firewall at the master computer and make sure, the demo server port is configured the same on both master and client computers? Can you "telnet <mastercomputer> 11400" on the client computer while a demo is running?

**Comment by joacliba** [comment]
I'm on ubuntu and I don't have an active firewall. Both master and client are configured at 11400 port.

I can't telnet the teacher's computer:

![veyon](https://user-images.githubusercontent.com/4459078/32391195-765a1ee0-c0d1-11e7-8641-c809c44b7c37.png)

I wasn't sure about the command so I tried telnet ip port and telnet 11400 when the demo was trying to connect.

**Comment by joacliba** [comment]
@jaucay I tried in a controlled network and I can't get it working. I tried both at my home and with virtualbox internal network and in all cases I've all functions working except the demo mode. I also tried to change to other ports like 8080 but it was impossible.

**Comment by jaucay** [comment]
@joacliba Sorry for the late reply. If you can, please post the IP addresses with their subnet masks of your master and client computers. I need a bit more information about the controlled network so I can get ideas of what might be causing your problem. Is the target client computers connected wirelessly? Do you use Layer 3 (such as routers and certain switches) devices to subdivide your production network?

**Comment by joacliba** [comment]
Hi @jaucay, don't worry! I'm very grateful for your help.

To avoid problems in the high school network I'm trying to get it working at home. This is the info you asked:

The network on the teacher computer:
enp0s3    Link encap:Ethernet  direcciónHW 08:00:27:7b:00:00b
          Direc. inet:**192.168.1.116**  Difus.:192.168.1.255  Másc:**255.255.255.0**
          Dirección inet6: fe80::487b:e889:92bd:a276/64 Alcance:Enlace
          ACTIVO DIFUSIÓN FUNCIONANDO MULTICAST  MTU:1500  Métrica:1
          Paquetes RX:8583 errores:0 perdidos:0 overruns:0 frame:0
          Paquetes TX:2142 errores:0 perdidos:0 overruns:0 carrier:0
          colisiones:0 long.colaTX:1000 
          Bytes RX:11742556 (11.7 MB)  TX bytes:174307 (174.3 KB)

On student computer:
enp0s3    Link encap:Ethernet  direcciónHW 08:00:27:90:00:61  
          Direc. inet:**192.168.1.117**  Difus.:192.168.1.255  Másc:**255.255.255.0**
          Dirección inet6: fe80::d41d:776f:7008:19c4/64 Alcance:Enlace
          ACTIVO DIFUSIÓN FUNCIONANDO MULTICAST  MTU:1500  Métrica:1
          Paquetes RX:5234 errores:0 perdidos:0 overruns:0 frame:0
          Paquetes TX:3982 errores:0 perdidos:0 overruns:0 carrier:0
          colisiones:0 long.colaTX:1000 
          Bytes RX:6281970 (6.2 MB)  TX bytes:5085374 (5.0 MB)

I have one router (it is from my ISP), but it hasn't any particular 

![image](https://user-images.githubusercontent.com/4459078/33314733-d6681a9c-d42e-11e7-839a-bc92ac23f87a.png)

**Comment by slm1977** [comment]
I had the same problem, but .... I had forgotten to start the veyon service "master side" ! If the veyon service is not running on the master PC, all the clients (slave) PCs cannot access to the master PC...

**Comment by joacliba** [comment]
@slm1977 thank you so much! That is the solution, start "veyon-service" before start the master.

**Comment by Jschroeder146** [comment]
Thank you for your time. However, it still is not working on my computer. The master computer says "state: running" in the service section of the configurator, but the demo doesn't work. Is there something else that needs to be done to start veyon-service?

**Comment by slm1977** [comment]
It depends. Can you access to remote clients from veyon-master?

**Comment by Jschroeder146** [comment]
Yes. I'm able to control clients with the master through the remote option

**Comment by slm1977** [comment]
I'm using veyon on ubuntu platform and I have to start the veyon service with sudo privileges. So I put the command "sudo veyon-service" instead of "veyon-service".

**Comment by Jschroeder146** [comment]
Where do you type that command in? Do you open "run" and type it there?

**Comment by slm1977** [comment]
On Ubuntu, I open a shell (the terminal application) and then put the command 
**sudo veyon-service**

**Comment by slm1977** [comment]
Then I open an other tab in the shell (ctrl+shift+t) and I start the veyon-master by typing
**veyon-master**

without "sudo"

**Comment by Jschroeder146** [comment]
I just have the regular windows platform, so don't know if I'm able to do that without Ubuntu

**Comment by marceldocarmo** [comment]
I was able to fix the problem by turning off the antivirus.

**Comment by tobydox** [comment]
Thanks for reporting back! I'm glad it works for you now!
