### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by cental63** [veyon/veyon#167]
it would be nice if could be possible make live tests to students (with score), and choose the students that you want to involve.

**Comment by tobydox** [comment]
Thanks for your input. The suggestion has been added to https://github.com/veyon/veyon/wiki/Brainstorming

**Comment by JasMich** [comment]
Couldn't you use third-party tools like Moodle (https://moodle.org/) or TestApp (https://testapp.ga/). In our school, we're using both.
