### ISSUE TITLE
Change Background Color

### ISSUE THREAD

**Issue by STaylorY** [veyon/veyon#169]
Is there a way to change the background color? On the screen that shows all of the student computer thumbnails the background is white. Since students are usually on pages that have white backgrounds it makes it difficult to see the where a screen ends and another begins. Is there a way to change the background color to a light gray? If so, how?

**Comment by tobydox** [comment]
This is currently not possible but shouldn't be too hard to implement :-)

**Comment by Lrobben52** [comment]
It would be nice if somebody explaining how to do this. Thank you.

**Comment by tobydox** [comment]
As of Veyon 4.0.3 you can set the (currently undocumented) property "BackgroundColor" in UserConfig.json (user-specific configuration file of Veyon Master) to whatever color you like, e.g. "#cccccc".
