### ISSUE TITLE
Permission problem on the client side.

### ISSUE THREAD

**Issue by Lrobben52** [veyon/veyon#17]
Hi Tobias,

I was trying your nice new monitoring system, but i have a little problem.
The problem is when i want to insert the public key, generated on the teacher-pc,, into a student-PC a window opens with the message: i don't have the permission to read the key or write permission to the folder C:\ProgramData\Veyon\Keys\ ....  on the student-PC.
Sorry for the pic, it's in dutch.
Also when i want to generate new keys in the teacher-PC after the first time. I need to delete the folder in C:\ProgramData\Veyon\.... Only then i can generate new keys.

![capture](https://cloud.githubusercontent.com/assets/25714742/26522702/9328b610-4306-11e7-86bf-2b199419c17d.JPG)

**Comment by onlurking** [comment]
@tobydox can you reopen this issue please? I was getting the same error but i found the problem.
The installer doesn't create the ```C:\ProgramData\Veyon\Keys\``` folder automatically, so it doesn't work out of box writing the imported public key there (```%GLOBALAPPDATA%```), you need to change the path where the keys will be written or create this folder manually, i will try to write an PR for the NSIS installer.

**Comment by Lrobben52** [comment]
This is correct "onlurking". I fixed the problem (in windows) also by coping the ProgramData folder and keys  manually from the master PC to the client PC's. If I try to insert the key with the Veyon Configurator, I get the error message above. I found the solution from the Linux install docs. When you install Veyon in Linux you have to copy it also manually. After that Veyon works.
