### ISSUE TITLE
Variable names for folders and folder redirection

### ISSUE THREAD

**Issue by trevelyanuk** [veyon/veyon#170]
How are variable names used by Veyon? Haven't been able to entirely figure it. For example, I would expect %HOMESHARE to have gone to my user's home folder. This is (for us) a redirected folder- and i'm not sure Veyon likes that. 

Anyway, the issue is that (specifically for the screenshots location) this variable seems to expand to (%HOME)SHARE. An example of that is C:/Users/OliverSHARE - which obviously then errors. I want it to be \\fileserver\home$\oliver - which should be %HOMESHARE% on the system.

A way around that is to use an absolutely path, or drive map, but thought I'd leave this here

**Comment by tobydox** [comment]
You can find a table in our (currently only German) manual at https://veyon.readthedocs.io/de/latest/admin/reference.html#platzhaltervariablen-fur-dateipfade - the examples should be easy to recognize. Alternatively use Google Translator ;-)
