### ISSUE TITLE
Multiple rooms with the same name

### ISSUE THREAD

**Issue by trevelyanuk** [veyon/veyon#171]
Its not a nice OU structure, and we are changing it for other reasons, but here's a situation:

Computer room is based on CN
Computer room filter is for (R*)
Only display the room the PC is in

- Computers
  - Learning
     - Room101
  - Admin
     - Room101

Room101, within Admin, will not have their PCs displayed. If there are no PCs in the Learning version of Room101, then there will be no room at all show for it. Veyon stops after it finds the OU that matches the room the PC is in, it seems, rather than matching it to the full tree.

**Comment by mondo28** [comment]
Also have the same situation on my site. We can have multiple sites where they may all have the same IT Suite name. once it finds one, it ignores the rest. is there a way of splitting them into their correct OU's, so it can then show these different machines.

**Comment by tobydox** [comment]
Multi-hierarchy support is still not implemented but requested frequently. As this requires major changes to the code base this will be lots of work so we need somebody who sponsors the development.

**Comment by tobydox** [comment]
Multi-hierarchy support is provided by the LDAP Pro add-on.
