### ISSUE TITLE
ERROR ON COMPILE RASPBERRY PI 3

### ISSUE THREAD

**Issue by pauloboc** [veyon/veyon#174]
cmake ..
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- Found Git: /usr/bin/git (found version "2.1.4") 
Can't identify target host. Assuming 32 bit platform.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test VEYON_HAVE_TLS
-- Performing Test VEYON_HAVE_TLS - Success
-- Looking for include file arpa/inet.h
-- Looking for include file arpa/inet.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file fcntl.h
-- Looking for include file fcntl.h - found
-- Looking for include file limits.h
-- Looking for include file limits.h - found
-- Looking for include file memory.h
-- Looking for include file memory.h - found
-- Looking for include file netdb.h
-- Looking for include file netdb.h - found
-- Looking for include file netinet/in.h
-- Looking for include file netinet/in.h - found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file stdbool.h
-- Looking for include file stdbool.h - found
-- Looking for include file string.h
-- Looking for include file string.h - found
-- Looking for include file strings.h
-- Looking for include file strings.h - found
-- Looking for include file sys/ioctl.h
-- Looking for include file sys/ioctl.h - found
-- Looking for include file sys/socket.h
-- Looking for include file sys/socket.h - found
-- Looking for include file sys/time.h
-- Looking for include file sys/time.h - found
-- Looking for include file sys/timeb.h
-- Looking for include file sys/timeb.h - found
-- Looking for include file sys/stat.h
-- Looking for include file sys/stat.h - found
-- Looking for include file syslog.h
-- Looking for include file syslog.h - found
-- Looking for include file pwd.h
-- Looking for include file pwd.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Looking for include file utmpx.h
-- Looking for include file utmpx.h - found
-- Looking for include file sys/wait.h
-- Looking for include file sys/wait.h - found
-- Looking for include file time.h
-- Looking for include file time.h - found
-- Looking for include file errno.h
-- Looking for include file errno.h - found
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for include file sys/ipc.h
-- Looking for include file sys/ipc.h - found
-- Looking for include file sys/shm.h
-- Looking for include file sys/shm.h - found
-- Looking for include file stdarg.h
-- Looking for include file stdarg.h - found
-- Looking for include file signal.h
-- Looking for include file signal.h - found
-- Looking for include file ctype.h
-- Looking for include file ctype.h - found
-- Looking for include file process.h
-- Looking for include file process.h - not found
-- Looking for include file dlfcn.h
-- Looking for include file dlfcn.h - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file vfork.h
-- Looking for include file vfork.h - not found
-- Looking for include file linux/fb.h
-- Looking for include file linux/fb.h - found
-- Looking for include file linux/input.h
-- Looking for include file linux/input.h - found
-- Looking for include file linux/uinput.h
-- Looking for include file linux/uinput.h - found
-- Looking for include file linux/videodev.h
-- Looking for include file linux/videodev.h - not found
-- Looking for include file linux/videodev2.h
-- Looking for include file linux/videodev2.h - found
-- Looking for include file ws2tcpip.h
-- Looking for include file ws2tcpip.h - not found
-- Performing Test PAM_MESSAGE_CONST
-- Performing Test PAM_MESSAGE_CONST - Success
-- Found PAM: /usr/lib/arm-linux-gnueabihf/libpam.so;/usr/lib/arm-linux-gnueabihf/libdl.so
-- Looking for dup2
-- Looking for dup2 - found
-- Looking for floor
-- Looking for floor - found
-- Looking for ftime
-- Looking for ftime - found
-- Looking for geteuid
-- Looking for geteuid - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for gethostname
-- Looking for gethostname - found
-- Looking for getpwnam
-- Looking for getpwnam - found
-- Looking for getpwuid
-- Looking for getpwuid - found
-- Looking for getspnam
-- Looking for getspnam - found
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Looking for getuid
-- Looking for getuid - found
-- Looking for grantpt
-- Looking for grantpt - found
-- Looking for inet_ntoa
-- Looking for inet_ntoa - found
-- Looking for initgroups
-- Looking for initgroups - found
-- Looking for memcmp
-- Looking for memcmp - found
-- Looking for memcpy
-- Looking for memcpy - found
-- Looking for memmove
-- Looking for memmove - found
-- Looking for memset
-- Looking for memset - found
-- Looking for mkfifo
-- Looking for mkfifo - found
-- Looking for mmap
-- Looking for mmap - found
-- Looking for fork
-- Looking for fork - found
-- Looking for pow
-- Looking for pow - found
-- Looking for putenv
-- Looking for putenv - found
-- Looking for select
-- Looking for select - found
-- Looking for seteuid
-- Looking for seteuid - found
-- Looking for setpgrp
-- Looking for setpgrp - found
-- Looking for setsid
-- Looking for setsid - found
-- Looking for setutxent
-- Looking for setutxent - found
-- Looking for socket
-- Looking for socket - found
-- Looking for strchr
-- Looking for strchr - found
-- Looking for strdup
-- Looking for strdup - found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for strpbrk
-- Looking for strpbrk - found
-- Looking for strrchr
-- Looking for strrchr - found
-- Looking for strstr
-- Looking for strstr - found
-- Looking for uname
-- Looking for uname - found
-- Looking for waitpid
-- Looking for waitpid - found
-- Found ZLIB: /usr/lib/arm-linux-gnueabihf/libz.so (found version "1.2.8") 
CMake Error at /usr/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.6/Modules/FindJPEG.cmake:42 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:154 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/home/pi/veyon/build/CMakeFiles/CMakeOutput.log".
See also "/home/pi/veyon/build/CMakeFiles/CMakeError.log".

?

**Comment by tobydox** [comment]
Please follow the steps as described in https://github.com/veyon/veyon#installing-dependencies - you'll also likely need to update your system. Veyon requires at least GCC 5 as well as Qt >= 5.5.

**Comment by jamj2000** [comment]
It seems you don't have installed libjpeg library for development or it can't be found.

Install libjpeg-dev or similar.
