### ISSUE TITLE
Lock Screen now able to be interupted.

### ISSUE THREAD

**Issue by Drickman** [veyon/veyon#175]
Hi, I have noticed that in the new build, when screen locked, the kids can press the windows button and the start bar appears and they can run things again. also ctrl, alt and delete now allows them to log off and then log back on again, now unlocked. 
thanks very much.

D. Rickman

**Comment by musaa2015** [comment]
I have noticed this issue as well. The students can also unlock their screen by simply using the ALT+F4 shortcut. This can be fixed if the user input (both keyboard and mouse) is blocked.

**Comment by coolforit** [comment]
Hi All,  I very much want to update to 4.0.2 (from 2.02) on my Windows 7 lab. Yet first I want to make sure that look screen can't be disabled as mentioned by comments above.  But I am not clear, can I fix issue when I set up program by blocking user input?  Or must I wait until issue is fixed?  And no, I don't have programming experience.  Thanks.

**Comment by musaa2015** [comment]
It seems like you have to wait until it's fixed. I couldn't find a way to fix it in the program settings.

**Comment by wdrcomputers** [comment]
Hi Everyone,
I have just discovered the same issue as everyone else above.  The Lock Screen works fine in version 3.99.7 but not in 4.0.2.  Does anyone know if there is a version in between that has the group permission stuff fixed (Comma's in Names problem) but still has the lock screen working properly? Also being new to GitHub, Is it possible to still access older compiled versions if a version does exist that addresses both of the above issues?
Cheers
Warren

**Comment by coolforit** [comment]
Hi Warren, sorry not sure about which is the best working version where the Lock Screen can't easily be defeated...  

Any idea if I install 4.0.2 on my 30 lab machines now, is it hard to upgrade to the fixed 4.0.x version later?  Would one simply reinstall new version over old, or would all the computer host names (or IP addresses or whatever is currently being used) need to be reentered again?

**Comment by wdrcomputers** [comment]
Hi coolforit,
The Rooms/Computers configuration is saved in a JSON string in the HKLM key of the registry.  I have changed a few machines from 3.99.7 to 4.0.2 both by running setup and installing over the top and also by un-installing old version and re-installing new version and in both instances, the Rooms/Computers and all other setting have remained intact.  Which make me think that the registry settings are being left intact during this process.  Having said that I'm currently having problems with the veyon configurator not displaying after some machines have been taken from 3.99.7 to 4.0.2.  I don't know if this is a problem with the upgrade process or some other problem.  I'm yet to put a handle on what causes this. My gut feeling is some file/s are being written to a folder other than Program Files\Vennon and these are not upgrading properly when 4.0.2 is being installed. But I really have no idea what is causing it.  All I know is that the configurator process is there in task manager but doesn't display on the screen and it just continues to take more and more memory.  I read a post somewhere else that said the configurator did eventually appear after 30 min or so.

**Comment by tobydox** [comment]
Can you please try to install Veyon 4.0.2 and afterwards download https://github.com/oblitum/Interception/releases/download/1.0.0/Interception.zip and extract "install-interception.exe" and run it at the command line with the install switch:

`
install-interception /install
`

This installs an older version of the input device interception library which has been used in previous versions of Veyon. Don't forget to reboot after installing! I'd like to know whether the update to Interception 1.0.1 broke the screen lock for some of you and if so we can ship version 1.0.0 with next Veyon release.

**Comment by Drickman** [comment]
Hi,
I can confirm that once I installed the interception you sent, the machine lock worked as advertised.
Thank you so much for addressing this problem.

David.

**Comment by wdrcomputers** [comment]
Yes, this also worked for me. Thank you very much for your quick response to this issue. I and I'm sure many other Veyon/Italc users can't thank you enough for this great project you created and made available through open source.
NB There was an error message after the interception installer finished asking the question, did the program install correctly, if not do you want to retry using other settings (Not the exact wording but I'm sure you know the message I'm talking about).  But it did fix the problem with the lock screen being bypassed.
Toby, do you mind if I share this file and information with my colleges in the Dept of Education in NSW Australia, as we have a substantial Yammer thread running at the moment on the current issues that we are having with installing Veyon in the detnsw environment. 
Cheers
Warren
PS: I love the new send keystroke feature,  If you could customise this menu with the addition of some custom registry keys in a Veyon Key in HKCU I think I you will have created the ultimate remote management somewhere available today.

**Comment by tobydox** [comment]
@Drickman: I'm glad it works now! After looking at our version history it's likely not the version of the Interception driver which makes the difference as we updated to 1.0.1 before Veyon 3.99.7. It must be some kind of installation issue. Can you verify that screen lock still works if you first uninstall 1.0.0 (install-interception /uninstall) and install 1.0.1 manually (https://github.com/oblitum/Interception/releases/download/v1.0.1/Interception.zip)?

@wdrcomputers Your notes also makes me think that there's rather an installation problem with Interception than a version problem. We'll investigate :-) You can of course share these information with your colleges.

Regarding keyboard shortcuts: I added your suggestion to our [Roadmap](https://github.com/veyon/veyon/wiki/Roadmap) for 4.1. However I can't promise there are sufficient developer ressources to get this ready for 4.1. You can of course prioritize this via donations ;-)

**Comment by tobydox** [comment]
Predefined key strokes didn't make it into 4.1, I'm sorry. Besides that I consider the original issue as resolved. If not, feel free to respond or re-open.
