### ISSUE TITLE
Feature Request: Import Computers list from CSV

### ISSUE THREAD

**Issue by xElementzx** [veyon/veyon#177]
Hey,

We've just added 150 Computers to our veyon, we were wondering if it is possible to add a feature that we can import them from CSV or any other file like this, or if this is already implemented how do we do this?

**Comment by tobydox** [comment]
Thanks for your input! This will be part of Veyon 4.1.x - see https://github.com/veyon/veyon/wiki/Roadmap for more information.

**Comment by Didu2000** [comment]
Hello!
I am also looking forward to this feature.
The year 2019 has already begun ... Is it possible to hope for the appearance of imports this year?
