### ISSUE TITLE
Remote Connection Setup - Home Study

### ISSUE THREAD

**Issue by bturcan** [veyon/veyon#178]
Hi, i am glad that i found veyon. its cool. I have one question. How can i add a user pc which is not in same network. There are 3 computers in in other building and thoose in different network behind a router.

**Comment by nrstanick0421** [comment]
I have the same problem.

**Comment by bturcan** [comment]
will anybody explain how can i do that?

**Comment by tobydox** [comment]
You can only access computers which are directly accessible and addressable directed TCP/IP connections. Computers behind routers won't work unless you set up some kind of port forwarding (e.g ROUTER:11101 -> HOST1:11100) and add the respective ports to hostname entries in the Veyon Configurator (e.g. ROUTERIP:11101).
