### ISSUE TITLE
Missing Dependency libpng12-0

### ISSUE THREAD

**Issue by alexriedl** [veyon/veyon#183]
Installation Fails on Kubuntu 17.10 because of a missing dependency "libpng12-0". 

It appears libpng12 is no longer supported on Ubuntu and the version that is available in the official repos is libpng16

**Comment by tobydox** [comment]
Thanks for this information, we'll provide dedicated packages for 17.10 with the next release.

**Comment by tobydox** [comment]
Preparation via 7c7ca0a238835b5ceb7c7051f03b7df5549ffd78
