### ISSUE TITLE
System and programs freezing when another program is launching while veyon master is running on Windows 10

### ISSUE THREAD

**Issue by orion777** [veyon/veyon#186]
Hello

It is a big problem in our classroom : on the veyon master computer, while veyon master is running with veyon windows clients,  teacher can't work on another programs. When they launch a web browser or another program like libreoffice, system is freezing, it is not possible to use other programs, mouse clisck doess't respond well and veyon master screen is bugging. We can't do nothing.
But when we close the opened programs and just keep veyon master running then all is ok and veyon master is ok.
Is it a problem with VNC or screen displaying ?
We can't use veyon master on windows 10 normallly whith this problem.
Thanks you for you help

**Comment by orion777** [comment]
Is there something to change in the veyon configurator options? or is ti a problem to fix in veyon master?

**Comment by tobydox** [comment]
Does the problem disappear if you stop the Veyon Service while keeping Veyon Master open?

**Comment by orion777** [comment]
Yes when i stop the veyon service the problem seems to disapear.
Can i disable the veyon service on the veyon master computer? Hope it won't create another problem with the veyon master functions.
Thanks you for your help 
Regards

**Comment by tobydox** [comment]
Please try again with Veyon 4.0.3 as we have a fix in the VNC server.

**Comment by brunovila** [comment]
It sill hapens also with Veyon 4.0.3. If you open LibreOffice or Google Chrome, you cannot move windows/maximize/minimize

**Comment by tobydox** [comment]
Closing as outdated and discussed in more recent issues.
