### ISSUE TITLE
Feature Request Chromebook Support

### ISSUE THREAD

**Issue by SRANTECH** [veyon/veyon#187]
Hello I was wondering is veyon going to be implementing chromebook support or could I try and give it a shot to add chromebook support to the code? With a custom extension to go along with it. Thank You

**Comment by tobydox** [comment]
Hi, there are currently no plans for supporting Chromebooks however we're actively working on moving all platform-specific code into plugins so supporting new platforms will just be a question of developing a new platform plugin. I expect the platform abstraction to be finished by the end of the year.

**Comment by tobydox** [comment]
So once the platform abstraction is finished your contributions are very welcome! :-)
