### ISSUE TITLE
Bad mouse coordinates in Windows 10 client with high DPI

### ISSUE THREAD

**Issue by svatopluk-svarc** [veyon/veyon#188]
Connecting to the client with high DPI display (2160x1440, tablet Chuwi Hi12, Intel HD Graphics, driver version 20.19.15.4444, Windows 10 16299.64) causes bad calculating of mouse coordinates - mouse cursor in master's window is in another place then in client's screen.
Configuration setting "Enable recalculate display for high resolution screens (high DPI)" ON or OFF has the same effect.

**Comment by timstans** [comment]
Same issue here need a fix !

**Comment by tobydox** [comment]
Will be fixed in 4.0.3 (release scheduled for today).
