### ISSUE TITLE
New Veyon install, WakeOnLan not working

### ISSUE THREAD

**Issue by arjaysam** [veyon/veyon#189]
I have just completed a new Veyon install (4.0.2) in computer lab, one Master and 15 client machines.  All machines have WOL enabled.  I tested against one machine and WOL worked.  Set up all the rest in Veyon and now WOL does NOT work either against individual computers or all.  Bug report from Master attached.

[StanHagenBugReport.zip](https://github.com/veyon/veyon/files/1483506/StanHagenBugReport.zip)

**Comment by spirkaa** [comment]
Same problem! WoL 100% worked with Advanced IP Scanner, but not with Veyon.

I tried add mac to different  computer attributes in AD, succesfully tested against it in Configurator but no luck in Master.
I tried local configuration and manually created one PC with ip and mac - no diffirence.

**Comment by tobydox** [comment]
Should be fixed in upcoming 4.0.4 release :-)
