### ISSUE TITLE
Schlüsselpaar auf der Linux Console erzeugen

### ISSUE THREAD

**Issue by chbmeyer** [veyon/veyon#190]
Hallo zusammen und Danke für Veyon.

Ich teste Veyon unter Linux und installiere es unter Debian mit FAI - Fully automatic installation.
Dabei kann ich auch Anpassungsskripte anwenden.
Versuche ich nun mit "veyon-configurator -CreateKeypair" automatisiert ein Schlüsselpaar zu erzeugen, erhalte ich die Fehlermeldung:
```
QXcbConnection: Could not connect to display 
Abgebrochen
```
Der Veyon-configurator benötigt eine GUI, um mein bash-Script auszuführen. Als reiner CLI-Code kann das natürlich nicht klappen.
In einer bereits erzeugten Schlüsseldatei steht leider auch nicht das Verfahren, wohl aber im Quellcode:
master/configurator/src/ConfiguratorCore.cpp .
Leider bin ich mit C++ nicht vertraut und bin auch nicht sicher, wohin mich "CryptoCore" verschlägt bzw. ob ich dort eine Antwort erhalte mit der ich weiterkomme.

Kann man nicht einfach z.B. mit ssh-keygen gültige Veyon-RSA-Schlüssel erzeugen und in Veyon.conf referenzieren? Oder gibt es eine andere CLI Lösung zum Erzeugen von Schlüsselpaaren für Veyon?

**Comment by tobydox** [comment]
Hallo,

es ist in der Tat eine Unzulänglichkeit, dass CLI-Operationen nicht ohne X funktionieren. Allerdings ist ohnehin geplant, die letzten beiden Configurator-Optionen "-createkeypair" und "-importpublickey" in ein CLI-Plugin zu verschieben, so dass diese Operationen über veyon-control möglich sein werden.

Für ein automatisiertes Deployment sollte es aber ohnehin nicht notwendig sein, jedes Mal ein neues Schlüsselpaar zu erzeugen, schon alleine, weil ja auf den Client-Computern überall der gleiche öffentliche Schlüssel installiert werden muss. Stattdessen sollten einmalig über die GUI erzeugte Schlüsseldateien entweder auf ein Netzshare gelegt und per Symlink eingebunden werden oder per Deployment/Configuration Management verteilt werden.

**Comment by tobydox** [comment]
Feature scheduled for 4.1.x - see https://github.com/veyon/veyon/wiki/Roadmap for details.
