### ISSUE TITLE
about compile for windows version

### ISSUE THREAD

**Issue by phenixwang19780316** [veyon/veyon#195]
Dear : 
    when compile the new version , i got the issue .
<
In file included from /home/phenix/Downloads/veyon/core/include/LockWidget.h:31:0,
                 from /home/phenix/Downloads/veyon/core/src/LockWidget.cpp:26:
/home/phenix/Downloads/veyon/core/include/InputDeviceBlocker.h:31:26: fatal error: interception.h: No such file or directory
compilation terminated.
>
please tell me how can i fix it.

**Comment by tobydox** [comment]
Please install all required packages as listed at https://github.com/veyon/veyon/blob/4.0/.travis/linux.cross.win32/Dockerfile :-)
