### ISSUE TITLE
Small inconvenience with authentication

### ISSUE THREAD

**Issue by shemsargent-rvtd** [veyon/veyon#199]
Using LDAP connected to Active Directory. Authentication works on Master, but the user name field in the authentication dialog that comes up is prefilled with DOMAIN\username. For some reason, signing fails with DOMAIN\username, but is successful with just the username without the domain. Everything else works as expected with AD OU and group filtering.

**Comment by tobydox** [comment]
I think this issue is fixed in Veyon 4.1.x. Please report back if not.
