### ISSUE TITLE
Feature Request: Multiple monitor

### ISSUE THREAD

**Issue by SilveryGod** [veyon/veyon#201]
Software is very good so far.
Actually some of my class do use multiple monitors(2)
Having a button to toggle between monitors would be very handly.

**Comment by tobydox** [comment]
You can enable dual monitor support in the Veyon Configurator in tab "Service" -> VNC Server -> Select "Builtin UltraVNC server" and enable the appropriate checkbox :-) Switching between monitors however is not possible.

**Comment by MarrekNozka** [comment]
In my configuration (on Linux) is not  "appropriate checkbox". I solve this problem by custom x11vnc parametr `-clip 1280x1024+1280+0`.
