### ISSUE TITLE
Nothing in the Computer rooms

### ISSUE THREAD

**Issue by FabSean** [veyon/veyon#202]
Already set up rooms with 1 - 2 clients as trial run but still nothing in the veyon master computer rooms tab.
I can remote control the clients using veyon master so that means there is a connection between master and client, right?

**Comment by tobydox** [comment]
Did you add rooms/computers in the Veyon Configurator=

**Comment by Lrobben52** [comment]
Veyon Monitoring in Active Directory:
https://www.youtube.com/watch?v=iUeC9H2q7xY&feature=youtu.be

**Comment by FabSean** [comment]
Thank you for the help, its kind of working now, but now it crashes. Here are the details:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	veyon-master.exe
  Application Version:	4.0.3.0
  Application Timestamp:	00400000
  Fault Module Name:	libqca-ossl.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	61e60060
  Exception Code:	c0000005
  Exception Offset:	0000000000075424
  OS Version:	6.3.9600.2.0.0.272.7
  Locale ID:	1033
  Additional Information 1:	912e
  Additional Information 2:	912e29336d7f08936991f7f880bb5966
  Additional Information 3:	cf3d
  Additional Information 4:	cf3db93cb3ccf5be486d8c9d01b21285

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by tobydox** [comment]
We fixed crashes in Veyon 4.1 so please try one of the pre-releases or try the final 4.1 next week. Feel free to re-open if you still have problems with 4.1 ;-)
