### ISSUE TITLE
Feature request : Option to save commands

### ISSUE THREAD

**Issue by pedrostorti** [veyon/veyon#203]
Hello
After analyzing the software, I checked that it could include the function of saving the commands sent to the stations. With this it would not be necessary to enter the command every time it is to request the opening of MS Word for example.

The software is working perfectly.

Thank you very much

**Comment by seyhunsaral** [comment]
Hi all, 
Great work. Thanks a lot for all the contributors for all the efforts.  I just want to add a small remark. Just the option to save commands itself would be a great improvement already. Usually there are few software and scripts that we ran in the lab constantly and copy pasting them all the time... well not so ideal.I just wanted to add that it would be even better to be able to access these commands as buttons or menu items.

Thanks a lot

**Comment by tobydox** [comment]
In Veyon 4.1 you can configure predefined programs and websites and access them through a submenu. Just checkout Veyon 4.1 Alpha which has been released today!
