### ISSUE TITLE
repository for Linux

### ISSUE THREAD

**Issue by edmundlaugasson** [veyon/veyon#204]
Would propose to establish a repository in order to install Veyon in Linux as it would be expected nowadays. Software management is usually automated via repository usage. It would be appreciated in both DEB and RPM part.

**Comment by tobydox** [comment]
Thanks for the feedback! Do you have a recommendation where to host the repositories? I agree that it would be nice to have automatically deployed repositories but we currently do not have ressources to provide that too. If you have experiences in this area, feel free to contribute! :-)

**Comment by ciampix** [comment]
Well for Ubuntu debs there is launchpad that gives you free space for repos and also a CI service... don't know for rpm though..

**Comment by edmundlaugasson** [comment]
yes - https://launchpad.net/

**Comment by tobydox** [comment]
I'm aware of Launchpad, we build our toolchain for Windows cross compiling there ;-) Nevertheless it doesn't integrate with Travis CI and GitHub so we always had to create/update packages manually. We would require a solution which can be used from within Travis CI and GitHub so binaries get built and published automatically as soon as we tag a new version.

**Comment by tobydox** [comment]
A PPA is now available at https://launchpad.net/~veyon/+archive/ubuntu/stable
