### ISSUE TITLE
Unlock with CTRL + D

### ISSUE THREAD

**Issue by s-r-grass** [veyon/veyon#205]
Hello! Version 4.0.3, Windows 7 x64. I lock the computer, but you can easily remove the lock by pressing the "CTRL + D" key combination. How to solve a problem? Is it planned to solve this problem?

**Comment by tobydox** [comment]
Did you reboot after installing Veyon? After reboot unlocking should not be possible. Alternatively try to install the interception driver manually, see https://github.com/oblitum/Interception for details :-)
