### ISSUE TITLE
Is it possible to disallow PCs configured with master to view each other?

### ISSUE THREAD

**Issue by Ben-Ronlund** [veyon/veyon#207]
Is there a way to:
Install veyon on PCs type A and PCs type B
Allow type A PC to access type B
Disallow type A PC to access type A PC

Configuration done using keys as we can not use LDAP because of security concerns with visible passwords.

**Comment by Ben-Ronlund** [comment]
Also the file "ConfigurationCommandLineUsage.txt" inside \Veyon\Docs\ mentions the command line:
veyon-configurator -ApplySettings MyCustomSettings.xml

Has this been replaced by "veyon-ctl config import settings.json"?

**Comment by tobydox** [comment]
You can make use of the access control features to define which computer or user is allowed to access specific computers. Thanks for pointing out the outdated instructions!

**Comment by tobydox** [comment]
Closing this due to missing feedback - feel free to join again.
