### ISSUE TITLE
VEYONVNC conflict

### ISSUE THREAD

**Issue by twichman** [veyon/veyon#211]
We have a few teachers that are really like using veyon but it is in conflict with our systems management software.   Our Systems management software installs its own VNC server which cause veyon to put up an error 'Another VNC server is already running. Please uninstall any iTALC or UltraVNC installations or disable the correspondig services of these products."  I was wondering if there is a way to install veyon so it does not conflict with other VNC Servers?
Thank you for your time,
Tahan

**Comment by MalletNGrease** [comment]
I have the exact same issue. We utilize a management agent that utilizes ultravnc for remote support.

**Comment by tobydox** [comment]
Please have a look at the recently added item in our FAQ: http://docs.veyon.io/en/latest/admin/faq.html#how-can-an-existing-vnc-server-be-used-in-conjunction-with-veyon

**Comment by MalletNGrease** [comment]
The entry in the FAQ was removed for some reason, please reopen the issue.

**Comment by tobydox** [comment]
Thanks for pointing that out! I updated the FAQ again :-)
