### ISSUE TITLE
Your computer is low on memory.

### ISSUE THREAD

**Issue by hayunike** [veyon/veyon#212]
We've started using Veyon in a lab with 50 PCs. All of the PCs have the same hardware (Intel i3, 4 GB RAM, X64 Win10). On client PCs, Veyon uses a lot of memory and it makes the students reboot the computer. The warning is "Your computer is low on memory". The screen resolution goes weird It doesn't happen quite a lot (3-4 PCs in a week, maybe a lot?).

**Comment by tobydox** [comment]
Thank you for your bug report! I personally never encountered such problems or behavious. Did you install the 64 bit version? Alternatively try to install UltraVNC separately and configure the Veyon Service on each client computer to use the local VNC server.

**Comment by Pieter1959** [comment]
We have the same problems as hayunike in our school. Before we use iTalc version 2 and didn't never have some kind of problems. Our teachers like the program very much because it is so user friendly. Can you give me more details how we can install UltraVNC separately an how to to use the service on each client, please ?

**Comment by hayunike** [comment]
@tobidox Yes I installed the 64bit version. Our students only use Chrome on those computers, so it shouldn't be a problem.

@Pieter1959 I've solved the problem by increasing the virtual memory. I followed the instructions here: http://troubleshooter.xyz/wiki/fix-your-computer-is-low-on-memory-warning/#Method_1_Increasing_Virtual_Memory

**Comment by Pieter1959** [comment]
Thanks, hayunike for your quick responce. We got the problem on the master and our clients.
Do you know a handy way to fix this with a script or reg key? We used SCCM 2012 R2 for deploying our software.

**Comment by hayunike** [comment]
@Pieter1959 Sorry, I have no idea about it. We mostly work manually, so the changes were made one-by-one :-(
