### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by hayunike** [veyon/veyon#213]
I want to see some features, but I'm not sure if they are easy to implement.
1- Veyon client which automatically connects to the master. After starting veyon master, it starts to broadcast on the network. And veyon master allows us to create an installation file which includes master IP, config.json and public key. So it will be easier to start. There will be no need to find out the IPs of a lot of PCs.
2- Only show active PCs. In veyon configurator there may be an option to see only the online PCs.
3- Web Blocking Feature. I think this is the most difficult one to implement (I need to say that I'm not a coder, so I'm not sure). In our labs, we don't want students to use the bet or illegal sites and social networking sites. So it will be great to have such a feature.

**Comment by tobydox** [comment]
Sorry for the late reply. Feature 1) and 3) will be available for subscribers in Q4/2018. Feature 2) is interesting but difficult to implement. We could add some kind of filter which will make offline computers hide automatically. Are you still interested in getting this done?

**Comment by HasanTekeli** [comment]
I'm glad these two features will be available. #2 is not that important, but it may be good. Thanks for the reply.
