### ISSUE TITLE
Yes/No dialog confirmation box for start/restart/shutdown button.

### ISSUE THREAD

**Issue by Lrobben52** [veyon/veyon#214]
When you accidently hit the restart/shutdown button in the toolbar, all the visible or selected clients wil immediately restart or shutdown without warning. This is not nice for a teacher who's taking a test of 24 students. Is it possible, when you select one of these buttons, to open a yes/no confirmation dialog box afterwards so that the master has some kind of safety.

**Comment by tobydox** [comment]
In Veyon Configurator you can enable the option "Show confirmation dialog for potential dangerous actions" in the Master configuration page :-)
