### ISSUE TITLE
Delays at change of slides

### ISSUE THREAD

**Issue by mrkaban** [veyon/veyon#215]
Hello, tell me please. I was approached by one of the computer science teachers with a small problem. Below I will quote his words.

"In a class on 11 computers +1 the manager at presentation demonstration there are delays at change of slides or occurrence of objects on a slide."

**Comment by tobydox** [comment]
How big are the delays? What are your network speeds?

**Comment by mrkaban** [comment]
Unfortunately, she did not say ... and I do not have the opportunity to check on a large class of computers. The program can not cause such problems when using 11 computers?

**Comment by tobydox** [comment]
We'll further improve the demo mode in Veyon 4.2 but until then I don't have a solution, I'm sorry. If you have more feedback or experiences, don't hesitate to reply.
