### ISSUE TITLE
Permission rules - groups only: direct members

### ISSUE THREAD

**Issue by Yh-xxl** [veyon/veyon#216]
While configuring permissions I noticed users accounts have to ba a direct member of the specified group.
Indirect members (so recursive processing) would be handy, and keep groups in LDAP clean

**Comment by mondo28** [comment]
i agree with this also. useful for staff accounts

**Comment by tobydox** [comment]
This has finally been implemented in 04208c0715ec0c58f300e18357340d3e28c9f0ce and will be part of the upcoming 4.5.6 release. In the meanwhile you can workaround this issue by appending `:1.2.840.113556.1.4.1941:` to the group member attribute (e.g. `member` -> `member:1.2.840.113556.1.4.1941:`).
