### ISSUE TITLE
UltraVNC and Veyon parallel install.

### ISSUE THREAD

**Issue by sethelyon** [veyon/veyon#217]
Hi!

Thank you for doing a great job. May I ask, would there be a solution in regards of running UltraVNC and Veyon in parallel?

Also, is file transfer a feature to be added on the future?

Thanks again!

**Comment by tobydox** [comment]
Please have look at the recently added item in our FAQ: http://docs.veyon.io/en/latest/admin/faq.html#how-can-an-existing-vnc-server-be-used-in-conjunction-with-veyon

File transfer is not planned but can be added as a plugin easily if there's a volunteering developer :-)
