### ISSUE TITLE
PC preview tumbnail orientation

### ISSUE THREAD

**Issue by bturcan** [veyon/veyon#218]
Is there a way to change pc preview orientation? We  have 4 vertical display in lab and when we see them on veyon master, we always see in horizontal preview. Can we change preview orientation of the display? or which part of the code we should edit?

As you know all pc remote tumbnails are displayed in horizontal view on veyon master...

**Comment by tobydox** [comment]
Unfortunately this is not possible, I'm sorry. You'd have to modify ComputerListModel::computerDecorationRole(...) in order to rotate the returned images.

**Comment by bturcan** [comment]
Thx i will try that.

**Comment by tobydox** [comment]
Ok I'm closing this for the meantime.
