### ISSUE TITLE
Pc Thumbnail Refresh Rate

### ISSUE THREAD

**Issue by bturcan** [veyon/veyon#219]
How can i change refresh rate of pc preview thumbnails in master pc ? (place where i can see all connected pc previews) Right now it spends big bantwith i want it to be little slower previews so bandwith usage will be less.

**Comment by bturcan** [comment]
Hi again can someone give information about how can we solve the issue ? we just want to lower refresh rate of each remote pc preview thumbnail.

**Comment by bturcan** [comment]
"""How frequent is the screen content updated?
Normally the screen contents are updated once a second in observation mode. Depending on the workloda of the network and the computer, this value may differ. """
How can i change this to update screen's content every 10 minutes?

**Comment by bturcan** [comment]
Do i have to change it from VeyonConfiguration.cpp " c.setComputerMonitoringUpdateInterval( 1000 );" or inside RemoteAccessWidget.cpp

 void RemoteAccessWidgetToolBar::connectionEstablished()
{
	m_connecting = false;
	m_iconStateTimeLine.stop();
	QTimer::singleShot( 3000, this, SLOT( disappear() ) );
	// within the next 1000ms the username should be known and therefore
	// we update
	QTimer::singleShot( 1000, this, SLOT( update() ) );

**Comment by bturcan** [comment]
That will be very usefull if we have update interval input on next update for to change screen content refresh rates. Cause for other monitoring alternatives i mean non classroom applications, veyon also usefull. For to limit bandwith usage; its better if i have ability to control screen content update times for all pcs thumbnails.

**Comment by tobydox** [comment]
In Veyon 4.1 (master branch) this will be configurable. Until then you'll have to change https://github.com/veyon/veyon/blob/4.0/core/include/ComputerControlInterface.h#L134 and https://github.com/veyon/veyon/blob/4.0/master/src/ComputerManager.cpp#L87

I'm closing this because we implemented it via 55c136782cf9a8a00a2d330ec385fe6a208ab470, 89d1fa5afd5064bfebe736f26bbf8c3b181e45d3 and 8c188bb68d025bac9f29075941272942fe3bde8a

**Comment by bturcan** [comment]
Thank you.
