### ISSUE TITLE
A bug in Veyon (Hebrew) that i have finally succeed to fix

### ISSUE THREAD

**Issue by Lior209** [veyon/veyon#220]
Hi all.

For the last couple of weeks, i have tried again and again to figure out why Veyon didn't worked on my machines.

I thought that I had problems with firewall permissions or keys problem or another VNC server working at the same time but nothing ! no matter what i have tried nothing worked. 

Finally, after thinking what can cause the problem, I have changed the language of the user interface on the Veyon configurator from default (system language - Hebrew) to English ! and voila ! all working excellent !

1. Please try to fix the bug on the next version.
2. Please publish the issue and the fix for it on your web site.

Thanks for you efforts !

**Comment by tobydox** [comment]
Thanks for reporting! Will be fixed in upcoming 4.2.2 release.

**Comment by tobydox** [comment]
Test release is available at https://github.com/veyon/veyon/releases/download/v4.2.1/veyon-4.2.1.26-win64-setup.exe
