### ISSUE TITLE
Master PC Freezing when Launching Veyon Master application

### ISSUE THREAD

**Issue by Bob-OS** [veyon/veyon#221]
Hey Veyon Team, 

I teach Computer Networking at a community college in North Carolina. I'm working on migrating from ITALC (which I love!) to Veyon. The abilities ITALC has given me have really helped create an immersive learning experience for students. I'm able to address issues and misunderstandings quickly without leaving my instructor station. Seeing that you all moved to a new project was exciting. Though ITALC is very useful it would crash every now and then, a minor inconvenience. Moving to Veyon seemed like a good step forward however, I am running into a major issue.

Issue: 
- Launching & running Veyon Master utilizes 100% CPU & 90% Memory
- Typically causing the system to completely freeze. I'm not even able to open Task Manager to quit the application. I'm forced to perform a hard shutdown.

Network Environment:

- 20 PCs running Windows 10 (all joined to a Windows Domain)
- Each PC has 16GB of RAM  & an Intel i5 processor

My Veyon Configurations:

- Using Key-file & Logon Authentication 
- Generating Master Key on master & importing that same key on all client computers
- Here is my Veyon Master Rooms & Computers configurations

![veyon master config](https://user-images.githubusercontent.com/33357023/34174298-700178ae-e4c6-11e7-9858-2839ab51e996.png)

Please help as soon as you can.

**Comment by jamj2000** [comment]
In Host Address/IP must appear a IP, doesn't it?

**Comment by Bob-OS** [comment]
jamj2000,

Thank you for responding. Not necessarily, I say this because a Domain controller also serves as the Primary DNS server so names are being resolved to IP addresses and vice versa.

Interesting enough I was browsing through the other issues posted and had the idea to make 2 changes that appear to have fixed my issue.

1. Changed default language to English 
2. On master ensured that authentication was set to local 
- After these changes were made Veyon started running stable

**Comment by tobydox** [comment]
Can you tell which of the two changes made the difference? Also what do you mean by "authentication set to local"?

**Comment by Bob-OS** [comment]
Tobias,

Under the authentication set of options at the very, top is a drop down menu that allows you to choose between local authentication & LDAP.

**Comment by Bob-OS** [comment]
Tobias,

Also I believe changing the authentication is what corrected the issue. I will try to recreate the issue when I return to the lab on Monday.

**Comment by Bob-OS** [comment]
Tobias,

The resolution is confirmed working. To fix this you must ensure Computer access control is set to default and not the blank option that is present following install. 

Veyon is working stable and my scripts work on Windows 10 now!

**Comment by tobydox** [comment]
In Veyon 4.0.4 domain groups are not queried per default any longer which should also fix hanging Veyon applications :-)
