### ISSUE TITLE
No menu launchers in Linux

### ISSUE THREAD

**Issue by ArtyomZorin** [veyon/veyon#222]
The Veyon package currently doesn't install menu launchers/shortcuts (".desktop" files in the `/usr/share/applications directory`) for the veyon-configurator and veyon-master apps.

This makes is necessary for the user to run these commands from the Terminal, instead of being able to simply open them from the app menu.

**Comment by tobydox** [comment]
Thanks for reporting this issue! It has been fixed in 80554ace73308ee43711f3ba73c6bf9d1d4cdf46 and will be part of 4.0.4 release.
