### ISSUE TITLE
How to install veyon on ubuntu 14.04

### ISSUE THREAD

**Issue by gam3rtr** [veyon/veyon#229]
Please help me to install veyon on ubuntu 14.04 please tell me correct details and give a brief installation instruction

**Comment by tobydox** [comment]
Veyon won't work on Ubuntu 14.04 as both compiler and the Qt framework is too old. Please use at least Ubuntu 16.04. Then you can install the provided DEB package, put Veyon Service to autostart and configure the setup using Veyon Configurator as described our admin manual at docs.veyon.io :-)

**Comment by gam3rtr** [comment]
Can i install on cent os 6.6

**Comment by tobydox** [comment]
No you'll need at least CentOS 7.3.
