### ISSUE TITLE
pop up issue

### ISSUE THREAD

**Issue by diaz-matazz** [veyon/veyon#23]
I just intalled the software as a master and a pop up window keeps going on appaering.

![capture](https://user-images.githubusercontent.com/29396389/27071520-a144c468-501d-11e7-968a-eae4c83189a3.JPG)

**Comment by tobydox** [comment]
Do you have UltraVNC installed already? Veyon and UltraVNC currently can't be used in parallel however there's going to be a solution in Veyon 4 RC2.

**Comment by neilpdj** [comment]
I have this same issue - except this is only appearing on my client machines. The window instantly re-appears after it has been closed. 
My client machine is a slightly older build of Windows 10 Education. Master is on 1703.

I can't upload the bug .json file here...

**Comment by tobydox** [comment]
@diaz-matazz: do you have iTALC installed in parallel?

**Comment by tobydox** [comment]
We'll add a more informative message box about uninstalling iTALC first.

**Comment by Lrobben52** [comment]
I had the same window on the master and student PCs. You need to uninstall Italc and UltraVNC if you have does. After a restart it works OK.

**Comment by neilpdj** [comment]
You're absolutely right :) Thanks all.

**Comment by diaz-matazz** [comment]
UtraVNC is not installed but iTalc is.
