### ISSUE TITLE
Can I authenticate the browser via code?

### ISSUE THREAD

**Issue by andrecesarlino** [veyon/veyon#231]
218/5000
In my classroom I have a proxy on the students' computers, and I have an account of mine to authenticate too, I get via code to put the site and authenticate at the same time without having to do machine by machine.

**Comment by tobydox** [comment]
I guess that's not possible - all you can do is easing this task by remote controlling each computer. Alternatively try to find a solution where you can control the proxy server through a command line call. Then you can use the "run program" feature.
