### ISSUE TITLE
can i monitor one class room on two different teacher PC?

### ISSUE THREAD

**Issue by asif138** [veyon/veyon#232]
HI
I have one class room which i want give access to monitor two teacher on two different PC?
is it possible to configure veyon that both teacher can view one class room at a time?

Thanks

**Comment by tobydox** [comment]
Yes, that's possible - please see our FAQ for details ;-) http://docs.veyon.io/en/latest/admin/faq.html#is-it-possible-to-use-veyon-master-on-multiple-computers

**Comment by asif138** [comment]
Thanks, but i am able to do that. i use key file to configure. public key generated from master is imported on each client computer, so to make other master which key is to use for other master.?

Thanks

**Comment by tobydox** [comment]
You have to copy the private key from one master computer to the other one. On Windows copy C:\ProgramData\Veyon\keys\private and on Linux copy /etc/veyon/keys/private

**Comment by asif138** [comment]
Thanks,
in 2nd master PC where is private key will be pasted? in which folder

Thanks,

**Comment by tobydox** [comment]
Copy it to the same folder on the target computer so the folder structure is identical. Replace any existing files.
