### ISSUE TITLE
LDAP Computer import

### ISSUE THREAD

**Issue by mondo28** [veyon/veyon#236]
I have got LDAP to bring back the list of OU's. We have 8 main OU's, each containing sub-OU's (rooms), where these then have computers. Without using the "Perform Recursive search" option in Environment Settings, I get the list of 8 main OU's, but these obviously don't contain the computers. When I tick the box, a list of every sub-OU is brought back and lists the computers. 
When I launch Master I see these 90 OU's as well as the 8 main OU's. How do I get these OU's to be ordered under their correct Main OU's, sub-OU's etc, not just one long list?

**Comment by tobydox** [comment]
Thank you for your message! Unfortunately Veyon does not support nested rooms/OUs yet and I'm currently focussing on other features. Contact me if your organization is willing to sponsor the development of nested room/OU support so we can speed up the implementation of this :-)
