### ISSUE TITLE
Access Control Issues with Rules

### ISSUE THREAD

**Issue by justein230** [veyon/veyon#237]
In my configuration, I set a rule to allow only members of the group "Veyon Admins". While members of that group are allowed to log in, students are also able. Is there any way to change it so that only members of the Veyon Admins group can log in to the Veyon Master client?

![image](https://user-images.githubusercontent.com/7889269/35071414-9a6320e4-fbae-11e7-8ff9-9048d628ce22.png)

**Comment by tobydox** [comment]
You can simply enable the option "Perform access control at program start" in the master configuration page. This will prevent even the start of Veyon Master by students.
