### ISSUE TITLE
Block websites

### ISSUE THREAD

**Issue by cesarpineda1307** [veyon/veyon#238]
Fantástico Software, muy útil.
Lo acabo de instalar en mi sala de computo y me esta funcionando muy bien, sería muy bueno agregar opciones como ser:
- Ordenar Alfabeticamente en Aulas y Equipos de Veyon Configuration.
- Un botón de actualizar o refrescar pantalla en Veyon Master
- La opción de bloquear sitios web para la red que administramos

Por los pocos días que tengo de usarlo me ha encantado.
Felicito a todos los colaboradores.

**Comment by ciampix** [comment]
Please give a hand to everyone and write in English, perhaps your problems (and their solutions) are interesting to others...

**Comment by cesarpineda1307** [comment]
431/5000
Fantastic Software, very useful.
I just installed it in my computer room and it is working very well, it would be very good to add options such as:

- Sort Alphabetically in Classrooms and Equipment of Veyon Configuration.
- One button refresh or refresh screen in Veyon Master
- The option to block websites for the network that we administer

For the few days that I have to use, it I loved it.
I congratulate all the collaborators.

**Comment by tobydox** [comment]
Thank you for your bug report! Rooms and computers are already sorted alphabetically. A refresh button is not neccessary thanks to the auto update feature - simply configure the auto update interval for the network object directory in Veyon Configurator (first page). Internet access control likely will be available in Veyon 4.1.x in a few months.

**Comment by Emalton** [comment]
Hi tobydox,

Has the ability to block websites become a reality yet?

Let me know,

Emalton

**Comment by tobydox** [comment]
It's being worked on and will be available for purchase as an additional plugin in Q1 or Q2/2019.

**Comment by Emalton** [comment]
Thank you!

**Comment by Emalton** [comment]
Hi tobydox,

Is that blocking website feature a reality yet?? 😀

LMK,

John P.

**Comment by Chrisapo147** [comment]
Hello everyone,
I'm asking for webaccess blocking (specific sites).
Is it possible please?

**Comment by tobydox** [comment]
Blocking specific websites is not possible. With the Internet Access Control add-on you can only block the Internet access completely.
