### ISSUE TITLE
Password problem with special characters

### ISSUE THREAD

**Issue by Pat-iut** [veyon/veyon#24]
Hi,

Veyon 3.99.5 for Windows (tested with 32 and 64bits version, on Windows 7 and Windows 10 Pro) :
I had a problem with italc 3, same issue with Veyon 3.99.5 => authentification fail if the password contains special characters like é,à,ç,ù,è, ... (french keyboard).
Tested with local accounts and ActiveDirectory accounts.

Please can you fix it ? (i'm ready to beta-test if needed)
(Logs attached (one successful authentification, then i add character 'é' to my password and authentification failure)

Very good job btw
Thx
PM
[logs_veyon.zip](https://github.com/veyon/veyon/files/1071413/logs_veyon.zip)

**Comment by tobydox** [comment]
Thanks for reporting this issue! I'll have a look at it!
