### ISSUE TITLE
Feature Request: ability to edit the shortcut list

### ISSUE THREAD

**Issue by rdarlin2** [veyon/veyon#240]
Great tool!
We would like the ability to add/delete/modify the shortcut list, so that commands needed by our applications can be added to the short list.

Mainframe emulator needs the 'Ctrl' key as part of it's built in menu management system.  None of the existing shortcuts will work as they include other keys along with the Ctrl key as well.

**Comment by tobydox** [comment]
Thank you for feature request and your feedback! Customizing the shortcut list is already on our roadmap at https://github.com/veyon/veyon/wiki/Roadmap - however I currently can't promise we'll get it finished for 4.1.x already. Of course things can be prioritized if there's an organization which sponsors the development.
