### ISSUE TITLE
Installation on Linux Mint

### ISSUE THREAD

**Issue by Blackphantom96** [veyon/veyon#246]
#Error while cloning git://anongit.kde.org/kldap.git 
![screenshot from 2018-01-30 13 00 07](https://user-images.githubusercontent.com/19200060/35582591-3cb6815c-05bd-11e8-8fb7-c3fcd60b242b.png)

**Comment by tobydox** [comment]
This was probably a temporary issue with the servers of the KDE project. Cloning works fine here :-)
