### ISSUE TITLE
VMWare Virtual Machine

### ISSUE THREAD

**Issue by Zyahko** [veyon/veyon#249]
Before testing Veyon we used UltraVNC. We had a few machines that utilize the VMWare Virtual Machine and those users would remote desktop into their respective virtual machine from their thin client. When we would need to VNC into their machine we would have to change the port from 5900 to 5901 to see what they are seeing. When I try it with Veyon it just shows the default session that they aren't utilizing and I can't see what they are seeing. Is there a way to toggle logged on sessions or something?

Please Advise.

Thanks,

**Comment by tobydox** [comment]
From my perspective you could specify the port manually, e.g. add hosts "<IP>:590X".

**Comment by Zyahko** [comment]
UltraVNC default port is 5900 and just increments the port by number for the different user sessions on there. From what I have tried testing I can't get Veyon to see that other sessions on the Virtual Machine. How would we go about testing your advice.

Thanks,

**Comment by tobydox** [comment]
We're still working on multi session support. You can try the latest version and enable it via `veyon-ctl config set Service/MultiSession 1` at the command line. Afterwards restart the service and computers in Veyon Configurator such as "localhost:11100", "localhost:11101" etc.
