### ISSUE TITLE
No monitor connection between Veyon-master 4.0.4 on windows 7 and windows 10 client 

### ISSUE THREAD

**Issue by Agnes20** [veyon/veyon#250]
Good morning to all
I have installed the teacher veyon in a windows 7 and the veyon student in a windows 10.
I get this:

![veyon](https://user-images.githubusercontent.com/25745771/35726063-d56cfad2-0803-11e8-9ea4-384e6864ef09.jpg)
I put the record of the veyon master.lg

[VeyonMaster.log](https://github.com/veyon/veyon/files/1688737/VeyonMaster.log)

Thank you very much

**Comment by tobydox** [comment]
There seems to be a firewall issue as the Veyon Master can't connect or ping the remote host. Can you try to disable the firewall? Also see the troubleshooting section in our manual at docs.veyon.io :-)

**Comment by Agnes20** [comment]
it tells me authentication error and what done as it says in the manual at docs

**Comment by tobydox** [comment]
Can you change the log level to debug? Did you configure key or logon authentication properly?

**Comment by tobydox** [comment]
Closing due to missing feedback. Feel free to come back and respond.
