### ISSUE TITLE
Run a programs as administrator on the remote computer

### ISSUE THREAD

**Issue by jaywang0tw** [veyon/veyon#251]
Sometimes we need to do something requiring administrator's privilege in order to make some programs to run correctly such as turning off the firewall.

I think that running a program as administrator on the remote computer is a good feature to implement.

**Comment by Lrobben52** [comment]
Try RunAsTool.

**Comment by willianpts** [comment]
Also on linux you can run the veyon-service on client as root and the master can do anything with it.

**Comment by tobydox** [comment]
I think the proposed RunAsTool is the best solution here. Adding the possibility to run commands with administrative privileges would likely introduce severe security problems and would allow non-admin users (teachers) to run programs as administrator even if they're not allowed to do that. This would effectively bypass UAC which is something we definitely do not want.

@willianpts It's true that we need to improve the implementation on Linux.
