### ISSUE TITLE
Translation isn't complete on a compiled veyon 4.0.4

### ISSUE THREAD

**Issue by goforgit** [veyon/veyon#252]
I compiled veyon 4.0.4 from git master yesterday (2018-02-05). Unfortunately the translation dosen't work 100%. So the sections
- Rooms & computers
- Authentication keys
- Internet access control
keep the english language. The same applies, if I choose french or spain.
I checked the de_DE.ts file and this seems ok. That this issue also happens in french and spain make's me believe that the fault is somewhere else. Where?

Kind regards, Roland
By the way: Thank's a lot to the developers for all the work.

**Comment by tobydox** [comment]
Please checkout branch "4.0" to get the real 4.0.x series :-)

**Comment by tobydox** [comment]
Sorry forgot to add my comment before closing this issue :-/
