### ISSUE TITLE
Could not start/stop veyon service when using veyon_4.0.4-debian-stretch_amd64.deb

### ISSUE THREAD

**Issue by goforgit** [veyon/veyon#253]
Hello.
I try to setup veyon 4.0.4 on a network with pc's using debian stretch. When I use the offered debian stretch deb file (2018-02-04) I cannot start or stop the service. The keys under service (Dienst) are greyed out and the status message says stopped.
When I compile veyon 4.0.4 from the git (master branch), this works. But in the compiled version, I haven't been asked for the administrator password, so every user (also students) can start/stop the service. Is this on purpose?

Kind regards, Roland

**Comment by tobydox** [comment]
Thanks for your feedback! The master branch actually contains the future 4.1.x series which has full systemd service support on Linux. Veyon 4.0.x does not support service management on Linux so you'll have to run veyon-service manually via xinitrc, autostart or Xsetup.
