### ISSUE TITLE
It can allow the student to show demo?

### ISSUE THREAD

**Issue by ICCDamian** [veyon/veyon#255]
It can allow the student to show demo? one of the most used functions in italc is to allow the student to demonstrate to everyone in the classroom how a procedure does

**Comment by tobydox** [comment]
Unfortunately this is not implemented yet as we had to rewrite all functionalities for the new architecture in Veyon. There are chances it'll return however our development ressources are very limited and mainly prioritized by sponsoring. If you have the chance to sponsor the development of this feature, contact me!

**Comment by ICCDamian** [comment]
Cuanto costaría?

Enviado desde mi smartphone Sony Xperia™

---- Tobias Junghans escribió ----


Unfortunately this is not implemented yet as we had to rewrite all functionalities for the new architecture in Veyon. There are chances it'll return however our development ressources are very limited and mainly prioritized by sponsoring. If you have the chance to sponsor the development of this feature, contact me!

**Comment by tobydox** [comment]
Please send an e-mail to info@veyon.io to discuss things in private :-)
