### ISSUE TITLE
how to monitor one class room in two different Computers?

### ISSUE THREAD

**Issue by asif138** [veyon/veyon#256]
hi 

i want to monitor one class room having 6 computers on two different PC (at different location or say two teacher monitor same class). is it possible and how?

Thanks,
Asif Iqbal

**Comment by tobydox** [comment]
Please have a look at our FAQ ;-) http://docs.veyon.io/en/latest/admin/faq.html#is-it-possible-to-use-veyon-master-on-multiple-computers
