### ISSUE TITLE
Veyon needs a restart when the class is changed (Linux)

### ISSUE THREAD

**Issue by joacliba** [veyon/veyon#257]
On Ubuntu Linux if veyon is opened with a different class and then is switched to the correct one, it doesn't load the computers and it is needed to close the application and open again.

I think this is not happening on the Windows version of veyon and it could be related with this issue:
https://github.com/veyon/veyon/issues/142

Thanks

**Comment by tobydox** [comment]
It's probably a timeout issue. How long did you wait after switching?

**Comment by joacliba** [comment]
I've waited for 30 minutes and still not working. All machines are in grey.

**Comment by tobydox** [comment]
Ok, what do you mean by switching class? Do you select other computers in Veyon or do users log off and on again on the same computers?

**Comment by joacliba** [comment]
I'm refering to the master, if you uncheck the previous class, and then check the new one veyon doesn't update the machines in linux.

The steps:
1. I open veyon and previous class is checked.
2. I uncheck the previous class.
3. I check the new class.
4. Veyon doesn't update so I need to close and open again.
5. Veyon updates normally.

The cllients identification is done by the computer name.

**Comment by tobydox** [comment]
This is strange and we need to debug this. In the meanwhile there'll be an option to refresh via F5 in the next release - maybe this will help.

**Comment by tobydox** [comment]
Additionally in Veyon 4.1 this will completely reconnect to all computers - feel free to test Veyon 4.1 alpha :-)
