### ISSUE TITLE
Windows installer does not request user rights elevation

### ISSUE THREAD

**Issue by me21** [veyon/veyon#258]
Windows installer tries to install Veyon into Program Files folder, but does not request user rights elevation. Please fix that either by installing into user writable location, or request administrator rights automatically.

**Comment by tobydox** [comment]
Are you using the official installers provided here? They should already request user rights elevation, at least implicitely by containing the keyword "setup" in the installer file.

**Comment by me21** [comment]
Yes, I do use official installer.
