### ISSUE TITLE
Unable to unlock single computer after lock

### ISSUE THREAD

**Issue by heremansgeert** [veyon/veyon#26]
When right-clicking on a computer and locking it. It's impossible to unlock it afterwards. The context-menu doens't state unlock.

Group locking and unlocking does work.

**Comment by neilpdj** [comment]
I have the same issue.
I do, however, love the new features for launching apps or specific websites! :) Thanks for those!

**Comment by onlurking** [comment]
@heremansgeert, did you click the ```monitoring``` button? i don't know if is supposed to work this way(quite non intuitive because we expect the ```lock``` button both lock and unlock), but clicking ```monitoring``` works for me.

**Comment by tobydox** [comment]
Yes currently you can leave modes such as demo and lock mode by switching back to "overview" mode. I admit that the usability is not optimal and will propose a better solution.

**Comment by Lrobben52** [comment]
It's stil possible to unlock a student PC. Try "Ctrl-shift-Esc", taskmanager wil open and you can stop Veyon from there.
