### ISSUE TITLE
What do I install on the Client Student's PCs

### ISSUE THREAD

**Issue by jradxl** [veyon/veyon#260]
Hello,
REF: veyon_4.0.4-ubuntu-xenial_amd64.deb

I'm sorry if I appear so stupid, but I can work out what I need to install on the Client/Slave/Student's PCs.
I have no previous experience of iTALC and only have experience of Teamviewer....

I have the DEB (4.0.4) installed on Ubuntu 16.04, and both the Veyon Configurator and Master appear in the menus and open fine. 

1. In the Veyon Configurator > Service Menu, the Service is Stopped and both buttons are greyed out.
I don't see an systemctl ???.service file, but there is /usr/bin/veyon-service and /usr/bin/veyon-worker

2. I can run /usr/bin/veyon-service from a console and see that /usr/bin/veyon-worker starts too. The log to the console all seems fine, and it appears to be x11vnc listening on port 11200

3. So far, I'm concluding that I install the DEB on all machines, but that makes me ask about what if the Students run the Master and or the Configurator?

4. There are no PNG images in either the online or pdf documents in Chapter 1.3, which might have helped. But the network diagram in 1.4 does help.

5.  I'll keep working from first principles and no doubt discovered more by the time anyone comments on this. If I've missed something in the Docs, I'm sorry, but perhaps my comments might lead to clarifications for a beginner in the documentation.

Thank you
John

**Comment by tobydox** [comment]
Hi John,

thanks for the detailled feedback! Unfortunately Veyon 4.0.x does not have system service support on Linux. This will be one of the major new features introduced with Veyon 4.1.x in a few months. Until then you'll have to start veyon-service "manually" by either adding a corresponding file to /etc/xdg/autostart or add it to xinitrc or Xsetup as described at https://github.com/veyon/veyon/blob/master/INSTALL
