### ISSUE TITLE
Traffic compression

### ISSUE THREAD

**Issue by SnelsSM** [veyon/veyon#261]
Hi. How about traffic compression when "teacher" use "view" or "control" at master? Is this possible? I believe that this possibility is very important, because it is quite uncomfortable to operate remote computers.

**Comment by tobydox** [comment]
Do you have specific problems with traffic? What traffic do you see under normal conditions? I'm asking because Veyon actually uses various types of traffic compression already (as implemented in the VNC protocol).

**Comment by SnelsSM** [comment]
Sometimes there are significant delays. Delays do not allow me to comfortably manage computers. Using an ordinary VNC client, I have the ability to manage compression. How can I control the compression in the "master"?

**Comment by tobydox** [comment]
There's currently no such option as Veyon uses compression automatically. We'll improve the VNC server integration in future releases (but probably not before 4.2.x) to support more compression algorithms (e.g. Tight encoding).
