### ISSUE TITLE
Set central config on startup

### ISSUE THREAD

**Issue by pmoussier** [veyon/veyon#262]
Hello,
Is there a way to have the master config reload on service startup?
When I change veyon central config file (config.json), I need to reinstall veyon on each computer to use the new config.
Do you have another way?
Thanks,
PM

**Comment by tobydox** [comment]
Luckily you do not have to reinstall Veyon every time :-) You can import the updated configuration through the command line interface as described at http://docs.veyon.io/en/latest/admin/cli.html#administration-of-your-configuration (reload the page a few times if it doesn't load immediately). You can even automate this process by adding the `veyon-ctl config import` call to your SCM.
