### ISSUE TITLE
Fails in the compiled executable of veyon

### ISSUE THREAD

**Issue by besstmaster** [veyon/veyon#263]
Good morning, I have problems compiling veyon, without making any changes to the source code. the compilation process ends with no apparent problem and generates the executable but when I install it I get an error when starting the service, I followed the steps indicated for the process.

**Comment by tobydox** [comment]
Without any further details I can't help here, I'm sorry. Do you have a build log somewhere?

**Comment by jimmy5678** [comment]
When I compile the source does the same thing. It will create an exe. But when you install it crashes. something to do with Veyon-clt (configure) and Veyon-service and qt5core.dll. using Ubuntu and cross compiling for windows 64.  

log from windows
Faulting application name: veyon-service.exe, version: 4.0.4.356, time stamp: 0x00000000
Faulting module name: Qt5Core.dll, version: 5.6.4.0, time stamp: 0xa878a868
Exception code: 0xc0000005
Fault offset: 0x00000000000aa9f2
Faulting process id: 0x1148
Faulting application start time: 0x01d3ba340b72a6d1
Faulting application path: C:\Program Files\Veyon\veyon-service.exe
Faulting module path: C:\Program Files\Veyon\Qt5Core.dll
Report Id: 4a6eea47-2627-11e8-878c-d43d7e403dd0

**Comment by tobydox** [comment]
Please switch to our latest toolchain based on Ubuntu 18.04 and try again (Qt 5.9 etc).

@besstmaster please respond and/or re-open this issue if things still are not working as expected.
