### ISSUE TITLE
Backgroundcolor 

### ISSUE THREAD

**Issue by Lrobben52** [veyon/veyon#264]
I tried to change the backgroundcolor in the mastersection of the myconfig.json file but it don't change the color after i load it again in the veyon configurator. I used the win 32 and 64 bit version.

example:

    "Master": {
        "AccessControlForMasterEnabled": "false",
        "AutoAdjustGridSize": "true",
        "AutoSwitchToCurrentRoom": "false",
        "BackGroundColor": "#00ccc0",
        "ComputerFilterHidden": "false",
        "ConfirmDangerousActions": "true",
        "EnforceSelectedModeForClients": "true",
        "LocalComputerHidden": "false",
    },

Thank you.

**Comment by tobydox** [comment]
The property is currently not located in the central Veyon configuration. You'll have to add the property "BackgroundColor" to the "UI" section in your personal user configuration - on Windows you can find it in %APPDATA%/Roaming/Veyon/Config/UserConfig.json

**Comment by Lrobben52** [comment]
I changed the UserConfig.json, but still no grey backgroundcolor:


{
    "UI": {
        "BackGroundColor": "#AAAAAA",
        "CheckedNetworkObjects": {
            "JsonStoreArray": [
            ]
        },
        "MonitoringScreenSize": 980,
        "WindowGeometry": "AdnQywACAAAAAAHJAAAAjgAABbYAAANpAAAB0QAAAK0AAAWuAAADYQAAAAAAAAAAB4A=",
        "WindowState": "AAAA/wAAAAD9AAAAAAAAA94AAAJmAAAABAAAAAQAAAAIAAAACPwAAAABAAAAAgAAAAEAAAAOAHQAbwBvAGwAQgBhAHIBAAAAAP////8AAAAAAAAAAA=="
    }
}

**Comment by tobydox** [comment]
Please use "BackgroundColor", i.e. a small "g" for "ground".

**Comment by Lrobben52** [comment]
Thank you Tobias, it's working ....


![capture](https://user-images.githubusercontent.com/25714742/36204856-141b2cd0-118d-11e8-9044-b4c3734f7fbc.JPG)
