### ISSUE TITLE
Use of gettext i18n strings support

### ISSUE THREAD

**Issue by ciampix** [veyon/veyon#267]
Hello devs,
I am a free software translator (from English to Italian). I found that there are no tools better than the gnu gettext and associated .po files. I was wondering... why not make veyon use gettext .po files instead of what is currently using (xml format)?

**Comment by tobydox** [comment]
Thanks for your feedback! We're using the builtin translation system from Qt which is performing well and integrates perfectly with Transifex & co. You can also use tools like Qt Linguist for translation. I don't see a reason to change that ;-)
