### ISSUE TITLE
Make Veyon service unit file multi-seat capable

### ISSUE THREAD

**Issue by lbssousa** [veyon/veyon#270]
I know that veyon-service binary accept a `-session` parameter which shifts its ports numbers, making it suitable for multi-seat setups. However upcoming 4.1 systemd unit file for veyon-service seems not aware of this possibility.

Maybe converting it into a parametrized one (I mean, a `veyon-service@.service` file, where the parameter should be passed to `-session` argument), or even making veyon-service itself shift port numbers by default, based on `XDG_SEAT` or `XDG_SESSION_ID` values, would be fine.

**Comment by tobydox** [comment]
That's an excellent proposal! Let's keep this in mind for 4.2!

**Comment by tobydox** [comment]
Added to our roadmap at https://github.com/veyon/veyon/wiki/Roadmap

**Comment by tobydox** [comment]
You can check out the latest source code which has basic multi session support for Linux (implementation for Windows still pending). If you can't compile on your own, wait for 4.1 Beta in a few days.
