### ISSUE TITLE
authenication failed or access denied

### ISSUE THREAD

**Issue by krazi16** [veyon/veyon#271]
Hi,
I am unable to connect to a remote session using veyon.  I've imported the keys to the master and exported to the clients.  I also turned off logon authentication, but I still can't connect.  I get message authentication failed or access denied when i put my mouse cursor over the computer that I'm trying to connect to in the master window.  Am I missing something or is this a port forwarding issue?

**Comment by jradxl** [comment]
I'm have a similar issue too!!
2018-02-22T18:03:36.709: [WARN] ServerAuthenticationManager: empty list of allowed IPs

Where is the "List of allowed IPs" configured?

I have this is the client's computer (the pupil's computer) on Debian 9, in /var/log/VeyonService.log
I too have exported and imported the keys - that got rid of the error messages about the Teacher's name.
But in the Configurator on the client, in Access Control, I can't see where a list of allowed IPs could go,
I've tried adding a Room, entering the Teacher's IP, and then making a Rule that refers to the Room. But that hasn't worked.

Please advise
Thx

**Comment by willianpts** [comment]
I've deployed Veyon on some computers using Ubuntu/Debian and everytime I've seen this error it was caused by:
- Keys not installed correctly on client; be sure that the current user has read permissions on the keys and the service is running

- Mismatched veyon config; export your config from the master and import on the cleint [as described in the docs.](http://veyon.readthedocs.io/en/latest/admin/configuration.html#importing-exporting-a-configuration).

**Comment by tobydox** [comment]
Did you solve the issue in the meanwile?

**Comment by krazi16** [comment]
yes, it had to do with a problem in our apartment's network.  I tried it on
another network and it worked fine.  Make sure to check your port
forwarding options on your router and if you have windows defender, make
sure to disable the firewall.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by tobydox** [comment]
Ok, perfect! Thanks for the feedback!

**Comment by matydelomas** [comment]
Hello

I was using version 4.0.7.0 and everything worked perfect.

update all the PCs to version 4.1.7.1 and in several the authentication error occurred. I can not solve. Please help!
![veyon 1111](https://user-images.githubusercontent.com/47567509/52645667-f7a61a00-2ebf-11e9-8e91-cf242f3f64e9.JPG)

**Comment by slm1977** [comment]
I'm having the same problem. I have a room with one master and 17 clients (the veyon configuration seems ok (all client ip has been specified) and also the lan connection works) , but I don't know why only 3 clients on 16 properly connect  to the master: for the remaining clients I get the message "authentication failed or access denied". Any suggestions for solving the problem?

**Comment by tobydox** [comment]
Please upgrade to Veyon 4.2 where we improved user authentication.

**Comment by matydelomas** [comment]
thanks my friend!!

________________________________
De: Tobias Junghans <notifications@github.com>
Enviado: miércoles, 19 de junio de 2019 15:30
Para: veyon/veyon
Cc: matydelomas; Comment
Asunto: Re: [veyon/veyon] authenication failed or access denied (#271)


Please upgrade to Veyon 4.2 where we improved user authentication.
