### ISSUE TITLE
browser proxy

### ISSUE THREAD

**Issue by andrecesarlino** [veyon/veyon#272]
Hi, who can i create a code to execute to open the browser and research a website and use a user proxy like,
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
"open www.google.com.br"
user: "1V" pass: "word"

i know that i can open website in the options but in my lab i have this proxy, and when a have to teach littlekids i have to do manually.
obs. my proxy open in a box from the browser is not like a website proxy.
obs 2. I can't take it off, cause i have older children, and them have their own users.

**Comment by tobydox** [comment]
Thank you for your feedback! I guess you want to fill a password dialog automatically? Unfortunately this is not supported by Veyon as everything which happens inside the browser is out of Veyon's control. Veyon can only start the browser.
