### ISSUE TITLE
can i run veyon on windows 10

### ISSUE THREAD

**Issue by asif138** [veyon/veyon#274]
hi all
can i run veyon on windows 10?
is there any other requirements?

Thnaks,
Asif

**Comment by Fiala06** [comment]
Yes works fine. Currently running it on ~1000 Win10 machines. Not sure about requirements.

**Comment by tobydox** [comment]
Veyon is compatible with Windows 10. Please see http://docs.veyon.io/en/latest/admin/installation.html#system-requirements for more details.
