### ISSUE TITLE
NO access to computer mac address by LDAP on AD

### ISSUE THREAD

**Issue by mmeyer56** [veyon/veyon#275]
I used the LDAP method (connection to AD Windows 2012R2 standard Server) to control the computers.
I configured all the option of LDAP and all works fine to access correctly rooms and computers in rooms, users.
But only the field for the MAC address attribute is not OK. I tested nothing, hwAddress, dhcpAddress or macAddress (attribute listed on schema AD) but none of them work.

Is there a bug or not implemented ? Is someone is experimented this ok ?
WOL is not possible by this way ?

**Comment by ldlx** [comment]
Windows clients are not storing their MAC address(es!) in the computer object in AD. First you need an AD attribute where you can store the MAC address, e. g. by using an existing attribute like "wwwHomepage" or extend the AD Scheme (in my AD scheme none of the attributes you mentioned exist). You need to store the MAC address in the AD object yourself. 

I gave the members of the domain computers group write access to "SELF" and stored the MAC address of the first physical LAN-Adapter in it by using a PowerShell startup script (install RSAT tools + enable AD PowerShell feature).

**Comment by tobydox** [comment]
@ldlx: thanks for the explanation! I added it to our manual at http://veyon.readthedocs.io/en/latest/admin/ldap.html#index-19
