### ISSUE TITLE
veyon-service crashes on linux

### ISSUE THREAD

**Issue by goeba** [veyon/veyon#276]
I am using 4.04 , rpm for suse.

I have set up a room, can view the clients. When I remote-view or remote-control a client, veyon-service crashes on that client and the connection is lost.

Maybe there is a workaround.

Edit: I´ve tried today in a different room with different hardware. Here the problem did not occur, so it seems to be hardware dependent. (end edit)

This is the output of the veyon-service of the client:

PORT=11200
veyon-service > veyon_problem.txt
2018-02-28T15:12:02.918: [INFO] Exec
28/02/2018 15:12:02 passing arg to libvncserver: -rfbport
28/02/2018 15:12:02 passing arg to libvncserver: 11200
28/02/2018 15:12:02 passing arg to libvncserver: -passwd
28/02/2018 15:12:02 x11vnc version: 4.0.4 lastmod: 2015-11-14  pid: 2658
28/02/2018 15:12:02 Using X display :0
28/02/2018 15:12:02 rootwin: 0xa3 reswin: 0x3800001 dpy: 0x60007d40
28/02/2018 15:12:02 
28/02/2018 15:12:02 ------------------ USEFUL INFORMATION ------------------
28/02/2018 15:12:02 X DAMAGE available on display, using it for polling hints.
28/02/2018 15:12:02   To disable this behavior use: '-noxdamage'
28/02/2018 15:12:02 
28/02/2018 15:12:02   Most compositing window managers like 'compiz' or 'beryl'
28/02/2018 15:12:02   cause X DAMAGE to fail, and so you may not see any screen
28/02/2018 15:12:02   updates via VNC.  Either disable 'compiz' (recommended) or
28/02/2018 15:12:02   supply the x11vnc '-noxdamage' command line option.
28/02/2018 15:12:02 
28/02/2018 15:12:02 Wireframing: -wireframe mode is in effect for window moves.
28/02/2018 15:12:02   If this yields undesired behavior (poor response, painting
28/02/2018 15:12:02   errors, etc) it may be disabled:
28/02/2018 15:12:02    - use '-nowf' to disable wireframing completely.
28/02/2018 15:12:02    - use '-nowcr' to disable the Copy Rectangle after the
28/02/2018 15:12:02      moved window is released in the new position.
28/02/2018 15:12:02   Also see the -help entry for tuning parameters.
28/02/2018 15:12:02   You can press 3 Alt_L's (Left "Alt" key) in a row to 
28/02/2018 15:12:02   repaint the screen, also see the -fixscreen option for
28/02/2018 15:12:02   periodic repaints.
28/02/2018 15:12:02 
28/02/2018 15:12:02 XFIXES available on display, resetting cursor mode
28/02/2018 15:12:02   to: '-cursor most'.
28/02/2018 15:12:02   to disable this behavior use: '-cursor arrow'
28/02/2018 15:12:02   or '-noxfixes'.
28/02/2018 15:12:02 using XFIXES for cursor drawing.
28/02/2018 15:12:02 GrabServer control via XTEST.
28/02/2018 15:12:02 
28/02/2018 15:12:02 Scroll Detection: -scrollcopyrect mode is in effect to
28/02/2018 15:12:02   use RECORD extension to try to detect scrolling windows
28/02/2018 15:12:02   (induced by either user keystroke or mouse input).
28/02/2018 15:12:02   If this yields undesired behavior (poor response, painting
28/02/2018 15:12:02   errors, etc) it may be disabled via: '-noscr'
28/02/2018 15:12:02   Also see the -help entry for tuning parameters.
28/02/2018 15:12:02   You can press 3 Alt_L's (Left "Alt" key) in a row to 
28/02/2018 15:12:02   repaint the screen, also see the -fixscreen option for
28/02/2018 15:12:02   periodic repaints.
28/02/2018 15:12:02 
28/02/2018 15:12:02 XKEYBOARD:
28/02/2018 15:12:02 Switching to -xkb mode to recover these keysyms:
28/02/2018 15:12:02    xkb  noxkb   Keysym  ("X" means present)
28/02/2018 15:12:02    ---  -----   -----------------------------
28/02/2018 15:12:02     X           0x40  at
28/02/2018 15:12:02     X           0x5b  bracketleft
28/02/2018 15:12:02     X           0x5d  bracketright
28/02/2018 15:12:02     X           0x7b  braceleft
28/02/2018 15:12:02     X           0x7d  braceright
28/02/2018 15:12:02     X           0x7c  bar
28/02/2018 15:12:02     X           0x5c  backslash
28/02/2018 15:12:02 
28/02/2018 15:12:02   If this makes the key mapping worse you can
28/02/2018 15:12:02   disable it with the "-noxkb" option.
28/02/2018 15:12:02 
28/02/2018 15:12:02 
28/02/2018 15:12:02 X FBPM extension not supported.
28/02/2018 15:12:02 X display is capable of DPMS.
28/02/2018 15:12:02 --------------------------------------------------------
28/02/2018 15:12:02 
28/02/2018 15:12:02 Default visual ID: 0x21
28/02/2018 15:12:02 Read initial data from X display into framebuffer.
28/02/2018 15:12:02 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/6720
28/02/2018 15:12:02 
28/02/2018 15:12:02 X display :0 is 32bpp depth=24 true color
28/02/2018 15:12:03 
28/02/2018 15:12:03 Listening for VNC connections on TCP port 11200
28/02/2018 15:12:03 rfbListenOnTCP6Port: error in bind IPv6 socket: Die angeforderte Adresse kann nicht zugewiesen werden
28/02/2018 15:12:03 listen6: bind: Die angeforderte Adresse kann nicht zugewiesen werden
28/02/2018 15:12:03 Not listening on IPv6 interface.
28/02/2018 15:12:03 
28/02/2018 15:12:03 Xinerama is present and active (e.g. multi-head).
28/02/2018 15:12:03 Xinerama: number of sub-screens: 1
28/02/2018 15:12:03 Xinerama: no blackouts needed (only one sub-screen)
28/02/2018 15:12:03 
28/02/2018 15:12:03 fb read rate: 216 MB/sec
28/02/2018 15:12:03 fast read: reset -wait  ms to: 10
28/02/2018 15:12:03 fast read: reset -defer ms to: 10
28/02/2018 15:12:03 The X server says there are 12 mouse buttons.
28/02/2018 15:12:03 screen setup finished.
28/02/2018 15:12:03 

The VNC desktop is:      localhost:5300
28/02/2018 15:12:03 possible aliases:  localhost:11200, localhost::11200

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval.  It should work with any VNC viewer.  Try it by running:

    x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

2018-02-28T15:12:03.073: [INFO] Running worker for feature "Icon im Infobereich"
28/02/2018 15:12:03 Got connection from client 127.0.0.1
28/02/2018 15:12:03   other clients:
28/02/2018 15:12:03 check_access: client 127.0.0.1 matches host 127.0.0.1
28/02/2018 15:12:03 incr accepted_client=1 for 127.0.0.1:46128  sock=24
28/02/2018 15:12:03 Client Protocol Version 3.8
28/02/2018 15:12:03 Protocol version sent 3.8, using 3.8
28/02/2018 15:12:03 rfbProcessClientSecurityType: executing handler for type 2
28/02/2018 15:12:03 copy_tiles: allocating first_line at size 54
28/02/2018 15:12:03 Pixel format for client 127.0.0.1:
28/02/2018 15:12:03   32 bpp, depth 24, little endian
28/02/2018 15:12:03   true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0
28/02/2018 15:12:03 no translation needed
28/02/2018 15:12:03 rfbProcessClientNormalMessage: ignoring unsupported encoding type ultraZip
28/02/2018 15:12:03 Using compression level 9 for client 127.0.0.1
28/02/2018 15:12:03 Enabling KeyboardLedState protocol extension for client 127.0.0.1
28/02/2018 15:12:03 Enabling NewFBSize protocol extension for client 127.0.0.1
28/02/2018 15:12:03 Enabling SupportedMessages protocol extension for client 127.0.0.1
28/02/2018 15:12:03 Enabling SupportedEncodings protocol extension for client 127.0.0.1
28/02/2018 15:12:03 Enabling ServerIdentity protocol extension for client 127.0.0.1
28/02/2018 15:12:03 Using ZRLE encoding for client 127.0.0.1
28/02/2018 15:12:07 client 1 network rate 74,7 KB/sec (6954,3 eff KB/sec)
28/02/2018 15:12:07 client 1 latency:  0,5 ms
28/02/2018 15:12:07 dt1: 0,0279, dt2: 0,9868 dt3: 0,0005 bytes: 75822
28/02/2018 15:12:07 link_rate: LR_BROADBAND - 1 ms, 74 KB/s
28/02/2018 15:12:07 client_set_net: 127.0.0.1  0,0000
28/02/2018 15:12:07 created   xdamage object: 0x3800039
28/02/2018 15:12:13 called initialize_xfixes()
28/02/2018 15:12:13 Got connection from client 127.0.0.1
28/02/2018 15:12:13   other clients:
28/02/2018 15:12:13      127.0.0.1
28/02/2018 15:12:13 check_access: client 127.0.0.1 matches host 127.0.0.1
28/02/2018 15:12:13 incr accepted_client=2 for 127.0.0.1:46132  sock=28
28/02/2018 15:12:13 Client Protocol Version 3.8
28/02/2018 15:12:13 Protocol version sent 3.8, using 3.8
28/02/2018 15:12:13 rfbProcessClientSecurityType: executing handler for type 2
28/02/2018 15:12:13 Pixel format for client 127.0.0.1:
28/02/2018 15:12:13   32 bpp, depth 24, little endian
28/02/2018 15:12:13   true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0
28/02/2018 15:12:13 no translation needed
28/02/2018 15:12:13 Enabling KeyboardLedState protocol extension for client 127.0.0.1
28/02/2018 15:12:13 Enabling NewFBSize protocol extension for client 127.0.0.1
28/02/2018 15:12:13 Enabling SupportedMessages protocol extension for client 127.0.0.1
28/02/2018 15:12:13 Enabling SupportedEncodings protocol extension for client 127.0.0.1
28/02/2018 15:12:13 Enabling ServerIdentity protocol extension for client 127.0.0.1
28/02/2018 15:12:13 Using hextile encoding for client 127.0.0.1
28/02/2018 15:12:14 client 2 network rate 194,4 KB/sec (16274,5 eff KB/sec)
28/02/2018 15:12:14 client 2 latency:  0,5 ms
28/02/2018 15:12:14 dt1: 0,0165, dt2: 0,4171 dt3: 0,0005 bytes: 84272
28/02/2018 15:12:14 link_rate: LR_BROADBAND - 1 ms, 74 KB/s
28/02/2018 15:12:14 client_set_net: 127.0.0.1  0,0000
28/02/2018 15:12:20 increased wireframe timeouts for slow network connection.
28/02/2018 15:12:20 netrate: 74 KB/sec, latency: 1 ms
caught XIO error:
28/02/2018 15:12:21 deleted 53 tile_row polling images.
sjamuell1@m298:~>

**Comment by goeba** [comment]
Hi,
I have now found out that the crashes don´t occur when I use the -noxdamage flag for x11vnc.

Disabling xdamage decreases performance, that is the downside.

**Comment by tobydox** [comment]
Thanks for the investigation! It's a problem with x11vnc then which I can't fix. Have you tried to update to 4.0.5 which has a few build-system related fixes for x11vnc?

**Comment by goeba** [comment]
Hi,
I have not yet tried that, but I am very sure that it´s a KDE related issue, because the xcb-related crashes occur with other vnc-servers, too.
Those crashes do not occur when using a different Desktop environment (xfce, for instance), and they also do not occur when using a newer KDE + QT combination (I have tried Opensuse Tubmleweed for that).
So I would consider thad bug as "fixed", but it is still a problem for me, as I had hoped to be able to use Opensuse Leap 42.3 for the next year at least. Upgrading QT + KDE on that system is not trivial, as some standard-packages rely on the older QT 5.6 Version that ships with Leap 42.3. Sigh ...

**Comment by tobydox** [comment]
Thank you for your feedback! I added an according entry to the troubleshooting chapter in the admin manual.
