### ISSUE TITLE
Removing the remote access input text dialog

### ISSUE THREAD

**Issue by mvcmaker** [veyon/veyon#281]
Hi, when you want to get control or view from a selected client pc on the pc list, a dialog with the title "remote access" appears and you must to put the ip or hostname destination. There's any way to avoid this dialog, due you've selected the remote pc before and this information should be accessible before.

**Comment by tobydox** [comment]
Thanks for your feedback! You must select only one computer when using the global "remote control" operation. If none or more than one computer is selected it will ask for the computer to remote control (which is an intended feature to quickly also control computers which are not shown). Alternatively use the context menu and/or configure "remote control" to be the default feature on double click.
