### ISSUE TITLE
Error starting Veyon Master when using key authentication

### ISSUE THREAD

**Issue by stephaniebamerico** [veyon/veyon#284]
I'm having trouble setting up veyon. I followed the instructions for authentication by key (login authentication disabled). I generated the keys in the master and imported in the client. But when trying to start Veyon master, I find the following message and Veyon is not started: "No key authentication files are found or existing ones are outdated." When login authentication is enabled Veyon Master starts without errors, but I can not authenticate with the client.

I've been trying to find a solution for two days and I'm about to give up. Too bad, because the system looks incredible. Can someone help me to find the problem?

**Comment by stephaniebamerico** [comment]
The problem is that the Veyon Master needs to be run with root permission to find the keys. There is a simple way to ensure that the user runs as root, I believe I would avoid these problems.
But thank you very much, the tool is wonderful!

**Comment by lbssousa** [comment]
I suspect this problems affects Veyon for Linux, specifically. I think there should be another way to start Veyon Master as a normal user in Linux with key authentication (Epoptes, for example, creates a special group that owns the daemon sockets, and any user belonging to that group is able to launch Epoptes-server GUI).

**Comment by lbssousa** [comment]
@stephaniebamerico, to be able to run Veyon Master with key authentication as a normal user on Linux, this user must have read access to e.g. `/etc/veyon/keys/private/teacher/key`.

@tobydox maybe a good practice here for Veyon Master install under Linux is to create a special group (e.g. `veyon-<role>`) with read access to `/etc/veyon/keys/private/<role>/key`. Then I would add myself to `veyon-<role>` group to be able to run Veyon Master with key authentication.

**Comment by tobydox** [comment]
Thanks for your feedback!

@stephaniebamerico You have to change the group of the key file in order to make it accessible by normal users.

@lbssousa In Veyon 4.1 there's dedicated support for assigning auth keys to user groups which will automatically adjust file permissions and owner - feel free to test the Alpha version we released today :-)

**Comment by RadenCrypton** [comment]
You have to run it with root access in linux. there are several ways including by running command `sudo veyon-master`
