### ISSUE TITLE
Windows 10 veyon client freezing when running some softwares with veyon master

### ISSUE THREAD

**Issue by orion777** [veyon/veyon#285]
Hello

When our students are running some programs like Solidworks or Sweethome 3d, windows 10 clients are freezing and nothing is working. The problem is solved when the Veyon master is closed. 
Then the programs are launching and running. But when the Veyon master is started then programs are freezing again. I tested with Sweethome 3d and Solidworks but it is possible that another programs have the same problem when running.
It is a big problem. This problem is experienced also wjth the latest Veyon version.
Any idea to fix this?
thanks you very much for your help

**Comment by orion777** [comment]
I specifiy that our windows 10 client are in a samba domain with login sessions.
Same problem when login another user.

**Comment by tobydox** [comment]
Can you try with Veyon 4.1 Alpha? It comes with an updated VNC server which might fix your issue.

**Comment by tobydox** [comment]
I guess this is related to #295 - therefore I'm closing this ;-)
