### ISSUE TITLE
Text message

### ISSUE THREAD

**Issue by cesarpineda1307** [veyon/veyon#286]
When a text message is sent, the user does not show it, but it is sent behind the open windows.
I suggest that the text box be shown in front of everyone.

I do not know if I can understand?

**Comment by tobydox** [comment]
Which operating system do you use? On Windows bringing dialogs to front does not work due to restrictive UI policies of Microsoft :-/

**Comment by cesarpineda1307** [comment]
I use Windows 7, it does work sending message but if there are windows open, that message is behind all the windows

**Comment by tobydox** [comment]
Unfortunately there's no official way of bringing dialogs to front on Windows. Microsoft prevents this kind of application behaviour for UI experience and security reasons.
