### ISSUE TITLE
Veyon-Configurator not start - Error

### ISSUE THREAD

**Issue by pauloboc** [veyon/veyon#287]
```
sudo apt-get update
sudo apt-get upgrade

sudo apt install g++ make cmake qtbase5-dev qtbase5-dev-tools qttools5-dev qttools5-dev-tools xorg-dev libxtst-dev libjpeg-dev zlib1g-dev libssl-dev libpam0g-dev libprocps-dev liblzo2-dev libqca2-dev libqca-qt5-2-dev libldap2-dev

sudo apt install git

git clone --recursive https://github.com/veyon/veyon.git && cd veyon

mkdir build
cd build
cmake ..
make -j4

fakeroot make package

sudo dpkg -i veyon_4.0.4_amd64.deb 

sudo veyon-configurator
```

user@mac:~$ sudo veyon-configurator 
sudo: unable to resolve host mac
Adding plugin search path "/usr/local/lib/veyon"
PluginManager: discovered plugin "LinuxPlatformPlugin" at "/usr/local/lib/veyon/linux-platform.so"
2018-03-17T11:03:55.631: [ERR] InternetAccessControl::initBackend(): no internet access control backend plugin found!
● veyon-service.service - Veyon Service
   Loaded: loaded (/lib/systemd/system/veyon-service.service; disabled; vendor p
   Active: inactive (dead)
lines 1-3/3 (END)

-----------------------------------------
Ubuntu Xenial  64bits
COMMITS  3,521

**Comment by tobydox** [comment]
The documentation for building Veyon is for the master branch only. This means you built the current development version instead of the stable 4.0.x series. This is not a problem as the veyon-configurator should work even with the master branch. Can you please try to launch veyon-configurator without "sudo"? It should invoke the proper graphical sudo dialog automatically. Please remove any other Veyon-related files before. Also I recommend to run cmake with "-DCMAKE_INSTALL_PREFIX=/usr" so the binaries inside the generated packages are located in /usr/bin instead of /usr/local/bin.

**Comment by pauloboc** [comment]
I compiled with "-DCMAKE_INSTALL_PREFIX=/usr"
continue with error

```
usuario@mac:~$ veyon-configurator 
Adding plugin search path "/usr/lib/x86_64-linux-gnu/veyon"
PluginManager: discovered plugin "LinuxPlatformPlugin" at "/usr/lib/x86_64-linux-gnu/veyon/linux-platform.so"
QIODevice::write (QFile, "/tmp/VeyonConfigurator.log"): device not open
2018-03-19T20:15:50.173: [ERR] InternetAccessControl::initBackend(): no internet access control backend plugin found!
Adding plugin search path "/usr/lib/x86_64-linux-gnu/veyon"
PluginManager: discovered plugin "LinuxPlatformPlugin" at "/usr/lib/x86_64-linux-gnu/veyon/linux-platform.so"
2018-03-19T20:15:54.659: [ERR] InternetAccessControl::initBackend(): no internet access control backend plugin found!
● veyon-service.service - Veyon Service
   Loaded: loaded (/lib/systemd/system/veyon-service.service; disabled; vendor p
   Active: inactive (dead)
lines 1-3/3 (END)
```

Ubuntu Xenial 64bits
COMMIT 3,531

Can you compile a pre-reliase 4.1 to test with autostart?

**Comment by tobydox** [comment]
This is related to #310 and has been fixed already. You can compile the latest version (make sure to remove all old plugins in /usr/lib/*/veyon/* before installing) or wait for 4.1 Beta. Thanks again for reporting!
