### ISSUE TITLE
using veyon-ctl to import a local computer room config

### ISSUE THREAD

**Issue by itkpeter** [veyon/veyon#289]
Hello,

I'm using Veyon 4.0.5 on W10 x64.
I would like to use veyon-ctl to export/import just a custom computer room config while leaving the rest of the config untouched.
In the configurator I set up a demo computer room with 3 computers to determine which value and syntax I have to use. 

With the command
`veyon-ctl.exe config get LocalData/NetworkObjects`
I get this output:
`[{Name:Computerraum,Type:2,Uid:{13a1098c-b8fc-4d08-be02-70f1e8ac679d}},{HostAddress:192.168.123.101,MacAddress:00:AA:BB:12:34:01,Name:PC01,ParentUid:{13a1098c-b8fc-4d08-be02-70f1e8ac679d},Type:3,Uid:{542a96e1-3673-4ee4-b3d7-ee4b4213be7a}},{HostAddress:192.168.123.102,MacAddress:00:AA:BB:12:34:02,Name:PC02,ParentUid:{13a1098c-b8fc-4d08-be02-70f1e8ac679d},Type:3,Uid:{e7463d74-f107-48be-8c08-859abbe922c5}},{HostAddress:192.168.123.103,MacAddress:00:AA:BB:12:34:03,Name:PC03,ParentUid:{13a1098c-b8fc-4d08-be02-70f1e8ac679d},Type:3,Uid:{6ec1fded-da79-49cf-ae3b-fab2f54ab668}}]`

now I clear the value:
`veyon-ctl.exe config unset LocalData/NetworkObjects`
and set it again to the previously output value:
`veyon-ctl.exe config set LocalData/NetworkObjects [{Name:Computerraum,Type:2,Uid:{13a1098c-b8fc-4d08-be02-70f1e8ac679d}},{HostAddress:192.168.123.101,MacAddress:00:AA:BB:12:34:01,Name:PC01,ParentUid:{13a1098c-b8fc-4d08-be02-70f1e8ac679d},Type:3,Uid:{542a96e1-3673-4ee4-b3d7-ee4b4213be7a}},{HostAddress:192.168.123.102,MacAddress:00:AA:BB:12:34:02,Name:PC02,ParentUid:{13a1098c-b8fc-4d08-be02-70f1e8ac679d},Type:3,Uid:{e7463d74-f107-48be-8c08-859abbe922c5}},{HostAddress:192.168.123.103,MacAddress:00:AA:BB:12:34:03,Name:PC03,ParentUid:{13a1098c-b8fc-4d08-be02-70f1e8ac679d},Type:3,Uid:{6ec1fded-da79-49cf-ae3b-fab2f54ab668}}]`

the output of `veyon-ctl.exe config get LocalData/NetworkObjects` stays the same, but the objects won't show up in configurator or master anymore.

when exporting the original config, the JSON lines of my computer room look like this:
```
    "LocalData": {
        "NetworkObjects": {
            "JsonStoreArray": [
                {
                    "Name": "Computerraum",
                    "Type": 2,
                    "Uid": "{13a1098c-b8fc-4d08-be02-70f1e8ac679d}"
                },
                {
                    "HostAddress": "192.168.123.101",
                    "MacAddress": "00:AA:BB:12:34:01",
                    "Name": "PC01",
                    "ParentUid": "{13a1098c-b8fc-4d08-be02-70f1e8ac679d}",
                    "Type": 3,
                    "Uid": "{542a96e1-3673-4ee4-b3d7-ee4b4213be7a}"
                },
                {
                    "HostAddress": "192.168.123.102",
                    "MacAddress": "00:AA:BB:12:34:02",
                    "Name": "PC02",
                    "ParentUid": "{13a1098c-b8fc-4d08-be02-70f1e8ac679d}",
                    "Type": 3,
                    "Uid": "{e7463d74-f107-48be-8c08-859abbe922c5}"
                },
                {
                    "HostAddress": "192.168.123.103",
                    "MacAddress": "00:AA:BB:12:34:03",
                    "Name": "PC03",
                    "ParentUid": "{13a1098c-b8fc-4d08-be02-70f1e8ac679d}",
                    "Type": 3,
                    "Uid": "{6ec1fded-da79-49cf-ae3b-fab2f54ab668}"
                }
            ]
        }
    },
```

when exporting the config of my veyon-ctl imported computer room, it looks like this:
```
    "LocalData": {
        "NetworkObjects": "[{Name:Computerraum,Type:2,Uid:{13a1098c-b8fc-4d08-be02-70f1e8ac679d}},{HostAddress:192.168.123.101,MacAddress:00:AA:BB:12:34:01,Name:PC01,ParentUid:{13a1098c-b8fc-4d08-be02-70f1e8ac679d},Type:3,Uid:{542a96e1-3673-4ee4-b3d7-ee4b4213be7a}},{HostAddress:192.168.123.102,MacAddress:00:AA:BB:12:34:02,Name:PC02,ParentUid:{13a1098c-b8fc-4d08-be02-70f1e8ac679d},Type:3,Uid:{e7463d74-f107-48be-8c08-859abbe922c5}},{HostAddress:192.168.123.103,MacAddress:00:AA:BB:12:34:03,Name:PC03,ParentUid:{13a1098c-b8fc-4d08-be02-70f1e8ac679d},Type:3,Uid:{6ec1fded-da79-49cf-ae3b-fab2f54ab668}}]"
    },
```
It seems not to be treaten as a "JsonStoreArray" but as a single text value.
veyon-ctl should recognize a given value surrounded by square brackets to be a JsonStoreArray. Could you fix this or give me a hint for a workaround?

Thanks in advance
Peter

**Comment by tobydox** [comment]
Dealing with JSON data inside the configuration is a bit difficult with the config CLI module. Nevertheless there's a (probably not yet properly documented) way of setting JSON data: pass "json" as the 3rd argument to "config set", e.g.

    veyon-ctl config set LocalData/NetworkObjects "[{Name:Computerraum,Type:2 .... ]" json

In Veyon 4.1 we'll have a dedicated CLI module for managing computer rooms and objects so you won't have to deal with the JSON data any longer :-)

**Comment by itkpeter** [comment]
Thanks for the hint, but when I try it, the value of "LocalData/NetworkObjects" is just set to ``[]``.
I tried several possibilities, with single and double quotes at various positions, with additional ``JsonStoreArray:[...]``, with and without square brackets, but it was always set to ``[]``.

Taking a look at the corresponding registry key "HKLM\Software\Veyon Solutions\Veyon\LocalData" with my working original config, it has:
``NetworkObjects="@@JsonValue(<Base64encodeddata>)"``

When I decode the Base64 data, I get my computer room array, wrapped around by an "a:{...}".
So I tried the same steps above with that data, still without success.

Then I encoded that string back to Base64 and finally had success with:
``veyon-ctl config set LocalData/NetworkObjects @JsonValue(<Base64encodeddata>)``

My goal is to write a little installer wrapper with AutoIt for installing Veyon in computer rooms without a server. It would do the following steps:
- install service and master on 1st machine and generate a key pair
- create a new folder at installer location (eg. usb key) with public key and a csv file for room data
- install the service on the remaining machines, import public key, read Name, MAC and IP of every machine and put it in the csv
- import the csv into the config of master on 1st machine

With iTALC and GlobalConfig.xml it worked like a charm, but moving to Veyon and the JSON config the last step is where I have this issue. So I'll try to put Base64 encoding into my script for getting this to go.

When do you plan to release 4.1? Do I have to change my installer again then?

**Comment by tobydox** [comment]
I'm glad you found a workaround! An alpha version will be released in April so you'll be able to test the new CLI module which will also include CSV import support.

**Comment by tobydox** [comment]
Please checkout Veyon 4.1 Alpha which has full support for data import as well as network object management.
