### ISSUE TITLE
Configuration Problem

### ISSUE THREAD

**Issue by valluminarias** [veyon/veyon#29]
I have problem configuring my veyon setup, I cannot successfully do the remote control. It says Authentication not successful. Can you give a detailed way on how to configure. Anyways great app.

**Comment by tobydox** [comment]
Currently there's only a German manual but you can translate it to your favourite language via Google: https://translate.google.com/translate?hl=en&sl=de&tl=en&u=http%3A%2F%2Fveyon.readthedocs.io%2Fde%2Flatest%2Fadmin%2Fconfiguration.html&sandbox=1

**Comment by onlurking** [comment]
@valluminarias Veyon shares a lot in common with iTALCS, maybe you need to turn off the ```Logon authentication``` and just enable the ```Key file authentication```, i've managed to get up and running in a entire school following this [video](https://www.youtube.com/watch?v=OnM0cCGtVdI), the ```Logon authentication``` in Veyon would be the "```ACL based logon authentication```" on iTALC.

**Comment by valluminarias** [comment]
Thanks for the reply, I'll do all your suggestions later.

**Comment by forstera** [comment]
Hello all, 
I followed the video proposed by Onlurking (key file authentication) but still impossible to connect to a remote client. I always get the following error if restarting the service on the remote client :  user .. tried to access this computer but could not authenticate sucessfully. 
In both computer I've the option key file authentication. I genereated the public key from the master and copied it to the $GLOBALAPPDATA\keys\private folder (importing the key failed).
Any suggestion is really welcomed :)
Thanks to all from your help

**Comment by Lrobben52** [comment]
**@forstera** Copy the folder "C:\ProgramData\Veyon\keys\public\teacher\" (public and private) with the keys from the master PC to the student PC. Also turn off the Logon authentication and just enable the Key file authentication on both PC's.

**Comment by valluminarias** [comment]
Thanks for the reply, I got my setup working now. Thanks for the video @onlurking, it's very helpful.

**Comment by forstera** [comment]
Works like a charm now, thanks very much : )

**Comment by tobydox** [comment]
Glad it works now! However please note that you should not copy the private key to student computers! Otherwise students may be able to access other computers in your network even if Veyon Master is not installed (it can be downloaded and run standalone easily).

**Comment by jacobosanchez2019** [comment]
hello to all I have problems since I have everything that he has found on the internet but he does not connect me with the pc of the students and it can not be done if someone can help me my mail

jacsan2013@gmail.com
