### ISSUE TITLE
Hide user in monitoring

### ISSUE THREAD

**Issue by pauloboc** [veyon/veyon#291]
Can you add an option to hide the username on the monitoring screen?

Thanks

**Comment by 04amh1** [comment]
Just click "Computer Rooms" in the bottom left, and then uncheck everyone you want to hide :)

**Comment by tobydox** [comment]
Welcome to Veyon! There's currently no option for changing this behaviour. It would be possible to do that but currently has a rather low priority so I can't make any promises when it will be available. Feel free to prioritize via a donation to the Veyon project ;-)
