### ISSUE TITLE
Future Suggestion

### ISSUE THREAD

**Issue by 04amh1** [veyon/veyon#294]
Before I start, can I please just say how brilliant Veyon is! It is an incredible program and I am thrilled to be able to use it in a classroom environment...

I just have a couple of suggestions for future versions (please ignore me if this isn't feasible or practical)..

1. Ability to disable internet
2. Ability to mute volume/control volume levels

Once again, thank you so much for this amazing program, and I will continue to use it indefinitely!

**Comment by 04amh1** [comment]
Thank you for your reply.

I appreciate your suggestion, but I was hoping to be able to control specific PC's easily... ie, once a student has finished their work they are allowed to play games on the internet. The problem is some students will finish quickly and instantly get onto games and others will not...

**Comment by ciampix** [comment]
Yes, I mean if the veyon client control the client PC gateway then you can control who (which student) is allowed to go to the Internet and who is not.

**Comment by tobydox** [comment]
Thank you for your positive feedback! :-)

A plugin for internet access control is currently being developed and will be part of future releases even though I can't promise a definite release date yet.

As for changing volume levels you can use the "run program" feature and use 3rdparty tools such as NirCmd (see https://www.nirsoft.net/utils/nircmd.html for details). In Veyon 4.1 we'll have support for running predefined programs so you'll be able to configure custom commands which are available through submenus in Veyon Master.
