### ISSUE TITLE
Wake on Lan on Veyon 4.0.5

### ISSUE THREAD

**Issue by googleman26** [veyon/veyon#298]
Good Day!

Why is that i cannot remote power on my client pc thru veyon?

I already set the MAC address  and IP address to my master computer but i cannot power it on..

**Comment by jamj2000** [comment]
Have you enabled WOL (Wake On LAN) in BIOS?

**Comment by googleman26** [comment]
Good morning!!

Yes, i already enabled WOL on PC BIOS.
I set static ip address on all the PC's and i can see them all ung master PC.

and one more thing .. once i locked all the PC's it locked but on windows 8 Pro i can still click Ctrl Alt Del on windows 8 client pc

**Comment by tobydox** [comment]
Does WOL work with other tools besides Veyon? Are the computers in the same subnet?

Regarding the locking issue: can you try to install the Interception driver at https://github.com/oblitum/Interception/releases/download/v1.0.1/Interception.zip manually? Run "install-interception /install"

**Comment by googleman26** [comment]
do i really need to install it one by one on all windows 8 pc?

**Comment by googleman26** [comment]
Yes it works now the WOL!! and it is on the same subnet.

**Comment by tobydox** [comment]
Perfect, thanks for the feedback!
