### ISSUE TITLE
Impossible to import the key under windows 10

### ISSUE THREAD

**Issue by forstera** [veyon/veyon#30]
Hello all, 
I'm trying to install veyon for a school (thanks for your work) but under windows 10 I always get the following error : 
An error occured while importing the public access key. You probably are not permitted to read the source key or to write the destination file.

I tried to start Veyon configuration in admin mode, changed the destination folder, deactivated the UAC but still can't import the key. If someone has an idea :) 
Per advance, thanks to all for your help :)

**Comment by tobydox** [comment]
This seems to be the same issue as #17. You can try to create C:\ProgramData\Veyon\keys manually. We'll fix it in the next release.

**Comment by forstera** [comment]
Hello again, 
Thanks for the answer. According to the Summary displayed before starting the import of the key, it seems it's just a '/' problem used instead of '\' ? 

it's written : Import acces key from c:/MyfilePlace/privatekey.key.txt  but shouldnt it be  c:\MyFilePlace\private\key.key.txt  ? 

Thanks for your job :)

**Comment by tobydox** [comment]
Fixed via 74ebe72 which will be included in Veyon 4.0 RC2.
