### ISSUE TITLE
veyon service not starting on mint/elementary

### ISSUE THREAD

**Issue by tltucker** [veyon/veyon#300]
New to Veyon, I am running 2 different machines. One running linux mint 18.3, the other elementary loki. 

I installed the 4.05 version of veyon and the configurator comes up, but under services, the start service is greyed out on both of them.
![image](https://user-images.githubusercontent.com/34378870/37982372-05d2f8b2-31b6-11e8-830a-ccb9071795ef.png)

  I tried to sudo veyon-ctl register service on command line, then start the service, but it shows failed as well. 

This is before I have changed any of the major configurations..

What am I doing wrong?

**Comment by goeba** [comment]
The autostart feature does not work on linux (at least for now).
You will have to start veyon-service manually and then, if that works, establish some way of auto-starting that service.
I have done this by placing a suitable .desktop-file under /etc/xdg/autostart 

I think that the whole autostart-section in veyon-configurator should be greyed ot on linux with a warning that this must be done "by hand"!

**Comment by tltucker** [comment]
Thank you for your response... I got it to work...

The only problem I am having now is it is not working on linux machines that authenticate to a domain. It says it's working (the service is running) but the master does not see the machine...

Any linux machines that are not authenticating to the domain seem to work. I am going to work more on this, but that is where I stand at the moment.

Also, the linux machines will not power off or reboot via command from the master, it seems to ignore it.

**Comment by goeba** [comment]
I don´t know exactly what you mean by "domain", as it is a windows-term.

How do you identify your clients, via host name, ip-adress or mac ? It is likely that joining your domain changes the name of the clients, thus veyon won´t find them anymore.

There might be other reasons. If I debug this kind of stuff, first thing to do is ping the clients from the master. If that works, you´ll have to investigate further.

**Comment by tltucker** [comment]
I found the problem. 

The client generates firewall settings when it joins the domain. 

I had to add your firewall exceptions to the firewall settings. 

The system I am using is linuxschools, a server and client based system designed for schools. It has a samba4 domain (acts like an active directory domain). You can join windows and linux clients to this domain. 

You can read my discussion on the linux schools forums about the veyon problem here, for anyone who is having a similar problem.

https://www.linuxschools.com/forum/viewtopic.php?f=5&t=778&p=4359#p4359

**Comment by goeba** [comment]
Hi,
very interesting. I use a linux-server for our school, too (www.openschoolserver.net). We will switch to samba4 this summer, so maybe I´ll run into similar problems then.
I have, by the way, turned off the firewall on the clients. I thought it would be overkill to have a firewall in an internal network when we have one on the server anyway.

**Comment by tobydox** [comment]
Thanks for your feedback! Veyon 4.1 has builtin systemd support for the service so it should start automatically. You can try the alpha version released today. Feel free to open a new issue if you still have problems with 4.1 alpha.
