### ISSUE TITLE
windows registering and starting service issues.

### ISSUE THREAD

**Issue by tltucker** [veyon/veyon#303]
I have created a batch file to install veyon on my windows machines.
The installation works fine, but if I try to register or start the veyon service from a batch file I get the following:

![image](https://user-images.githubusercontent.com/34378870/38203937-8a73e040-3666-11e8-8a18-71db675c72fe.png)

If I click OK on this, it goes ahead and registers or starts the service, but the batch file will not continue until I do. 

How do I make it so it does not pop up a window?

Here is the commands I am using:
"c:\Program Files\Veyon\veyon-ctl.exe" service register
"c:\Program Files\Veyon\veyon-ctl.exe" service start

**Comment by tobydox** [comment]
For Veyon 4.0.x please use "......\veyon-service -quiet -registerservice" (important: run with administrative privileges!).

With Veyon 4.1.x onwards you'll be able to use veyon-ctl for this kind of operations. All feedback will be printed to standard output instead of showing popup dialogs.
