### ISSUE TITLE
Access Control Issue: Ask logged on user for permission 

### ISSUE THREAD

**Issue by hectorpuello** [veyon/veyon#306]
![image](https://user-images.githubusercontent.com/38078312/38318156-b980618c-37fc-11e8-97f8-5cd95ee6d5a0.png)

When i click on yes , the pc wich its inside on the room, when i try to view or remote control it keeps as it shows in the following photo:

![image](https://user-images.githubusercontent.com/38078312/38318381-2bc54d16-37fd-11e8-95eb-59ce18c9d8c5.png)

See my settings:

![image](https://user-images.githubusercontent.com/38078312/38318424-48246834-37fd-11e8-807d-122b3f7ebc62.png)

![image](https://user-images.githubusercontent.com/38078312/38318403-3b7426e2-37fd-11e8-9c88-029561728960.png)

The logs of the Veyon app are here:
[Logs.zip](https://github.com/veyon/veyon/files/1876532/Logs.zip)

**Comment by tobydox** [comment]
Welcome to Veyon! Did I get it right you want to ask for permissions if a computer outside the computer room accesses a computer (you checked the "Invert all conditions" option)? Does monitoring mode in Veyon Master work properly?

**Comment by hectorpuello** [comment]
**(you checked the "Invert all conditions" option)?**
I was testing with the rule figured in the image above, and it was partly working as its shows in the following image:
![image](https://user-images.githubusercontent.com/38078312/38992524-ffe2ded0-43ae-11e8-9408-f1f8b7b8f812.png)

But either if i create the same rule with an user condition, it will  do the same thing but when the alert appears to the monitored computers users and when they click on "Yes" or "Always for this session", nothing happens.....

That why i uploaded the log file of the application, so you guys can see the error

for example:

2018-04-04T10:03:25.828: [DEBUG] [LDAP] asyncSearch() base=" "OU=Computers,OU=suBmyEnterPrise,OU=myEnterPrise,DC=capgefi,DC=local" " scope= 2 filter=" "" " attrs= ()
2018-04-04T10:03:25.828: [DEBUG] [LDAP] ( 4 , 3000 ): Waiting 3000 msecs for result. Attempt # 1

**Does monitoring mode in Veyon Master work properly?**
Of course it´s working properly with the public key and with a ldap configuration.

**Comment by tobydox** [comment]
Key file authentication unfortunately might not work properly with access control rules as the user is not authenticated and thus can't be evaluated when processing access control rules. Can you try with logon authentication temporarily?

**Comment by tobydox** [comment]
Issue has been fixed in 4.2.x.
