### ISSUE TITLE
Login Remote Workstation

### ISSUE THREAD

**Issue by cgirdler** [veyon/veyon#31]
This is more of a suggestion than an issue, i've been trialing Veyon over our current remote support software, and it does everything we currently want to do, and quicker, except for one thing. It would be nice to have the ability to remotely login a batch of workstations with a provided credential.

Other than that, great piece of software.

**Comment by Lukasz3d2** [comment]
I'am waiting for this option, after that this will be best classroom managment software on web.

**Comment by tobydox** [comment]
We just need somebody who figures out how to make the winlogon screen login with given username and password. Unluckily I'm not aware of a generic mechanism for this.

**Comment by did46** [comment]
Hi,
Great application,
can you use something like that 
https://gallery.technet.microsoft.com/scriptcenter/Set-AutoLogon-and-execute-19ec3879
Just use a autloginfontion and specify a login and password and run this function as local administrator

Other suggestions:
 is it possible to have a function to close web with whitelist adress ?
automatically run an application when the pc run once,  or when a session is open by a user ?

thanks

**Comment by Avaryan** [comment]
This is actually a process I am familiar with. Windows has AutoLogon settings (likely what was indicated in the post above this, which I didn't read 👍 ).

Just edit a couple registry values and restart. The computer will login after the restart. Haven't found a way to do it without the restart though (never looked either).

**Comment by Oiligriv** [comment]
Hi you can see if this can help
https://docs.microsoft.com/it-it/sysinternals/downloads/

**Comment by eeennnooo** [comment]
Any update on this feature? This alone would make it the most perfect software for school sys admins.

**Comment by shanequinn001** [comment]
Hi 
Is this Feature available or is it in the pipeline?
thanks
S

**Comment by tobydox** [comment]
The feature requested by the OP has been implemented in Veyon 4.3 already. Logging in with multiple credentials is currently not implemented but discussed in #438.
