### ISSUE TITLE
Veyon 4.1 Alpha - Error

### ISSUE THREAD

**Issue by pauloboc** [veyon/veyon#310]
**I installed using "dpkg" and restart the computer**
**Configurator does not start by graphical mode or by command.**

Ubuntu Xenial 64bits

![screenshot_1](https://user-images.githubusercontent.com/679128/38615403-efbe189c-3d66-11e8-8b9e-3b8e652e21d8.png)

**Comment by tobydox** [comment]
Thanks for testing and the feedback! Can you try to run it with "gksudo" or "gksu" manually?

**Comment by pauloboc** [comment]
![screenshot_1](https://user-images.githubusercontent.com/679128/38628985-24f423fe-3d89-11e8-8be2-b25826e18878.jpg)

**Comment by tobydox** [comment]
So it works with gksudo?

**Comment by pauloboc** [comment]
Configurator opened, but the veyon-service does not start
