### ISSUE TITLE
Lock not working again

### ISSUE THREAD

**Issue by vincentvije** [veyon/veyon#317]
Hello Tobias,

My computers have Opensuse Tumbleweed. Veyon was working good, but not anymore.

I have "veyon-service &" in /etc/X11/xdm/Xsetup, in the beginning of the file.
Veyon is working well and from my windows computer, I can see and control Linux computers.

But When I want to Lock screens, it does not work anymore.

If I start manually veyon-service from a terminal window, Lock is working well...

I tried to add veyon-service to /etc/X11/xinit/xinitrc but it doesn't start. And furthermose, with /etc/X11/xdm/Xsetup it was perfect because I can control the logon window.

Do you have an idea why veyon-service from  /etc/X11/xdm/Xsetup does not react to Lock command, but started mannually, it locks and unlocks well ?

Thanks a lot.
kind regards,

Vincent

**Comment by tobydox** [comment]
Hi Vincent,

actually I have no idea why this doesn't work. Do all the other features work properly? Can you see a lock screen at all? It would be interesting for me to know how Veyon 4.1 Alpha works in your environment. The service is started via systemd and our own service helper. The only drawback is that currently you won't be able to control the logon screen - something we have to work on.

Best regards

Tobias

**Comment by vincentvije** [comment]
Hello Tobias,
When I start Veyon manually, I can lock and see the lock. When I start Veyon from .config/autostart-scripts/, I can lock too and see the lock. Demo works too.

When I start from /etc/X11/xdm/Xsetup, I can't lock, the client stay free of any lock, and show no lock because it keeps working normally. No way to make lock working. 
Demo also does not work.
If in master I choose "Lock" or "Demo mode", then the context menu of the station stay stuck with "Unlock" or "Stop Demo". The client works normally and ignore lock or demo.

About 4.0.9 version, I'll try asap. Thre is no rpm for opensuse, I will compile, if no package update required.

Thanks for any idea.
Kind regards,

Vincent

**Comment by vincentvije** [comment]
Hello again Tobias,

Compiling Veyon 4.0.9, I got this error

-- cotire 1.7.10 loaded.
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
-- Found QCA: /usr/lib64/libqca-qt5.so (2.1.3)
-- Checking for module 'libprocps'
--   No package 'libprocps' found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  plugins/platform/linux/CMakeLists.txt:6 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/root/Downloads/veyon-master/build/CMakeFiles/CMakeOutput.log".
See also "/root/Downloads/veyon-master/build/CMakeFiles/CMakeError.log".

I've libprocps 3.3.12-11.1 installed...
I don't know what to do ?

Thanks again,
Kind ragards,

Vincent

**Comment by tobydox** [comment]
The provided openSUSE RPM should work for Tumbleweed as well.

Besides that did you take a look at the log files? Please examine Veyon*.log and look whether you can spot any differences between the two launch modes.

**Comment by tobydox** [comment]
You'll need "procps-devel". Also take a look at .travis/linux.opensuse.42.3/Dockerfile for more information on required packages. Alternatively try to use the provided RPM for 42.3.

**Comment by vincentvije** [comment]
Thanks Tobias,
There is no Opensuse 42.3 rpm provided for 4.0.9 nor for 4.0.7. Always 404 error.

I tried with fedora package : but restaring the computer, it seems il didn't add to systemd
I try to lauch it manually but get :
Adding plugin search path "/usr/lib64/veyon"
PlatformPluginManager: no platform plugin available!
Aborted (core dumped)

Then I try to compil source but get 
[ 75%] Building CXX object plugins/desktopservices/CMakeFiles/desktopservices.dir/moc_RunProgramDialog.cpp.o                                                                  
/root/Downloads/veyon-master/plugins/ldap/LdapDirectory.cpp: In member function ‘void LdapDirectory::initTLS()’:
/root/Downloads/veyon-master/plugins/ldap/LdapDirectory.cpp:754:13: error: ‘class KLDAP::LdapServer’ has no member named ‘setTLSRequireCertificate’
   d->server.setTLSRequireCertificate( KLDAP::LdapServer::TLSReqCertDefault );
             ^~~~~~~~~~~~~~~~~~~~~~~~
/root/Downloads/veyon-master/plugins/ldap/LdapDirectory.cpp:754:58: error: ‘TLSReqCertDefault’ is not a member of ‘KLDAP::LdapServer’
   d->server.setTLSRequireCertificate( KLDAP::LdapServer::TLSReqCertDefault );
                                                          ^~~~~~~~~~~~~~~~~
/root/Downloads/veyon-master/plugins/ldap/LdapDirectory.cpp:757:13: error: ‘class KLDAP::LdapServer’ has no member named ‘setTLSRequireCertificate’
   d->server.setTLSRequireCertificate( KLDAP::LdapServer::TLSReqCertNever );
             ^~~~~~~~~~~~~~~~~~~~~~~~
/root/Downloads/veyon-master/plugins/ldap/LdapDirectory.cpp:757:58: error: ‘TLSReqCertNever’ is not a member of ‘KLDAP::LdapServer’
   d->server.setTLSRequireCertificate( KLDAP::LdapServer::TLSReqCertNever );
                                                          ^~~~~~~~~~~~~~~
/root/Downloads/veyon-master/plugins/ldap/LdapDirectory.cpp:760:13: error: ‘class KLDAP::LdapServer’ has no member named ‘setTLSRequireCertificate’
   d->server.setTLSRequireCertificate( KLDAP::LdapServer::TLSReqCertHard );
             ^~~~~~~~~~~~~~~~~~~~~~~~
/root/Downloads/veyon-master/plugins/ldap/LdapDirectory.cpp:760:58: error: ‘TLSReqCertHard’ is not a member of ‘KLDAP::LdapServer’
   d->server.setTLSRequireCertificate( KLDAP::LdapServer::TLSReqCertHard );
                                                          ^~~~~~~~~~~~~~
/root/Downloads/veyon-master/plugins/ldap/LdapDirectory.cpp:761:13: error: ‘class KLDAP::LdapServer’ has no member named ‘setTLSCACertFile’
   d->server.setTLSCACertFile( m_configuration.tlsCACertificateFile() );
             ^~~~~~~~~~~~~~~~
/root/Downloads/veyon-master/plugins/ldap/LdapDirectory.cpp:765:13: error: ‘class KLDAP::LdapServer’ has no member named ‘setTLSRequireCertificate’
   d->server.setTLSRequireCertificate( KLDAP::LdapServer::TLSReqCertDefault );
             ^~~~~~~~~~~~~~~~~~~~~~~~
/root/Downloads/veyon-master/plugins/ldap/LdapDirectory.cpp:765:58: error: ‘TLSReqCertDefault’ is not a member of ‘KLDAP::LdapServer’
   d->server.setTLSRequireCertificate( KLDAP::LdapServer::TLSReqCertDefault );
                                                          ^~~~~~~~~~~~~~~~~
[ 75%] Building CXX object plugins/demo/CMakeFiles/demo.dir/moc_DemoConfiguration.cpp.o
make[2]: *** [plugins/ldap/CMakeFiles/ldap.dir/build.make:191: plugins/ldap/CMakeFiles/ldap.dir/LdapDirectory.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:4738: plugins/ldap/CMakeFiles/ldap.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

And then in the end make stops with :
[ 77%] Building CXX object plugins/demo/CMakeFiles/demo.dir/qrc_demo.cpp.o
[ 77%] Linking CXX shared module linux-platform.so
[ 77%] Linking CXX shared module demo.so
[ 77%] Built target linux-platform
[ 77%] Built target demo
make: *** [Makefile:152: all] Error 2

For the moment, I'm stuck (and furthermore I don't use ldap).

Well, if you have any tips, I will try them.

Thanks again,
Kind regards,

Vincent

**Comment by vincentvije** [comment]
Note : if I could use a rpm it would be fine, but the one for fedora doesn't work.

**Comment by tobydox** [comment]
My fault, the RPM package name was wrong (still indicating 42.2 while built for 42.3). Please try again with the downloads ;-)

Regarding your error: if you switch the branches between 4.0 und master please always update the submodules as master uses a different commit of kldap: "git submodule update --init".

**Comment by vincentvije** [comment]
Thanks Tobias,

I just downloaded the last sources from github (https://github.com/veyon/veyon/), then copy-pasted the 3rd party softwares from 3.0.7 sources (from veyon website: https://veyon.io/download/ -> sources) to the files downloaded from github (because it was empty).

I don't understand about "if you switch the branches between 4.0 und master please always update the submodules as master uses a different commit of kldap: "git submodule update --init"."

So what do I need to do  when I'm inside the build directory I made in the Github sources in the terminal window ?

Vincent

**Comment by vincentvije** [comment]
I just downloaded the sources from github without git...

**Comment by vincentvije** [comment]
Hello Tobias,

I'm starting a heavy 15 days travel for my job. I will not hve much time nor my computers to work and make my tests on Veyon... Il need Veyon to work at mid-May. If I can't solve the problem, I will start Veyon 4.7 service from user autostart folder.
When I can, I come back on Veyon. You're right, it's better going with Veyon 4.1.
So in May I will heavy test Veyon 4.0.9 or 4.1 and write to you about it.

I'll come back in this opened issue.

Thanks a lot for your help and your great work.
Kind regards,

Vincent

**Comment by tobydox** [comment]
Hi Vincent,

thanks for your feedback. Good luck with your travel! Just report back as soon as you have news :-) 4.1 Beta will be available within 1-2 weeks.

Best regards
Tobias

**Comment by vincentvije** [comment]
Hello Tobias,

I'm back !
I just installed the new Veyon 4.1 Beta (4.0.91) released on 2018-05-07 on OpenSUSE.
But he service fail to start.

I did : veyon-ctl service start

But got:
PlatformPluginManager: no platform plugin available!
Aborted (core dumped)

I don't know what to do ?
Whatever "veyon-ctl service" command I use,  I get the same error...
And with veyon-configurator too.

Please what do I miss ?

Thanks a lot.
Kind regards,

Vincent

**Comment by vincentvije** [comment]
Hello Tobias,

I'm back !
I just installed the new Veyon 4.1 Beta (4.0.91) released on 2018-05-07 
on OpenSUSE.
But he service fail to start.

I did : veyon-ctl service start

But got:
PlatformPluginManager: no platform plugin available!
Aborted (core dumped)

I don't know what to do ?
Whatever "veyon-ctl service" command I use, I get the same error...
And with veyon-configurator too.

Please what do I miss ?

Thanks a lot.
Kind regards,

Vincent

**Comment by swhaat** [comment]
Hi,

in Arch Linux after compilation i get the same error:
```
PlatformPluginManager: no platform plugin available!
```
Debug just shows:
```
Starting program: /usr/bin/veyon-ctl 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffea80d700 (LWP 18397)]
[New Thread 0x7fffe050a700 (LWP 18398)]
[New Thread 0x7fffdfd09700 (LWP 18399)]
PlatformPluginManager: no platform plugin available!

Thread 1 "veyon-ctl" received signal SIGABRT, Aborted.
0x00007ffff5fd286b in raise () from /usr/lib/libc.so.6
```

**Comment by tobydox** [comment]
Plugin errors are related to improper Veyon installations or builds. If built and installed properly, you should not see them ;) As the original issue is solved, I'm closing this issue.
