### ISSUE TITLE
LDAP bind password stored as plain text

### ISSUE THREAD

**Issue by ldlx** [veyon/veyon#318]
I noticed that the LDAP bind password is stored as plain text in the windows registry visible for all users. Please store the password encrypted.
As a workaround I created a new user account in AD which is not member of any default user group (e. g. domain users) so my LDAP bind account is useless for anything else than querying the AD.

**Comment by tobydox** [comment]
In Veyon 4.1 all passwords are encrypted. You can try Veyon 4.1 Alpha for testing. Thanks for the feedback anyways ;-)
