### ISSUE TITLE
I can't install from AUR from my school

### ISSUE THREAD

**Issue by zaknafein99** [veyon/veyon#328]
I can install from AUR with no issues from my home, but from my school the instalation always get stuck at cloning kldap, it's the only repository that doesn't work and it's the only one that's different (anongit.kde.org/kldap.git). Do you have any mirror (preferably on github) for kldap to try?

**Comment by tobydox** [comment]
You can change the kldap entry in .gitmodules and use "https://github.com/KDE/kldap.git" alternatively.

**Comment by zaknafein99** [comment]
Nice!! I managed to install using your link in the AUR PCKGBUILD.
