### ISSUE TITLE
Veyon for Android

### ISSUE THREAD

**Issue by valluminarias** [veyon/veyon#33]
Does veyon supports android as a client or master?

**Comment by tobydox** [comment]
No, currently not, I'm sorry. Nevertheless we're plannung to create at least a mobile/touch interface version of Veyon Master using QML/Qt Quick so we could provide that as an Android app as well. The most work would however be to implement all the client functionality such as screen lock, remote control/VNC server etc.

**Comment by mesmariusz** [comment]
Hi. Howard do you ThinkPad Howard much timer do you need to introduce?

**Comment by robertosptcosta** [comment]
Tobias Junghans, how about adroid news! Does not have an Android client / master solution for Veyon yet?

**Comment by robertosptcosta** [comment]
We have a great opportunity here in Brazil, at Mogi das Cruzes, all de City Schools have received Android tablets and Chrome Books from the Major and we need as fast, as possible a laboratory/classroom master panel to control and manage child classes.

**Comment by robertosptcosta** [comment]
from the Mayor* (sorry)

**Comment by tobydox** [comment]
We plan to provide Veyon in PlayStore later this year, however we do not have an ETA yet.

**Comment by rodjerhell** [comment]
прошел год .....

**Comment by Eretick** [comment]
> We plan to provide Veyon in PlayStore later this year, however we do not have an ETA yet.

Hello. It's 2026 already :D 

Any news about Android app?
