### ISSUE TITLE
Veyon service does not start up on Arch

### ISSUE THREAD

**Issue by zaknafein99** [veyon/veyon#331]
I installed from AUR with no issues, but the veyon service does not start.
`veyon-ctl service register` just prints dots on screen but `veyon-configurator` does not recognize the service as running

**Comment by tobydox** [comment]
Thanks for your feedback! Veyon 4.0.x does not have proper systemd service support so this won't work at this level. You can either integrate the service manually as described in our INSTALL file (various autostart mechanisms) or try 4.1 alpha (soon: 4.1 beta) which has full systemd support. In the meanwhile I'm closing this issue. Feel free to respond and/or re-open if necessary.
