### ISSUE TITLE
Add support for opening a Linux client's root terminal in master computer

### ISSUE THREAD

**Issue by lbssousa** [veyon/veyon#332]
One feature I use a lot in Epoptes is the ability to open a remote root terminal from a client's computer directly in my server computer. With the new Linux architecture coming in Veyon 4.1, I wonder if would be possible for veyon-master talk directly to a client's system-wide veyon-service instance so that it can perform directly some tasks as root, as well as opening a remote root terminal in veyon-master computer.

**Comment by tobydox** [comment]
Thanks for the suggestion! Even though this would probably be possible in general I think Veyon is not the right tool for that - I suggest using SSH or similar instead. Remote-executing commands as root is a high security risk so I'd rather not implement this in general. If you need a customized solution for your environment based on a paid plan please contact me in private via tobydox@veyon.io so we can elaborate possible options.
