### ISSUE TITLE
Remote View triggers nesting screens and thumbnails blank/not-connected

### ISSUE THREAD

**Issue by gwfranz** [veyon/veyon#333]
If I click on remote view and enter a host name, I can view or control a computer, but if I double-click on a computer I get infinite nested windows of my own screen.  Also, the computer thumbs are always blank and show disconnected.  Lock, demos, text message, reboot, etc. have no effect whatsoever.

I've attached screenshots, and a zipped json logfile
![screenshot 2018-04-27 18 56 10](https://user-images.githubusercontent.com/8339975/39389388-93539d36-4a4d-11e8-951b-53b605133c8a.png)
![screenshot 2018-04-27 18 55 57](https://user-images.githubusercontent.com/8339975/39389389-936af116-4a4d-11e8-9057-434f961b625a.png)

[Bug 2018-04-27.zip](https://github.com/veyon/veyon/files/1957040/Bug.2018-04-27.zip)

**Comment by tobydox** [comment]
Thank you for your bug report! As far as I can see you did not set a valid host address for the computers so Veyon Remote Access tries to access localhost. Can you try to add an IP addresses for one computer in Veyon Configurator and try again?

**Comment by gwfranz** [comment]
I put in the MAC address and the computer name.  The IP varies because I am using laptops and dhcp.  I have been connecting with the computer name when I type in the single computer name (which works), but I can’t put in IP addresses, because they  change every time.  Shouldn’t the computer name work just as well, especially since it works when you type it in individually?  It’s only the double click that causes trouble.  That and the fact that all of the thumbnails show disconnected.

**Comment by tobydox** [comment]
I see you're still using version 4.0.5. The issue has been fixed in 4.0.7 as well as the current pre-releases (4.1 RC) - please upgrade :-)
