### ISSUE TITLE
Veyon service installation on client PC, Linux Fedora O.S.

### ISSUE THREAD

**Issue by rmarz72** [veyon/veyon#337]
When I install Veyon on client PCs with Fedora O.S., the full package is installed but I would like to install only the Veyon-service app. Unlike on Windows O.S. on Linux installation wizard I don't have the option to disable the Veyon master installation. How can I perform this ? Or how can I remove Veyon-master after it was installed ?

Thank you for your suggestions.

**Comment by jamj2000** [comment]
Yes, you can remove veyon-master on client PCs after it was installed. I do that.

**Comment by tobydox** [comment]
Right, simply remove /usr/bin/veyon-master if you don't want to have it installed on client computers (even though it wouldn't harm as students shouldn't be able to use it anyway). On Windows the only difference is whether veyon-master.exe is being installed or not.
