### ISSUE TITLE
Problems in the Authentication keys

### ISSUE THREAD

**Issue by lavos3rd** [veyon/veyon#338]
Hi Guys,

I have an error of: 
**"User _NAME_ tried to access this computer but could not authenticate successfully"**

Here are the Steps I did for the Authentication keys:

1. Installed Veyon 4.0.9 on a Windows 10 for Master
2. Clicked the "create key pair" at the Authentication keys tab
2. Named the Keys Group to "Master" and clicked OK
3. Exported the Master Public Key
4. Installed Veyon 4.0.9 on a Linux-mint for Client (Tried installing a Veyon 4.0.7 but the Veyon Configurator won't open)
5. Imported the Master Public Key
6. Named the Group to "Master"
7. Ticked the Process Access Control Rules
8. Created an Access Control Rules that "Always process rule and ignore conditions"

Can you guys point out where I did wrong or other steps that I may not have done?

Thank you

**Comment by tobydox** [comment]
Thanks for the feedback! We revised authentication key management in 4.1.x so things should work better now. If you still have issues feel free to join our community forum :)
