### ISSUE TITLE
Veyon Master can't access a client

### ISSUE THREAD

**Issue by staifer** [veyon/veyon#339]
I have a "10.0.11.0/24" network and Veyon Master 4.0.7 on a Windows 7 x64 and Linux Mint 18.3 clients.

Master cannot access the client If I register the client's IP with "10.0.11.05", but it works fine if I correct the IP to "10.0.11.5". I tried Veyon Master on Linux Mint 18.3 and it has no such issue.

**Comment by tobydox** [comment]
Please note that "10.0.11.05" is not a valid IP and it's likely that Veyon - depending on the underlying operating system - will not be able to open a TCP connection successfully as DNS resolve will fail in this case. If everything works fine with "10.0.11.5" then there's no bug in Veyon and everything works as expected.
