### ISSUE TITLE
is compatible with windows xp ?

### ISSUE THREAD

**Issue by cvillarreal77** [veyon/veyon#34]
i have a error when i try to acess a configurator in xp

" No se encuentra el punto de entrada del procedimiento SHGetKnownFolderPath en la biblioteca de vinculos dinamicos SHELL32.dll"

:)

**Comment by tobydox** [comment]
I'm sorry but Veyon is not compatible with Windows XP. Please update to a supported version of Windows (such as 7 or newer) to use Veyon.
