### ISSUE TITLE
Provide 32-bit builds for your packages

### ISSUE THREAD

**Issue by lbssousa** [veyon/veyon#340]
Would it be possible for you to provide 32-bit builds for Veyon package? We would like to test it in some Lubuntu 32-bit installations in our lab. Some of our machines are not upgradeable to 64-bit OS because they have less than 1GB RAM available.

**Comment by jamj2000** [comment]
You can easily generate packages from source code following the instructions in [README.md](https://github.com/veyon/veyon/blob/master/README.md)

It's important follow the steps in the target distro, in your case Lubuntu 32 bits.

**Steps**

1. Download the source code.

```bash
git clone --recursive https://github.com/veyon/veyon.git && cd veyon
```
2. Install the dependency packages

```bash
apt install g++ make cmake qtbase5-dev qtbase5-dev-tools qttools5-dev qttools5-dev-tools \
            xorg-dev libxtst-dev libjpeg-dev zlib1g-dev libssl-dev libpam0g-dev \
            libprocps-dev liblzo2-dev libqca2-dev libqca-qt5-2-dev libldap2-dev
```

3. Compile

```bash
cmake -DCMAKE_INSTALL_PREFIX=/usr ..

mkdir build && cd build
cmake ..
make -j4
```

4. Generate package veyon_x.y.z_arch.deb

```bash
fakeroot make package
```

5. Then you can copy this file in a USB or share on network and install in another computer

```bash
dpkg  -i  package veyon_x.y.z_arch.deb
apt install -f     # for resolving previous dependencies 
```


note: x.y.z is version numbers, e.g. 4.0.7

**Comment by SambaPatty** [comment]
In my case (compiling within a Docker Debian-i386 on CentOS) it was necessary to add some vars in the call of cmake:
`cmake -DCMAKE_INSTALL_PREFIX=/usr -DCPACK_SYSTEM_NAME=i386 ..`
You may also consider:
`-DCMAKE_SYSTEM_PROCESSOR=i386 -DCMAKE_CXX_FLAGS=-m32 -DCMAKE_C_FLAGS=-m32`

**Comment by tobydox** [comment]
@jamj2000 @SambaPatty Thank you for your help!

@lbssousa I hope you were able to build your packages. We will not provide 32 bit packages (basically only for legacy systems) as this would effectively double our maintenance efforts and increase complexity of our build configurations. We hope Veyon will be included in Debian Buster so sooner or later it will be official part of Debian/Ubuntu.
