### ISSUE TITLE
Change the Privileges key to "sudo" (or other) by default

### ISSUE THREAD

**Issue by pauloboc** [veyon/veyon#341]
![download](https://user-images.githubusercontent.com/679128/39665529-55371a4e-506c-11e8-9ef2-451c72edbdee.png)

**AFTER CHANGE GROUP TO "SUDO", WORK!**

![download 1](https://user-images.githubusercontent.com/679128/39665532-647aa872-506c-11e8-8852-e43d6d3263ad.png)
![screenshot_1](https://user-images.githubusercontent.com/679128/39665546-a50a6634-506c-11e8-8e5e-2a0375b86578.png)

---------
Ubuntu 18.04
Commits 3,694 (05-05-2018)
Veyon Alpha 4.1

**I am using an admin user**

**Comment by tobydox** [comment]
Thank you for your suggestion and for testing the alpha release!

The described behaviour is intended as admins should always set a dedicated group explicitly so the default setup will force you to take action. Furthermore there might be systems/distributions which do not have the sudo group so I vote for keeping things as they are right now.
