### ISSUE TITLE
Veyon beta 4 0.91 : Authentification key failed on windows 10 master with linuxmint 18 client 

### ISSUE THREAD

**Issue by orion777** [veyon/veyon#342]
Hello

I didn't have any problem with authentification key on veyon version 4.0.X but now with veyon beta 4.0.91 there are some changes with authentification key privlieges and using the same method like before doesn't work. I imported new pair of key and restarted the veyon service but there is always the error authentification message alert. How to fix thos problem with linuxmint client and windows 10 master?
Thanks you for your help

**Comment by pauloboc** [comment]
I have the same problem.

Windows Veyon Master not work.
Linux Veyon Master work :)

**Comment by tobydox** [comment]
Thanks for your reports! Did you set an access group for the private key on the Windows master? If so, which group? I'll also check the function on Windows again.

**Comment by orion777** [comment]
I also defined the private key and public key as administrators by default on the windows master 
And i am logged as local administrator on the linuxmint client but authentification failed.

**Comment by KuroShirogane** [comment]
Hello,

I think i have the same problem of your,
i've tried to import private and public key in one veyon master 4.0.91 for done snapin by fog! by this command line  "veyon-ctl authkeys import ....."

veyon say me : "The name of your key have invalid caracter" ! or "The writing of entrance files have failed. Please check you permissions."

I've thinking to make a accessgroup but for this we need to import a Key.

If someone know how import Key by command line to make one autorun (bat files), could it share to me.

Thanks in front.

**Comment by svenzimmermann** [comment]
Same problem here with v4.1.7. :(

Any solution for this problem?

Thx
Sven
