### ISSUE TITLE
Veyon beta 4.0.91 on linuxmint : problem with automatic startup veyon service

### ISSUE THREAD

**Issue by orion777** [veyon/veyon#343]
On veyon configurator in service tab,  even if the automatic startup is checked veyon service doesn't run when the machine shutdown and reboot. Only works when a session is closed and restart.
Thanks you for fixing this issue.

**Comment by lavos3rd** [comment]
I also have that problem, Also when a non-admin user logins in, its fine for a few minutes of use, but then force closes the veyon-service.

Details of Client:
OS: Linux Mint 18.3 Sylvia 64-bit, Kernel Linux 4.13.0-26-generic x86_64

**Comment by tobydox** [comment]
Many systemd-related issues have been fixed recently. Either build packages of the latest master branch on your own or wait for the final 4.1 release next week.
