### ISSUE TITLE
Automatically creating folder in program data (windows) and etc (linuxmint) during veyon install

### ISSUE THREAD

**Issue by orion777** [veyon/veyon#344]
Could it be possible to have the folders automatically generated with the veyon installation?
Because when you have lot of clients to install it is necessary to open the veyon configurator and creating the folders for key authentification. It take lot of time.
Thanks you for your help 
Regards

**Comment by tobydox** [comment]
You can automate most tasks through `veyon-ctl` - see https://docs.veyon.io/en/latest/admin/cli.html for more information. In Veyon 4.1 (try the latest RC) there's also a CLI module for managing authentication keys. I already blogged about it: https://veyon.io/blog/2018/04/24/network-object-management-cli/ - feel free to ask questions if you have problems with `veyon-ctl`.
