### ISSUE TITLE
Computer rooms doesn't not display automatically in Veyon Master

### ISSUE THREAD

**Issue by Catskan** [veyon/veyon#347]
Hi all,

I'm setting up Veyon in my compagny but I have a problem to display the computer rooms.

I connect veyon to my LDAP and the computer room test is successfull (5 rooms request).

In my Veyon master, my rooms does not appear automacally. I must add manualy by "Add a room manualy" button. But with this method, when I restart my Veyon Master, the rooms erase and I must re-add manualy.

How to make for veyon adding my rooms automacaly ni veyon master ?

In attachment, my configuration file.
[config.json.txt](https://github.com/veyon/veyon/files/1997447/config.json.txt)

Thanks you in advance for your help :).

Sorry for my english

**Comment by tobydox** [comment]
Welcome to Veyon! According to your config you have the option "Only show current room" enabled. This will make Veyon only show the room which the current computer belongs to and you have to add other rooms manually. Simply uncheck the option and try again.

**Comment by Catskan** [comment]
Hi,

Thanks you for your answer. I disabled "Only show current room" and it is working !

Catskan
