### ISSUE TITLE
Predefined websites don't work, open Windows Explorer

### ISSUE THREAD

**Issue by pedrostorti** [veyon/veyon#349]
Hi.

I started the tests with the new beta version of Veyon to 4.0.91, to test the functions of pre-defined websites, when sending to the stations, they open windows explorer instead of the browser.
I set Chrome or firefox as the default system and I did not succeed.

**Comment by tobydox** [comment]
Thanks for testing! Did you enter a non-empty string as URL? Only entering the URL in the first column "name" won't help and lead to the situation described.

**Comment by pedrostorti** [comment]
In the Name field, I enter the name of the site. In the URL field, I entered the URL of the site usually ex: http://www.uol.com.br

**Comment by tobydox** [comment]
Thanks for the feedback! Does the feature work when opening non-predefined websites, i.e. enter it in the dialog on the master manually?

**Comment by pedrostorti** [comment]
Yes, this feature works when opening non-predefined websites on the master manually.
