### ISSUE TITLE
Can the Client be completely Silent?

### ISSUE THREAD

**Issue by schorne** [veyon/veyon#350]
I don't EVER want the client to show an error or message of any sort on the screen of the student computer. Is there a switch or setting that can make it so the client doesn't ever show any indication the screen is being viewed? Currently we are using login authentication and we find that if the teacher enters the wrong password on the Veyon Master, all the student screens will show an authentication error.  We use this software to proctor students taking tests in the classroom. We don't ever want them to be interrupted by a Veyon message on their screens.

Thanks!

**Comment by tobydox** [comment]
There's currently no switch but Veyon Master should refuse to start if the teacher enters wrong credentials. I therefore wonder why you still have these kind of messages. Are you using logon authentication exclusively, i.e. disabled key authentication?

**Comment by ldlx** [comment]
I notice logon failure messages from time to time although the user at the master computer authenticates successfully using logon authentication and rules at the client are set so that the user at the master computer is allowed to view the client.

**Comment by tobydox** [comment]
This has been implemented in 9c94bfa9da46c468106242b69ac2f2fbd06cfd70 and will be part of final 4.1 release.
