### ISSUE TITLE
Computer offline or switched off

### ISSUE THREAD

**Issue by randomthrowaway** [veyon/veyon#351]
Whenever I try to connect to a student computer it says "computer offline or switched off". It worked before, and now it isn't.

**Comment by tobydox** [comment]
Did you update Veyon? If so, from which version to which version? Did your firewall settings change? Which operating system?

**Comment by nejlich** [comment]
I have also encountered this issue. Ive tried disabling windows firewall on both machines, and ive made sure that veyon service was running on student computer, but it still shows up as "offline or switched off". Im still a newbie to veyon, so i might have missed something obvious. Thanks in advance for your help

**Comment by aphiach** [comment]
Whenever I try to connect to a student computer it says "computer offline or switched off". It worked before, and now it isn't. How can i fix this issue?

**Comment by tobydox** [comment]
@aphiach which version of Veyon are you running (both on the affected student computers and the teacher computer) and on which platform?
