### ISSUE TITLE
Look screeans

### ISSUE THREAD

**Issue by joabbremer** [veyon/veyon#353]
Hello good day!

I'm testing the veyon and would like an advanced option. When a computer is locked the veyon does not allow to move the mouse nor the keyboard this is what I need, but if I restart the computer the lock does not remain. So I'm thinking of doing the lock manually by passing the parameter to the veyon-worker. Could you tell me if it is the veyon worker that does the blocking process and which argument.

**Comment by tobydox** [comment]
Hello,
in the master configuration page in Veyon Configurator there's an option called "Enforce selected mode for client computers". This will make Veyon Master always restore the selected mode even if a computer has been restarted manually.
