### ISSUE TITLE
Clients randomly get locked/unlocked

### ISSUE THREAD

**Issue by ldlx** [veyon/veyon#355]
I got a call these days that some client computers randomly lock/unlock within seconds. While that happened Veyon master was running in an admin VM in a disconnected RDP session (which was running over 2-3 days probably viewing the affected computers, but because the bug mentioned below I can't tell for sure). The clients get restarted daily. The Windows event log shows errors on both client and master. The behaviour vanished as the clients and the master (which may caused that behaviour) were restarted (maybe restarting the master would be enough). I didn't try to leave the master viewing clients in a disconnected session again. I'll send you the Windows event log as XML file of 2 clients and the master by mail (it may contain user data so please consider it as confidential data). All affected computers are running Windows 8.1.

PS: It may sound stupid to leave the master running in a disconnected session, but there's also a bug in Windows 8.1 since 2 years that won't let one reconnect to a disconnected RDP session randomly until rebooting the machine.

**Comment by tobydox** [comment]
Is this still an issue and worth investigating it?

**Comment by ldlx** [comment]
I didn't got messages regarding recent issues.
