### ISSUE TITLE
Clipboard support

### ISSUE THREAD

**Issue by kakjitOTC** [veyon/veyon#358]
Hello, I work at a college where we have a testing center that works with an LMS. When students enter this testing center they usually have to have an access code/password entered before they can take their test. We had been using a similar program to Veyon to remote control the student's workstation just long enough to copy/paste the access code. We've noticed in Veyon that we can't do this. Does Veyon not support clipboard yet or is there a setting I'm not aware of?

Thanks.

**Comment by tobydox** [comment]
We currently do not have clipboard support but it's on our roadmap so expect it in Veyon 4.2 :-)

**Comment by luedi69** [comment]
Hallo @tobydox  fine to hear. I currently use Veyon 4.6. 
Is this feature still on your roadmap or do I miss some setting that clipboard sharing works?

best regards
Thomas

**Comment by tobydox** [comment]
Indeed we forgot about that feature but I know that @SlrG mentioned that he wants to try to implement this feature in the foreseeable future.

**Comment by luedi69** [comment]
Hello Tobias,
Thank you for your Feedback,
as told we would love to have this feature in one of the futrue 
Versions.

Best Regards
Thomas


Am 07.01.2022 12:41 schrieb Tobias Junghans:

**Comment by SlrG** [comment]
Sadly that's not exactly what I said. :(

I would like this feature and so I tried to implement it. But I never got it to work. There is a lot of code on the vnc side, which seems like it could support this functionality but I was not able to connect it to the veyon side of things. Someone with a lot more knowledge, than myself will have to work on this. Sorry. :(

**Comment by tobydox** [comment]
@SlrG No problem :-) If we're going to implement this, it will be independent of VNC. We'll add a `FeatureProvider` with a new `Feature` e.g. called `Clipboard` and handle the clipboard exchange through it. Don't worry, I can work on it as well.

**Comment by tobydox** [comment]
Feature likely is going to be backported to the 4.7 branch and part of the upcoming 4.7.1 release.
