### ISSUE TITLE
Any news concerning the problem with "failed authentification" and session login disconnection with linuxmint?

### ISSUE THREAD

**Issue by orion777** [veyon/veyon#359]
Hello
In the next Veyon Version will you fix these current problems with Linuxmint?
There is problems between veyon service and session logins., so Veyon can't be used on linux machines
Thanks you very much

**Comment by tobydox** [comment]
Can you try with latest RC again please?

**Comment by tobydox** [comment]
systemd support has been improved recently so it should work properly on Linux Mint - either try the latest master branch or wait for the final 4.1 release next week.
