### ISSUE TITLE
Power On Function

### ISSUE THREAD

**Issue by lincro54** [veyon/veyon#360]
I am having an issue getting my lab computers to power on.  Powering them all off and accessing them works fine.  I have had a few where the veyon app needed to be restarted.

**Comment by tobydox** [comment]
Thanks for reporting this issue. We have an important fix for WOL which will be part of the next releases (4.0.8 / 4.0.92) soon. Please re-open or comment on this issue if this still happens with the next releases.

**Comment by ldlx** [comment]
What did you change? release notes are not available for 4.0.92 at the moment.

**Comment by emajava** [comment]
Hi, thanks for the answers. I had same problems with "power on" function before this post. I disabled virtual network cards on the Master (I run Virtualbox and VMWare Workstation Player for educational purposes, as a teacher) and now everything works like a charm. It would be better have the possibility to choice the network card by which the Master sends Magic Packets. Thanks for adjusting my day. Thanks ldlx.
