### ISSUE TITLE
Authentification error on Windows 10

### ISSUE THREAD

**Issue by foboro** [veyon/veyon#364]
I get an authentication error (windows 10) by using pubkey-authentification.
I followed the instructions in the video here

https://www.youtube.com/watch?v=iUeC9H2q7xY

... key files are accessible from client and master.

Nearby my veyon-config file and a screenshot of the VeyonService-log-file.
Thanks for any advice to this subject!!

[config.json.txt](https://github.com/veyon/veyon/files/2145439/config.json.txt)
<img width="1335" alt="bildschirmfoto 2018-06-28 um 15 13 39" src="https://user-images.githubusercontent.com/40665252/42036733-ad4aee78-7ae6-11e8-8f1b-891447b6808b.png">

**Comment by foboro** [comment]
This is the error message in Windows 10
![37666698-dc21e246-2c68-11e8-90bc-71fa92783cb2](https://user-images.githubusercontent.com/40665252/42079957-6d2606a2-7b81-11e8-8d2b-c245c4329cff.jpg)

**Comment by tobydox** [comment]
Maybe an issue with UNC paths? Have you tried using local keys? Is the private key readable by the user using Veyon Master?

**Comment by foboro** [comment]
Hello ... same problem with keys locally generated/stored on desktop ... any ideas how to debug this problem? I have seen, that this problem has been already addressed before. Is this feature working on Windows 10? Thanks!

**Comment by tobydox** [comment]
Closing due to missing feedback - feel free to re-open or join our community forum :)
