### ISSUE TITLE
[Linux] Programs run through Veyon belong to user "lightdm"

### ISSUE THREAD

**Issue by ysalmon** [veyon/veyon#365]
Hello,
I am beginning to test Veyon in my Linux classroom (Debian 9).
I am using yesterday's master from github.
So far, I configured the classroom, the settings and had the veyon service run at startup.

With veyon-master, I can see the other computer's login prompt, and the username "lightdm". Alas, when somebody logs into a computer, veyon does not seem to catch it username, and keeps on displaying "ligthdm".

This makes it very inconvenient to know which screen correspond to which student.

Is this a configuration error on my part ?

**Comment by tobydox** [comment]
Are you running the Veyon Sever via systemd-based Veyon Service? Or are you launching veyon-service or veyon-server manually from a start script?

**Comment by ysalmon** [comment]
I did ```veyon-ctl service register```.

BTW, the problem is worse than I thought : when I use the "Run a program" feature, the process is run on the distant machine by the lightdm user, which I reckon may be a serious security problem.

**Comment by tobydox** [comment]
This is all related to the same issue - veyon-server is not run as the user who is logged in. I'll setup a Debian 9 system and have a look at it.

**Comment by tobydox** [comment]
Which desktop environment are you running?
BTW you do not need to run "service register" - simply enable autostart via Configurator which should call "systemctl enable veyon-service".

**Comment by ysalmon** [comment]
I think it is a good thing that veyon-server is run as lightdm and not the logged in user : if it were the case, the user would be able to terminate it.

But the server should be aware of the active user to report it to master and to be able to spawn some subprocesses as this user ("Run program" command, but the process for locking the screen, for example, should belong to lightdm/root).

I am using XFCE.

**Comment by tobydox** [comment]
Thanks for your quick responses! You're right, the veyon-server process is not supposed to run as the logged on user but as root so it can spawn subprocesses as the logged on user. This is how it works on Ubuntu 18.04 already. I guess we have to test on all other supported distros as well. There seems to be a problem with detecting which user is logged on. I'll have a look at it.

**Comment by ysalmon** [comment]
A trick that I already used with success to detect the logged-on user is to enumerate users with ```who``` and checking which user has terminal ```tty7``` ou ```pts/0```.

**Comment by tobydox** [comment]
I think I fixed the issue yesterday. Did you compile Veyon on your own? If so, can you try to build the latest version?

**Comment by ysalmon** [comment]
I tested it today ; it works : veyon-control correctly shows the active user name for each machine and programs are run with that user as owner. Thanks a lot !
