### ISSUE TITLE
[Linux] Remote control completely irresponsive, shutdown does not work

### ISSUE THREAD

**Issue by ysalmon** [veyon/veyon#367]
I am testing the different features of Veyon in my environment.

Observe, Remote View, Lock, Power up and Message seem to work.

However, Remote control is irresponsive. I do not know if this is just extremely slow or the remote just does not get any input. I am currently testing with just the master computer and one remote powered up so I highly doubt a network congestion (there are also no courses at the time).

Shutdown seems to do nothing.
Logout did not work two days ago, but today it is.

I set the logs to debug level but they do not seem to convey much information anyway - no error messages at least.

How safe is it to upload logs and config files here ? Regarding VNC passwords and so on, I mean.

**Comment by tobydox** [comment]
Thank you for taking time to test Veyon! Are you running 4.1 RC (4.0.92)? I'd suggest to do so as it has better Linux support than 4.0.x. IIRC you're running Debian 9 with Xfce? As promised I'll test with a Debian 9 VM. Can you try to stop veyon-service and run veyon-server in a terminal inside a user session manually. You'll then see the output of the VNC server (decrease Veyon log level to prevent the output from being flooded by Veyon itself) - may be it prints out some helpful diagnostics such as issues with Xdamage or Xfixes.

**Comment by ysalmon** [comment]
Yes, I am using the github master from two weeks ago.

I tested again today with the server run from a user's terminal (to get the logs). With this setup, Remote control was very sluggish but did respond, so the input is transmitted (but it is not usable : it takes more than one minute to take mouse movement into account). The Shutdown feature also worked (this might be related to the fact that Veyon does not issue the same system command when it is run as root and non root, if I read the code correctly).

Here are the logs obtained by ```veyon-server &> /tmp/veyon-server-master.log``` and the same for the slave machine.
[veyon-server-master.log](https://github.com/veyon/veyon/files/2175781/veyon-server-master.log)
[veyon-server-slave.log](https://github.com/veyon/veyon/files/2175782/veyon-server-slave.log)

Here are the Veyon logs from the master machine.
[VeyonFeatureWorker-8e997d84-ebb9-430f-8f72-d45d9821963d.log](https://github.com/veyon/veyon/files/2175800/VeyonFeatureWorker-8e997d84-ebb9-430f-8f72-d45d9821963d.log)
[VeyonFeatureWorker-e4b6e743-1f5b-491d-9364-e091086200f4.log](https://github.com/veyon/veyon/files/2175801/VeyonFeatureWorker-e4b6e743-1f5b-491d-9364-e091086200f4.log)
[VeyonMaster.log](https://github.com/veyon/veyon/files/2175802/VeyonMaster.log)
[VeyonServer.log](https://github.com/veyon/veyon/files/2175803/VeyonServer.log)
[VeyonService.log](https://github.com/veyon/veyon/files/2175804/VeyonService.log)

Here are the logs on the slave machine.
[VeyonConfigurator.log](https://github.com/veyon/veyon/files/2175813/VeyonConfigurator.log)

[VeyonFeatureWorker-7b6231bd-eb89-45d3-af32-f70663b2f878.log](https://github.com/veyon/veyon/files/2175814/VeyonFeatureWorker-7b6231bd-eb89-45d3-af32-f70663b2f878.log)
[VeyonFeatureWorker-8e997d84-ebb9-430f-8f72-d45d9821963d.log](https://github.com/veyon/veyon/files/2175815/VeyonFeatureWorker-8e997d84-ebb9-430f-8f72-d45d9821963d.log)
[VeyonFeatureWorker-ae45c3db-dc2e-4204-ae8b-374cdab8c62c.log](https://github.com/veyon/veyon/files/2175816/VeyonFeatureWorker-ae45c3db-dc2e-4204-ae8b-374cdab8c62c.log)
[VeyonFeatureWorker-ccb535a2-1d24-4cc1-a709-8b47d2b2ac79.log](https://github.com/veyon/veyon/files/2175817/VeyonFeatureWorker-ccb535a2-1d24-4cc1-a709-8b47d2b2ac79.log)
[VeyonFeatureWorker-e75ae9c8-ac17-4d00-8f0d-019348346208.log](https://github.com/veyon/veyon/files/2175818/VeyonFeatureWorker-e75ae9c8-ac17-4d00-8f0d-019348346208.log)
[VeyonServer.log](https://github.com/veyon/veyon/files/2175819/VeyonServer.log)
[VeyonService.log](https://github.com/veyon/veyon/files/2175820/VeyonService.log)

And the configuration file : 
[config.json.txt](https://github.com/veyon/veyon/files/2175825/config.json.txt)

**Comment by tobydox** [comment]
The laggy remote control issue has been fixed via c859cf5191c9d4d81e7a75a517c84c883b8c76d9 - please try the latest master branch or wait for the final 4.1 release.

**Comment by ysalmon** [comment]
Indeed, it works much better now !
