### ISSUE TITLE
Non-root can export Veyon configuration

### ISSUE THREAD

**Issue by ysalmon** [veyon/veyon#368]
It appears one does not need to be root to successfully do ```veyon-ctl config export myconfig.json```. Is it safe ? This contains passwords for LDAP binding and VNC.

**Comment by tobydox** [comment]
This is not a bug as the configuration is readable in /etc/xdgVeyon Solutions/ anyway - it even has to be readable for applications running by users ;-) In Veyon 4.1 all passwords are stored encrypted so they are not visible in plain text.
