### ISSUE TITLE
Slow Thumbnail Previews (v4.1.0)

### ISSUE THREAD

**Issue by teotwawki16** [veyon/veyon#377]
Hello! I am using Veyon for my classroom. I'm currently using the latest release (v4.1.0) and I have a problem. When the student computers are open but not in use, the thumbnails I see in Veyon Master are all just black but the computers are not in sleep mode or whatsoever. But when I try to move the mouse pointer or open a program from the student computers, the parts of the thumbnail that updated are only shown and the rest of the thumbnail would still be black (as seen on the image). I am not having this situation from v4.0.7. Any help? Thanks!

![thumbnail_black](https://user-images.githubusercontent.com/25724815/43114292-dad6ff40-8f30-11e8-9cf3-946d0314d053.png)

**Comment by teotwawki16** [comment]
This might look like a little problem but I crucially need this to check if all of my students are doing their activities correctly and not check them one by one. Thanks!

**Comment by tobydox** [comment]
Yes there seem to be some issues within the builtin UltraVNC. I have a fix for you to test. Can you try to replace the file builtin-ultravnc-server.dll on all affected clients (inside C:\Program Files\Veyon\plugins) - stop the Veyon Service and all Veyon-related programs before, otherwise overwrite fill fail ;-)

[builtin-ultravnc-server.dll.zip](https://github.com/veyon/veyon/files/2228672/builtin-ultravnc-server.dll.zip)

**Comment by teotwawki16** [comment]
I tried your fix on one affected unit at it became unreachable. Good thing backed up the original dll and had to revert.

**Comment by cremilton** [comment]
Hello,

I'm having the same problem reported, I currently only deployed in a test lab, but I've already made a lot of changes to resolve this detail, all to no avail!

I have deployed Veyon 4.0.7 in all my labs, all working properly.

Thank you.

**Comment by tobydox** [comment]
Thanks for testing! If you want you can give the attached DLL a try. Otherwise wait for 4.1.1 which will likely be released next week.

[builtin-ultravnc-server.dll.zip](https://github.com/veyon/veyon/files/2246418/builtin-ultravnc-server.dll.zip)

**Comment by tobydox** [comment]
Fixed in final 4.1.1 release.
