### ISSUE TITLE
Could NOT find LZO

### ISSUE THREAD

**Issue by shah-aadil** [veyon/veyon#378]
After cloning the git repository all dependencies like ZLIB, PNG, JPEG gets included except LZO and QCA despite providing all the required dependencies in the same directory and setting the PATH variable accordingly. I am using Windows 10 64bit and Visual Studio Community Edition. Following is the output log

CMake Error at cmake/modules/FindLZO.cmake:24 (message):
  Could NOT find LZO
Call Stack (most recent call first):
  CMakeLists.txt:128 (FIND_PACKAGE)

![2](https://user-images.githubusercontent.com/27730678/43132651-1f33eafe-8f45-11e8-84f8-fcb715e73089.JPG)
![1](https://user-images.githubusercontent.com/27730678/43132652-1f5ff784-8f45-11e8-931b-b70eed0480b7.JPG)

**Comment by tobydox** [comment]
We don't support MSVC at the moment and I don't have any experiences with it. You probably will have to build LZO and QCA on your own with MSVC first so it can be detected properly. What compiler is used internally? MSVC or some kind of mingw gcc?

**Comment by shah-aadil** [comment]
MSVC

1> C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\aadil\CMakeBuilds\252530f5-a734-023c-b907-fbe2667c3a28\install\x86-Debug"  -DCMAKE_CXX_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/HostX86/x86/cl.exe"  -DCMAKE_C_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/HostX86/x86/cl.exe"  -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "C:\Users\aadil\Source\Repos\veyon" returned with exit code: 1
CMake Error at cmake/modules/FindLZO.cmake:24 (message):

**Comment by shah-aadil** [comment]
The Compiler

-DCMAKE_CXX_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/HostX86/x86/cl.exe" -

**Comment by tobydox** [comment]
Is the library liblzo2 library available in your system? You can also try to pass LZO_INCLUDE_DIR and LZO_LIBRARIES to cmake e.g. cmake ... -DLZO_INCLUDE_DIR=C:\lzo
