### ISSUE TITLE
Restore configuration

### ISSUE THREAD

**Issue by Jp1933** [veyon/veyon#38]
Veyon-ctl config import/export is useful to restore computer list and rooms.

But how can I save and restore displayed room/computer in veyon master for all users on Windows ?

This would be a useful tool for my users if the room is already selected as they run veyon master. (The teacher computer is used to control the same room by all my user)

Thanks.

**Comment by tobydox** [comment]
Depending on your setup you can either activate the function "Automatically switch to current room at start" in page "Master" or copy the file UserConfig.json (inside local configuration folder) to the same folder of other user's profiles.

**Comment by Jp1933** [comment]
Thank you for your quick answer. Copy userconfig.json to user's profile will not not be effective for me as We have severals rooms with different master computer. (also have a large amount of user).

But "Automatically switch to current room at start" and "hide local computer" are great. (as well as don't "allow to modify room / computer list"). Wonderfull job ! Is it possible add "automaticly resize view at startup" (same as "auto" button in veyon)

I think it could be great if veyon configurator could be restricited to admin / domain admins (but remote control is ok for everyone). Is there a way do to it ? after testing : in access control, if i grant access only to admin : normal user can't run veyon configurator (great) / normal user can run veyon but don't see what's happening on remote computers : too bad :( (all the computer have se same veyon config (and cryptographic keys) - easy to deploy ) - something like veyon configurator access would be great (conf file has to be stored in program files to prevent users from modifying it).

Thanks

PS : i can help for french translation.

**Comment by tobydox** [comment]
Veyon Configurator is a local program which can be run with administrative privileges only. It has nothing to do with access control or computer access configuration. You can use access control to configure which users or groups are allowed to access computers under certain conditions. Please refer to the administrator manual for more information :-) Feel free to open a new issue for problems with access control. The French translation just has been completed but you're welcome to join the team to improve it or update it with future changes.
