### ISSUE TITLE
ubuntu ppa

### ISSUE THREAD

**Issue by eoli3n** [veyon/veyon#380]
Hi, 
Please create a PPA to release Ubuntu builds... Its easier to upgrade, doesn't need to test if already present, and in last version : 
[How do i create ppa](https://askubuntu.com/questions/71510/how-do-i-create-a-ppa)

I use Veyon on 800 nodes.

**Comment by tobydox** [comment]
Veyon for Ubuntu is now available at https://launchpad.net/~veyon/+archive/ubuntu/stable - thanks for the input!

**Comment by eoli3n** [comment]
Great !
