### ISSUE TITLE
Computer Containers filter not working

### ISSUE THREAD

**Issue by Dark345** [veyon/veyon#381]
Hi, since the upgrade to veyon 4.1.0, this filter is not working
previously I used to filter like: ou=ma* (since my rooms are the OU starting with MA* character)

here is the screen

![immagine](https://user-images.githubusercontent.com/39943216/43367899-bd53e622-9354-11e8-95c8-c1793032e3b1.png)

thanks

**Comment by tobydox** [comment]
Thanks for your feedback! In Veyon 4.1 we changed the format for filters to the well-known format (foo=bar) - see https://veyon.io/blog/2018/07/23/veyon-4-1-released/ and https://docs.veyon.io/en/4.1/admin/ldap.html#optional-object-filters for details. In case of an upgrade all configured filters should have been adopted automatically.
