### ISSUE TITLE
DOMAIN\USER is not working when "Authorized user groups" from domain are used

### ISSUE THREAD

**Issue by dxdemetriou** [veyon/veyon#384]
DOMAIN\USER is not working,
but just the USER is working.

Every user has to remove the domain part,
otherwhise every computer will not be accessible.

It's not used the LDAP integration,
it's just enabled the "Enable usage of domain groups"

**Comment by alexisantos** [comment]
This problem is affecting me as well :(

**Comment by tobydox** [comment]
In which situation does this happen? When starting Veyon Master?

**Comment by dxdemetriou** [comment]
Yes, when starting "Veyon Master" on "Veyon Logon" when asking for credentials.
When DOMAIN\USER is used every computer is inaccessible.
When USER is used every computer is accessible.

In "Veyon Configuration" in "Access Control" it's with "Enable usage of domain groups" and "Grant access to every authenticated user" (I've tried "Restrict access to members of certain user groups" too)
