### ISSUE TITLE
How to test multi-session feature in Veyon 4.1?

### ISSUE THREAD

**Issue by lbssousa** [veyon/veyon#385]
I would like to test experimental multi-session support in Veyon 4.1 using a multi-seat Ubuntu 18.04 machine. I've already run `sudo veyon-ctl config set Service/MultiSession true` and I've already checked that there are two veyon-server instances running in my system (one for each seat, I presume). However, only one client is being shown in my veyon-master.

Is veyon-master currently aware of multi-session clients, or I should add the second one explicitly (example: IP `x.x.x.x` for the first client, `x.x.x.x:11101` for the second one)?

**Comment by tobydox** [comment]
You're right, in case of multiple sessions the servers are listening at *:111XX so you'll have to add computers with identical host addresses and additional increasing ports in Veyon Configurator.

**Comment by lbssousa** [comment]
Any plans to make veyon-master communicate directly to clients' veyon-service to automatically get the list of veyon-server instances, so I don't need to duplicate IPs expliciting the port?

**Comment by tobydox** [comment]
This might be part of the future commercial addon for auto discovery. However without auto-discovery it would be difficult to handle the situation that one register computer is to be displayed as multiple computers.

**Comment by tobydox** [comment]
Closing this since multi session mode can be easily tested/utilized via Network Discovery add-on.
