### ISSUE TITLE
AD-based ACLs -- Regression from iTALC

### ISSUE THREAD

**Issue by alex-rosenberg35** [veyon/veyon#386]
I am transitioning from iTALC; however, I've hit a wall as it appears that it is no longer possible to set ACLs for specific AD groups in a multi-domain environment.

![veyon_acls](https://user-images.githubusercontent.com/5471233/43538261-83018f6e-958f-11e8-9ac7-10059c924325.png)

This is the setup I am trying to replicate from iTALC:

![italc_acl_auth](https://user-images.githubusercontent.com/5471233/43537477-69e32198-958d-11e8-99f4-fe36f8a3fe10.png)

As you can see, I need to add the "EMPLOYEES\Domain Users" group; however, there is no way to do so.  The lab computer is on a different domain from the users, so none of the groups that are listed are relevant.  I do need ACL-based authentication as users on a another domain should have no access.   I have no alternative as I have no control over the school's AD environment.

Why was this capability removed and is there anyway to go back to the way ACLs were done before with the native Windows dialog in iTALC?

**Comment by tobydox** [comment]
Hi Alex,
thanks for the feedback! You're right that the native ACL dialog has been removed. We did this to to unify the new (much more powerful) access control feature across all platforms. This was only possible by implementing our own generic platform-independent mechanisms (=access control based on local and default domain groups) which unfortunately are not capable of multi-domains at the moment. Have you tried to set up LDAP integration? May be you could be able to fetch groups from both domains if your LDAP/AD server provides both domains. However I have no experience with multi-domain setups so I'm afraid I can't assist you in this. I'll check whether we can enumerate groups from foreign domains internally as well.

**Comment by alex-rosenberg35** [comment]
Hi Tobias,
Unfortunately, we had to continue using iTALC as we could not resolve this.  In the future, would it be possible to incorporate the legacy ACL mechanism for the Windows build of Veyon?  In addition to supporting multi-domain environments, the native Windows dialog allowed us to easily target specific AD groups and users.

![italc_native_dialog](https://user-images.githubusercontent.com/5471233/45064430-a62c7000-b081-11e8-80c7-7f259e21da09.png)

In Veyon, it is really cumbersome to select specific users or groups from a list of everyone on a domain (like ours) with hundreds of users and groups.

**Comment by tobydox** [comment]
Hi Alex,

I'm sorry but we probably won't make any progress here. We'll provide a commercial version of the LDAP module which will support multiple base DNs and maybe also multiple servers. Tell me if you're interested in it and if you would like to evaluate/try it.
