### ISSUE TITLE
Veyon Master (4.1.0) crashes when a client shuts down

### ISSUE THREAD

**Issue by bradmcclintock** [veyon/veyon#387]
Running in a Windows environment (AD back end for sourcing Room/Computer configuration) Veyon Master is crashing every time a client machine shuts down.

(Did raise this on the community forum so apologies for the double up but not sure whether you prefer these sorts of issues raised here).

**Comment by tobydox** [comment]
Thanks for reporting! I'll try to reproduce this and hopefully will find a solution for 4.1.1.

**Comment by tobydox** [comment]
I was not able to reproduce this so far. However I recently fixed a few potential issues within computer connections so if you like you can test the attached unofficial test release. If possible install on both master and clients.

[veyon-4.1.0.12-win64-setup.zip](https://github.com/veyon/veyon/files/2257896/veyon-4.1.0.12-win64-setup.zip)

**Comment by bradmcclintock** [comment]
Excellent, yes that seems to have resolved the issue.

Thanks!

**Comment by tobydox** [comment]
Fixed in final 4.1.1 release.
