### ISSUE TITLE
REQUEST: Version of Veyon on client - Mouse put

### ISSUE THREAD

**Issue by pauloboc** [veyon/veyon#389]
REQUEST: In the master, when we put the mouse on the client, along with the "state, room, host, features" add version of veyon on client.

**Comment by tobydox** [comment]
Thank you for your proposal! Even though I like it in general I think it should not the scope of Veyon Master application. Veyon Master designed for simple and easy use so we should be careful to not overload the user interface with too much information, especially if something like the installed version of Veyon is something, usually nobody except for administrators cares fore. If you have a working software distribution mechanism which installs software automatically you won't need this kind of information in Veyon either ;-)
