### ISSUE TITLE
LDAP and WOL - Veyon 4 RC2 (3.99.6)

### ISSUE THREAD

**Issue by RvdH72** [veyon/veyon#39]
Veyon 4 RC2 (3.99.6)

At first I filled 'Local data' with 10 PC's including mac addresses. Power On (WOL), Run Program and Open website worked. As we have 500+ computers it seemed LDAP was a better idea.

So I configured LDAP, all test are ok except in: Environment settings > Object attributes > Computer MAC address attribute (Value typed in: macAddress)

Computers are populating Veyon Master and it works (so that's all good!), but Wake-On-LAN, Run Program and Open website didn't work
Perhaps because the LDAP search for Computer MAC addresses attribute is not valid.
Active Directory doesn't hold the macadresses?

I get the error when testing:

Could not query any computer MAC addresses. Please check the computer MAC address attribute parameter or enter the name of an existing object.

LDAP error description: 0000208F: NameErr: DSID-0310022D, problem 2006 (BAD_NAME), data 8350, best match of: `<computername>`
`
Maybe it is possible let Veyon do a ping and arp -a (at the background) to resolve the mac-adresses and work with that instead so WOL will work?

![ldap problem computer mac adress attribute](https://user-images.githubusercontent.com/29754578/27640705-4aff1d8e-5c1a-11e7-8ff1-3cf9b50f3cb4.jpg)

**Comment by tobydox** [comment]
ping/arp will not work if the computer is not powered on ;-) All I can suggest is to add the information into your Active Directory by adding the missing attribute via an appropriate additional LDAP schema. Does your AD server also act as an DHCP server? If so the attributes should be stored somewhere in the directory.

**Comment by RvdH72** [comment]
You're absolutely right! I found the macAddress attribute in the AD Schema, so it's already there, but it is not under AllowedAttibutres and therby not shown in the Attibute editor of the computeraccounts, so I'll change that in AD Schema under the computer class as an optional attibute. I'll report back.

**Comment by RvdH72** [comment]
Update: After adding the macAddress attribute to the computer class the macAddress attribute is now shown in the Attibute editor of the Computeraccount, but it was <not set>. This attibute will not be auto-polupulated, so I did a DHCP export by using the netsh command with a command-prompt (elevated): netsh dhcp export together with ldif.exe for an AD export and combining them together gave me a file to import with ldif again. Now Active Directory has the attribute macAddress filled with a value and WOL via Veyon works now. This is not easy and time-consuming and when a computerroom gets new PC's I have to do this procedure again (export/import or manual edit the macAddress attribute per computer in AD). 

Is it not possible to let Veyon look at the DHCP server for the recent mac address of a computer?
Something like: Netsh DHCP server \\<myserver> scope <192.168.0.0>  show clients | findstr "<YourMACAddressHere>"?

**Comment by RvdH72** [comment]
By the way: While macAdress is filled in Active Directory, the test still doesn't work and shows the same error message

**Comment by tobydox** [comment]
Thanks for figuring this out! Even though it still is desirable to have all information in AD I understand the demand for alternative ways to retrieve the MAC address information. A possible solution would be to provide different mechanisms for looking up MAC addresses:

  * Network object directory (default)
  * netsh
  * External file (CSV/JSON)
 
These mechanisms would be configured in a separate configuration page.

**Comment by ldlx** [comment]
What DHCP servers should Veyon support? I would like to have it to support DHCP servers of Sophos UTMs. Just kidding.

Veyon could read the actual MAC address of online computers, but they have to be on the same subnet and it can only read the MAC address of the current connection (LAN/WLAN) - this is not desirable in my opinion.

You can write the MAC addresses of each computer to AD by using PowerShell (maybe even batch scripts would work) when booting the computer. The computer needs write access to its own computer object and your script should select the correct interface (so a LAN interface that's not virtual - imagine computers that have an OpenSSL client installed and a virtual network interface or both LAN/WLAN interfaces).

PS: I used the wwwhomepage attribute - it already exists in computer objects and is neither displayed in MMC dialogue nor useful (in my environment). I assume that the computer has only one physical LAN interface in my Powershell script.

**Comment by tobydox** [comment]
As suggested by @ldlx and others there are possibilities do keep MAC addresses in AD. The admin manual has been updated and contains some basic information on that. I therefore consider the issue as resolved - feel free to respond and/or re-open it.

**Comment by chrisakak9** [comment]
Hi @ldlx Would it be possible to share your script with us please?

Thanks

**Comment by ldlx** [comment]
powershell -command "get-adcomputer $env:computername | set-adcomputer -HomePage  (get-netadapter | where {$_.Interfacetype -eq 6 -and -not $_.Virtual -and  $_.HardwareInterface } | select -First 1).MacAddress"

**Comment by ldlx** [comment]
please note that it must be $_ instead of $ in the "where" statement

**Comment by ciesept** [comment]
Does Veyon read the MacAdress attribute from Active Directory? Which format ?
