### ISSUE TITLE
REQUEST: Screen client higher than the master

### ISSUE THREAD

**Issue by pauloboc** [veyon/veyon#390]
When the screen/resolution client  is greater than the master, 
change width of remote control to master width.

*** If the client resolution is greater than the master resolution: Ex:

Client: 1600x1024
Master: 1366x768

Remote control set: 1366x768 (master resolution)

**Comment by pauloboc** [comment]
To solve this, we could put a configuration in Veyon, to define the size of the windows in pixel (fixed) or percentage (with respect to the resolution of the master).

Ex: Master 1600x900
We put in the window: 90%, so the window (only read and remote control) comes with 1440x810.

**What do you think?**

**Comment by tobydox** [comment]
I think this would make things too complicated. If the client resolution is greater than master resolution the screen will be scaled automatically which is the best option. Resizing the window manually is still possible. Feel free to modify the remote control plugin such that it sets your custom desired resolution by inserting a "setFixedSize(x, y);" call into RemoteAccessWidget.cpp right after the "move( 0, 0 );" call.
