### ISSUE TITLE
Text messages do not appear

### ISSUE THREAD

**Issue by MrJDickinson** [veyon/veyon#392]
I can use other features such as remote control on student machines, however the text message function does not work - I send the message and the message will not appear on student screens.

**Comment by tobydox** [comment]
Thank you for your bug report! Are you using the latest version of Veyon? Which operating system are you running? Did you make sure the computer name is not identical to the user name (which can cause troubles internally)?

**Comment by tobydox** [comment]
Closing due to missing feedback.
