### ISSUE TITLE
previews in master are ok but no connection to clients

### ISSUE THREAD

**Issue by Dark345** [veyon/veyon#393]
Hi

after upgrading to 4.1 and 4.1.1, there's  strange beheaviour in my veyon master, previews of my clients are shown correctly in Master, but if I try to connect to them (view only or control), a black screen appears stating it's connecting.... Randomly the connection might work after 5 seconds or two minutes of waiting.
I can present on all of my clients with no troubles or delays, i can lock the screen, shut down them, no problem.

I'm using TightVNC 2.8.11 64bits, Veyon 4.1.1 64 bits, W7 64 bits and key files auth method.

With pre-4.1 version of Veyon problem didnt happen, but to be sure, after the upgrade, I re-created a new pair of keys and a new config file for all my clients.

Can you help me trouble shooting this?

thanks

**Comment by merasiz** [comment]
I'm using built-in VNC server and I have a problem to connect to clients (same view only or control), a black screen appears stating and waiting randomly the connection on version 4.1.1 too. But I have delay within view or control alternate with black screen appears.

Then I have to close service Veyon and I try to install TightVNC 2.8.11 to remote and view without Veyon service so it work fine.

In addition, I try to present with demo screen and waiting for long time that I can't to demo screen to my clients. 


thank you

**Comment by tobydox** [comment]
Please update to 4.1.2 where this problem should be solved :-)
