### ISSUE TITLE
"PlatformPluginManager: no platform plugin available!" since 4.0.9 and even with 4.1.1

### ISSUE THREAD

**Issue by vincentvije** [veyon/veyon#397]
Hello Tobias,

Please I really need your help.

Since Abril, I've the same problem with all Veyon versions from 4.0.9 to even 4.1.1. I tried to make it run a lot of time with all versions.
I install Veyon from RPM in Opensuse, and when running veyon-configurator or veyon-master, I always get

> Adding plugin search path "/usr/lib64/veyon"
> PlatformPluginManager:  no platform plugin available!
> Aborted (core dumped)

I don't know what to do. I can't use Veyon...

I found it in your code PlatformPluginManager.cpp, but I really don't understand.
I found some old issueswith the same problem but no solution.
Please could you help.

Thanks in advance.
Kind regards,

Vincent

**Comment by vincentvije** [comment]
Hello Tobias, please do you have some hint ? Since abril updates, I've always this problem... Thanks in advance.

**Comment by vincentvije** [comment]
Hello,
Have this problem been solved in 4.1.2 ?
Thanks,
Vincent

**Comment by tobydox** [comment]
We can try to solve this in a support session as proposed via PM.

**Comment by swhaat** [comment]
I had the same problem on Arch for as long as the issue here mentions it..
it was recently resolved when the CMAKE_INSTALL_LIBDIR=lib... before it was =/usr/lib...
at least on Arch it was more of a packaging issue..
hope it helps

**Comment by vincentvije** [comment]
Thanks a lot swaat, so you removed the leading "/" to give just a relative path ?

The README.md instruct to use "cmake .." or "cmake -DCMAKE_INSTALL_PREFIX=/usr .."
Then I should use a relative path like what ?
Why do you use /usr/lib ?

Thanks again !

**Comment by swhaat** [comment]
you can have a look at the build file used for Arch:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=veyon

I dont know which system u will use it in, so the lib directory might be different e.g. lib64.. just check that for your system and try building..

**Comment by vincentvije** [comment]
Thanks so much swhaat ! I'll try this asap !

**Comment by tobydox** [comment]
AFAIR this has been fixed in your environment. If not, please re-open.
