### ISSUE TITLE
Load computers list

### ISSUE THREAD

**Issue by robatz** [veyon/veyon#40]
Please, can you make possible to load a computers list from a CSV file? Thanks

**Comment by RvdH72** [comment]
+1 to load a computers list by using an export of DHCP. That's much easier instead of filling Active Directory with mac addresses.

**Comment by tycoony** [comment]
How about a Veyon <-> Webservice connect? like: https:\\webservice.int\getveyonjson.jsp?mac=001999123456 ... username and pc name and the answer is a json or xml with all classroom data we need? Alls the classroom logic can be handled in the server backend (connect AD, LDAP, ZENworks or whatever database/logic)

**Comment by PlazzmiK** [comment]
+1 to load a CSV file, or even add computers manually.

**Comment by tobydox** [comment]
What do you mean by manually? You can add computers manually using the "local data" plugin and the "local data" configuration tab.

**Comment by tobydox** [comment]
The tab is now named "Rooms & computers". CSV import will be part of Veyon 4.1.x in a few months.

**Comment by tobydox** [comment]
Veyon 4.1 Alpha & newer have capabilities for CSV import at the command line - feel free to checkout ;-)
