### ISSUE TITLE
Connection Issues when Master PC is Booted Before Client PCs

### ISSUE THREAD

**Issue by ccopel** [veyon/veyon#403]
Veyon 4.1.1 x64, Windows 10 1803. We are experiencing an issue where if the PC running the master is booted first (whether logged in first or not,) when the client PCs are booted they will get stuck on "Establishing connection" and bounce between the default grey monitor image and an attempted preview that is pure black. Remote view/control can connect, but will be left with a fully black screen. This issue is resolved by rebooting the PC running the master - as long as the clients are booted first, this behavior does not occur.

Not critical to functionality, but it is causing issues with the user experience for our less technical users. I don't see any log lines that seem helpful, but please let me know if I can send any more useful information. As always, thanks for your assistance.

**Comment by tobydox** [comment]
Does this still happen with just released 4.1.2?

**Comment by ccopel** [comment]
This appears to be fixed in 4.1.2. I will continue to monitor and confirm after some time.

**Comment by ccopel** [comment]
@tobydox Seems to be good. Thank you.
