### ISSUE TITLE
Veyon Password Reset?

### ISSUE THREAD

**Issue by ekostun** [veyon/veyon#404]
I used Veyon in my classroom computer lab all year last year and loved it. I tried to log in for this school year and it's saying I'm not entering the same password. I cannot find a place to either recover or change my password. How can I do this?

**Comment by tobydox** [comment]
You'll always have to enter your regular user password also used for logging on to the computer :-)

**Comment by scanlanmel** [comment]
I'm very confused about how to log in. I see a screen that says All when I open the Master. I've tried every password I can think of. Please help :)

**Comment by Antoinenz** [comment]
When I open Veyon Master, it asks for a Logon Authentication, and although it seems obvious that it would be the computer password, I'm running Windows 11 without a password, but instead- a pin... How do I find the password!?

**Comment by tobydox** [comment]
Normally you would enter the password of your account. If your account doesn't have a password, you should change the Veyon configuration such that key file authentication is used on all computers. See the manual for details :-)
