### ISSUE TITLE
Cryptocore: failed to decrypt password 

### ISSUE THREAD

**Issue by topeminent** [veyon/veyon#405]
Hi just trying out the latest and greatest veyon 4.1.2.0 version from win10 x64 to win10 x64. And could not authenticate the master to the client . My log shows me the failed to decrypt password. After i reinstalled the old version 4.0.7 everythings working, so it s not a networking issue

**Comment by topeminent** [comment]
Had to change my firewall filter a bit on the destination pc, it s working properly now

**Comment by ankitasaini01** [comment]
hello, could you please elaborate the changes made in the firewall . as i am also facing this issue. Thanks
