### ISSUE TITLE
Release of unofficial versions Ubuntu 16.04 32bits and Raspberry PI ARM

### ISSUE THREAD

**Issue by pauloboc** [veyon/veyon#407]
**Veyon version 4.1.2 (commit 3962)**

**Ubuntu Xenial 16.04 (32bits)** [veyon_4.1.2_32bits_xenial_commit_3962.zip](https://github.com/veyon/veyon/files/2376763/veyon_4.1.2_32bits_xenial_commit_3962.zip)
**Raspberry PI (ARM)** [veyon_4.1.2_armv7l_raspberry_commit_3962.zip](https://github.com/veyon/veyon/files/2376764/veyon_4.1.2_armv7l_raspberry_commit_3962.zip)

**Comment by tobydox** [comment]
Thanks for the files! Our PPA has 4.1.2 packages for Ubuntu 16.04 already, unfortunately there's no possibility to build/provide armel/armv7l binaries in PPAs any longer. You'll need at least an RPI2 so you can use the armhf packages. Please also note that for security reasons we can't officially publish files contributed by users but you're welcome to maintain and publish them on your own page and announce them in our community forum :+1:
