### ISSUE TITLE
Task Manager

### ISSUE THREAD

**Issue by dsjiern** [veyon/veyon#41]
Same problem as in iTALC: When display is locked, a pupil can open the Windows-TaskManager with [Ctrl]+[Alt]+[Del] and then close the display-lock...

**Comment by tobydox** [comment]
Thank you very much for your bug report! Did you restart the computer after installing Veyon? Input device locking does not work until a complete reboot due to a special driver being installed.

**Comment by dsjiern** [comment]
Thank you for this info. After restarting the locking works!
