### ISSUE TITLE
Authentification key still failed on Linuxmint 18 with windows 10 veyon master

### ISSUE THREAD

**Issue by orion777** [veyon/veyon#411]
Hello

I don't understand what is wrong with authentification key when using veyon master on windows 10 with linuxmint 18 client. Here is the issue using Veyon 4.1.2

![capture 1 veyon](https://user-images.githubusercontent.com/29846901/45599190-8bde8480-b9e7-11e8-8f74-c6d98b6fde38.JPG)

No connection with the Mint veyon client on the windows master screen. Monitor client remind red color on the master screen control.
keys were created with veyon configurator on the windows 10 master like this :

![capture 2 veyon](https://user-images.githubusercontent.com/29846901/45599228-00192800-b9e8-11e8-9afd-3c3126f20401.JPG)

Private key was copied in /etc/veyon/keys/public/teacher with permissions like this 👍 
chmod -R 0755 /etc/veyon/keys/public/teacher

And when veyon service is running on linuxmint we have the following message on Mint desktop

![capture d ecran_2018-09-16_19-19-24](https://user-images.githubusercontent.com/29846901/45599256-89305f00-b9e8-11e8-8663-a804f8d3df8b.png)

**Comment by orion777** [comment]
The message indicate authentification error, user 'PC-ATP" (on windows veyon master)tried to access to this computer but failed to authentificate.

In our school we often have windows master for linuxmint client but at this time we still can't install veyon because of this issue. Can you fix this? Thanks you very much

I don't know if  same issue exists with Linuxmint veyon master and Linuxmint veyon client.

**Comment by temp76** [comment]
Hello!
Did you change authentification method in client config? This setting must be same on master and client.
![img01](https://user-images.githubusercontent.com/43370326/45675775-c73c9880-bb38-11e8-9bda-bcd07a4cbdef.PNG)

**Comment by orion777** [comment]
Yes i specified key file authentifciation on master and client. So what is wrong ? Is there anything else to configure? Thanks you for your help.

**Comment by orion777** [comment]
I copied the public key of course
Since i specified the key file authentification on the client side, Veyon master on windows 10 can display only the Linuxmint login screen windows but once i entered nickname and password to be logged on the Linuxmint session then Monitor Linuxmint client become red color.
In our school Linuxmint session are based on Openldap and samba domain. 
In the early versions of Veyon, authentification key worked very well and Mint session were displayed in the windows veyon master without problem.  So what is wrong now?
I also tried to check the access control options. See capture below . It seems that only this option checked allow displayed the Mint login screen windows on the master. With the other options monitor screen remain red all the time
Thanks you for your help. Hope to find a solution. 
![veyon4](https://user-images.githubusercontent.com/29846901/45849495-6c6e9100-bd32-11e8-8600-f3c63b7544ce.JPG)

**Comment by wsr-energy** [comment]
Hello!
Try set settings like that on client first. If this doesnt work, then set it on both master and client.
![img02](https://user-images.githubusercontent.com/43405616/45866110-5db2c900-bd88-11e8-804a-5b24687d6053.png)

**Comment by orion777** [comment]
Hello
Thanks you for your help but it doesn't work. I tried all the possible access control options There is a problem when using key authentification and  Linuxmint domain environment. Domain session on Linuxmint  doesn't allow to have access to key authentification and so it isn't displaying on the veyon control master. Hope this will be fixed soon.

**Comment by tobydox** [comment]
From what you wrote in another issue everyhing works for you in Veyon 4.2, right? I'm therefore closing the issue. Thanks to all others for your help and suggestions!
