### ISSUE TITLE
Prevent Master versions from seeing other Masters

### ISSUE THREAD

**Issue by peterajgreen** [veyon/veyon#412]
Hi,
Does anyone know of a way to prevent Masters from viewing other Masters?
I have Veyon set up in a school, with student version for student PCs and Master version on Teacher laptops - but teachers can see/access other teachers' machines.
Is there a way to hide all master machines?
Or hide one room in which I could locate all the teachers' laptops?

**Comment by temp76** [comment]
Hello!
Use this option on teachers' computers. Then use "Show only active computers" button in master interface.
Here documentation: https://docs.veyon.io/en/4.1/admin/reference.html#network
![img02](https://user-images.githubusercontent.com/43370326/45676507-8cd3fb00-bb3a-11e8-856a-c53e9196ec0f.PNG)

**Comment by peterajgreen** [comment]
Thanks @temp76 seems to be working - glad it was so simple as a checkbox!

**Comment by tobydox** [comment]
@temp76 thanks for helping!
