### ISSUE TITLE
LDAP authentication in Master causes execution of login scripts

### ISSUE THREAD

**Issue by ysalmon** [veyon/veyon#413]
Greetings,
I do not know for sure whether this is a Veyon bug or a configuration error on the side of my system admin, but upon authenticating with my ldap credentials in veyon-master, my personal drives on the NFS were mounted a second and even a third time, which means that some login scripts are executed when I think we do not want them to.
![capture d ecran_2018-09-18_10-29-09](https://user-images.githubusercontent.com/536850/45675236-28f80500-bb2f-11e8-8669-3cbddc3178f4.png)

**Comment by tobydox** [comment]
Veyon uses PAM for authenticating a user so it's possible some kind of PAM session modules (such as pam_mount) perform additional actions. I'll have a look at it.

**Comment by tobydox** [comment]
Issue should be fixed in latest master branch and upcoming 4.1.3 release.
