### ISSUE TITLE
Privacy issue: ask for permission on client

### ISSUE THREAD

**Issue by caerts** [veyon/veyon#414]
Hi,

Because of GDPR, we are looking for a way to leave choice to client to accept or not that Master can look or take control of his desktop. Notification seems to be not sufficient (the free and informed consent of the person concerned).

Thanks in advance

**Comment by wsr-energy** [comment]
Hello!

Try using access control rules: https://docs.veyon.io/en/4.1/admin/access-control-rules.html
It seems that option "Ask logged on user for permission" is what you want. 
You only need to choose the right condition.

![img01](https://user-images.githubusercontent.com/43405616/45745749-30401100-bc0a-11e8-84e9-53713ae65093.png)

**Comment by tobydox** [comment]
Proper answer given by @wsr-energy  - thank you very much!
