### ISSUE TITLE
Error filtering clients - UTF8

### ISSUE THREAD

**Issue by pauloboc** [veyon/veyon#416]
My Room:

> "Diretorio 1"
"Diretório 2"
"Diretorio 3"

I enter the filter: 
> "Diretorio"

Only displayed:
> "Diretorio 1"
"Diretorio 3"

The "Diretório 2" is not displayed because of the accent "ó".
**It is possible on the filter to ignore accent?**

**Comment by tobydox** [comment]
This is not possible as technically these are different characters. Fuzzy matching would require lots of additional code to maintain without any real benefit for many users. You can try to use regular expressions such as "[oò]".
