### ISSUE TITLE
UAC Prompt when installing with /S /NoMaster

### ISSUE THREAD

**Issue by Shadowfita** [veyon/veyon#418]
Hi! I was having a play with veyon at one of my schools today (for work) and think its fantastic! I had only one concern though.

When installing it silently with the /S and /NoMaster switches it opens up a UAC prompt at the very end of installation. Has anyone else had this issue? I'm a bit worried because I wanted to deploy it to all machines in both computer labs silently but it may not work.

Thanks!

**Comment by ideamk** [comment]
For install you can use build-in admin account (RID 500), or use psexec with -s switch (use system account).

**Comment by tobydox** [comment]
@Shadowfita Which version did you try? I tried to reproduce this on both Win 7 and 10 but everything worked as expected with latest releases. When you run the installer as a non-admin user UAC prompt will appear at the beginning of the installation. When running as an admin-user there's no UAC prompt at all. When installing silently your deployment mechanisms should run always run installers with administrative privileges so there shouldn't be an issue here.

**Comment by Shadowfita** [comment]
@tobydox I used the latest version from the website at the time which I think was 4.1.2. I was logged in with my admin account and it was working fine until the very end of the install. I might need to try it with these switches: "/S /NoMaster -s". I'll have to report back after trying on some other computers next week. We've just had school holidays so I haven't been on site.

**Comment by tobydox** [comment]
Closing this due to missing feedback - feel free to join again :)
