### ISSUE TITLE
Authentification key still failed on Linuxmint 18 with Linuxmint 18 veyon master 

### ISSUE THREAD

**Issue by orion777** [veyon/veyon#419]
This time i  made the veyon master installation on the Linuxmint 18 and here again authentification key failed. Linumint master can't even display it screen on Veyon master. See below
![veyon2](https://user-images.githubusercontent.com/29846901/45849828-d9365b00-bd33-11e8-9fb3-71ceec693ab8.png)

And when running the veyon master on the Linuxmint i can see this on the terminal but not sure if it is linked with the key authentification problem
![veyon3](https://user-images.githubusercontent.com/29846901/45849862-0256eb80-bd34-11e8-9a0a-b99dfa91f987.png)

So is there a problem with authentification key linked to linux client ? And specially with linux client samba sessions?
Thanks you for your help because here we can't use Veyon with linux but only windows, and we have lot of linux computers.
Regards

**Comment by wsr-energy** [comment]
I just installed Veyon on Linux Mint, and connect using key authentification. It's working. I think your Veyon cannot handle domain users (As you said, you can view screen before login in). Try 'Enable usage of domain groups' optinon (see other comment).
![img03](https://user-images.githubusercontent.com/43405616/45874306-31557780-bd9d-11e8-9097-8949a0a7f06c.png)

**Comment by tobydox** [comment]
Which specific version of Linux Mint are you running? 18.1/2/3? 32 or 64 bit? Which version of Qt5 packages is installed (5.x)? Did you build Veyon packages on your own or are you using DEB files available from the project page?

**Comment by orion777** [comment]
Hello Tobias,
I'm running Linuxmint 18.3 xfce 64 bits. Version of Qt5 is 5.5.1.
I installed latest version of Veyon using DEB files available here >>https://veyon.io/download/
I downloaded the Ubuntu 16.04/Deb/amd 64 link
Thanks you for your help.

**Comment by orion777** [comment]
I see you released Veyon 4.1.3. Is there any chance it fix this issue?
Regards

**Comment by orion777** [comment]
It works now. Authentification key is working on Linuxmint environment but there is another problem when user is logging on it session (with ldap authentification) I will open a new issue for this.
