### ISSUE TITLE
Having trouble configuring LDAP

### ISSUE THREAD

**Issue by JAG1117** [veyon/veyon#42]
I have an OU with 10 computers in it, LDAP and Base DN both test successfully. I put the rest of the DN settings in the computer tree under Environment settings and that says 10 computers found, but when I open the Veyon Master nothing is there. What am I missing?

**Comment by JAG1117** [comment]
Here's my configuration:
User Tree: OU=TECH (this is the OU where my username lives and that's the account I'm using for testing.

Group Tree: OU=Groups,OU=Junior High,OU=Pools,OU=Horizon (there is a group inside this tree that all of the computers I'm using to test with are a part of, not sure why this is necessary.)

Computer Tree: OU=Technology Lab 1,OU=Junior High,OU=Pools,OU=Horizon (this is where my 10 test computers are)

User login attribute: sAMAccountName
group member attribute: memberUid
Computer host name: dNSHostName

These settings are not working.

**Comment by JAG1117** [comment]
Figured it out.

**Comment by RvdH72** [comment]
Probably forgot to set Backend on Network object directory to LDAP?

**Comment by Lrobben52** [comment]
@JAG1117 Can you describle how you did it?

**Comment by RvdH72** [comment]
![1-ldap general](https://user-images.githubusercontent.com/29754578/27833504-706b6ee8-60d3-11e7-901e-0e1e0da8d7c4.jpg)

Computer host name=name in my case, the rest seems ok looking at your initial comment.

**Comment by JAG1117** [comment]
That's what I forgot.
