### ISSUE TITLE
Remote control inserts single quote when double quote is pressed

### ISSUE THREAD

**Issue by ysalmon** [veyon/veyon#424]
When trying to help a student using Remote control, I experienced that when I type a ```"``` on my computer, this translates to a ```'``` on their machine. This happened with the IDE we are using, and also happens when doing the same with a lightdm login prompt, so I suspect it is not related to the particular application on the remote computer.

**Comment by tobydox** [comment]
I can't reproduce it. Which keyboard layout are you using?

**Comment by ysalmon** [comment]
It's the [standard French configuration](https://en.wikipedia.org/wiki/AZERTY) ; double-quote and single-quote are on different keys, so it is not a problem with a modifier.

**Comment by ysalmon** [comment]
Today, I experienced that typing a ```_``` gives a ```-``` and that typing a ```*``` gives a ```8``` !!

**Comment by ysalmon** [comment]
Thanks ; I tried today and while it is now possible to input double quotes, I encounter the following problems :
 - on some occasions, the very first key stroke is interpreted with the (presumably default) QWERTY layout, not the AZERTY layout which is used on both local and remote computers ;
 - numlock and capslock are not taken into account ;
 - dead keys do not work : normally on a French keyboard, to produce a ```ê``` for example, one presses the ```^``` dead key, then ```e``` ; but doing so gives nothing on the remote computer (not even an unaccented ```e```).

**Comment by tobydox** [comment]
Thanks for the feedback! Are you still working with "nomodtweak"?

**Comment by ysalmon** [comment]
I am working with the master from yesterday morning ; I did not change de configuration file from my earlier setup.

**Comment by tobydox** [comment]
OK, can you try the new version without the  `-nomodtweak` option?

**Comment by ysalmon** [comment]
There has never been such an option in my configuration file.
