### ISSUE TITLE
connecter un utilisateur

### ISSUE THREAD

**Issue by oliviercalpetard** [veyon/veyon#425]
Bonjour
J'utilise veyon en établissement scolaire et c'est super (environnement linux et windows)
Braovo pour ce fabuleux travail
ayan utiliser "impero" par le passe , il y avait un truc très partique, on pouvait connecter un utilisateur  sur plusieurs pc en même temps dans le menu (comme pour la deconnection) .....

**Comment by oliviercalpetard** [comment]
Hello
I use veyon in school and it's great (environment linux and windows)
Braovo for this fabulous job
I was using "impero" in the past, there was something very practical, you could connect a user on several pc at the same time in the menu (as for the disconnection) .....
sorry if the translation is not perfect

**Comment by SARAH12345677** [comment]
*DAVE BUSH*

WHAT SCHOOL DO YOU GO TOO

**Comment by tobydox** [comment]
Automatic login is currently not implemented but planned for future releases - watch out for news in 2019 :)
