### ISSUE TITLE
Cannot sort computers by hostname

### ISSUE THREAD

**Issue by esmuigors** [veyon/veyon#429]
Dear developers and users,

Recently we installed veyon v. 4.1.2 in the classroom with ubuntu 18.04 on every PC, both master and clients. The connection in the room is by DHCP for some reasons, and the main sysadmin is reluctant to change it to static addressing for certain reasons. The addresses are, however, from a quite narrow address range, although still there are more available addresses than are PCs in the classroom, so if I added all possible 253 addresses, the management screen (Veyon Master window) would be barely navigable.

My questions are as follows:
1. Can I make only active connections visible in the management screen?
2. Can I sort the connections by their hostname or by MAC address (or, at the very least, by IP address)?

Thank You in advance.

**Comment by HasanTekeli** [comment]
I haven't used 4.1.2 yet, but in [the blog post about the release 4.1](https://veyon.io/blog/2018/07/23/veyon-4-1-released/), it says you can hide powered-off computers.

**Comment by esmuigors** [comment]
Thank You very much, HasanTekeli! This did most of what I needed so far.
