### ISSUE TITLE
Common Attribute instead of Dedicated computer groups?

### ISSUE THREAD

**Issue by JAG1117** [veyon/veyon#43]
If I wanted to use an attribute like part of the hostname how would I set this up? 
I tried: (&(objectcategory=computer)(name=*0112*))
How do I do this?

**Comment by JAG1117** [comment]
Basically I just want all the computers in a specific OU to be part of a classroom without having to keep up with putting all of them in a group. Working in a Horizon environment the computers constantly change. How would I achieve this?

**Comment by RvdH72** [comment]
See the examples somewhere in the middle of this page combined with the operators '&', '|' (pipeline) and '!': https://social.technet.microsoft.com/wiki/contents/articles/5392.active-directory-ldap-syntax-filters.aspx

**Comment by JAG1117** [comment]
I tried those settings but I can't seem to get any of the computers to show up inside of the Master. This is where all of my computers live: OU=Technology Lab 1,OU=Junior High,OU=Pools,OU=Horizon,OU=asdf,DC=my,DC=company,DC=.com I just want all the computers in that OU to show up in the master.

**Comment by arinbiorn** [comment]
JAG1117:  I have exactly the same setup, and the same problem.   Did you figure this out?

**Comment by RvdH72** [comment]
For Veyon to work, you must create an OU, create a workgroup or multiple workgroups (the names of these workgroups appear as the classrooms in Veyon) in this OU and put the computers in the workgroup(s) you made, and put this OU in the Veyon Configurator under LDAP > Environment settings > Object trees under Computer group tree.

**Comment by tobydox** [comment]
Grouping computers by OU is currently not supported but indeed a very good and important suggestion which we'll deal with. If you want to prioritize the implementation and receive early updates for testing, you're invited to [make a donation](http://sourceforge.net/donate/index.php?group_id=132465).
