### ISSUE TITLE
Client computers freeze when Veyon Master is opened

### ISSUE THREAD

**Issue by cosmelopez** [veyon/veyon#430]
I have a problem in my classroom where Veyon 4.1.2 is installed.

When I open Veyon Master, client computers running Windows 10 Pro, freeze when they use LibreOffice, Microsoft Office or Google Chrome. They cannot move/maximize/minimize their opened windows.

We use the key files as the login method.

What can I do? Thanks

**Comment by sz-blacky** [comment]
Hello cosmelopez!

Did you manage to figure this out? We are currently on Veyon 4.1.1 and experience an issue very much like you describe - after Veyon Master is started, windows on client computers go haywire and do not respond graphically to input. Alt Tabbing (which I guess forces a complete redraw of the screen) and pressing Ctrl+Alt+Del works and forces the windows to redraw, but they won't display changes after that until the next forced redraw (or quitting Veyon Master).

I will try upgrading to 4.1.5 this weekend and see if that helps (the VNC improvements in 4.1.3 and 4.1.5 might help), but this happens only intermittently (or at least I failed to reproduce it outside of classes), so if you found a surefire way to solve this issue, I would appreciate if you published it.

**Comment by cosmelopez** [comment]
Hello, we solve the problem by installing version 4.1.4, so update the version can solve your problems.
