### ISSUE TITLE
computers not showing when started before master Veyon master is started

### ISSUE THREAD

**Issue by dirkdemuynck** [veyon/veyon#431]
If I start  a PC running windows 10, before I open VEYON on the master, it never shows up as being reachable in the master screen. When I run Veyon master (on Win 10) first, all works fine and the same computer is showing up fine.
What could be the reason of that ?
thanks,
Dirk

**Comment by SARAH12345677** [comment]
Try to refresh thepage

Davey Bush

**Comment by dirkdemuynck** [comment]
How do I do that ? I'm using the latest version.

**Comment by ldlx** [comment]
Are you using hostnames or ip addresses for connection? Is connection with IP working in all cases? Is the hostname of the client registered in DNS/resolvable when the Master starts? How often does the DNS cache on the Master computer and the DNS server flushed and the clients are re-registering?

**Comment by tobydox** [comment]
Thanks for the feedback! As pointed out by @ldlx you need to have a working DNS setup and proper host names added in the Veyon Configurator.
