### ISSUE TITLE
Config distribution

### ISSUE THREAD

**Issue by fgarciapatino** [veyon/veyon#432]
Hello.

I would need to share master configuration of class and computers, and make changes on configuration available to every master at same time for mantainance convenience. I do not have network resources to make it possible, so I have to find another solucion.

One solution, could be to specify an url as a configuration path, and make a request to a web server to retrieve the right config info each time the master starts. Also, identifying the master instance on each request, would make possible to discriminate between master instances, and calculate a different configuration depending on the concrete master function on each case.

**Comment by ldlx** [comment]
You could write settings to the client computers running the Veyon Master using Group Policy Preferences (Registry), by running reg.exe or regedit.exe /s <configfile> (e. g. remote with PSExec), by PowerShell, whatever. Also veyon-ctl could be used to write settings (e. g. remotely with PSExec or PowerShell, maybe a startup-script). I think a restart of Veyon Master would be necessary to apply the new config if it is applied while Veyon Master is running.

**Comment by tobydox** [comment]
@ldlx thanks for your suggestions

If you're talking about the personal user configuration of Veyon Master you can simply change the path in Veyon Configurator, see https://docs.veyon.io/projects/admin-manual/en/latest/reference.html#basic-settings for details.
