### ISSUE TITLE
Veyon 4.1.4 - dual screen doesn't work

### ISSUE THREAD

**Issue by o71** [veyon/veyon#433]
Clients : Windows 10 x64 dual screen

With version 4.1.2 it works well (simple or dual screen)
With 4.1.4 it work well only with one screen.

With 4.1.4 I see the client screen only when only one screen is used (before connecting or when doing ALT-CTRL-DEL) :
![4 1 4 before login](https://user-images.githubusercontent.com/2280629/46850654-0cc94a00-cdf5-11e8-8360-000d2e987756.PNG)
![4 1 4 ctrl-alt-supp](https://user-images.githubusercontent.com/2280629/46850656-0cc94a00-cdf5-11e8-8342-8d974a35b66b.PNG)

If both screens are active on the computer, I see nothing, no screen. I only see the name of the computer at the bottom.
![4 1 4 double screen ko](https://user-images.githubusercontent.com/2280629/46850658-0cc94a00-cdf5-11e8-8438-9bf730e8145d.PNG)

Thanks a lot

**Comment by o71** [comment]
I did a test on another identical client workstation. I see correctly the screen in veyon of the client computer when a user is connected. However, I only see one of the two screens. Is there a problem with the dual screen in this version? In 4.1.2 I do not have this problem.

**Comment by tobydox** [comment]
Can you please verify that multi monitor support is enabled in the VNC server configuration? See https://docs.veyon.io/en/latest/admin/platform-notes.html#ultravnc-server-settings for details.

**Comment by o71** [comment]
Sorry, I'm now with 4.2.1 version, and Its works fine.

Thank you !

Le mer. 19 juin 2019 à 17:38, Tobias Junghans <notifications@github.com> a
écrit :

**Comment by tobydox** [comment]
Thanks for the feedback!
