### ISSUE TITLE
non-root can't run veyon-master on Linux

### ISSUE THREAD

**Issue by MarrekNozka** [veyon/veyon#434]
Non-root user can't run `veyon-master`. Is it correct? In Veyon version a some about 1 year ago `veyon-master` runs under normal user.

```
$ veyon-master
Adding plugin search path "/usr/lib/x86_64-linux-gnu/veyon"
PlatformPluginManager: no platform plugin available!
zsh: abort      veyon-master
```

Thanks

**Comment by tobydox** [comment]
There seems to be a problem with your Veyon installation in general, i.e. plugins could not be loaded. Did you manage to figure it out by now? Which distribution and version are you using?

**Comment by tobydox** [comment]
Closing due to missing feedback. Feel free to join again :)

**Comment by MarrekNozka** [comment]
@tobydox Sorry for latency of my feedback.

I use Devuan/Linux Ascii. It is practically Debian Stretch without systemd.

When I use official debian package I get  the behaviour which is described above  (non-root can't run veyon-master). When I build it from source-codes (9fd66352a00e2d72ac1972394d7a08d8aca1b4f2), it works. 

I have different problem now. Devuan does not contain systemd because I run `veyon-servise` manually or from init script of X-window-manager. But when I run `veyon-servis` command "demo" doesn't work on most stations. When I run `veyon-server`instead, "demo" and "view" works.

I have 20 stations with the same system and the same installed programs. `veyon-service` does not work on most stations but `veyon-server` work only. I can not say where may by problem. From my point of view are intallations same.

What is the different between `veyon-server` nad `veyon-service`? 

Thanks.

**Comment by tobydox** [comment]
Sorry for the late reply. Please see our manual at https://docs.veyon.io/en/latest/admin/introduction.html#components for details on the software components. If you are not using any kind of service, simply make sure to run `veyon-server` inside the user sessions.
