### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by brunolafm** [veyon/veyon#437]
I can't send commands like Alt+Tab or Super key to open start menu on all Windows 7 lab.

PS: Doesn't work whit the keyboard or right click.

**Comment by SARAH12345677** [comment]
DID YOU TRY RESTARTING YOUR COMPUTER AT ALL

*DAVE BUSH*

**Comment by brunolafm** [comment]
Several times

**Comment by tobydox** [comment]
Trapping these special keys is technically somewhat difficult. That's why we have the "Send shortcut" button which allows to send special keyboard shortcuts.

**Comment by brunolafm** [comment]
I understand, but until these function isn't working properly.
