### ISSUE TITLE
Keyboard/Mouse stop working - input device interception driver

### ISSUE THREAD

**Issue by dxdemetriou** [veyon/veyon#439]
The problem with non-working input devices still exists on Veyon 4.1.4 (I had a whole lab with non working mouse/keyboard today).

Because of this, I am using after each installation/configuration on computers:
  "c:\Program Files\Veyon\interception\install-interception.exe" /uninstall
but with Veyon 4.1.4 it seems that the driver is reinstalled.
Is it possible to be an option on installation to not be used the device interception driver?

**Comment by tobydox** [comment]
Thank you for your feedback and bug report! This should be fixed in 4.1.5.
