### ISSUE TITLE
Current room and Hide local dosn't work with dNSHostName and FQDN

### ISSUE THREAD

**Issue by Phaturia** [veyon/veyon#44]
At the LDAP - Enviroment settings - Computer host name attribute
If I use "dNSHostName" and FQDN then the test is working, but "Automaticly switch to current room at start", "Only show current room in computer room management" and "Hide local computer in computer room management" isn't. Although if I use just "name" without FQDN then test and all the above feature is working like it should.

**Comment by tobydox** [comment]
Thanks for your bug report! I'll elaborate on this.
