### ISSUE TITLE
Veyon 4.1.4 - Win 10 - Unable to start Veyon Master and log on asa NON-admin

### ISSUE THREAD

**Issue by pandel** [veyon/veyon#441]
Hi!

I tried Veyon the first time today and am very impressed so far, BUT I am unable to use it as normal domain user. I configured LDAP authentication against our AD and it finds all groups, admins, users, computers and such. I also configured a special AD group "trainer" with designated domain admins and domain users as members who should be allowed to use Veyon. If I test authentication with a desired user (and member of the "trainer" group) from within the configurator it says everything is ok.

But now, if I start "Veyon Master" it always asks for a user and a password (is that correct, even though I didn't activate access control at program start?) and I can see three different reactions:

- first I tried a domain ADMIN which is also member of the "trainer" group -> everything works fine, master program opens and I can connect to clients

- second, I use a domain ADMIN, which is NOT member of the "trainer" group -> authentication works, but I get the message, that I am not allowed to connect to computers and I should talk to my Veyon admin -> also works as expected

- third, I use a domain USER -> I ALWAYS get something like "authentication not possible with this user/password combination", regardless of the user being member of the "trainer" group or not

It also doesn't seem to be of any importance if I am logged an to the machine itself as admin or user before I try to start Veyor Master - the behaviour is always the same. 

I tried to activate DEBUG logging, but that didn't write anything to the log file regarding my logon attempts.

Sadly, I wasn't able to disable the whole authentication mechanism for starting Veyon Master application , as the training room wouldn't really need a authentication mechanism at all.

Any ideas?

Regards
Holger

**Comment by Federica81** [comment]
I have the same problem too and I'm not able to solve it.
Regards,
Federica

**Comment by tobydox** [comment]
Have you resolved this issue in the meantime? I guess there's just a minor configuration issue due to unclear documentation or other types of misunderstanding. Access control in general only needs to be performed client-side. If you didn't enable the option "perform access control on start" for the Master component, you should be able to start Veyon Master without any issues (but still will be able to access computers only where access control passes).
