### ISSUE TITLE
Computers constantly changing position

### ISSUE THREAD

**Issue by Shadowfita** [veyon/veyon#442]
Hi,

I just set up Veyon to monitor students in one of our computer labs but when viewing the computers they seem to be jumping around lots rendering it almost unusable.

I've used notepad to cover up student names for confidentiality.

https://gfycat.com/FatEnlightenedGoose

Thanks!

**Comment by tobydox** [comment]
Thanks for reporting! Are you using different computer names? If they are identical there's no predictable sort order so please make sure to use distinct (host) names.

**Comment by Shadowfita** [comment]
> Thanks for reporting! Are you using different computer names? If they are identical there's no predictable sort order so please make sure to use distinct (host) names.

@tobydox 

The computer names which I wrote in manually when importing them are all "SSC Computer". The only change would be the user who is logged into them but that would remain static until another user logs in with a different first and last name I would imagine.

I installed the master on 2 separate computers and had the issue on both.

Thanks for your response! Please let me know if there's anything else I can do.

**Comment by tobydox** [comment]
Even though I still think you should use distinct computer names I committed a change which will additionally sort by hostname and user names so you should not get random positions at least in 4.1.5.

**Comment by Shadowfita** [comment]
> Even though I still think you should use distinct computer names I committed a change which will additionally sort by hostname and user names so you should not get random positions at least in 4.1.5.

Thanks for the speedy resolution! We do plan on using unique hostnames, it was a quick set up to show staff what it could be used for and then it occurred.
