### ISSUE TITLE
Cross Compile error for Win 64 build - current git

### ISSUE THREAD

**Issue by pandel** [veyon/veyon#443]
Hi!

I get the following error trying to cross compile for windows on Ubuntu 18.04 LTS on current master branch:

***
Scanning dependencies of target windows-platform

[ 59%] Building CXX object plugins/platform/windows/CMakeFiles/windows-platform.dir/WindowsPlatformPlugin.cpp.obj
/home/holger/Source/veyon/plugins/platform/windows/WindowsPlatformPlugin.cpp:41:1: error: definition of explicitly-defaulted ‘WindowsPlatformPlugin::~WindowsPlatformPlugin()’

 WindowsPlatformPlugin::~WindowsPlatformPlugin()
 ^~~~~~~~~~~~~~~~~~~~~

In file included from /home/holger/Source/veyon/plugins/platform/windows/WindowsPlatformPlugin.cpp:25:0: /home/holger/Source/veyon/plugins/platform/windows/WindowsPlatformPlugin.h:44:2: note: ‘virtual WindowsPlatformPlugin::~WindowsPlatformPlugin()’ explicitly defaulted here
  ~WindowsPlatformPlugin() = default;
  ^

plugins/platform/windows/CMakeFiles/windows-platform.dir/build.make:78: recipe for target 'plugins/platform/windows/CMakeFiles/windows-platform.dir/WindowsPlatformPlugin.cpp.obj' failed

make[2]: *** [plugins/platform/windows/CMakeFiles/windows-platform.dir/WindowsPlatformPlugin.cpp.obj] Error 1

CMakeFiles/Makefile2:2215: recipe for target 'plugins/platform/windows/CMakeFiles/windows-platform.dir/all' failed

make[1]: *** [plugins/platform/windows/CMakeFiles/windows-platform.dir/all] Error 2

Makefile:151: recipe for target 'all' failed

make: *** [all] Error 2

***

Sorry for the bad formatting, but the editor won't display long lines correctly..

Regards,
Holger

**Comment by tobydox** [comment]
Thanks for reporting!
