### ISSUE TITLE
Feature request: add custom comments from within Veyon Master to machines in classroom overview

### ISSUE THREAD

**Issue by pandel** [veyon/veyon#445]
Hi!

It would be very helpful if one could add a custom comment to a machine entry in the classroom overview. Often the machine name won't lead to the machine position in the classroom, like no. 1, no. 2, etc., especially if the machine names are perhaps auto-generated based on an i .e. hex numbering scheme or things like that.

Then it would simply be easier to say "I am in front of classroom pc no. 5" than read "fd673ab0" from a label on the screen ;-). Perhaps you could save that like you do with the custom screen sorting in VeyonMaster.json in the user's config folder.

Rergards,
Holger

**Comment by tobydox** [comment]
Thank you for your suggestion! Couldn't you simply use the computer name field for this purpose? It's displayed only so you can enter any information here as long as the host address field contains a hostname or IP address.

**Comment by pandel** [comment]
Hi! I'm not quite sure what you're talking about, but I think you're talking aboiut a manual configuration. My situation is as follows: We are connected to a *BIG* multi-tenant, fully automated AD, I have a special AD group that contains the machines for the classroom. This AD is mainly controlled by our data center, which means I can literally say "I want a new computer configuration" and so I get a new ID with which I can install new machine, but I cannot edit any of the AD fields directly, it is fully automated.

So the only chance for some kind of comment is to have the possibility to enter a description in Veyon directly...

**Comment by tobydox** [comment]
I understand :-) This is currently not planned (however patches welcome) but starting with Veyon 4.2 you can configure a custom computer display name attribute so you could maintain a certain attribute for each computer with additional human-readable information. It's also possible to rearrange computer icons to match their physical location.
