### ISSUE TITLE
Error compilling Veyon 4 RC2 (3.99.6) on Linuxmint 18

### ISSUE THREAD

**Issue by orion777** [veyon/veyon#45]
Hello
I'm not successful with Veyon 4 on Linuxmint 18. Compilation with make install  failed at 92% with the following error :
plugins/vncserver/x11vnc-builtin/CMakeFiles/builtin-x11vnc-server.dir/build.make:154 : la recette pour la cible « plugins/vncserver/x11vnc-builtin/CMakeFiles/builtin-x11vnc-server.dir/x11vnc-veyon.c.o » a échouée
make[2]: *** [plugins/vncserver/x11vnc-builtin/CMakeFiles/builtin-x11vnc-server.dir/x11vnc-veyon.c.o] Erreur 1
CMakeFiles/Makefile2:3457 : la recette pour la cible « plugins/vncserver/x11vnc-builtin/CMakeFiles/builtin-x11vnc-server.dir/all » a échouée
make[1]: *** [plugins/vncserver/x11vnc-builtin/CMakeFiles/builtin-x11vnc-server.dir/all] Erreur 2
Makefile:149 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2

Any help would be really appreciated. I really would want to try this new version for some school.
Thanks you very much

**Comment by jamj2000** [comment]
Are there any files in 3rdparty/x11vnc directory? 

Anyway, VNC connections don't work yet in Linux.

**Comment by tobydox** [comment]
Thank you very much for your bug report! Please follow the instructions at https://github.com/veyon/veyon#veyon-on-linux especially regarding repository cloning and submodule initialization. Downloading the source tarball will not work as submodule sources are not included.

Regarding comment of @jamj2000: VNC connections do work on Linux in general even though there seem to be issues in some environments like yours.

**Comment by orion777** [comment]
Hello

Thanks you for your help!!
I could success in compiling the sources following your instructions.
