### ISSUE TITLE
Searching for computers by MAC address

### ISSUE THREAD

**Issue by lacinamichal** [veyon/veyon#450]
Hello. I'm new in Veyon and I need your help. I want to use Veyon in school. I have assigned IP adress to class rooms. About 20 address for each room. The computers are getting address from DHCP server. So it haven't got static IP address. I want to search PC in Veyon by MAC address, because I want to save PC-1 = MAC-ADDRESS (I can't change from DHCP to STATIC ip address) but it's not working :(.
The key is created correctly.

**Comment by swazi-uta** [comment]
Hello.
I also couldn't use MAC address.  
How about to use Host name. The way was good for me.

**Comment by lacinamichal** [comment]
swazi-uta can you show me how to configure it. PC is in domain for example ABC.pl the name of PC is pr01-st01 users are login to domain ABC

**Comment by swazi-uta** [comment]
![image](https://user-images.githubusercontent.com/40870854/48193417-193cb600-e353-11e8-9386-27390c417e93.png)

**Comment by lacinamichal** [comment]
Ok thank you I will try and write you

**Comment by lacinamichal** [comment]
@swazi-uta So I try this and it's not working :( 
![zrzut ekranu 7](https://user-images.githubusercontent.com/39262184/48198367-e7c6e900-e358-11e8-8497-deefce3e37ac.png)
![zrzut ekranu 6](https://user-images.githubusercontent.com/39262184/48198378-f44b4180-e358-11e8-9416-cb5dc00a2c9d.png)
When I try it by IP address it's work but I don't want to use it, because I have dynamic IP address in all of 
class rooms.
![zrzut ekranu 8](https://user-images.githubusercontent.com/39262184/48198441-31173880-e359-11e8-9697-bc961c071403.png)
![zrzut ekranu 8](https://user-images.githubusercontent.com/39262184/48198472-442a0880-e359-11e8-8e43-12567cb7fef7.png)

**Comment by swazi-uta** [comment]
What is the machine's host name? not pr01-st01??
You can find the host name by "ipconfig /all" from command prompt
or right click on "This PC" from file explore and choose Properties.

**Comment by lacinamichal** [comment]
Ok I will check it in next week. The name of PC isn't pr01-st01 because I tried it on virtual machine 😉

**Comment by lacinamichal** [comment]
@swazi-uta thank you it is working :fireworks: :heart:

**Comment by 2astm** [comment]
Guys, problem didn't solved, using hostname is just workaround
