### ISSUE TITLE
veyon Causes the computer to flash，Keyboard drive failure。

### ISSUE THREAD

**Issue by qiudaozhang** [veyon/veyon#451]
I installed it on twenty machines，The above problems occurred in five machines. Is there any solution?

**Comment by tobydox** [comment]
Which version of Veyon are you using? Keyboard problems should be gone in 4.1.5.

**Comment by tobydox** [comment]
On affected computers please stop the service, remove ddengine64.dll / ddengine.dll and start the service again. Disconnects should be gone then.
