### ISSUE TITLE
Computer Lock doesn't work

### ISSUE THREAD

**Issue by Phorms** [veyon/veyon#452]
Hey
I am using window 10 Education Enterprise version. When I lock the student PC from the master. Student computer display the lock screen but all keys are working, the student can use windows key to call start menu, use Alt+Tab (or Str+Alt+Tab) to switch program, or call Ctrl+Alt+Del also Alt+F4 is possible.
Same at the demo screen.
Using: Veyon 4.1.4

Thanks for your great project.

**Comment by tobydox** [comment]
Can you try with 4.1.5 again? Can you also verify that the input interception driver is installed properly? Try to run `install.bat` from the `interception` directory in the Veyon installation directory.

**Comment by Phorms** [comment]
I tried it with 4.1.5 and Alpha (4.1.9) same issue
But everything works fine after running `install.bat` from the interception directory
