### ISSUE TITLE
Feature request: Broadcast student's screen easily

### ISSUE THREAD

**Issue by chbmeyer** [veyon/veyon#454]
Hello there,

I know that broadcasting a student's screen already is possible according to" Veyon User Manual":
"3.4 How can I broadcast the screen of a student to all other screens?"

Since it's not that convenient and many people like simple "one-click" solutions:
Is it possible to add a button to the menu bar that only is active when one computer is selected?
Probably it should be sufficient to just automate the steps mentioned in user manual.

Thank you for your great work!
Christian

**Comment by tobydox** [comment]
Hello Christian,

this feature is often asked for so we plan to implement it in a future version but can't give an estimate yet.

**Comment by tobydox** [comment]
This feature has been implemented in Veyon 4.5.x.
