### ISSUE TITLE
XDG_RUNETIME_DIR not set

### ISSUE THREAD

**Issue by eoli3n** [veyon/veyon#459]
Hi,
When trying to import my configuration file i get an error:
```
root@bionic:~# veyon-ctl config import /etc/veyon/veyon.conf
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
No protocol specified
qt.qpa.screen: QXcbConnection: Could not connect to display :0.0
Could not connect to any X display.
```

**Comment by eoli3n** [comment]
Strange, i don't have this error now.
Anyway, why a cli command checks if graphical var is set ?

**Comment by tobydox** [comment]
Because some CLI module provide graphical features such as the `remoteaccess` module ;-)
