### ISSUE TITLE
Is there a user limit?

### ISSUE THREAD

**Issue by dilhanmail** [veyon/veyon#46]
I'm using veyon for a class with 40 - 50 students. there are 40 Acer Iconia  10'' tabs. I'm using a Unifi AP AC Lite Access point to connect all of them. Im also using a gigabit switch. Veyon master is in a HP i-5 laptop with a 4 GB RAM. OS is windows 10 pro.
When i use only 10 -12 system is working properly. But when i I try to connect mor (20 -30) there is a huge delay in the demo(10 - 15 seconds). Also the veyon master frequently closes after exceptions. Is this happening because of the limit of concurrent desktop connections in windows 10?. Will it be sorted if i use a windows server 2012? or is there anything that u can advice me.

**Comment by tobydox** [comment]
When using wireless network connections there might be slowdowns with too many clients due to bandwidth limitations. We're still tweaking the new demo server for optimal performance so expect improvements in future releases.

However there should be no application crash. Are you using the 32 or 64 bit version of Veyon?

**Comment by dilhanmail** [comment]
Veyon 32 bit. Os is 64 bit in master. Student OS is 32 bit. Will there be a improvement if i use a windows server OS. Access Point has a bandwith of 850 Mbps. Tablet adapters has 150 Mbps. At the lowest signal reception we get 50 Mbps.

**Comment by tobydox** [comment]
Can you measure the used bandwidth during an active demo with many clients? Can you try to install the 64 bit version of Veyon on Master computer? I don't expect any changes with different Windows versions. The concurrent user limit should not affect Veyon at all.

**Comment by dilhanmail** [comment]
Veyon 32 bit. Os is 64 bit in master. Student OS is 32 bit. Will there be a
improvement if i use a windows server OS. Access Point has a bandwith of
850 Mbps. Tablet adapters has 150 Mbps. At the lowest signal reception we
get 50 Mbps.

**Comment by dilhanmail** [comment]
i did measured. it's below 30Mbps

**Comment by tobydox** [comment]
What about CPU usage? How many cores do you have? Are all of them used?

**Comment by dilhanmail** [comment]
CPU usage never goes more than 55 %

**Comment by dilhanmail** [comment]
your product is really good. if you can test it in wireless environment for 40 it will be great. how ever those exceptions did came when no users got higher.

**Comment by dilhanmail** [comment]
thanks for the info. Ill try with 64 bit version.

**Comment by tobydox** [comment]
Any news on the 64 bit version?

**Comment by dilhanmail** [comment]
Yes I did. There was no notable improvement.

**Comment by tobydox** [comment]
Crashes should be fixed in Veyon 4 RC3 (3.99.7) - please update. This version also allows to tune the demo server parameters in Veyon Configurator so you can try to modify them and see whether this improves performance for you. If so I'd be interested in your feedback :-)

**Comment by dilhanmail** [comment]
thx. ill try. give me few days

**Comment by Tabonet** [comment]
It's possible to restrict usages of application while running without to remote to close it from Master

**Comment by tobydox** [comment]
Unfortunately not possible.

**Comment by Tabonet** [comment]
while student access youtube so I can not lock the computer, but this way I think not good. so I want limit access silently.
