### ISSUE TITLE
unable to authenticate successfuly (access control issue)

### ISSUE THREAD

**Issue by farhantahirt** [veyon/veyon#462]
I have installed master on windows server 2012
Installed it, set authentication type to "key based" generated key, exported key.

copied exported key on student PC (windows 10) 
made authentication mechanism to "key based" , imported master public key, and get following error (tried t to generate new keys, never worked, tried to check firewall, no firewall is present , everything is on LAN, all ports open, still i get error that master tried to authenticate but authenticaiton was not successful.

Here is screenshot: http://prntscr.com/lymmd5

I am really upset, that after trying all day, authentication never works, and there is no way to know that how Logon based authentication need to be setup (the interface is very cluttered, not user friendly)

**Comment by tobydox** [comment]
Sorry for the late reply. Have you managed to get everything workin in the meantime?

**Comment by tobydox** [comment]
Closing due to missing feedback - feel free to come back and re-open :)
