### ISSUE TITLE
Integrate veyon with wapt

### ISSUE THREAD

**Issue by sfonteneau** [veyon/veyon#463]
Could we imagine using wapt to provision veyon?

wapt speaks json

We can recover the name of the machine, their ip, their mac, computer_ad_dn...

Some examples of requests with the API :

https://srvwapt/api/v1/groups
https://srvwapt/api/v1/hosts?groups=group1&columns=connected_ips,mac_addresses&limit=10000

This will allow you to use veyon with dhcp dynamic.

More information https://www.wapt.fr/en/doc/ (open source projet)

We have just integrated veyron to the console for remote control.

Simon

**Comment by tobydox** [comment]
Sorry for the late reply. Thank you very much for your suggestion! Fetching data through an HTTP-based API should be possible via Qt so basically all what needs to be done would be to write a plugin which implements the NetworkObjectDirectoryPluginInterface and create a proper subclass of NetworkObjectDirectory (+optional CLI and configuration page support). Are you interested in starting this?

**Comment by sfonteneau** [comment]
Why not ! I have already written a little script that provides computers and room to veyon veyon-ctl. This would be external plugin? In what language would it be written?

**Comment by tobydox** [comment]
Great! It would be written in C++ with the Qt framework. You could start with cloning the BuiltinDirectory plugin and replace the functions which return computers and rooms.

**Comment by tobydox** [comment]
Any news on this?

**Comment by sfonteneau** [comment]
unfortunately, I will not have time...

On the other hand, I made a wapt package that works with veyon-cli.exe and imports the machines from wapt.

https://wapt.lesfourmisduweb.org/details-package?package=smp-config-veyon_5_all.wapt

About that:
Since the new version, the %room% variable no longer works. but %location% is working but the doc is out of date. https://docs.veyon.io/en/latest/admin/cli.html#network-object-directory

**Comment by tobydox** [comment]
Thanks for pointing out the error in the documentation! I just fixed it.

I think for the time being your import script is perfect and creating a separate directory plugin might be overkill. Whoever searches for "veyon" and "wapt" will find your script so I think we can close this issue. Feel free to propose an addition to our admin manual regarding Veyon and WAPT (source files at https://github.com/veyon/docs/tree/master/admin).
