### ISSUE TITLE
Issue on computer list for LDAP

### ISSUE THREAD

**Issue by killmasta93** [veyon/veyon#464]
Hi,
I was wondering if someone could shed some light on the issue im having. i could not get it working to show the computer list which is on the computer tree CN=Computers, when i click on test it shows the computers but when i open the master does not show any computers? any ideas? 
See pictures

https://imgur.com/a/Bm5vpuz

Thank you

**Comment by tobydox** [comment]
Have you switched the network object directory to "LDAP" in the general settings page?

**Comment by tobydox** [comment]
Closing due to missing feedback.
