### ISSUE TITLE
Does Veyon have the planing recording screen of client?

### ISSUE THREAD

**Issue by zengchao** [veyon/veyon#469]
Does Veyon have a plan of new feature of desktop screen recording?

**Comment by tobydox** [comment]
It's currently not planned unless someone pays for the development of this feature. Feel free to contact us via support@veyon.io for professional services.

**Comment by tobydox** [comment]
Screen recording is available through the new Screen Recorder add-on in v4.7.1. You can try it by installing Veyon 4.7.1 and the add-ons 4.7.1.
