### ISSUE TITLE
Has anyone gotten access control to work?

### ISSUE THREAD

**Issue by JAG1117** [veyon/veyon#47]
I've configured the access control and I'm a member of the group that is in the authorized user groups but it denies me access when trying to login? Anyone figure this out?

![veyon](https://user-images.githubusercontent.com/29801108/27920240-959e9278-6239-11e7-975f-d2832459633c.png)

**Comment by tobydox** [comment]
Are you using domain accounts? Does the "Test" button work?

**Comment by JAG1117** [comment]
Yes I'm using a domain account and no the test button does not work.

**Comment by tobydox** [comment]
OK then group membership identification does not work properly. Does the LDAP integration test "List all groups of a user" return all groups for your user account? If not, check the group member attribute as well as user login attribute and group member identification settings.

**Comment by tobydox** [comment]
Any news on this?

**Comment by tobydox** [comment]
Closing due to missing feedback - please request to re-open if this is still an issue.
