### ISSUE TITLE
Veyon - Students cancelling Lock Screen

### ISSUE THREAD

**Issue by tred44** [veyon/veyon#472]
I'm sorry if this has been answered elsewhere but we're having issues with students cancellign the lock screen. 
All they need to do is pull out the network cable and re-insert to get the full function back on their workstation. 
I realise that the Master will then show it as being unlocked but it would be nice if the session coudl re-connect in it's original state to prevent this workaround. 
I'm wondering when the ability to block internet access becomes available, would this procedure have the same consequences.

**Comment by tobydox** [comment]
Thanks for reporting this issue! Have you tried to enable the "Enforce selected mode for client computers" option (https://docs.veyon.io/projects/admin-manual/en/latest/reference.html#behaviour) so the affected computers will get locked again automatically?

**Comment by tred44** [comment]
Many thanks, I had missed that in my initial setup. However, have now enabled "Enforce selected mode for client computers" on both Master & Client, restarted both services and locked the client but it still comes back with full capability when back online?

Has anyone else experienced this or can soemone confirm it works okay for them?

**Comment by tobydox** [comment]
Is this still an issue? Do clients get locked once a user logged on? This may take a few seconds.

**Comment by tred44** [comment]
No, this issue has now been corrected thank you.
