### ISSUE TITLE
4.1.5  failed authenticating client "::ffff:192.168.1.154" "veyon" 

### ISSUE THREAD

**Issue by max11212** [veyon/veyon#473]
Hello, in a classroom all win7sp1 , veyon 4.1.5 a i can access to all client only with builtin administrator account, but not with an apposite user created (administrator group) in every machine. 
only 3 pc accept the user "veyon".

https://drive.google.com/file/d/1yz3FPTYAPUg40MJTiH8Xt2WFdBQ-o6Xt/view?usp=sharing
https://drive.google.com/file/d/1-9cr6adYd4imaT2ES1tuJzzkzrL0-Dmj/view?usp=sharing

**Comment by tobydox** [comment]
Are you using local or domain users? If local users, make sure they exist on all target computers and have the same password.

**Comment by max11212** [comment]
Tks for reply

The classroom is composed of 12 win7 sp1 pc’s. workgroup (all pc have same
workgroup name)  and all target have same, apposite created user&pwd
(administrator group)

All targets have Kaspersky Endpoint Security  10, same config and release.

I tried to disable Kaspersky and however all targets pc are stil reachable
with KES active only if Veyon master is logged with administrator (all
target have the same local admin pwd), only 3 targets are reachable with
the dedicate user.

I need another user then administrator due the master will used from
teachers,  they can’t know admin pwd.

For me could be sufficient memorize master logon pwd, so teachers can
operate without know it






Da: Tobias Junghans <notifications@github.com> <notifications@github.com>
Rispondi: veyon/veyon
<reply@reply.github.com>
<reply@reply.github.com>
Data: 21 gennaio 2019 at 15:40:19
A: veyon/veyon <veyon@noreply.github.com> <veyon@noreply.github.com>
Cc: max11212 <infoseek4tips@gmail.com> <infoseek4tips@gmail.com>, Author
<author@noreply.github.com> <author@noreply.github.com>
Soggetto:  Re: [veyon/veyon] 4.1.5 failed authenticating client
"::ffff:192.168.1.154" "veyon" (#473)

Are you using local or domain users? If local users, make sure they exist
on all target computers and have the same password.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/veyon/veyon/issues/473#issuecomment-456096161>, or mute
the thread

**Comment by max11212** [comment]
Hi, some news about ? Tomorrow i'm onsite , there is other test that can i do ?

**Comment by max11212** [comment]
Solved removing this https://support.microsoft.com/it-it/help/4480970/windows-7-update-kb4480970

**Comment by max11212** [comment]
Local users who are part of the local "Administrators" group may not be able to remotely access shares on Windows Server 2008 R2 and Windows 7 computers after installing security updates for the January 2019. This has no impact on domain accounts in the local "Administrators" group. | This problem has been fixed in KB4487345.

**Comment by tobydox** [comment]
Thank you for your investigations and your feedback!
