### ISSUE TITLE
Feature Request: Import classes and computers from csv

### ISSUE THREAD

**Issue by Didu2000** [veyon/veyon#475]
Hello!
I am also looking forward to this feature.
The year 2019 has already begun ... Is it possible to hope for the appearance of imports this year?

**Comment by Didu2000** [comment]
This offer has already been.
(Feature Request: Import Computers list from CSV #177)
But it is marked as closed.
There is no functionality, so I found it necessary to open it again.

**Comment by tobydox** [comment]
CSV import is available at the command line in all Veyon 4.1.x releases already :-) See https://veyon.io/blog/2018/04/24/network-object-management-cli/ for details.

**Comment by mrkaban** [comment]
When will this functionality in the configuration wizard?

**Comment by mrkaban** [comment]
I support the theme, the functionality is quite necessary. Through the command line import can cause difficulties for many users.

**Comment by tobydox** [comment]
As of 55aa8169ff36fd661d11162a24b1e2a1535d48f6 there'll be a hint in the configuration page in Veyon 4.2 about the import possibilities at the command line and a link to the online documentation.

**Comment by tobydox** [comment]
Contributions/pull requests for extending the configurator are welcome of course.
