### ISSUE TITLE
Veyon client Service STOP automatically

### ISSUE THREAD

**Issue by SaudITAcademy** [veyon/veyon#476]
Hi, i am facing a problem of Veyon client service STOP automatically, therefore i have to manually start the service. What could the issue be??
Note: i am using Veyon Software v4.1.6 on 50 computers.

**Comment by SaudITAcademy** [comment]
I am using Windows 10 Pro. I believe the service automatically stops due to windows updates.

**Comment by tobydox** [comment]
Can you try again with Veyon 4.2.0?

**Comment by SaudITAcademy** [comment]
I will try it and let you know if the problem still occurs.

**Comment by tobydox** [comment]
A fix will be available in 4.3.3.
