### ISSUE TITLE
Use current windows session authentication as SSO

### ISSUE THREAD

**Issue by baby-gnu** [veyon/veyon#477]
Hello.

We are testing Veyon on windows clients joined to a Samba4 AD domain.

Is it possible to use the current session authentication token as credential to bind to the LDAP server?

I think it may even be possible to query the AD without configuring the LDAP connection with native API, for example [in PowerShell](https://blogs.technet.microsoft.com/heyscriptingguy/2010/12/01/use-powershell-to-query-active-directory-from-the-console/):

```PowerShell
(New-Object DirectoryServices.DirectorySearcher "ObjectClass=user").Find
All() | Select path
```

This could:

* simplify a lot the configuration when using Active Directory on windows, it will remove the need to store a login / password in the configuration (and keep it synced).
* avoid the double authentication when starting the Master

Regards.

**Comment by tobydox** [comment]
Hello,

we're currently using a common generic LDAP client implementation for all platforms (Linux+Windows) based on OpenLDAP. AFAIK this implementation does not allow SSO (except for Linux via SASL/GSSAPI) so we would have to develop a Windows-specific LDAP backend. I clearly see the benefits from an end-user's perspective but unfortunately there currently are no ressources to implement such a backend. Of course any contributions/pull requests are welcome :)

The logon authentication is not related to LDAP. It's used to gain credentials which are used for authenticating client-side against the respective authentication provider (which of course differs between Linux and Windows clients and even within one OS).

Best regards
Tobias

**Comment by tobydox** [comment]
Closing this due to missing development ressources. Contributors are invited to join development on this issue.
