### ISSUE TITLE
Feature Request: Copy Clipboard

### ISSUE THREAD

**Issue by pauloboc** [veyon/veyon#478]
**It would be very useful to copy and paste.**

1 - Copy the teacher and paste on student
2 - And copy the student and paste on teacher

**Comment by SaudITAcademy** [comment]
Copy Paste is a must feature.

**Comment by Zyahko** [comment]
Agreed this is a must need feature

**Comment by pauloboc** [comment]
@tobydox 

are there plans to implement?

**Comment by luedi69** [comment]
I also would love this feature.

**Comment by tobydox** [comment]
Feature likely is going to be backported to the 4.7 branch and part of the upcoming 4.7.1 release.

**Comment by tobydox** [comment]
Yes it works in both directions but only on clipboard changes, i.e. the clipboard content existing before opening the remote access window will not be synchronized. I'm also unsure if we should add another button with a menu allowing to select the clipboard sync behavior (None, bi-directional, local -> remote, remote -> local). The implementation would be quite simple but I always have in mind that we should keep the user interface as simple as possible (this is what many users/teachers love about Veyon!) and take care of not overloading it with buttons.

**Comment by pauloboc** [comment]
> Yes it works in both directions but only on clipboard changes, i.e. the clipboard content existing before opening the remote access window will not be synchronized. I'm also unsure if we should add another button with a menu allowing to select the clipboard sync behavior (None, bi-directional, local -> remote, remote -> local). The implementation would be quite simple but I always have in mind that we should keep the user interface as simple as possible (this is what many users/teachers love about Veyon!) and take care of not overloading it with buttons.

This configuration could be in Veyon Configurator.

**Comment by JoaoPedroSchlindwein** [comment]
I guess i t would be so much useful!
Maybe it could be in Master → Features and start by default as a disable feature.
