### ISSUE TITLE
Veyon 'Power on' option no longer works.

### ISSUE THREAD

**Issue by jajava83** [veyon/veyon#482]
We have upgraded to v4.1.2 last weekend, and it would seem that the 'Power on' option no longer works.

**Comment by coolforit** [comment]
Why don’t you upgrade to the latest stable version 4.1.7 and see if that fixes it?

**Comment by tobydox** [comment]
In Veyon 4.1 we made wake-on-lan act more standard-conform. However between 4.1.2 and 4.1.7 we improved the power-on-functionality even more to send WoL packets to all network interfaces instead of the default one only. So please update to 4.1.7 as already suggested by @coolforit

**Comment by googleman26** [comment]
Good day! @tobydox  cross vlan power on is not working in veyon 4.1.7 but i can see the instructor computer on my veyon master. Have you tested cross vlan power on?

**Comment by tobydox** [comment]
If you have individual interfaces for each VLAN Veyon should send WoL packets to each VLAN. Besides that I'm not even aware of WoL working across VLANs.

**Comment by googleman26** [comment]
@tobydox  thank you for the reply.  thats why im asking sir if cross vlan monitoring is working on my master computer why is power on is not, but power off is working across VLANs.

**Comment by ldlx** [comment]
AFAIK WoL packets are sent to "the" broadcast address of the network adapter. Does your computer have multiple ip addresses on one interface?

**Comment by tobydox** [comment]
I'm closing this as broadcasting WoL packages across VLANs is not possible. Power off works as it uses TCP/IP connections which work across VLANs.
