### ISSUE TITLE
veyon master button features

### ISSUE THREAD

**Issue by googleman26** [veyon/veyon#486]
When i try to shutdown or reboot all client's computer from the master computer, everything shutdown or reboot without notification or prompt. maybe it is better to have notification if accidentally the teacher/s click the master veyon features.
![untitled](https://user-images.githubusercontent.com/25044145/53213967-c5e23f80-3685-11e9-8857-c45a75697b7b.jpg)

**Comment by pauloboc** [comment]
![screenshot_2](https://user-images.githubusercontent.com/679128/53243789-be239a80-3687-11e9-97a1-c4205ec7d838.jpg)

**Comment by googleman26** [comment]
@pauloboc thank you for the reply, it works.
