### ISSUE TITLE
Can't change the authentification method with 

### ISSUE THREAD

**Issue by orion777** [veyon/veyon#489]
Hello
I'm just trying the Veyon 4.2 Beta  you released a few days ago and i noticed a problem that didn't exist before : can't change the authentification method with veyon-configurator.  Each time i select the authentification key in general authentification method it doesn't apply the changes and keep on authentification by login. 
Please note that i am experiencing this issue on Linuxmint 18.3 So i can't see the screen computer displayed on veyon master because the authentification key can't be selected.
Thanks you for your help

**Comment by tobydox** [comment]
Can you please read the current setting for the logon method via

`veyon-cli config get Authentication/Method`

and try to reset it via

`cli/veyon-cli config unset Authentication/Method`. Are you able to change it in the Configurator afterwards?

**Comment by orion777** [comment]
Hello
I tested again with Veyon 4.2 RC and also same problem.
Here are the settting you asked for :
veyon-cli config get Authentication/Method
0
veyon-cli config unset Authentication/Method
[OK]
I can select authentification key or authentification user but when applying and restarting veyon configurator it's always checked on authentification user which is the first default choice.
So with this problem it's not possible using veyon with authentification key as usual.
Please can you fix it before releasing the 4.2 stable version? This problem occurs since Veyon 4.2 beta on Linuxmint 18.3. Maybe some command changes about authentification method dialog box.
Thanks you very much for your great help

**Comment by orion777** [comment]
Hi my friend
I'm nearly sure you will fix this problem because it worked perfectly with Veyon 4.2 alpha.
Let me know when you fix it, i need to make veyon working for linux 18.3 in our LDAP domain . Actually Veyon can't be used i our school because of tis problem of authentification method.

**Comment by tobydox** [comment]
Yes we'll fix it but I need a few more information. Which version of Qt are you using? You can go to Configurator -> About -> About Qt. Can you try to set the Authentication Method via CLI?

`veyon-cli config set Authentication/Method 1`

**Comment by orion777** [comment]
It is always QT 5.5.1 but this problem doesn't occur before you update the Veyon 4.2 pre release. Maybe this issue is du to some code changes since the alpha release.
veyon-cli config set Authentication/Method 1
it returns [OK] but also same problem when closing and reopening the veyon configurator the authetification method keep selected on login medthod by default.

**Comment by tobydox** [comment]
Issue is fixed in latest master branch. Thanks again for reporting!

**Comment by orion777** [comment]
Thanks you but where can i download this latest master branch updated release?

**Comment by tobydox** [comment]
You will have to build packages on your own or wait for the final release in 1-2 weeks ;-)
