### ISSUE TITLE
How add room/computers

### ISSUE THREAD

**Issue by lepikon** [veyon/veyon#49]
Hi
As the topic

**Comment by orion777** [comment]
Hello
I'm trying to add room and computers on Linuxmint 18 (i opened issue) but it doesn't work for my actually.
Well run veyon-configurator, go to general and in network object directory backend select default store object in local configuration)
Then go to local data and select + to add room and computers. Hope it will work for you. Good luck!

**Comment by orion777** [comment]
if all is ok, i think room and computer will appear when you run veyon-master.
Are you on linux or windows?

**Comment by lepikon** [comment]
It is all right now. thank you
