### ISSUE TITLE
Cross compiling Veyon for Windows does not create installer

### ISSUE THREAD

**Issue by NJJJCAustin** [veyon/veyon#490]
Trying to set up my environment to add Smartcard authentication to Veyon.  I have followed the instructions at https://github.com/veyon/veyon/wiki/Cross-compiling-for-Windows but get an "unable to locate package" for all of the *-mingw-w64 packages on Ubuntu 17.10.  I built a second build VM on 18.04 substituting software-properties-common for python-software-properties (as it is not available in 18.04).  Because the build scripts are no longer at source root, I use "../cmake/build_mingw32 make win-nsi" instead of "../build_mingw32 make win-nsi" in the instructions.  I have tried both the 32 and 64 bit scripts and neither make the msi.  (or are putting it somewhere I cannot find it.)

The only other change from the instructions is that I am git cloning branch 4.1 from my fork (https://github.com/NJJJCAustin/veyon).  At this point I have made no source code changes.

I am new to Linux development so I would appreciate any help I can get.

**Comment by pauloboc** [comment]
**I built these commands that build all the packages (.deb, .exe 32 bit and .exe 64 bit).

Banch 4.1
Tested Ubuntu 18.04 and 16.04.**

```
sudo apt-get install python-software-properties -y
sudo add-apt-repository ppa:tobydox/mingw-w64 -y
sudo apt-get update

sudo apt install git g++ make cmake qtbase5-dev qtbase5-dev-tools qttools5-dev qttools5-dev-tools xorg-dev libxtst-dev libjpeg-dev zlib1g-dev libssl-dev libpam0g-dev libprocps-dev liblzo2-dev libqca2-dev libqca-qt5-2-dev libldap2-dev libsasl2-dev nsis tofrodos g++-mingw-w64 qt5base-mingw-w64 qt5tools-mingw-w64 qt5translations-mingw-w64 openssl-mingw-w64 libz-mingw-w64-dev libpng-mingw-w64 libjpeg-turbo-mingw-w64 interception-mingw-w64 openldap-mingw-w64 lzo2-mingw-w64 qca-mingw-w64 -y

sudo rm -R veyon* || true && git clone -b 4.1 --single-branch https://github.com/veyon/veyon.git && cd veyon && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/usr .. && make -j4 && fakeroot make package && sudo dpkg -i veyon_* && cp -R veyon_* ../../ && cd ../cmake && ./build_mingw64 && sudo make win-nsi && cp -R veyon-*setup* ../../ && cd ../../ && sudo rm -R veyon && git clone -b 4.1 --single-branch https://github.com/veyon/veyon.git && cd veyon && cd cmake && ./build_mingw32 && sudo make win-nsi && cp -R veyon-*setup* ../../ && cd ../../ &&  sudo rm -R veyon 
```

**Comment by NJJJCAustin** [comment]
That helps a lot.  In the instructions it looks like make win-nsi was a parameter to the build script, not a chained command.  ("../build_mingw32 make win-nsi" vs " ../build_mingw32 && make win-nsi")  I'll leave this open for now so that they can update the Wiki.

**Comment by NJJJCAustin** [comment]
Not sure if this is an 18.04 issue, but I also needed to add cyrus-sasl-mingw-w64 to my list of apt-get to build for windows

**Comment by tobydox** [comment]
I updated the instructions in the Wiki, thank you for your feedback!

**Comment by shah-aadil** [comment]
I use ubuntu 18.04. I followed all the instructions given on veyon github, installed all the dependencies, but I am unable to make .exe file. I thought I might have messed my system so I created a brand new virtual machine and followed the same instructions and failed again. 

Make command works fine. make win-nsi fails terribly. I couldn't figure this out: Following is the error I get:
cp: cannot stat '/usr/x86_64-w64-mingw32//lib/qt5/plugins/styles/*.dll': No such file or directory
CMakeFiles/win-nsi.dir/build.make:57: recipe for target 'CMakeFiles/win-nsi' failed
make[3]: *** [CMakeFiles/win-nsi] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/win-nsi.dir/all' failed
make[2]: *** [CMakeFiles/win-nsi.dir/all] Error 2
CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/win-nsi.dir/rule' failed
make[1]: *** [CMakeFiles/win-nsi.dir/rule] Error 2
Makefile:186: recipe for target 'win-nsi' failed
make: *** [win-nsi] Error 2
