### ISSUE TITLE
Display logged-in user name in Remote view

### ISSUE THREAD

**Issue by ysalmon** [veyon/veyon#494]
Since Veyon 4.1, the name (or login) of the active user is displayed along with the machine name in the overview of Veyon Master. However when displaying a specific machine in Remote view, only the machine name is displayed as the window's title. It would be interesting to have the user name there too.

**Comment by SlrG** [comment]
I would like to vote for this feature, too. It would be really helpful.

**Comment by tobydox** [comment]
Fixed via c4b186710ff97363e3319a36818ff6ae4d274b5c and in upcoming 4.5.0 release.
