### ISSUE TITLE
Veyon extremely slow to show master screen on clients

### ISSUE THREAD

**Issue by Tarloth** [veyon/veyon#498]
I upgrade from iTalc to Veyon 4.1.7 everything "works" but presentation mode it's unusable. Screen refresh it's to very slow, the same machines that did work perfect in 1280x720 last year with iTalc this year can't refresh properly even at 800x600. A sequence in the master to open an application takes one minute or two to display in clients and getting worse second to second.

I try all the options in the configurator, the student machines have windows 7 32 bit, master windows 10 64 with 8 gb ram, all key authentication. It's the same hardware than last year.

I really need a solution or I need to uninstall al the machines and install iTalc again. THANKS in advance

**Comment by wakka9876** [comment]
Confirming we're having a similar issue, we were using 4.1.7 across the school and using fullscreen demo, the clients got about 1-2 fps, but when viewing something like a  youtube video or a circuit wizard program, it will go down to about 0.2fps. 

The computers in the school are all i3/i5, 4gb ram, HDD, but viewing the resource monitor, there is a tiny increase in resource load (about a 5% increase in cpu, ram, disk, network, nothing compared to what's available), even if I change the settings in Veyon Configurator. I tested this on a few machines in the office which were i5, 8gb ram, ssd and the results were exactly the same. 

We upgraded a few machines in the test OU to 4.1.91 and this is even worse, we get lower refresh speed and slower connection times and the options in the configurator to change refresh speed and memory usage are removed. 

Is there a setting I'm missing somewhere? something to allow it to utilize more resources?

**Comment by tobydox** [comment]
The settings are not gone in Veyon 4.2 but moved to advanced view which can be enabled through the menu. Besides that 2 questions: what is the bandwidth of your network? How many clients did you use in your test? Is there a difference with 1 or 2 clients only?

**Comment by Tarloth** [comment]
Can I answer this questions for me, I have 100Mb network and i not seen noticeable differences between one client or twelve. Last week I uninstall Veyon and install Italc again and everything work OK and the screen it's refreshed as usual

**Comment by wakka9876** [comment]
I'll check changing the settings on Monday.

We're the same, there doesn't seem to be any noticable difference between using one machine and an entire classroom of 30, we use 100mb everywhere internally, and 1gb out

**Comment by tobydox** [comment]
Is the master computer equipped a dual or quad core CPU?

**Comment by wakka9876** [comment]
i5-8500, quad core (office test pc)
i3-7500, dual core (standard school PC)

affecting both to a similar degree but I'll see if I can get some more testing done as it's school holidays at the minute but I suspect it'll be the same outcome

**Comment by tobydox** [comment]
The demo server in Veyon 4.5 will use multithreading so this should also improve performance and likely solve this issue. Feel free to respond after testing, once the new version has been released in a few days ;-)

**Comment by ert11er** [comment]
I have the same issue as well.** but i actually use veyon for my home.**
