### ISSUE TITLE
Open website without admin permission in client computer

### ISSUE THREAD

**Issue by pedrostorti** [veyon/veyon#5]
Hi.

When sending a command to open a website to a PC that is logged in with a user who does not have administrator permissions, firefox and google chrome browsers do not open. Only internet explorer works this function.
In firefox it presents the error that the user profile could not be opened, it was not found.

Google chrome does not even open.

I appreciate it if you can help me.

**Comment by tobydox** [comment]
Thank you very much for your bug report and the detailed analysis! I'll have a look at it.

**Comment by tobydox** [comment]
Can you please verify the issue? Everything works normally as a normal user here. Did you disable "cmd" for non-admin users? Veyon uses cmd for opening websites so if it is disabled or not available, the functionality might not work. Also did you set a standard browser?

**Comment by Lrobben52** [comment]
Hi Tobias,

 

Sorry, but my question is about generating authentication keys in the launch key file assistant from the teacher PC.

The program generates keys after you install the program (first time). But the second time (new set of key files) it don’t.

When you next copy the public key in the student laptop, he never accept the public key.

 

Thank you,   Ludo.  

 

Van: Tobias Doerffel [mailto:notifications@github.com] 
Verzonden: dinsdag 30 mei 2017 20:03
Aan: veyon/veyon <veyon@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: Re: [veyon/veyon] Open website without admin permission in client computer (#5)

 

Can you please verify the issue? Everything works normally as a normal user here. Did you disable "cmd" for non-admin users? Veyon uses cmd for opening websites so if it is disabled or not available, the functionality might not work. Also did you set a standard browser?

**Comment by pedrostorti** [comment]
The tests I did were with users with "advanced users"

**Comment by tobydox** [comment]
You can test again with the new release 3.99.5.
