### ISSUE TITLE
[4.1.8] problem with keyboard keys : 'ALT GR' 'WIN' 

### ISSUE THREAD

**Issue by o71** [veyon/veyon#501]
Hello,

I'm french and I use Azerty keyboard. The problem appear with 4.1.8. The PC use Windows 10 (master and client).

When I remote control a client, if I use 'ALT GR' I have an extra character that appears :

![veyon problem1](https://user-images.githubusercontent.com/2280629/55672931-6b9de680-58a1-11e9-9407-332823f6be47.PNG)

When I use the menu "send shortcut" and I select 'win', 
the action does not execute and I also have a character that appears in the notepad :

![veyon problem2](https://user-images.githubusercontent.com/2280629/55672935-70fb3100-58a1-11e9-9714-1b256b8badf3.PNG)

I changed the language setting of the client and the master with 'auto' 'fr' 'en_us', the problem persists.

Thank you for your help.

**Comment by tobydox** [comment]
Thank you for your bug report! Did you encounter this issue with previous versions as well?

**Comment by o71** [comment]
I have this problem only since the last version. In 4.1.7 no problem.

Le ven. 12 avr. 2019 à 12:03, Tobias Junghans <notifications@github.com> a
écrit :
