### ISSUE TITLE
Allow two authentication modes at the same time

### ISSUE THREAD

**Issue by Percherie** [veyon/veyon#502]
Hello,

My park is in a domain with an AD, authentication to "Veyon Master" is provided with a connection username.

Some master workstations are outside the domain and use an authentication key.

Is it possible to add a function so that the master outside the domain with a private key can connect to clients configured by default to use an identifier and having the public key?

Currently only one method can be used at a time. Being able to use both methods simultaneously would make it possible to operate on several physically separate domains.

Translated with www.DeepL.com/Translator

**Comment by MiaoMKung** [comment]
How to unsubscribe this?

发自我的 iPhone

**Comment by tobydox** [comment]
@MiaoMKung : simply unwatch the Veyon project at the top.

@Percherie using two methods simultanously is currently not possible. We plan to add multi-site/instance support in Veyon 5. You'll be able to select individual authentication methods for each site then. However I can't tell you when this will be available.

**Comment by tobydox** [comment]
Closing this as we won't make any progress here soon - I'm sorry.
