### ISSUE TITLE
Restrict Access to Configurator

### ISSUE THREAD

**Issue by Tiny88** [veyon/veyon#503]
We want to prevent access to the Veyon Configurator on all machines.  How do we set up Veyon to only allow a certain LDAP group (our IT staff) to access the configurator on all student computers...while not allowing students access to open it.  FYI, we have LDAP set up and working in Veyon with Access Control in place for access to computers -- all working.  We just can't see how to prevent access to the configurator.  thanks!

**Comment by tobydox** [comment]
Thanks for your report! Access to Veyon Configurator is restricted to users with administrative privileges already. If your students have administrative privileges there's nothing that can stop them from changing the Veyon configuration or disabling it at all anyway ;-) If students do not have administrative privileges they'll be unable to start the Veyon Configurator. This is not related to access control or LDAP groups so basically there's nothing we can do here.

**Comment by Tiny88** [comment]
thanks for the clarification!
