### ISSUE TITLE
feature request like ispy

### ISSUE THREAD

**Issue by irulvam** [veyon/veyon#508]
I want to know who uses a PC in the room, so I can use it to give a warning to that person if he is doing things that are not justified in the room. so I need a picture of that person via the webcam available on the PC. can it be provided?

**Comment by cs8898** [comment]
Nirsoft WebcamImageSave, probably thats something you are searching for, i don't think thats a feature you wanna integrate into a multihead vnc client...

**Comment by tobydox** [comment]
Veyon does not have any webcam support except someone is going to implement an appropriate plugin for this - as usual code contributions are welcome :-)
