### ISSUE TITLE
Silent install with importing the public key

### ISSUE THREAD

**Issue by lighk** [veyon/veyon#510]
Is there a way to deploy Veyon clients (no master) with the Authentication key?
I'm using PDQ to deploy PCs(Domain PC) with silent install as below.
(veyon-x.y.z-win64-setup.exe /S /NoMaster /ApplyConfig=%cd%\MyConfig.json)
Everything and configuration run very well except the Authentication Key missing.
Is it possible to apply, import or copy the public key to all clients at one time? Or that do need to import  key manually with administrators one by one?
or is there anything that u can advice me.
thanks.

**Comment by tobydox** [comment]
Even though the installer does not support importing authentication keys you can easily automate this via `veyon-cli` (or `veyon-ctl` for Veyon < 4.2):

`veyon-cli import teacher/public teacher_public_key.pem`

For Veyon 4.2 and newer you can also use `veyon-wcli` to suppress the console window.

See http://docs.veyon.io/en/latest/admin/cli.html#authentication-key-management for more details on the supported operations.

**Comment by lighk** [comment]
thanks a lot~!!
