### ISSUE TITLE
Unable to create windows installer - cross compiling on Ubuntu 18

### ISSUE THREAD

**Issue by shah-aadil** [veyon/veyon#512]
I use ubuntu 18.04. I followed all the instructions given on veyon github, installed all the dependencies, but I am unable to make .exe file. I thought I might have messed my system so I created a brand new virtual machine and followed the same instructions and failed again.

Make command works fine. make win-nsi fails terribly. I couldn't figure this out: Following is the error I get:
cp: cannot stat '/usr/x86_64-w64-mingw32//lib/qt5/plugins/styles/*.dll': No such file or directory
CMakeFiles/win-nsi.dir/build.make:57: recipe for target 'CMakeFiles/win-nsi' failed
make[3]: *** [CMakeFiles/win-nsi] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/win-nsi.dir/all' failed
make[2]: *** [CMakeFiles/win-nsi.dir/all] Error 2
CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/win-nsi.dir/rule' failed
make[1]: *** [CMakeFiles/win-nsi.dir/rule] Error 2
Makefile:186: recipe for target 'win-nsi' failed
make: *** [win-nsi] Error 2

**Comment by pauloboc** [comment]
I have the same problem.

**Comment by tobydox** [comment]
Please switch to the 4.1 branch to build. Instructions for building the master branch will be updated once the toolchains are up to date and working properly.
