### ISSUE TITLE
File transfer for mapped network drives

### ISSUE THREAD

**Issue by orion777** [veyon/veyon#516]
Hello there, Hello Tobbias

Transfer file is a very interesting option since Veyon 4.2.0 release but with this option files are copied on local hardrive only. In our school, students are working on LDAP environment with network shares using SMB protocol. Users sessions on windows and linuxmint are running with restricted access rules to prevent and protect network security and operating system computers clients.
Users students session don't have permissions to write on local machine so they have to save or copy files on the mapped network drives. Below is a capture of these network drives in our school.
![Screenshot_2](https://user-images.githubusercontent.com/29846901/56871077-fabd9a80-6a18-11e9-9707-737c60ec5f15.jpg)

So when Veyon master try the transfer file option on user student session it doesn't work. Is it possible to add another setting for transfer file allowing the possibility to choose the path for file transfer copy?
 In this case it would be great to select the right network drive. Thanks for your help. Hoping it is possible to do that.

**Comment by orion777** [comment]
Hi
Any news for this?

**Comment by tobydox** [comment]
Not yet - the path may be configurable in a future release but this currently has low priority only, I'm sorry. Feel free to change the path in the code (https://github.com/veyon/veyon/blob/master/plugins/filetransfer/FileTransferPlugin.cpp#L169) and build Veyon from source on your own ;-)

**Comment by SlrG** [comment]
I would like to vote for this feature, too.

**Comment by tobydox** [comment]
Source and destination directories will be configurable in Veyon 4.5 (coming in a few weeks).
