### ISSUE TITLE
Student window is on top of all windows

### ISSUE THREAD

**Issue by pauloboc** [veyon/veyon#517]
In version 4.2.0.

When we open the student window, it sits on top of all windows.
Is this a bug?

**Comment by tobydox** [comment]
Can you explain a bit further which window you're talking about?

**Comment by pauloboc** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/679128/56909563-da282b80-6a7e-11e9-868b-c6677c7c7c8e.png)

I'm clicking on windows explorer and even then a student window continues on top
