### ISSUE TITLE
Windows Installer (MSI)

### ISSUE THREAD

**Issue by ldlx** [veyon/veyon#52]
Are you going to provide a Windows Installer package (MSI) for Veyon or may I assist you in creating it?

**Comment by tobydox** [comment]
It's currently not planned due to advanced methods for auto-installation as described in the administrator manual. However any contributions are welcome. One fundamental requirement would be automated creation of MSI packages via Travis CI. Last time I checked this was difficult as WiX & friends do not run on Linux natively. Do you see possible solultions for that?

**Comment by tobydox** [comment]
Any news? If not I'll close this issue for the time being.

**Comment by Emalton** [comment]
Having a MSI would make it really easy to deploy in System Center, it would be great if this could be added!

**Comment by ldlx** [comment]
I would share my WiX source code if it's ok for @tobydox, so you can build it yourself (needs unpacking of the original setup files). If you don't want to use Visual Studio, you can do it with WiX alone, but it needs the two WiX commands "Candle" and "Light" (I can give examples for it). But I don't have any knowledge of Travis CI, so I can't help with this.

**Comment by tobydox** [comment]
Sure, why not, thank you! :-)

**Comment by ldlx** [comment]
- Extract the ZIP file.
- Extract veyon-4.7.3.0-win64-setup.exe and put the contents into source_x64. You can delete $PLUGINSDIR and uninstall.exe.nsis.
- You need the files mouse.sys and keyboard.sys for interception. To get them, run install.bat in the directory "interception" and copy the files from c:\windows\system32\drivers afterwards to interception_x64.
- You can create an installer for x86 with the same project, extract the x86 setup to source_x86. But I'm sure you need to install the interception driver on a x86 Windows to get x86 driver files (name the directory interception_x86).
- I don't use the update function of MSIs - with group policy deployment it is safer to use uninstall/install instead of updates (happens to other MSI installers as well).
- There are two transform files in the zip archive: no-master.mst (for student computers) and no-interception.mst (to not install interception driver, have a look at https://github.com/veyon/veyon/issues/555, but the driver also interferes with other remote control software like R-Admin when one wants to send ctrl+alt+entf). As long as you don't modify the source code too much, you can use them for your deployments.

To use WiX with Visual Studio, you need WiX Toolset Extension for Visual Studio for your VS version.

To build it at the command line, use commands like the following. This example is from my Firefox MSI (not Mozilla's EXE wrapper-MSI ;-))
- You can find the ICE exlusions for Veyon in the wixproj file
- Everything specific is replaced by batch variables, so use set these environment variables before running Candle and Light:
    set product=Firefox (like I said, it's just example code ;-))
    set version=102.0.1
    set devdir=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\\

x64:
"%WIX%bin\candle.exe" -dDebug -d"DevEnvDir=%devdir%" -d"SolutionDir=%~dp0\.." -dSolutionExt=.sln -dSolutionFileName=%product%.sln -dSolutionName=%product% -d"SolutionPath=%~dp0\..\%product%.sln" -dConfiguration=Debug -dOutDir=bin\x64\Debug\ -dPlatform=x64 -d"ProjectDir=%~dp0\" -dProjectExt=.wixproj -dProjectFileName=%product%_%version%_x64.wixproj -dProjectName=%product%_%version% -d"ProjectPath=%~dp0%product%_%version%_x64.wixproj" -d"TargetDir=%~dp0bin\x64\Debug\\" -dTargetExt=.msi -d"TargetFileName=%product% %version%.msi" -d"TargetName=%product% %version%" -d"TargetPath=%~dp0bin\x64\Debug\%product% %version%.msi" -out obj\Debug\ -arch x64 -ext "%WIX%bin\WixUtilExtension.dll" -ext "%WIX%bin\WixUIExtension.dll" "%~dp0filesx64.wxs" "%~dp0Product.wxs"
"%WIX%bin\Light.exe" -out "%~dp0bin\%product% %version% x64.msi" -cultures:null -ext "%WIX%bin\WixUtilExtension.dll" -ext "%WIX%bin\WixUIExtension.dll" -sice:ICE69 -contentsfile obj\Debug\%product%_%version%.wixproj.BindContentsFileListnull.txt -outputsfile obj\Debug\%product%_%version%.wixproj.BindOutputsFileListnull.txt -builtoutputsfile obj\Debug\%product%_%version%.wixproj.BindBuiltOutputsFileListnull.txt -wixprojectfile "%~dp0%product%_%version%_x64.wixproj" "%~dp0obj\Debug\filesx64.wixobj" "%~dp0obj\Debug\%Product%_x64.wixobj"

x86:
"%WIX%bin\candle.exe" -dDebug -d"DevEnvDir=%devdir%" -d"SolutionDir=%~dp0\.." -dSolutionExt=.sln -dSolutionFileName=%product%.sln -dSolutionName=%product% -d"SolutionPath=%~dp0\..\%product%.sln" -dConfiguration=Debug -dOutDir=bin\x86\Debug\ -dPlatform=x86 -d"ProjectDir=%~dp0\" -dProjectExt=.wixproj -dProjectFileName=%product%_%version%_x86.wixproj -dProjectName=%product%_%version% -d"ProjectPath=%~dp0%product%_%version%_x86.wixproj" -d"TargetDir=%~dp0bin\x86\Debug\\" -dTargetExt=.msi -d"TargetFileName=%product% %version%.msi" -d"TargetName=%product% %version%" -d"TargetPath=%~dp0bin\x86\Debug\%product% %version%.msi" -out obj\Debug\ -arch x86 -ext "%WIX%bin\WixUtilExtension.dll" -ext "%WIX%bin\WixUIExtension.dll" "%~dp0filesx86.wxs" "%~dp0Product.wxs"
"%WIX%bin\Light.exe" -out "%~dp0bin\%product% %version% x86.msi" -cultures:null -ext "%WIX%bin\WixUtilExtension.dll" -ext "%WIX%bin\WixUIExtension.dll" -sice:ICE69 -contentsfile obj\Debug\%product%_%version%.wixproj.BindContentsFileListnull.txt -outputsfile obj\Debug\%product%_%version%.wixproj.BindOutputsFileListnull.txt -builtoutputsfile obj\Debug\%product%_%version%.wixproj.BindBuiltOutputsFileListnull.txt -wixprojectfile "%~dp0%product%_%version%_x86.wixproj" "%~dp0obj\Debug\filesx86.wixobj" "%~dp0obj\Debug\%Product%_x86.wixobj"

PS: Use a software like Orca, SuperOrca or InstEd to modify the MSI or generate transform files (I prefer InstEd).

[Veyon 4.7.3.0.zip](https://github.com/veyon/veyon/files/9103295/Veyon.4.7.3.0.zip)

**Comment by Emalton** [comment]
Does this help @tobydox?

**Comment by tylla** [comment]
May we hope that this would be addressed in the near future?
It would make a domain-wide / multi-machine deployment way easier.

**Comment by ldlx** [comment]
Everything you need to build your own MSI is in my comment above. The WiX source code (= names of the source files) for the current version shouldn't have changed much.
