### ISSUE TITLE
Lock screen can be overridden

### ISSUE THREAD

**Issue by mhughes5698** [veyon/veyon#520]
Hi,

I've just downloaded the new Veyon 4.2 and it appears that when a PC is locked it can be overridden by using Ctrl + Alt + Delete... I've tried everything (restarts/reinstallations etc), but just can't get it to work! The rest of the input seems hit and miss (ie, pressing just windows key doesn't bring up the start menu, but pressing windows key + D takes me to the start menu). Not sure if it's a bug or if I'm doing something wrong!

Thanks!

**Comment by tobydox** [comment]
Hi @mhughes5698 

thanks for reporting! Have you used an older version of Veyon successfully before? Can you try to run "install.bat" from an command line started with admin privileges inside `C:\Program Files\Veyon\interception`? Does it print any error messages?

**Comment by mhughes5698** [comment]
Thanks for the quick reply!

It appears the interception directory doesn't exist? I have an "interception.dll" but no interception directory or "install.bat"

**Comment by tobydox** [comment]
Have you disabled the Interception component during installation?

**Comment by mhughes5698** [comment]
Think I have just realized my mistake... I have the following set up

 -Teacher PC
Service + Master + Interception

-Student PC
Service

I'm guessing my error is in not installing the Interception on the student machines... Am I correct in thinking so?

________________________________

**Comment by tobydox** [comment]
Yes right, you need the interception driver on all computers whose screen to lock :)

**Comment by mhughes5698** [comment]
My bad, thought it was just the Master that needed it... Thanks a ton for your help!
________________________________

**Comment by tobydox** [comment]
No problem, you're welcome!

**Comment by mhughes5698** [comment]
Sorry to keep pestering you! I now have two issues...

I tried what you said and keep getting the error "Cannot write to /system32/drivers". This is definitely in an elevated cmd. I've tried the instructions (uninstall, reboot, reinstall, reboot), but to no avail!

The second error is, after the screen has been unlocked, the Windows taskbar remains unclickable...

**Comment by tobydox** [comment]
So may be the driver is already installed? Does blocking ctrl+alt+del work after reboot?

Regarding the task bar: you can disable the new behaviour which hides and disables  the taskbar through the "Windows" configuration page which is shown when you switch the view from "Standard" to "Advanced" - see http://docs.veyon.io/en/latest/admin/platform-notes.html#screen-lock for details.
