### ISSUE TITLE
LDAP Authentication doesn't work

### ISSUE THREAD

**Issue by JuliusTZM** [veyon/veyon#521]
Since the 4.2.0 version LDAP authentication throws error message:

2019-04-30T20:59:58.947: [ERR] LinuxUserFunctions: VeyonAuthHelper failed: 6 "" "free(): double free detected in tcache 2"

OS: Manjaro Linux

**Comment by tobydox** [comment]
@JuliusTZM As of Veyon 4.2 the PAM service "login" instead of "su" us used on Linux (see http://docs.veyon.io/en/latest/admin/release-notes.html#veyon-4-2) which might be the cause of the error here. You can try to change the PAM service back to "su" or whatever works for you using the new advanced option: http://docs.veyon.io/en/latest/admin/platform-notes.html#id1

**Comment by JuliusTZM** [comment]
Dear Tobias,

Journalctl shows me the following messages, which looks ok to me:

máj 05 18:31:13 manjaro-laptop veyon-auth-helper[18310]: pam_sss(login:auth): authentication success; logname= uid=1875001106 euid=0 tty= ruser= rhost= user=test
máj 05 18:31:13 manjaro-laptop audit[18310]: ANOM_ABEND auid=1875001106 uid=1875001106 gid=1875000513 ses=2 pid=18310 comm="veyon-auth-help" exe="/usr/bin/veyon-auth-helper" sig=6 res=1
máj 05 18:31:13 manjaro-laptop kernel: audit: type=1701 audit(1557073873.899:312): auid=1875001106 uid=1875001106 gid=1875000513 ses=2 pid=18310 comm="veyon-auth-help" exe="/usr/bin/veyon-auth-helper" sig=6 res=1

What should I check in pam services then? Can you please give me a hint?

Best regards,
Jules

**Comment by tobydox** [comment]
Hi Jules,

unfortunately the messages are not OK and seem to indicate a problem with SELinux - at least the first search result are all related to SELinux when searching for "ANOM_ABEND" . I guess the veyon-auth-helper binary needs to be enabled in the SELinux stack. I'm not familiar with SELinux but may be your system configuration tools provide some related options?

Best regards
Tobias

**Comment by tobydox** [comment]
Can you test with the latest master branch? Alternatively wait for 4.2.0 at the end of this week.

**Comment by JuliusTZM** [comment]
Dear Tobias,

Journalctl shows me the following messages, which looks ok to me:

máj 05 18:31:13 manjaro-laptop veyon-auth-helper[18310]: pam_sss(login:auth): authentication success; logname= uid=1875001106 euid=0 tty= ruser= rhost= user=test
máj 05 18:31:13 manjaro-laptop audit[18310]: ANOM_ABEND auid=1875001106 uid=1875001106 gid=1875000513 ses=2 pid=18310 comm="veyon-auth-help" exe="/usr/bin/veyon-auth-helper" sig=6 res=1
máj 05 18:31:13 manjaro-laptop kernel: audit: type=1701 audit(1557073873.899:312): auid=1875001106 uid=1875001106 gid=1875000513 ses=2 pid=18310 comm="veyon-auth-help" exe="/usr/bin/veyon-auth-helper" sig=6 res=1

What should I check in pam services then? Can you please give me a hint?

Best regards,
Jules

**Comment by JuliusTZM** [comment]
Dear Tobias,

Sure I will. Besides I have the doubt this error messages "free(): double free detected in tcache 2" comes from the glibc 2.29 which is quite new and SELinux is not enabled at all on arch based distros.
I hope the next release will show us a fix for the issue. I will let you know the details.

Many thanks,
Jules

**Comment by JuliusTZM** [comment]
Dear Tobias,

The issue remained with the same symptoms.

Any idea?

Thx
