### ISSUE TITLE
Veyon 4.2 - Screenshot not working

### ISSUE THREAD

**Issue by mhughes5698** [veyon/veyon#522]
Hi,

I cannot get Veyon to save a screenshot. It pops up saying "screenshot taken successfully" but it doesn't actually save it.

Thanks!

**Comment by hajo20** [comment]
Hi,
Veyon mit rechter Maustaste.. als Administrator ausführen. Dann klappt es auch mit den screenshots.
Right-click Veyon .. as administrator. Then it works with the screenshots.

**Comment by mhughes5698** [comment]
If I run as Administrator, I can successfully screenshot PC's that aren't logged in. If a PC is logged in, it won't screenshot...

**Comment by tobydox** [comment]
@mhughes5698 can you please check the [screnshot directory setting](https://docs.veyon.io/en/latest/admin/reference.html#basic-settings)? When set to its default value `%APPDATA%/Screenshots` screenshots are saved to the users profile. Is there a difference if local users or domain users are logged on the machines which to take screenshots of? I suspect there could be an issue if the username contains the "\" character.

**Comment by tobydox** [comment]
I just verified that screenshots can't be created if the username contains `\` (i.e. for domain users). I'll try to fix this for the next release.
