### ISSUE TITLE
The button show only powered is not working - Veyon 4.2.0

### ISSUE THREAD

**Issue by pauloboc** [veyon/veyon#526]
The button show only powered is not working - Veyon 4.2.0

When clicked, it hides all computers, including those connected.

![Screenshot_2](https://user-images.githubusercontent.com/679128/57197666-81ee9f00-6f40-11e9-960c-97bb4dec4328.png)

**Comment by tobydox** [comment]
Thanks for reporting! This has been fixed via d3b2f1eb56cd89d980feedb4945d37921c096d89 already and will be fixed in upcoming 4.2.1 release.
