### ISSUE TITLE
After upgrade to 4.2.1 no preview of computers, but remote control is working

### ISSUE THREAD

**Issue by ldlx** [veyon/veyon#530]
I upgraded one Windows machine from Veyon 4.1.7 to 4.2.1 and afterwards the preview of computers is broken (grey screen as if they are turned off). Connecting to the screen and remote control is working as expected.

This also happens to the preview of the upgraded computer (so no issue with version 4.1.7 on the other computers).

**Comment by tobydox** [comment]
Does this still happen with 4.2.2? Did you upgrade both computers? Are you using key file or logon authentication?

**Comment by ldlx** [comment]
Yes, with 4.2.2 it is the same behaviour, no preview.
But I have to correct myself... it's not viewing the client when connecting for viewing/remote control, but the local computer - when trying with 4.2.1 the first time I rdp'ed into the master computer - and the desktop session showed the login screen like any of the clients (and I didn't try to login in the client screen :-))
When logging into the desktop session of the master computer and connecting to a client it looks like this: ![grafik](https://user-images.githubusercontent.com/5896642/60395596-2868b200-9b36-11e9-8c3a-6978e818a1cc.png) - master is cli-alb-v01, client is cli-alb-v10, but it is only showing the master's desktop. The client can even be switched off, the master will show it's own desktop.
I'm using Logon authentication. The registry settings are the same like the configuration of 4.1.7. I also changed a setting in Configurator just to re-apply the config through Configurator, but that doesn't help.

**Comment by ldlx** [comment]
Should I give 4.2.3 a try?

**Comment by ldlx** [comment]
After throwing away the Veyon registry keys and reconfiguring the Master computer the connection to remote computers is working again (which are at 4.1.7 and have the old config).

When comparing old and new registry values, the most suspicious key is
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Veyon Solutions\Veyon\Network]
"LocalConnectOnly"="0" (before) and "false" (after)
```
As the config has grown since iTalc there were of course more deprecated registry values :-)
