### ISSUE TITLE
Veyon 4.2 PPA builds failing for Ubuntu 16.04

### ISSUE THREAD

**Issue by lbssousa** [veyon/veyon#532]
I've just noticed that all builds related to version 4.2 in Veyon PPA are failing for Ubuntu 16.04 (the latest successful build was for version 4.1.8)

Here's the latest buildlog:

https://launchpadlibrarian.net/424969593/buildlog_ubuntu-xenial-amd64.veyon_4.2.2-1~xenial_BUILDING.txt.gz

**Comment by tobydox** [comment]
I'm aware of that but I really have no clue what's wrong here. Our CI builds for plain Ubuntu 16.04 environments work fine and we have no problems on all other versions and distributions. There must be a bug in cmake or the Qt development packages.

**Comment by tobydox** [comment]
The issue has been resolved and our PPA now contains Veyon 4.2.3 for Ubuntu 16.04.
