### ISSUE TITLE
Translation request: Klingon

### ISSUE THREAD

**Issue by JasMich** [veyon/veyon#535]
Hello there,

are any Klingon translations planed? If yes, I'd like to contribute to them.

Regards,
*JasMich*

---

nab mugh tlhIngan Hol? mughmoHchugh, vIQaH.

Qapla'
*JasMich*

**Comment by tobydox** [comment]
Unfortunately Transifex doesn't allow me to add a Klingon translation so I'm afraid we can't offer a Klingon translation for Veyon... Feel free to contact Transifex support to add Klingon to the list of supported languages ;-)

Qapla'
