### ISSUE TITLE
Error while creating access keys in veyon-configurator

### ISSUE THREAD

**Issue by orion777** [veyon/veyon#54]
I always have the problem with the access keys creation.
I send you the attached file with the error. I put all the permissions on /etc/veyon/keys/private/teacher but it is always unable to write the key in the folder

Thanks you very much for your help
![capture d ecran_2017-07-15_22-27-19](https://user-images.githubusercontent.com/29846901/28242483-6c4866a8-69ad-11e7-8ca9-c685576e4292.png)

**Comment by tobydox** [comment]
I guess there's a problem with the installed QCA library (Qt Cryptographic API) on your system. Probably the encryption key type used by Veyon is not supported by the used backend.

Can you please change the log level to debug, restart Configurator and search for the line "[DEBUG] CryptoCore instance created - features supported by QCA:" in log files / console output. Please paste the complete line here?

**Comment by orion777** [comment]
Here the complete line 

2017-07-16T20:28:47.009: [DEBUG] CryptoCore instance created - features supported by QCA: ("random", "md5", "sha1", "keystorelist")

**Comment by V-Zemlyakov** [comment]
fix in linux mint: install: libqca-qt5-2-plugins

**Comment by orion777** [comment]
Great !!!!!!!!!!  It works now !

ConfiguratorCore: creating new key pair in "/etc/veyon/keys/private//teacher/key" and "/etc/veyon/keys/public//teacher/key"
...done, saved key-pair in

/etc/veyon/keys/private//teacher/key

and

/etc/veyon/keys/public//teacher/key


For now the file is only readable by root and members of group root (if you
didn't ran this command as non-root).
I suggest changing the ownership of the private key so that the file is
readable by all members of a special group to which all users belong who are
allowed to use Veyon.

**Comment by tobydox** [comment]
Thank you guys for reporting this bug and help fixing it. I committed a change which from now on reports missing RSA support in QCA and proposes packages to be installed.
