### ISSUE TITLE
Veyon is not showing recursed list of user and groups for access control

### ISSUE THREAD

**Issue by ben-coates** [veyon/veyon#542]
Setting up Veyon with active directory. Everything binds correctly and I can use the search functionality to search though my AD instance and find everything. However, when I go to Access Control, none of the users or groups are showing up. I have "perform recursive search operations in object trees" checked and everything else seems to be working fine, but there nothing showing in Access Control.

**Comment by tobydox** [comment]
Thanks for your feedback! Did you change the user groups backend to LDAP/AD?

**Comment by ben-coates** [comment]
I did. I'll try to attach a couple screenshots soon.

**Comment by ben-coates** [comment]
![Capture1](https://user-images.githubusercontent.com/22177504/60610801-b2ad5200-9d92-11e9-938f-cb354493d8bf.PNG)
Here is my settings on the access control window. I should note that I had a previous version of veyon working, but it stopped so I decided to update to the latest version.

**Comment by tobydox** [comment]
OK, then it's likely still an LDAP/AD configuration issue. Do all the integration tests work fine? After changing LDAP/AD parameters you'll have to restart Configurator to reload the groups for access control configuration.

**Comment by ben-coates** [comment]
I finally, got the configuration working. I imported a config from the previous installation I had working and adjusted it from there. Not sure what it was thanks for the help. I am having issues with some computers showing "Computer offline or switched off" which is what lead me to do the uninstallation to begin with...any threads you know of with helpful info for troubleshooting that? I can't seem to isolate what the difference between them is other than the model of computer, but it was working and then it just stopped working.

**Comment by tobydox** [comment]
Thanks for your feedback! Likely the configuration upgrade somehow failed from 4.1 to 4.2. If everything works now, we can close this issue. Feel free to re-open if you still have issues.
