### ISSUE TITLE
Documentation: Windows compiler.

### ISSUE THREAD

**Issue by pauloboc** [veyon/veyon#543]
Hello, could you update the documentation please.
Thanks.

[https://github.com/veyon/veyon/wiki/Cross-compiling-for-Windows](https://github.com/veyon/veyon/wiki/Cross-compiling-for-Windows)

**Comment by tobydox** [comment]
Hi @pauloboc 
the page has been updated with the information that building for Veyon is not supported officially any longer. We'll of course continue to release Windows builds.
