### ISSUE TITLE
Still cannot add Unauthorized User Groups with the CLI

### ISSUE THREAD

**Issue by littlevale** [veyon/veyon#546]
Related: #537 

I've downloaded Veyon 4.2.3 and tried this again but with no success. I used `veyon-cli config clear` to clear the configuration, then `veyon-cli service restart` just to be sure. Checking the configurator panel now lists no user groups, `Access Restricted To User Groups` is unchecked, as is `DomainGroupsEnabled`. `veyon-cli config list` agrees with this. So far, so good.

Now, I tried setting the two flags with 
```
veyon-cli config set AccessControl/AccessRestrictedToUserGroups true
veyon-cli config set AccessControl/DomainGroupsEnabled true
veyon-cli service restart
```
Checking with the configurator shows the new settings have been applied.

Lastly
```
veyon-cli config set AccessControl/AuthorizedUserGroups "Administrators;WKSAdmin"
veyon-cli service restart
```
and check again with the configurator: the authorised user list is blank.

Listing the config gives
`AccessControl/AuthorizedUserGroups=Administrators;WKSAdmin`

Adding the required user groups with the configurator and listing again now gives
`AccessControl/AuthorizedUserGroups=Administrators;WKSAdmin;WKSAdmin;Administrators`

Exporting the configuration to a JSON file now gives:
```
"AccessControl": {
  "AccessRestrictedToUserGroups": "true",
  "AuthorizedUserGroups:: [
    "Administrators;WKSAdmin",
    "Administrators",
    "WKSAdmin"
  ],
  "DomainGroupsEnabled": "true"
},
```
Clearly, the CLI utility is still not parsing the string properties properly.

**Comment by tobydox** [comment]
Thank you for testing and for your feedback! I'll have a look at it again. In the meantime you can use an undocumented feature by passing the data type as an additional argument:

```
veyon-cli config set AccessControl/AuthorizedUserGroups "Administrators;WKSAdmin" list
```

That's what's working here definitely.
