### ISSUE TITLE
4.2.4.0 - Remote View Instead Views localhost and Repeats Viewing Windows

### ISSUE THREAD

**Issue by natelan69** [veyon/veyon#549]
Sorry, I am brand new to GitHub, I hope I don't break any rules.  I am also new to Veyon and am inexperienced at coding.

I am attempting to deploy Veyon to approximately 100 Windows 10 PC's.

I had successfully tested version 4.1.7.0 on about 10 PC's and could perform all remote functions including viewing, shut down, messages, etc.  I seem to have had LDAP configured properly, as well as access control.

Now, I have upgraded to 4.2.4.0 and I am having a new problem during testing, before I deploy across my network.  The problem is very similar (or identical) to the problem mentioned here: https://github.com/veyon/veyon/issues/333

I too, see "grey" screens instead of previews/thumbnails.  And when I attempt to Remote View a PC, it too triggers an endless loop of windows.

During the loop, if I click the Maximize Window button in the top-right, it stops the repeating Windows, but then displays MY screens, rather than the remote target's screens.

I never had this problem with the previous version.

Is this a bug in the new version?  Or perhaps I have configured something wrong this time?

BTW- We use DHCP, so hard coding specific IP addresses to host names is not possible for us.

Please let me know if and how I should provide any additional information or log data.

Many thanks!

**Comment by natelan69** [comment]
I downgraded the "Teacher" PC's version from 4.2.4.0 back down to 4.1.7.0, and the Remote View (and all other remote functions) have been restored.  The "Student" PC's are on 4.2.4.0 and the "Teacher" PC is on 4.1.7.0 and all appears to be working now, using the same configuration file.

**Comment by ldlx** [comment]
I had the same issue with 4.2 - I had to delete the reg key HKEY_LOCAL_MACHINE\SOFTWARE\Veyon Solutions\Veyon and to create the config from scratch.
I suspect it could be the value of HKEY_LOCAL_MACHINE\SOFTWARE\Veyon Solutions_neu\Veyon\Network\LocalConnectOnly - which was 0/1 in old versions and now is false/true.

**Comment by tobydox** [comment]
Thank you for reporting the issue. Veyon 4.4 comes with an improved VNC and network stack which should also cover your issue.
