### ISSUE TITLE
Mouse cursor not visible on the master

### ISSUE THREAD

**Issue by marcdiversion** [veyon/veyon#550]
Hi,
I've used Veyon a couple of times (and love it), and each time I open a client from the master, my mouse cursor  disappears when on the controlled PCs window.
So there is no way to know where I am on the controlled PC window.
Sometimes it works on one or more controlled PC, but most of the time it's not there.
Is there any option I should check to make sure I see it all the time?
Thank you!

**Comment by wildanihadi** [comment]
I have the same problem. when controlling other PC, suddenly mouse cursor disappear.
