### ISSUE TITLE
Windows key not functionning

### ISSUE THREAD

**Issue by marcdiversion** [veyon/veyon#551]
Hi,
The windows key of the controlled PCs does not work, if the controlled PCs are doing something in full screen and I need to click on the taskbar, the only option is alt+tab, no way to activate the win key, neither with the master key, nor with the keyboard shortcut.
Thanks you!

**Comment by tobydox** [comment]
Thank you for your bug report! Have you tried pressing Ctrl+Esc or sending the keyboard shortcut Ctrl+Esc?

**Comment by tobydox** [comment]
In Veyon 4.2.5 sending the Win shortcut will work properly.
