### ISSUE TITLE
Veyon 4.2.4 is in English

### ISSUE THREAD

**Issue by ysalmon** [veyon/veyon#552]
Hi,
I just upgraded to 4.2.4 and the interface is in English instead of French. Settings are "Use system default" (there is no other choice anyway).

What's happening ?

**Comment by tobydox** [comment]
Which platform are you running Veyon on? Windows? Linux?

**Comment by tobydox** [comment]
Seems to be a Linux issue and has been fixed in 0f342398d8ce83039cef3439f2ca25eaed1a2b47 and will be fixed in 4.2.5 - thanks for reporting!
