### ISSUE TITLE
Interception driver breaks RDP server

### ISSUE THREAD

**Issue by ldlx** [veyon/veyon#555]
After several RDP sessions on a computer where the interception driver is installed, it is not possible to connect via RDP again until reboot. Local login is still possible.
When the interception driver is uninstalled (manual removing in the registry, renaming the interception directory inside the Veyon directory and rebooting) RDP is working as expected.

This occurs at least on computers with Windows 8.1 x64, Windows 10 x64 and Windows Server 2016.

Maybe related to #154 ?

**Comment by dxdemetriou** [comment]
Still happens on latest version 4.3.5
