### ISSUE TITLE
Win 10 - Win 7 but not Win 10 - Win 10

### ISSUE THREAD

**Issue by djwusmc** [veyon/veyon#556]
Power on works with a Win 10 master and Win 7 clients, and with Win 7 Win 7, and with Win 7 Win 10. However, power on does not work with a Win 10 master and Win 10 clients. Any fix, or am I doing something wrong? (Win 10 and Win 7 are the Enterprise version.)

**Comment by tobydox** [comment]
Thank you for your message! Power on uses the well-known Wake-on-LAN mechanism which (on the client-side) is implemented at the UEFI/BIOS level, i.e. definitely not an operating system version issue except for cases where the operating system/network driver disables WoL for the network card. So please verify the WoL settings on the affected clients and make sure the clients are on the same (networking) subnet as the master computer so the WoL broadcasts can be received properly.

**Comment by djwusmc** [comment]
Yes, but what doesn't make sense is that only with Win 10 master Win 10 client power on does not work. All other Win 10, Win 7 combinations work perfectly. Most strange. For example, in a classroom with a Win 7 master, power on worked for the Win 10 student clients. But, when IT "upgraded" the instructor computer to Win 10, power on no longer worked. Yet, in a Win 7 classroom where only the instructor computer switched from Win 7 to Win 10, again power on still worked normally.

Thanks for your prompt reply.
________________________________________
