### ISSUE TITLE
Enhancement Request: Login for Windows User

### ISSUE THREAD

**Issue by painkiller507** [veyon/veyon#560]
It would be very helpful to have a function to automatically login the user in Windows. My idea is, that you create additional space in the veyon configurator where you can define the rooms and the computers and you can add the username and password for each computer. 
Then there is a button in the main mask of Veyon with which you can use the Windows login with the saved information.

**Comment by tobydox** [comment]
This feature will be available in Veyon 4.3.0 which will be released this week :)

**Comment by tobydox** [comment]
Veyon 4.3.0 has been released today - please check out the new logon feature.

**Comment by Buburip** [comment]
Hello,
I do not find this feature in the configurator, rooms and computers, VEYON 4.3.0.0 x64.
Can not add user name and password for each computer.
Thanks for your feedback ...

**Comment by tobydox** [comment]
The logon feature is restricted to a single user which is logged in on all computers. Logging in individual users is currently not possible. If required the implementation can be done on a commercial base - contact support@veyon.io if you're interested.
