### ISSUE TITLE
Screen flicker

### ISSUE THREAD

**Issue by scrfc71** [veyon/veyon#561]
installed Version 4.2.5 (Latest version now available).
OS: Win10 x64 (latest pachtes)

We have the problem that certain applications (e.g. Microsoft Access), which access network shares, flicker when Veyon is open.

As soon as Veyon is closed, the flickering is no longer present. The problem was also present with Veyon 4.2.0.

Any recommendations??

**Comment by scrfc71** [comment]
still no updates?

**Comment by luedi69** [comment]
We have the same problem - Veyon Version 4.3.1 Win10 x64.
If Veyon Master or a Veyon Client Window is open, most of the Screens flickr, and also the Control-Key on the local Machine is not always recognized. (depending on the flickr)

**Comment by Eruthon** [comment]
On version 4.4.2 it's still an issue; I also had the Ctrl key circle animation arround the cursor turned on and it was doing it every second or so, on mutiple PCs when Veyon Master was opened. That's why the Ctrl key wasn't recognized sometimes imo.
