### ISSUE TITLE
Problem sending url

### ISSUE THREAD

**Issue by kriminals** [veyon/veyon#563]
When i try to send to students the following url, windows file explorer opens.
http://www.bizdim.gr/index.php?option=com_content&view=article&id=157&Itemid=143
Veyon 4.2.2 on windows 10.

**Comment by lastuptodate** [comment]
Same problem here.
Veyon 4.3.0.0 + Windows 10 1903

**Comment by tobydox** [comment]
Which web browser are you using? Is it configured as the default web browser?

**Comment by lastuptodate** [comment]
Another test on a computer (W10 1903).
Chrome is the default internet browser and http + https protocol are linked to Chrome.
If I send an url (https://www.google.com), it ask for choosing a browser

**Comment by kriminals** [comment]
Chrome.

**Comment by Sanya44** [comment]
Same problem. If the URL contains "=", then the client pc doesn't open the browser.

**Comment by tobydox** [comment]
The issue will finally be fixed in the upcoming 4.3.6 release.
