### ISSUE TITLE
Lock override

### ISSUE THREAD

**Issue by saraniim** [veyon/veyon#565]
My students have managed to override the lock  - super annoying. I haven't managed to figure out how.
i am using version 4.1.8 on Windows 10. 

I am also not very experienced with programming. 
Help!!!

**Comment by tobydox** [comment]
Thanks for reporting. However without any further information we can't do anything about this. So please figure out what they're doing. Please also consider upgrading to Veyon 4.2.x which has additional improvements regarding screen lock.

**Comment by saraniim** [comment]
How can I quickly update? I did an individual install on each...

**Comment by tobydox** [comment]
Either run the installer on all computers manually (in-place upgrade possible without any further actions) or (recommended) set up automated deployments (https://docs.veyon.io/en/latest/admin/installation.html#automated-silent-installation). Please note that we can't provide further support through the issue tracker.
