### ISSUE TITLE
Remote logon feature on domain computers

### ISSUE THREAD

**Issue by dxdemetriou** [veyon/veyon#569]
The remote logon feature is not working on domain computers, probably because of CAD & LegalNotice, and I'm using these registry keys for make it working:

reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\policies\system" /v LegalNoticeCaption /t REG_SZ /d "" /f /reg:64

reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\policies\system" /v LegalNoticeText /t REG_SZ /d "" /f /reg:64

reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" /v DisableCAD /t REG_SZ /d "1" /f /reg:64

reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" /v DisableCAD /t REG_DWORD /d "1" /f /reg:64

**Comment by tobydox** [comment]
Thanks for the clarification! We updated the documentation at https://docs.veyon.io/en/latest/admin/platform-notes.html#user-login
