### ISSUE TITLE
Log in Feature Error

### ISSUE THREAD

**Issue by googleman26** [veyon/veyon#572]
Good Day! 

I am testing the new login feature in veyon 4.3.0.0 version in windows 7 but unfortunately it was not running as a expected to be..  I attached a screenshot on my client computer. 
![veyon login feature error](https://user-images.githubusercontent.com/25044145/66969169-1d249c80-f0bb-11e9-9d6d-5ec9284a8c7f.jpg)

**Comment by iesbecquer** [comment]
Hi all!!!

I am also dealing the same problem. Any suggestion to fix it???

Thanks.

**Comment by tobydox** [comment]
Please see https://docs.veyon.io/en/latest/admin/platform-notes.html#user-login for more information on how to make user login work on Windows.
