### ISSUE TITLE
Run Program

### ISSUE THREAD

**Issue by djwusmc** [veyon/veyon#577]
Can run program be used to update Veyon, and if so, how?

An instructor asked if run program can be used to give an exam, and if yes, how?

Can you provide some examples about how to use run program?

**Comment by tobydox** [comment]
Please see the documentation at https://docs.veyon.io/en/latest/user/features.html#run-program for details on possible use cases :-)

Updating Veyon through this function is probably difficult you all you can do is try to logon a user with administrative privileges and run the installer through the run program function.
