### ISSUE TITLE
Would like to fix some Veyon weaknesses

### ISSUE THREAD

**Issue by djwusmc** [veyon/veyon#578]
What do I have to do to access the code for the purpose of fixing what is not as user-friendly as it should be? My initial goal is to enable creating a text file that can be imported into the Veyon Configurator out of respect for this very useful free program. Creating a text file with computername, IP, and MAC would be far more user-friendly than manual input into the configurator. My coding is a bit more than a bit rusty. However, I used to easily write 10,000 line assembly language code.

**Comment by tobydox** [comment]
The source code is available here at Github. Feel free to submit a pull request which meets the coding and style conventions. Also when implementing a graphical text file import feature please re-use the code which already exists in the BuiltinDirectoryPlugin class.

**Comment by djwusmc** [comment]
OK, thank you.
