### ISSUE TITLE
Run Program

### ISSUE THREAD

**Issue by djwusmc** [veyon/veyon#582]
Does anyone know how to use Run Program to run a program from the Master to the Clients with the program being only on the Master and not on the Clients?

**Comment by jamj2000** [comment]
You are suposed you are going to run a client program, not a master program.

That's way is the app is intended to.

**Comment by djwusmc** [comment]
Thank you, was concerned about that.

We used to use Altiris, but it just became too expensive, and SCCM is free junk.

Since Veyon has suggested a commercial version is in the works, this “run from master” functionality would be a huge plus.

On our newer computers with SSD drives, Veyon is lightning quick.

**Comment by tobydox** [comment]
The kind of functionality you mentioned is not available in Veyon. As pointed out by @jamj2000 you can either run programs on all clients. Alternatively use the demo mode to allow students seeing a program you're running on the master.
