### ISSUE TITLE
error compiling x11vnc plugin with libressl instead openssl

### ISSUE THREAD

**Issue by RyzhakovAndrey** [veyon/veyon#583]
Error compiling on Linux Gentoo with error `undefined reference to 'SSL_CTX_set_security_level'`
x11vnc is also built with libressl instead of openssl
Tail of build.log is attached
[build.tail100.log](https://github.com/veyon/veyon/files/3814810/build.tail100.log

**Comment by tobydox** [comment]
Since x11vnc is a 3rdparty component, there's nothing we can do here, I'm sorry...
