### ISSUE TITLE
Remote View vs Remote Control

### ISSUE THREAD

**Issue by southpas1966** [veyon/veyon#584]
We have remote control and screen shots disabled via Disabled Features registry settings on the Master computer. However we have noticed when you allow Remote View you are able to take screen shots and remote control computer. Is there a true "Remote View" only disabling screen shots and remote control?
Thank you,

**Comment by tobydox** [comment]
In Veyon 4.4.0 the configured features are also honored by the remote access window (via 5fdca5d73c0a3504084bb0f146ab9c972e6fa39d). The view only toggle button is hidden if one of the 2 remote access feature is disabled.
