### ISSUE TITLE
Execute command line by veyon-cli.exe

### ISSUE THREAD

**Issue by Arc-Soul** [veyon/veyon#585]
Such as the title, I can run program for each computer by veyon master(UI).
But I want to use veyon-cli.exe to do this, is it possible?

**Comment by brifsttar** [comment]
I have the exact same need, but I don't think that it's currently possible using the CLI.

**Comment by tobydox** [comment]
Currently this is not implemented (though technically not that hard any longer as of b3a27c03d7276eed436d21c6a6b93a784c29a8f6) but in the meanwhile one possibility would be to write a small Python/Powershell script which controls remote computers through the Veyon WebAPI (if enabled client-side).

**Comment by brifsttar** [comment]
I didn't know about the WebAPI, interesting. Does it support "Run program"? The [latest doc](https://docs.veyon.io/fr/latest/developer/webapi.html) doesn't mention it in the available features, and I don't have a running Veyon on hand to query the WebAPI for features.

**Comment by tobydox** [comment]
Indeed the documentation is incomplete, it just mentions the features a customer required when WebAPI was developed. When querying available features, you should see the `RunProgram` feature with UUID `da9ca56a-b2ad-4fff-8f8a-929b2927b442` (as coded in `plugins/desktopservices/DesktopServicesFeaturePlugin.cpp`). As arguments you can specify the programs to run: `{ "programs": [ "app1.exe", "app2.exe" ] }`.
