### ISSUE TITLE
Veyon closes fullscreen apps when returning from lock

### ISSUE THREAD

**Issue by superslurt** [veyon/veyon#586]
Hi!

First of all: Veyon works really well for us!

But:
Whenever I lock the computers with Veyon, the users full screen apps closes. We use Veyon at our school at the computer lab, and often we use it for gaming. When locking the computers during a game, all the games minimizes and returns to desktop after unlocking.

It's not a big issue, but the students get quite frustrated.

Is there a way to restore a full screen window after locking, so it doesn't always show the desktop afterwards?

**Comment by tobydox** [comment]
Thank you for your bug report. The issue should be fixed in upcoming 4.3.5 release.

**Comment by superslurt** [comment]
Wow, thanks!

**Comment by tobydox** [comment]
If it persists, try disabling the options described at https://docs.veyon.io/en/latest/admin/platform-notes.html#screen-lock
