### ISSUE TITLE
No thumbnail display for hosts with connected users

### ISSUE THREAD

**Issue by eoli3n** [veyon/veyon#588]
Hi
Thumbnails show a red screen for hosts with connected user but not for inactive ones running lightdm.
Veyon version : 4.3.0-1~bionic

![thumb](https://user-images.githubusercontent.com/14223657/69856298-9f44db00-128d-11ea-8892-0e954f226746.png)

**Comment by eoli3n** [comment]
Is there anybody here ?

**Comment by tobydox** [comment]
Yes :-) Do you still encounter problems with the latest 4.5.5 release?

**Comment by eoli3n** [comment]
That was just a ping, thanks for your answer ;) I don't face that issue anymore.

**Comment by tobydox** [comment]
Thanks for the feedback! :-)
