### ISSUE TITLE
Does not transmit Cyrillic

### ISSUE THREAD

**Issue by mrkaban** [veyon/veyon#59]
Hello, iTALC also had such a problem, with remote management, if the teacher's computer language is switched to English, then it passes them without problems, that is, in a text document, you can print English letters without problems. But if you switch the language to Russian on the teacher's computer, then it does not transmit anything, and you press the keys, and nothing appears in the text document.

And another question, about the translation of the window of the wizard into Russian, maybe some help is needed? or how?

**Comment by mrkaban** [comment]
And yet, how can I unblock a computer if I blocked it with a context menu? In the context menu there is only "Lock", "Unlock" does not appear.

**Comment by tobydox** [comment]
Are you running Veyon on Windows or Linux?

Switching back to "Overview" mode stops any active features such as demo and screen lock :-)

**Comment by mrkaban** [comment]
I'm sorry, I did not specify it at once, I use two computers on Windows 7 x64 + the third one will be on Windows 10 x64.

How can I solve this problem? But it is actively asked about it by Russian-speaking users.

**Comment by tobydox** [comment]
I have to figure out first whether this is problem in the VNC server or the VNC client. I'll do some tests and report back later.

**Comment by mrkaban** [comment]
Well thank you! On my site iTALC is very popular, and regularly asked about it. Now published by Veyon. Thank you very much for this software !!! If interested, I can give a link =)

**Comment by mrkaban** [comment]
Hello, in the settings I found the ability to create a report with an error. Attached, suddenly help.
[1.zip](https://github.com/veyon/veyon/files/1168135/1.zip)

**Comment by jamj2000** [comment]
@mrkaban you can join to translation team in https://www.transifex.com/veyon-solutions/veyon/

You can use your github account to identify yourself.

**Comment by tobydox** [comment]
This is a general issue with UltraVNC (see http://forum.ultravnc.info/viewtopic.php?t=18801 for details). We'll come up with a new VNC key mapper and an improved UltraVNC implementation with Veyon 4.1. Until then please switch to English keyboard layout during remote control.

**Comment by mrkaban** [comment]
Thank you very much! Will wait! Very cool program! People often write words of gratitude!
