### ISSUE TITLE
Remote control does not transmit Cyrillic

### ISSUE THREAD

**Issue by mrkaban** [veyon/veyon#590]
Hello, I asked a similar question about iTALC, and in version 4.3.1.0 this problem persisted. Two pieces of Windows 10 64-bit and Windows 7 64-bit are used. With remote control, you can even simply open the notebook and try to write something, if the English layout is enabled, then it writes without problems. However, if the Russian layout is enabled, then he writes nothing.

**Comment by tobydox** [comment]
See discussion in #779 - unfortunately there's currently no possibility for fixing this.
