### ISSUE TITLE
Clients won't show demo. Configuration does not show on master.

### ISSUE THREAD

**Issue by iperiz** [veyon/veyon#593]
Veyon Master often fails to start demo on clients (they get a blank windows, waiting for connectcion).

I chose to check configuration, but Veyon Configurator doesn't show up. When clicked, I can see a process via Task Manager.

I decided to uninstall. I removed application folder.

I installed again. Veyon Configurator does not show up still.

And demos does not work yet.

**Comment by tobydox** [comment]
Which version did you use? Have you been able to fix this issue by using a recent version?

**Comment by tobydox** [comment]
The fix will be part of Veyon 4.5.0.
