### ISSUE TITLE
Master fails to launch unless using "Classic Interface"

### ISSUE THREAD

**Issue by NJJJCAustin** [veyon/veyon#597]
I have traced the issue to the following test is all of the Auth Plugins:
if( qobject_cast<QApplication *>( QCoreApplication::instance() ) )

I originally though all that was needed to get it to work was to change the test to QGuiApplication, however that causes the following error:
QWidget: Cannot create a QWidget without QApplication

The root cause is the change in main.cpp's main function to 
"	const auto classicUi = VeyonConfiguration().classicUserInterface();
	QGuiApplication* app = classicUi ? new QApplication( argc, argv ) : new QGuiApplication( argc, argv );
"

**Comment by tobydox** [comment]
The new user interface in the master branch does not work with QWidgets so if there's any plugin which creates or shows a widget it will crash. I'm currently working on making all plugins handle both UI modes. The current master branch with no additional plugins already works with the new UI. So if your new auth plugin creates widgets you should stick with the classic UI and we'll add a QtQuick/QML implementation for your UI later.

**Comment by tobydox** [comment]
As of a967e8b9371a9eea069fae55ebf2fa0d4ccdfec7 Veyon defaults to it classic interface now. We might revert it once the new user interface is finished.
