### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by thewillwilson** [veyon/veyon#6]
Do you have any screenshots of the control panel?

**Comment by jamj2000** [comment]
Here you have screenshot of **veyon-configurator**

![virtualbox_windows 10_04_05_2017_20_19_03](https://cloud.githubusercontent.com/assets/2934084/25718650/2340db0e-3107-11e7-9e40-000b42497c4b.png)

**Comment by tobydox** [comment]
I think I can close this issue as there has been no actual problem to solve :-)
