### ISSUE TITLE
no mouse cursor when no mouse is plugged in

### ISSUE THREAD

**Issue by chldbwnstm** [veyon/veyon#601]
Is it possible to show mouse cursor on master vnc connection even if no mouse is plugged in?
I know that chrome remote desktop can, but is this possible for Veyon?

**Comment by brifsttar** [comment]
On Windows you can have that natively: https://superuser.com/questions/1129210/no-mouse-cursor-when-no-physical-mouse-device-plugged-in

I've been using that on most slaves, it works fine.

**Comment by tobydox** [comment]
@brifsttar thank you for sharing a solution! Besides this there's nothing we can do on Veyon side.
