### ISSUE TITLE
Can not remote login computers

### ISSUE THREAD

**Issue by itsgahndi** [veyon/veyon#603]
Hey,

So the issue I'm having is that I can not log into our student computers with a Microsoft account PIN on them. When I try to login with either the PIN or Microsoft account password, it selects the "I forgot my PIN" option. When I try to log into the administrator account, it still defaults to the student account. Any suggestions?

**Comment by tobydox** [comment]
Thank you for your feedback! The remote login feature is not intended to be used with the PIN logon mechanism. After configuring Windows to show the regular logon screen and use password authentication, everything should work as expected.
