### ISSUE TITLE
No keyboard lock.

### ISSUE THREAD

**Issue by TanyaSm** [veyon/veyon#605]
Hello! If you lock the student's computer, the keyboard is not blocked, you can go to the task Manager and remove the lock. After installing the Veyon client, I did a reboot and installed the interception driver. Nothing helped. Veyon Version 4.3.2.0. Windows 7 operating system. 
But after using the "full-screen demo" function, the keyboard was blocked on some computers. only a system reboot helped. Can you tell me how to fix this problem? Thanks.

**Comment by tobydox** [comment]
If the interception driver does not work on your system, unfortunately there's nothing we can do about it :-( Try installing the interception driver manually by invoking C:\Program Files\Veyon\interception\install-interception.bat with administrative privileges.
