### ISSUE TITLE
Cannot demo teacher screen if teacher is on RDP session

### ISSUE THREAD

**Issue by ctincristi** [veyon/veyon#609]
In an environment where both teacher and student machines use Windows with remote sessions, when pressing the 'Fullscreen demo' or 'Window demo' buttons:
- what should happen: the teacher's remote session should be broadcasted to the student's machine;
- what happens: a locked login screen is broadcasted to the student's machine.

**Comment by truatpasteurdotfr** [comment]
I guess that RDP and VNC are not playing nice together... VNC from veyon is copying the local display (locked screen) and RDP is displaying on the teacher remote computer.

**Comment by tobydox** [comment]
Issue is fixed in recent releases :-) Please update to 4.4.2 or newer.
