### ISSUE TITLE
My idea for Veyon

### ISSUE THREAD

**Issue by Ludvi01** [veyon/veyon#612]
My ideas:

1. Blank Screen / Lock Screen:
Example:
![simple-custom-lock](https://user-images.githubusercontent.com/46907508/74363902-ceb6ae80-4dcb-11ea-9eb9-495d290d9575.png)

Save custom messages, and dropdown menu.

2. Switching between Teacher or Student mode:
Each machine could be selected to be in teacher or student mode.
And when teacher mode is there, it doesn't disable anything, and it turns back to student mode after turning it off.

3. Limiting web and apps:
"🤚 Sorry you have no right to access this web page!"

4. Disable File Explorer.
5. Option to log browser history for checking by a teacher.
6. Option to disable keyboard shortcuts.
7. Disable keyboard and mouse for student's.
8. Mute student's computer sound.
9. Voting system.

This is my nine points.

**Comment by tobydox** [comment]
Thank you for your suggestions! In my opinion most of them are very special and would require lots of (platform-specific) development efforts so I fear that these features won't get implemented unless a volunteer starts developing and contributing them. At least audio muting could be done by using the existing "Start app" feature and make it run an appropriate utility or powershell script.
