### ISSUE TITLE
Issue - Control my self not my network !

### ISSUE THREAD

**Issue by Mohamed-Elmasri** [veyon/veyon#614]
Hi,
I have an issue which is in the below picture
I am using Public key method
shown in this video

[https://www.youtube.com/watch?v=HrHJqdsCXUw](https://www.youtube.com/watch?v=HrHJqdsCXUw)

![image](https://user-images.githubusercontent.com/39469567/74419804-1c2a2e80-4e53-11ea-9b14-d54468852542.png)

Please help !

**Comment by tobydox** [comment]
You likely did not enter proper host names in the "Computers & locations" tab so it falls back to `localhost`.
