### ISSUE TITLE
Demo is not working with hybrid configuration

### ISSUE THREAD

**Issue by cpasoft** [veyon/veyon#616]
I have three display on my windows (two monitors + projector). I have configured it as 1+3 (duplicated) and 2 extended (hybrid configuration).

With the Veyon 4.2.5 I can share my main screen to the clients. With the 4.3x this is not working (black screen, but connected).
If I change my configuration to extended, then I can share my main screen without problem, but I need to duplicate one of the monitor with the projector.

Is a master's service problem, because I can use the 4.3.3 version on my clients, and 4.2.5 service on the master and then everything works right. Also I can use the Veyon-Master.exe of the new 4.3.3 and still working well, but the service must be the 4.2.5.

For sure is any update on the internal uvnc library. Please check this...

**Comment by cpasoft** [comment]
Using the uVnc 1.2.3.0RC as external vnc service, there is no problem.

**Comment by tobydox** [comment]
Is this still an issue with Veyon 4.6.x?

**Comment by cpasoft** [comment]
I have not tested... I'll do it this week and I'll report it back
