### ISSUE TITLE
Remote Control: Failure of security / privacy

### ISSUE THREAD

**Issue by CiroXM** [veyon/veyon#618]
Even if the remote control functionality is disabled in Veyon Configurator (Master> Features: Remote Control disabled), when the user opens Remote View, the option “Remote Control” appears, and it works! Therefore, if the functionality is disabled, it should not be possible to use, being an application inconsistency. It is extremely important that this option is removed when configured.

Another additional security and privacy option would be to enable the customer to only have the screen monitored, but not have the computer controlled, regardless of the master.

To further improve, the functionality settings of the master (Veyon Configurator> Master> Features) should be linked to the permissions of the Access control groups.

Veyon version used: 4.3.3

**Comment by tobydox** [comment]
We can implement various privacy-related features (including #630). Please contact sales@veyon.io to discuss commercial details on possible paid development tasks.

**Comment by tobydox** [comment]
As of Veyon 4.4 the view only button is hidden when the remote control feature is disabled.
