### ISSUE TITLE
Cannot start configurator on debain 10.3

### ISSUE THREAD

**Issue by Cyvros** [veyon/veyon#619]
We get his issue on every newly set up machine in debian.
We cannot start configurator.
Neither with sudo nor with root itself.
I fixed it on one machine 2 weeks ago but cannot remember what i did.
Please help!

SUDO:
> nsl@vorsicher:/Downloads$ sudo veyon-configurator
[sudo] Passwort für nsl: 
No protocol specified
qt.qpa.screen: QXcbConnection: Could not connect to display :0
Could not connect to any X display.
nsl@vorsicher:/Downloads$ 

And a Window pops up telling us there is no tool like sudo installed
the config file is not writeable and veyon-configurator needs higher priviledges (which IS)

ROOT:
> root@vorsicher:/# veyon-configurator
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
No protocol specified
qt.qpa.screen: QXcbConnection: Could not connect to display :0
Could not connect to any X display.
root@vorsicher:/# 

And then simply nothing happens at all

**Comment by truatpasteurdotfr** [comment]
maybe wayland VS  X11 ? does it work with an Xorg/X11 local session ?

**Comment by tobydox** [comment]
Please use `pkexec` or similar graphical sudo-tool to run Veyon Configurator. When installing the official packages, you should be able to run Veyon Configurator normally and it will request root privileges automatically.
