### ISSUE TITLE
Suggestion with the option "automatically switch to current room at start" with Veyon master.

### ISSUE THREAD

**Issue by orion777** [veyon/veyon#62]
When the option "automatically switch to current room at start" is checked in veyon-configurator, there is no computer / room displayed in the left frame of the veyon master.
It is necessary to click on the computer rooms button in the left corner below on Veyon master to display the room/computer left frame. But then room and computer aren't automatically checked. 
I think it could be a problem for teachers when launching the veyon master. When they used Italc master, the room and computers were automatically visible and displayed in the right frame.
I work with teachers and i know they will be disoriented with this.  The easier way for them is to automatically have displayed computers's room in Veyon master. Well maybe it is more a suggestion than a bug report.

**Comment by patdu59** [comment]
Hi !
I discovered Veyon yesterday afternoon as I wanted to see if Italc had been updated lately.
To be honest, I was quite puzzled when I tried to create a classroom and to see it in Veyon Master. Just like you orion77, I always had to click on the computer rooms button. I think I've found how to make the classroom appear when you launch the Master : when you create a classroom, you must add the computer used by the teacher. Then, the classroom will appear when you start Veyon Master.

There is a big problem I think, as far as Veyon is concerned : I can't put the computers at the right place, but it was possible with Italc. For instance, I can't create 3 rows, then put PC1 next to PC2 and in front of PC3. Therefore, as all the PCs are automatically put one after the other, it is not convenient at all and I think that it will be a problem for my colleagues. 

Last point : when the classroom is displayed in the master, I only see the name of the computer, not the name of the person who is logged.

Thanks for your help !

**Comment by tobydox** [comment]
Thanks for your report! You need to add the teacher computer to the classroom so Veyon knows which classroom the computer belongs to. If this doesn't work, check your DNS setup and/or use IP addresses for host addresses.

**Comment by orion777** [comment]
Thanks you for your help again!
Will you make an official annoucement concerning the release of a definitive stable Veyon release?  And what about the delay when a new version will be published? With Italc time was relatively long between versions.
Well if i ask you these questions it is because i have planned to remove all old italc installations for the new school year and install stable official Veyon release.
Thanx again for the infos.

**Comment by tobydox** [comment]
Yes there'll be official announcements as usual. The final 4.0.0 release will be available in August while 3.99.7 (RC3) will be released today (if no serious issues are discovered during testing).

There'll be more frequent updates to Veyon compared to iTALC so fixes should reach end users early :-)
