### ISSUE TITLE
2 screens management for Master

### ISSUE THREAD

**Issue by benoitfouc** [veyon/veyon#620]
Hello, i wanna talk about the "multi-screens" management for the Master.
In my park, all users have 2 screens, me too.
I can see the 2 screens in the same windows BUT it's too small and illegible :
[https://i.gyazo.com/c80b8fdbe4822a490cbd5669f5542c22.png](https://i.gyazo.com/c80b8fdbe4822a490cbd5669f5542c22.png)

Is it possible to switch to screen 1 or screen 2 with a simple button ? like in Teamviewer.

**Comment by turin331** [comment]
I have the same issue. Is there a way to choose which monitor to display? Otherwise the multiple screens are unworkable.

**Comment by benoitfouc** [comment]
> I have the same issue. Is there a way to choose which monitor to display? Simple button or no Otherwise the multiple screens are unworkable.

Yes this is a good idea. If the master have 1 monitor and slave 2 monitor, it's realy realy small. Text is not visible.

**Comment by Meister1593** [comment]
is there any work around this? this is quite needed feature.
I can either look at one screen full-screen or both, but not independently both.

**Comment by sergioinsti** [comment]
Yes, I'd like it, too.
I'm developer. May be with a little help I could do it

**Comment by jeetshut** [comment]
+1 request for this feature. Very much needed.

**Comment by dudefoxlive** [comment]
I agree that there should be something to choose a display but I think this is down to the VNC service that Veyon is using. Please correct me if I am wrong.

**Comment by sergioinsti** [comment]
Good question
