### ISSUE TITLE
Feature Request: Computer Groups "Slideshow"

### ISSUE THREAD

**Issue by CiroXM** [veyon/veyon#621]
Hi,

When you have many computers, it is good to split into groups. However, to follow the screens of the different groups, it is necessary to manually select the individual group. It would be very interesting, for better monitoring, that it was possible to "play" the display of the groups of computers, and every 25 seconds (for example) the veyon master would switch to the next group, and so on. The play and stop button can be close to the filters.

**Comment by tobydox** [comment]
For the most part implemented in Veyon 4.5.0.
