### ISSUE TITLE
C++ Runtime Library Errors in 32 bit W7

### ISSUE THREAD

**Issue by banzai200** [veyon/veyon#623]
In the latest version, when i open Veyon Master on my linux machine, some programs like Microsoft Office and Acrobat reader show the error "Microsoft Visual C++ Runtime Library - This application has requested to terminate it in an unusual way" and hangs

This only happens on Windows 7 clients, on Windows 10 machines it works properly.

Veyon master runs in a Arch Linux Machine

**Comment by tobydox** [comment]
Thank you for your bug report! Since we don't support Windows 7 any longer, unfortunately there's no solution for your problem. You can try using the 64 bit version in case the computer is a 64 bit computer.
