### ISSUE TITLE
Multi session mode - missing option in menu

### ISSUE THREAD

**Issue by ictprocz** [veyon/veyon#627]
Hello,
due to covid issue we need to run IT classes for our students remotely. All PCs in classroom are running Windows 10 and at this time they are all reachable from outside via RDP protocol. Now I'm looking for something how instructors can monitor student's activity and also can assist them on their desktops.
At this time we have configured Veyon (4.3.4) to be running fine when students are working in local class.

However if students are connected through RDP, then instructor can see only locked screen. According to Veyon guide this should be solved by enabling **"Multi session mode"** in config menu. However **this option is not listed in Service tab**.  Do we need some special plugin to enable this? Or downgrade to other specific Veyon version? 

Thanks,
Petr

**Comment by tobydox** [comment]
Please switch to View -> Advanced in the Veyon Configurator menu. You should then see advanced options like multi session support.

**Comment by ictprocz** [comment]
Thank you very much, I found it. I haven't noticed View menu.

Multi session in now enabled on all PCs. However I can't find where to configure session ID to Veyon Master to change from local session to RDP. Could you navigate me also please?
