### ISSUE TITLE
Session ID

### ISSUE THREAD

**Issue by Brad9999** [veyon/veyon#628]
I have an Several AZURE Windows 2016 machines with Veyon (4.3.4) installed and one with Veyon (4.3.4) Master installed. Training participants connect using a RDP Session. Veyon Master seems to start a console session on these machines with a different session ID so the screen cant be shadowed. The Session ID can be shown by typing a Quser at the command prompt. Is there a way to control the session ID so that they use the same one either in a windows policy or using Veyon?

**Comment by mceserani** [comment]
I'm struggling with the same problem.

**Comment by tobydox** [comment]
Please see the documentation at https://docs.veyon.io/en/latest/admin/reference.html#refmultisessionmode - multi session mode will be improved further in the next 4.4.x releases. The NetworkDiscovery add-on 4.4.1 will support scanning sessions on remote computers as well.

**Comment by tobydox** [comment]
Thanks again for your feedback. The issue has been fixed in 4.4.1. Veyon Master now properly connects to the Veyon Server instance of the current session and thus broadcasts the session's screen instead of the console session screen.

**Comment by mceserani** [comment]
Thank you very much!

**Comment by Brad9999** [comment]
I can confirm that I have been able to get this solution working now - thank you very much
