### ISSUE TITLE
veyon : Dépend: libprocps6 mais il n'est pas installable

### ISSUE THREAD

**Issue by npettiaux** [veyon/veyon#629]
Hello,

I run Ubuntu 19.10 eoan. I want to install veyon through

sudo apt install ./veyon_4.3.4-ubuntu-bionic_amd64.deb

and I get 

Les paquets suivants contiennent des dépendances non satisfaites :
 veyon : Dépend: libprocps6 mais il n'est pas installable
E: Impossible de corriger les problèmes, des paquets défectueux sont en mode « garder en l'état ».

I have tried 

sudo apt install -f 

but nothing changes.

I don't know what to do . Much thanks

**Comment by pauloboc** [comment]
I have the same problem on the raspberry raspbian buster, to fix it before installing Veyon, I install this package.

I don't know if it's compatible

[libprocps6_3.3.12-3_raspberry_buster_armhf.zip](https://github.com/veyon/veyon/files/4499448/libprocps6_3.3.12-3_raspberry_buster_armhf.zip)

**Comment by tobydox** [comment]
On Ubuntu you can simply add our PPA at https://launchpad.net/~veyon/+archive/ubuntu/stable/ which contains dedicated packages for Ubuntu 19.10.

**Comment by npettiaux** [comment]
Thanks but I cannot get the files. I did
add-apt-repository https://launchpad.net/~veyon/+archive/ubuntu/stable/ , then
sudo apt update
this gives me the following messages
======
Atteint :21 https://dl.jami.net/ring-nightly/ubuntu_19.10 ring InRelease        
Err :23 https://launchpad.net/~veyon/+archive/ubuntu/stable eoan Release
  404  Not Found [IP : 2001:67c:1560:8003::8003 443]
Lecture des listes de paquets... Fait
E: Le dépôt https://launchpad.net/~veyon/+archive/ubuntu/stable eoan Release n'a pas de fichier Release.
N: Les mises à jour depuis un tel dépôt ne peuvent s'effectuer de manière sécurisée, et sont donc désactivées par défaut.
N: Voir les pages de manuel d'apt-secure(8) pour la création des dépôts et les détails de configuration d'un utilisateur.
======
I understand that the ppa is not accessible

**Comment by tobydox** [comment]
Please follow the instructions at the PPA page, i.e.

```
sudo add-apt-repository ppa:veyon/stable
sudo apt-get update
```

**Comment by npettiaux** [comment]
works now. Much thanks.

Another problem 

sudo apt install veyon-plugins 
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Les NOUVEAUX paquets suivants seront installés :
  veyon-plugins
0 mis à jour, 1 nouvellement installés, 0 à enlever et 0 non mis à jour.
Il est nécessaire de prendre 0 o/533 ko dans les archives.
Après cette opération, 2.553 ko d'espace disque supplémentaires seront utilisés.
(Lecture de la base de données... 390007 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../veyon-plugins_4.2.4+repack1-2_amd64.deb ...
Dépaquetage de veyon-plugins:amd64 (4.2.4+repack1-2) ...
dpkg: erreur de traitement de l'archive /var/cache/apt/archives/veyon-plugins_4.2.4+repack1-2_amd64.deb (--unpack) :
 tentative de remplacement de « /usr/lib/x86_64-linux-gnu/veyon/authkeys.so », qui appartient aussi au paquet veyon 4.3.3-1~eoan
dpkg-deb: erreur: coller subprocess was killed by signal (Relais brisé (pipe))
Des erreurs ont été rencontrées pendant l'exécution :
 /var/cache/apt/archives/veyon-plugins_4.2.4+repack1-2_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by tobydox** [comment]
Please uninstall all Veyon-related packages and run "sudo apt --no-install-recommends install veyon"
