### ISSUE TITLE
Please add me (mantas) to Lithuanian translation team

### ISSUE THREAD

**Issue by Baltix** [veyon/veyon#632]
I can help with Veyon translation to Lithuanian language.

Please add me (mantas) to Lithuanian translation team at https://www.transifex.com/veyon-solutions/veyon/

I'm translating free software since 1999, see https://wiki.ubuntu.com/MantasKriau%c4%8di%c5%abnas

**Comment by tobydox** [comment]
Done - thank you for the ping and your future contributions!
