### ISSUE TITLE
Wayland is used instead of x11

### ISSUE THREAD

**Issue by pglira** [veyon/veyon#633]
I can't connect to one of my pcs.

On that pc the veyon service is running, however, there is a problem with wayland (which I'm not using):

```
[philipp:~] 130 $ sudo systemctl status veyon
● veyon.service - Veyon Service
   Loaded: loaded (/lib/systemd/system/veyon.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-05-04 09:27:18 CEST; 25s ago
     Docs: man:veyon-service(1)
 Main PID: 2774 (veyon-service)
    Tasks: 3 (limit: 4915)
   CGroup: /system.slice/veyon.service
           └─2774 /usr/bin/veyon-service

Mai 04 09:27:18 L1AS19 systemd[1]: Started Veyon Service.
Mai 04 09:27:19 L1AS19 veyon-service[2774]: 2020-05-04T09:27:19.084: [ERR] LinuxServiceCore: Can't start Veyon Server in Wayland sessions as this is not yet supported. 
```

```
echo $XDG_SESSION_TYPE
x11
```

How can I fix this?

I've tried to restart the x11vnc server, but that does not help.

**Comment by tobydox** [comment]
Thank you for your bug report! Wayland is currently not supported by Veyon. Veyon 5 in Q1/2021 will come with a new VNC server implementation which will also support Wayland.

**Comment by pglira** [comment]
Actually, the issue was that **I'm not using wayland at all**, but the error message mentioned wayland:

>  Can't start Veyon Server in Wayland sessions as this is not yet supported.

**Comment by tobydox** [comment]
Sorry, I didn't read carefully enough. Still all Veyon does is checking the session type and for some unknown reasons it's reported as wayland. May be it's the logon screen only which uses a Wayland-based display manager?

**Comment by pglira** [comment]
I'm using the standard ubuntu logon screen, so nothing special. However, my window manager is i3-wm (X11, not wayland), so maybe it's related to that.

**Comment by tobydox** [comment]
Still systemd-logind seems to report the session as `"wayland"`. Otherwise you won't see the indicated error message since Veyon explicitely checks for the session type being `"wayland"`. I don't see how we could fix this Veyon side.

**Comment by pglira** [comment]
Then I would propose to close the issue.

**Comment by tobydox** [comment]
OK thanks!
