### ISSUE TITLE
How to use environment variables?

### ISSUE THREAD

**Issue by EveryOtherUsernameWasAlreadyTaken** [veyon/veyon#636]
I have read the [documentation for environment variables](https://docs.veyon.io/en/latest/admin/reference.html#placeholder-variables-for-file-paths).

I have tried running `%TEMP%` (a variable that is documented to exist) and `%LOCALAPPDATA%` (not documented, but is a default Windows environment variable) both with and without quotes. But on the target computer, nothing opened.

I have also tried `explorer %TEMP%`. However, that just opens Explorer, but not the temp directory.

**Comment by tobydox** [comment]
Thank you for your feedback! Environment variables are used for paths inside the configuration only. Using environment variables for the "Run program" feature is currently not supported – patches/contributions are welcome :-) If your institution is interested in paid development services, please contact sales@veyon.io to discuss further possibilities.
