### ISSUE TITLE
How to configure an URL that opens a browser?

### ISSUE THREAD

**Issue by EveryOtherUsernameWasAlreadyTaken** [veyon/veyon#638]
I have configured the following URL to open a website: 

    https://www.duolingo.com/?isLoggingIn=true

Here's what it looks like in the configurator:

![grafik](https://user-images.githubusercontent.com/5978637/81750774-6e103e00-94ae-11ea-8941-82013b976f35.png)

However, when I attempt to open that URL on the client, it just starts a Windows Explorer at the Documents folder. The URL works when I enter it on the client manually (via remote access).

The client system is Windows 10 with Edge as the default browser. When I set Firefox as the default browser, the behaviour is still the same.

**Comment by tobydox** [comment]
Thank you for your feedback! Does it work for simple URLs, i.e. "https://www.duolingo.com"?

**Comment by EveryOtherUsernameWasAlreadyTaken** [comment]
Yes, https://www.duolingo.com on its own works.

**Comment by truatpasteurdotfr** [comment]
I can open both URL from a CentOS-7 master/student from the veyon-masteur console. Self rebuild version from the source tarball, not tried yet from the veyon-configurator application.

**Comment by truatpasteurdotfr** [comment]
confirming @EveryOtherUsernameWasAlreadyTaken: windows student open the short URL, but opens the file browser with the long one on a win10 2005 x64 client (dowloaded of from veyon) and the same veyon master running on centos-7.

**Comment by truatpasteurdotfr** [comment]
https://www.duolingo.com/?isLoggingIn opens the browser but https://www.duolingo.com/?isLoggingIn= open the file explorer.

**Comment by tobydox** [comment]
The issue will finally be fixed in the upcoming 4.3.6 release.
