### ISSUE TITLE
Problems with Veyon (?)

### ISSUE THREAD

**Issue by patdu59** [veyon/veyon#64]
Hi everybody !

I discovered Veyon yesterday afternoon as I wanted to see if Italc had been updated lately.

I've decided to post here to ask for help. I hope it is the right place :)

To be honest, I was quite puzzled when I tried to create a classroom and to see it in Veyon Master. I always had to click on the computer rooms button. I think I've found how to make the classroom appear when we launch the Master : when we create a classroom, we must add the computer used by the teacher. Then, the classroom will appear when we start Veyon Master. I think it is the correct way to do ?

Now, I face two serious problems : 
1) I can't move the screens in Veyon Master and I can't put the computers at the right place, but it was possible with Italc. For instance, I can't create 3 rows, then put PC1 next to PC2 and in front of PC3. Therefore, as all the PCs are automatically put one after the other, it is not convenient at all and I think that it will be a problem for my colleagues. 

2) when the classroom is displayed in the master, I only see the name of the computer, not the name of the person who is logged. In Italc, there was an option to display the student's name

Thanks for your help !

**Comment by tobydox** [comment]
Hi,

your observations are correct - if you want to use the auto-switch feature you have to add the local/teacher computer to the classroom so Veyon knows which classroom the local computer belongs to. If you do not want to show the local computer in Veyon Master you can simply activate the option "Hide local computer in computer room management".

Due to the rewritten user interface and new widgets being used it's currently not possibly to change the order of the items. It'll probably be possible by implementing drag'n'drop support for the model however that's to come later.

Showing user names is going to be implemented very soon. Expect it to be part of 4.0 RC3 :-)

**Comment by patdu59** [comment]
Hi !
Thanks for your answer :-)
I'm glad to learn that 4.0RC3 will help us to get usernames.

Concerning the order of the items, I really hope that you'll implement it as soon as possible :-)
It is not really convenient to have all the computers one after the other.
I guess it is not easy to implement, but I'm sure you'll manage to do it ;-)

Thanks again !

**Comment by orion777** [comment]
I'm agree with Patdu59,  teachers using monitoring software in our school need to have only user login with displayed screen computer in master control interface as our computers are integrated in active directory domain. 
Would be great to have this again on Veyon like it was on Italc and of course it's the best way for teachers when they need to identify the computer used by student.
I'm currently on Veyon 3.99.6 on windows10 and user login is only displayed on the left frame of the master with computer name but no login user on the main frame. Only name computers are showed there.
i can't wait for the new Veyon version !

**Comment by patdu59** [comment]
Hi,
As Tobias said, for the moment, it is not possible to move the items in order to respect the layout of the room.
Therefore, it is important to have the user name AND the name of the PC at the same time

**Comment by tobydox** [comment]
The implementation of usernames in working area is finished and will be part of upcoming Veyon 4 RC3 release this week :-) Expect extended sorting and grouping facilities in 4.1.

**Comment by patdu59** [comment]
Hi !
That's great ! I'll try Veyon 4 RC3 as soon as it is released :-)
That's good to hear that sorting / grouping will be possible in 4.1. 
Is it possible to subscribe to a newsletter to be informed when an update is available ?

**Comment by patdu59** [comment]
Hi again !
I don't know if it is the right place to ask this question...
In the future, with veyon master, have you planned to :
- control what the students can do on the internet (allow a/some sites and block the others, block all websites, etc)
- control the softwares they can / can't use
- create a chat between the teacher and the students ? (ex : a student could ask for help when needed)

Thanks !

**Comment by tobydox** [comment]
Currently there's no mailing list but you can watch the project here at Github and follow us at Twitter (https://twitter.com/veyon_io) or Facebook https://facebook.com/veyon.io/ :-)

Regarding the features: 1) and 2) are hard to implement (especially restricting software is really difficult) while 3) probably will be available as a commercial addon/plugin in 2018.

**Comment by patdu59** [comment]
Hi Tobias,
Thanks for your answer. I can easily imagine that features 1/2 are hard to implement :-)
Concerning feature 3, when you say "commercial" it means that we would have to pay ?

Last question : with iTalc, when we personalised the items (place, etc), we could copy our Windows profile into the default profile, so that all teachers had the same display. Is it the same with veyon ? or with 4.1 will it be the same when we place the items ?

Thanks

**Comment by tobydox** [comment]
You can use the "watch" button at the top so you get notified about updates/changes automatically ;-)

Concerning text chat: yes, I plan to make text chat an optional plugin which one will have to purchase. Selling plugins for additional functionalities will allow me to continue the development of Veyon with all important features as OpenSource software so still everyone can use it for free :-)

**Comment by tobydox** [comment]
With Veyon depending on whether you use auto-classroom-switching there's no need to provide a default user config any longer. All information and settings are stored system-wide (read only) while only some simple preferences can be changed by the user. Once you can reorder items we'll find a proper solution for that as well.

**Comment by patdu59** [comment]
I've activated the watch button :-)

Concerning the auto-classroom-switching, I think that I use this option (at least, when I launch Veyon Master, the classroom is immediately visible with its computers)

In iTalc, a student could show his computer to the other students (when the teacher used this functionality). I can't find it in Veyon

Thanks again for your precious help and answers :-)

**Comment by tobydox** [comment]
Yeah this functionality was quite a hack which no longer could be supported with our new modular architecture - I'll try to find a solution for 4.1 :-) In the meanwhile you can start a demo for the classroom, stop it on the one client and remote control the client. That way your remote control window will be broadcasted to all other students.
