### ISSUE TITLE
documentation: locking on linux requires /usr/bin/xlock

### ISSUE THREAD

**Issue by truatpasteurdotfr** [veyon/veyon#642]
On CentOS-7 student, one needs to install the xlockmore package from the EPEL repository to get the "lock" functionnality.

**Comment by tobydox** [comment]
Are you sure? The screen lock functionality does not call any external program so it really shouldn't require /usr/bin/xlock.

**Comment by truatpasteurdotfr** [comment]
oh, my bad then, maybe some issue on my built version: the lock function on a student centos7 is just disabling the keyboard, mouse be leave the screen as frozen, while on the win10 student it shows a big lock which is masking the desktop. I will try with your rpm.
