### ISSUE TITLE
veyon-4.4.0-src.tar.bz2 VS veyon.spec_veyon-4.4.0.tar.gz ?

### ISSUE THREAD

**Issue by truatpasteurdotfr** [veyon/veyon#643]
Hi, 

I am curious about the 2 source files https://github.com/veyon/veyon/archive/v4.4.0.tar.gz and  https://github.com/veyon/veyon/releases/download/v4.4.0/veyon-4.4.0-src.tar.bz2

Cheers

Tru

**Comment by tobydox** [comment]
v4.4.0.tar.gz contains the Veyon sources itself only while veyon-4.4.0-src.tar.bz2 is the official source tarball including 3rdparty sources.
