### ISSUE TITLE
CentOS-7 or 7.8 instead of 7.7

### ISSUE THREAD

**Issue by truatpasteurdotfr** [veyon/veyon#644]
Hi,

Is there any reason to stay on the point 7.7 point release insteaf of just using 7 or the 7.8 release for CentOS CI/building?

Cheers

Tru

**Comment by tobydox** [comment]
Mainly for compatibility reasons but you're right, we could bump to 7.8 and also provide binaries for 8.0 (which should work on 8.1 too I guess).

**Comment by truatpasteurdotfr** [comment]
yes, 7.7 is just a point release, as 7.8 is, just use 7 (&& yum upgrade if needed), imho. as for CentOS-8 (unless there is a reason to stay with the GA dot relase that I am not aware of)!

**Comment by tobydox** [comment]
I'm not familiar with CentOS and its release cycles. Does e.g. 7.8 contain newer/updated packets compared to 7.7, i.e. will packages built on 7.8 continue working with 7.7?

**Comment by truatpasteurdotfr** [comment]
7.7 is deprecated as soon as 7.8 is relased, there is only "7". The idea is that anything built on 7.x will stay functionnal on 7.y with y>x, unless a library/package rebase has been made which requires a rebuilt of any package dependant on it. Things are not supposed to be backward compatible.

**Comment by tobydox** [comment]
Ok, thanks for the clarification. In the future we'll built packages for the latest CentOS release of each supported release series. Packages for 8.2 are being prepared right now.
