### ISSUE TITLE
singularity builder and spec files

### ISSUE THREAD

**Issue by truatpasteurdotfr** [veyon/veyon#645]
Hi,

gists with singularity container builder and (quick and dirty) spec files to build veyon as non root.

https://gist.github.com/truatpasteurdotfr/ec6d29cbdf158853f2a753058b1dff38
https://gist.github.com/truatpasteurdotfr/d2b6033b7256389584895a4fbea38165

feel free to re-use adapt...

Tru

**Comment by tobydox** [comment]
Thank you! Since we use Docker for our CI jobs anyway, the current approach is sufficient ATM.
