### ISSUE TITLE
Feature: relay websocket

### ISSUE THREAD

**Issue by sfonteneau** [veyon/veyon#646]
We could imagine implementing a websocket server (like "meshcommander").
This will avoid having an open port on the machines.
I understand that libvncserver supports it ?

**Comment by tobydox** [comment]
Thank you for your feedback! If I understand things correctly, a websocket server would still cause an open port ;-) Also we do not only use libvncserver but other protocol extensions and network layers. BTW starting with Veyon 4.5 there'll be a WebAPI plugin which provides access to computers via HTTP, just in case this is useful for you.
