### ISSUE TITLE
4.4 Build Failure on Arch

### ISSUE THREAD

**Issue by nobicycle** [veyon/veyon#647]
Hello, the AUR package fails as follows:
best wishes

```
==> Retrieving sources...
  -> Updating veyon git repo...
Fetching origin
  -> Updating ultravnc git repo...
Fetching origin
  -> Updating libvncserver git repo...
Fetching origin
  -> Updating x11vnc git repo...
Fetching origin
  -> Updating kldap git repo...
Fetching origin
warning: redirecting to https://invent.kde.org/pim/kldap.git/
==> Validating source files with md5sums...
    veyon ... Skipped
    ultravnc ... Skipped
    libvncserver ... Skipped
    x11vnc ... Skipped
    kldap ... Skipped
==> Extracting sources...
  -> Creating working copy of veyon git repo...
Reset branch 'makepkg'
  -> Creating working copy of ultravnc git repo...
Reset branch 'makepkg'
  -> Creating working copy of libvncserver git repo...
Reset branch 'makepkg'
  -> Creating working copy of x11vnc git repo...
Reset branch 'makepkg'
  -> Creating working copy of kldap git repo...
Reset branch 'makepkg'
==> Starting prepare()...
error: The following untracked working tree files would be overwritten by checkout:
	.arcconfig
	src/ber.cpp
	src/ber.h
	src/ldapconfigwidget.cpp
	src/ldapconfigwidget.h
	src/ldapconnection.cpp
	src/ldapconnection.h
	src/ldapcontrol.cpp
	src/ldapcontrol.h
	src/ldapdefs.h
	src/ldapdn.cpp
	src/ldapdn.h
	src/ldapobject.cpp
	src/ldapobject.h
	src/ldapoperation.cpp
	src/ldapoperation.h
	src/ldapsearch.cpp
	src/ldapsearch.h
	src/ldapserver.cpp
	src/ldapserver.h
	src/ldapurl.cpp
	src/ldapurl.h
	src/ldif.cpp
	src/ldif.h
	src/w32-ldap-help.h
Please move or remove them before you switch branches.
Aborting
Submodule path '3rdparty/libvncserver': checked out 'f33c9d2d8a48de0a1ab01612b32df6a253eb3e76'
error: The following untracked working tree files would be overwritten by checkout:
	lzo.orig/lzoconf.h
	lzo.orig/lzodefs.h
	lzo.orig/minilzo.c
	lzo.orig/minilzo.h
	zlib.orig/.editorconfig
	zlib.orig/LICENSE.md
	zlib.orig/README
	zlib.orig/README.md
	zlib.orig/adler32.c
	zlib.orig/arch/aarch64/aarch64.h
	zlib.orig/arch/aarch64/adler32_neon.c
	zlib.orig/arch/aarch64/crc32_acle.c
	zlib.orig/arch/aarch64/fill_window_arm.c
	zlib.orig/arch/aarch64/insert_string_acle.c
	zlib.orig/arch/aarch64/update_hash.h
	zlib.orig/arch/x86/adler32_simd.c
	zlib.orig/arch/x86/adler32_simd.h
	zlib.orig/arch/x86/crc_folding.c
	zlib.orig/arch/x86/insert_string_sse.h
	zlib.orig/arch/x86/slide_sse.c
	zlib.orig/arch/x86/x86.c
	zlib.orig/arch/x86/x86.h
	zlib.orig/compress.c
	zlib.orig/crc32.c
	zlib.orig/crc32.h
	zlib.orig/deflate.c
	zlib.orig/deflate.h
	zlib.orig/gzclose.c
	zlib.orig/gzguts.h
	zlib.orig/gzlib.c
	zlib.orig/gzread.c
	zlib.orig/gzwrite.c
	zlib.orig/infback.c
	zlib.orig/inffast.c
	zlib.orig/inffast.h
	zlib.orig/inffixed.h
	zlib.orig/inflate.c
	zlib.orig/inflate.h
	zlib.orig/inftrees.c
	zlib.orig/inftrees.h
	zlib.orig/match.h
	zlib.orig/trees.c
	zlib.orig/trees.h
	zlib.orig/uncompr.c
	zlib.orig/win32/zlib1.rc
	zlib.orig/zconf.h
	zlib.orig/zlib.h
	zlib.orig/zlib.sln
	zlib.orig/zlib.vcxproj
	zlib.orig/zlib.vcxproj.filters
	zlib.orig/zutil.c
	zlib.orig/zutil.h
Please move or remove them before you switch branches.
Aborting
Submodule path '3rdparty/x11vnc': checked out 'f1a3921edea294c2149408f96096250ae3b6690e'
Unable to checkout '97728ad6042122124fb7633c7412d70d52e81bde' in submodule path '3rdparty/kldap'
Unable to checkout '7db8faa2eea0028806db50e386d62811cf5461af' in submodule path '3rdparty/ultravnc'
==> ERROR: A failure occurred in prepare().
    Aborting...

```

**Comment by tobydox** [comment]
This seems to be a Git issue. Please start with a fresh clone.

**Comment by nobicycle** [comment]
Fresh clone = no change

makepkg
==> Making package: veyon 4.4.0-1 (Thu 09 Jul 2020 22:26:01 WITA)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating veyon git repo...
Fetching origin
remote: Enumerating objects: 395, done.
remote: Counting objects: 100% (392/392), done.
remote: Compressing objects: 100% (81/81), done.
remote: Total 242 (delta 196), reused 206 (delta 161), pack-reused 0
Receiving objects: 100% (242/242), 64.90 KiB | 21.00 KiB/s, done.
Resolving deltas: 100% (196/196), completed with 103 local objects.
From https://github.com/veyon/veyon
   63e51051..51ee5a92  4.4        -> 4.4
   288686b2..dfa9b409  master     -> master
 * [new tag]           v4.4.1     -> v4.4.1
  -> Updating ultravnc git repo...
Fetching origin
  -> Updating libvncserver git repo...
Fetching origin
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 15 (delta 11), reused 9 (delta 7), pack-reused 0
Unpacking objects: 100% (15/15), 3.22 KiB | 183.00 KiB/s, done.
From https://github.com/veyon/libvncserver
   2aa20da..38fd347  master     -> master
  -> Updating x11vnc git repo...
Fetching origin
  -> Updating kldap git repo...
Fetching origin
warning: redirecting to https://invent.kde.org/pim/kldap.git/
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 4), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), 735 bytes | 245.00 KiB/s, done.
From https://anongit.kde.org/kldap
   bba6e6b..b064b3b  master                                                    -> master
 * [new ref]         refs/keep-around/7c2cd48ed04b3a7bd010f5b61e201039088022e9 -> refs/keep-around/7c2cd48ed04b3a7bd010f5b61e201039088022e9
 * [new ref]         refs/keep-around/b064b3b65d90a6b07269b5a249131dfb7cdb2722 -> refs/keep-around/b064b3b65d90a6b07269b5a249131dfb7cdb2722
 * [new tag]         v20.04.3                                                  -> v20.04.3
==> Validating source files with md5sums...
    veyon ... Skipped
    ultravnc ... Skipped
    libvncserver ... Skipped
    x11vnc ... Skipped
    kldap ... Skipped
==> Extracting sources...
  -> Creating working copy of veyon git repo...
From /home/me/System/Manjaro/yay/veyon/veyon
   63e51051..51ee5a92  4.4        -> origin/4.4
   288686b2..dfa9b409  master     -> origin/master
 * [new tag]           v4.4.1     -> v4.4.1
Fetching submodule 3rdparty/kitemmodels
warning: redirecting to https://invent.kde.org/frameworks/kitemmodels.git/
From https://anongit.kde.org/kitemmodels
   096fc02..075f437  master     -> origin/master
Fetching submodule 3rdparty/kldap
From /home/me/System/Manjaro/yay/veyon/kldap
   bba6e6b..b064b3b  master     -> origin/master
 * [new tag]         v20.04.3   -> v20.04.3
Fetching submodule 3rdparty/libvncserver
From /home/me/System/Manjaro/yay/veyon/libvncserver
   2aa20da..38fd347  master     -> origin/master
Reset branch 'makepkg'
  -> Creating working copy of ultravnc git repo...
Switched to a new branch 'makepkg'
  -> Creating working copy of libvncserver git repo...
From /home/me/System/Manjaro/yay/veyon/libvncserver
   2aa20da..38fd347  master     -> origin/master
Switched to a new branch 'makepkg'
  -> Creating working copy of x11vnc git repo...
Switched to a new branch 'makepkg'
  -> Creating working copy of kldap git repo...
From /home/me/System/Manjaro/yay/veyon/kldap
   bba6e6b..b064b3b  master     -> origin/master
 * [new tag]         v20.04.3   -> v20.04.3
Switched to a new branch 'makepkg'
==> Starting prepare()...
error: The following untracked working tree files would be overwritten by checkout:
	.arcconfig
	COPYING.LIB
	src/ber.cpp
	src/ber.h
	src/ldapconfigwidget.cpp
	src/ldapconfigwidget.h
	src/ldapconnection.cpp
	src/ldapconnection.h
	src/ldapcontrol.cpp
	src/ldapcontrol.h
	src/ldapdefs.h
	src/ldapdn.cpp
	src/ldapdn.h
	src/ldapobject.cpp
	src/ldapobject.h
	src/ldapoperation.cpp
	src/ldapoperation.h
	src/ldapsearch.cpp
	src/ldapsearch.h
	src/ldapserver.cpp
	src/ldapserver.h
	src/ldapurl.cpp
	src/ldapurl.h
	src/ldif.cpp
	src/ldif.h
	src/w32-ldap-help.h
Please move or remove them before you switch branches.
Aborting
Submodule path '3rdparty/libvncserver': checked out 'f33c9d2d8a48de0a1ab01612b32df6a253eb3e76'
error: The following untracked working tree files would be overwritten by checkout:
	lzo.orig/lzoconf.h
	lzo.orig/lzodefs.h
	lzo.orig/minilzo.c
	lzo.orig/minilzo.h
	zlib.orig/.editorconfig
	zlib.orig/LICENSE.md
	zlib.orig/README
	zlib.orig/README.md
	zlib.orig/adler32.c
	zlib.orig/arch/aarch64/aarch64.h
	zlib.orig/arch/aarch64/adler32_neon.c
	zlib.orig/arch/aarch64/crc32_acle.c
	zlib.orig/arch/aarch64/fill_window_arm.c
	zlib.orig/arch/aarch64/insert_string_acle.c
	zlib.orig/arch/aarch64/update_hash.h
	zlib.orig/arch/x86/adler32_simd.c
	zlib.orig/arch/x86/adler32_simd.h
	zlib.orig/arch/x86/crc_folding.c
	zlib.orig/arch/x86/insert_string_sse.h
	zlib.orig/arch/x86/slide_sse.c
	zlib.orig/arch/x86/x86.c
	zlib.orig/arch/x86/x86.h
	zlib.orig/compress.c
	zlib.orig/crc32.c
	zlib.orig/crc32.h
	zlib.orig/deflate.c
	zlib.orig/deflate.h
	zlib.orig/gzclose.c
	zlib.orig/gzguts.h
	zlib.orig/gzlib.c
	zlib.orig/gzread.c
	zlib.orig/gzwrite.c
	zlib.orig/infback.c
	zlib.orig/inffast.c
	zlib.orig/inffast.h
	zlib.orig/inffixed.h
	zlib.orig/inflate.c
	zlib.orig/inflate.h
	zlib.orig/inftrees.c
	zlib.orig/inftrees.h
	zlib.orig/match.h
	zlib.orig/trees.c
	zlib.orig/trees.h
	zlib.orig/uncompr.c
	zlib.orig/win32/zlib1.rc
	zlib.orig/zconf.h
	zlib.orig/zlib.h
	zlib.orig/zlib.sln
	zlib.orig/zlib.vcxproj
	zlib.orig/zlib.vcxproj.filters
	zlib.orig/zutil.c
	zlib.orig/zutil.h
Please move or remove them before you switch branches.
Aborting
Submodule path '3rdparty/x11vnc': checked out 'f1a3921edea294c2149408f96096250ae3b6690e'
Unable to checkout '97728ad6042122124fb7633c7412d70d52e81bde' in submodule path '3rdparty/kldap'
Unable to checkout '7db8faa2eea0028806db50e386d62811cf5461af' in submodule path '3rdparty/ultravnc'
==> ERROR: A failure occurred in prepare().
    Aborting...

**Comment by tobydox** [comment]
I'm sorry but there still seem to be dirty files in your working directory. Please remove *everything* and start as described at https://github.com/veyon/veyon/#downloading-sources Building from source definitely works, otherwise our CI jobs at https://travis-ci.org/veyon/veyon/builds/ would not work ;-)
