### ISSUE TITLE
Computer Room Empty

### ISSUE THREAD

**Issue by abhiaks** [veyon/veyon#65]
Hi There,

New to this product, I have configured it on two pc's and PC1 will be the controlling PC. So I have on PC1 under veyon configurator - local data - added the details of pc2. But on opening the Veyon master and clicking on computer room, there no pc's shown basically it is empty.

Please can you help.

Regards
Abhi

**Comment by orion777** [comment]
Hello

Did you check the "automatically switch to current room at start" in the veyon configurator >line master ?

**Comment by abhiaks** [comment]
Hi Orion777,

Thank you for the info.

Managed to get that working and can see computers now in the room, which are added manually. Now having issues where in when trying to autopopulate computers from an AD OU the master room view is just blank, tried different options and list population tests are working fine. Is there any documentation links for the active directory usage.

Regards
Abhi

**Comment by tobydox** [comment]
Did you switch the network object directory to LDAP? Also follow the troubleshooting guide in the documentation at docs.veyon.io (use machine translated version).

**Comment by TheFireMind-Tech** [comment]
abhiaks  From my experience the one thing that tripped me up was that I had ldap fully configured but missed the option on first configuration screen (general tab) to enabled ldap backend. After that was switched everything started working.

**Comment by patdu59** [comment]
Hi all,
Is there a tutorial to use LDAP please ? If I got it right, with LDAP we won't have to add computers manually ? When we use Veyon, I'll have more than 120 PC to create in 5 different rooms...
Thanks

**Comment by tobydox** [comment]
Please see the machine-translated documentation at http://docs.veyon.io - it doesn't have a tutorial but a reference for all LDAP related configuration options. You should be able to get it running by setting and testing the options step by step.
