### ISSUE TITLE
Locking and login not working on Fedora 32

### ISSUE THREAD

**Issue by rdinse** [veyon/veyon#655]
I've set up the current Veyon release on 17 Fedora Linux boxes (version 32) using Xfce desktop environment and the Fedora 31 package. Everything is running fine, except the login and locking functions. 

When running the login function, the screen simply turns black for a second and then returns to the LightDM greeter.

When locking a PC, it appears as locked in Veyon Master and the mouse cursor gets moved to the top-left, but then one can still make keyboard and mouse inputs.

**Comment by Luckasas** [comment]
It also happens with Ubuntu/Lubuntu 18.04. Seems a wide linux problem.

**Comment by rfdparker** [comment]
I'm seeing the same behaviour on Ubuntu 20.04 LTS (`focal`).

Specifically:

- the lock function lock screen only prevents keyboard input, whereas mouse input still works and (despite being logged-in) the lock screen symbol described in [the document](https://docs.veyon.io/en/latest/user/features.html#lock-screens) is not shown
- the login function does not work and a preview of the login screen is not shown

What I did find, when checking the status of Veyon Service with `sudo systemctl status veyon.service`, was a message complaining that Veyon does not yet support Wayland and to use X.Org instead. This lead me to discover that while Ubuntu 20.04 LTS does not use Wayland by default after logged in, GDM (the login screen) does appear to use Wayland if it can (this was on a system with Intel graphics). After un-commenting `WaylandEnable=false` in `/etc/gdm3/custom.conf` and rebooting, the preview of the login screen worked however login did not work properly ‒ that is, it logged in different user than the one entered and a message "encountered an error"-type message was shown indicating a crash of `veyon-worker` (indeed Veyon Master couldn't show a preview of, or control, the session).

NB: it seems #665 may relate the same issue(s).
