### ISSUE TITLE
Error displayed on Linuxmint 18 veyon client screen when using "logout user" on Veyon master windows10

### ISSUE THREAD

**Issue by orion777** [veyon/veyon#66]
Hello

I have a new error now on the linuxmint veyon client screen when using the "logout user" option on Veyon master. The window error is : 
"recue error during disconnection - Could not get owner of name 'org.xfce.SessionManager' : no such name.
In the same time i also have the error in the terminal linuxmint client where veyon service is running 
"cannot find '.logout' in object /KSMServer at org.kde.ksmserver

Hope you will find the solution. Thanks you again for your work!

**Comment by tobydox** [comment]
Can you run ``xfce4-session-logout --logout`` manually and does it perform a logout?

Regarding KSM server message: you can ignore it. Veyon tries to send logout messages to session servers of various desktop environments (such as Gnome, KDE 4, KDE 5 etc.). If a certain session is not running you'll get this message but it won't hurt.

**Comment by orion777** [comment]
No the **xfce4-session-logout --logout** command doens't perform  logout. 
But it displays the same screen error message i mentionned with the logout user issue : "recue error during disconnection - Could not get owner of name 'org.xfce.SessionManager': no such name

**Comment by tobydox** [comment]
Then something with your Xfce session is wrong. The used command is exactly as officially documented (https://linux.die.net/man/1/xfce4-session-logout) so if it doesn't work it's not Veyon's fault ;-) Feel free to propose a better approach.

**Comment by tobydox** [comment]
If

    xfce4-session-logout --logout

doesn't work with your distribution please report a bug for that package at the bug tracker of your distribution. We can't fix this Mint-specific problem in Veyon, I'm sorry :-(
