### ISSUE TITLE
UltraVNC is now on GitHub

### ISSUE THREAD

**Issue by Neustradamus** [veyon/veyon#660]
There is not "issues" section in https://github.com/veyon/ultravnc, I create the ticket here.

There is now UltraVNC on GitHub:
- https://github.com/ultravnc/ultravnc

Offical dev:
- https://github.com/RudiDeVos

**Comment by Neustradamus** [comment]
@tobydox: Thanks for your changes!

It is hard to create directly a fork (and add issues section)?

Keep your branch in a local machine to integrate.

First, you must to rename the current https://github.com/veyon/ultravnc to https://github.com/veyon/ultravnc-archive (for example) and inform in the subject that there is a new place (which will be the fork from official code), and archive the old repository or remove it.

Second, create the new fork with official code.

Add the branch with your code.

It will be easy to update and create PR in the same time :)

**Comment by tobydox** [comment]
Thanks for your feedback! As proposed, the existing repository has been renamed to "ultravnc-old" and the new is now an official fork.

**Comment by Neustradamus** [comment]
@tobydox: Thanks, it is more easy to manage now for you :)

Can you change the subject of the old to inform that the code of the Veyon fork is now: https://github.com/veyon/ultravnc and archive this old repository?

Maybe you can add the "issues" section in your good fork.

People do not want to contact the main dev, if the request is for you ^^
