### ISSUE TITLE
Outlook / Exchange conflict?

### ISSUE THREAD

**Issue by RandomArker** [veyon/veyon#661]
Having a bit of a problem with Veyon Master.

When a member of staff has Veyon Master open - their Microsoft Outlook 2016, connecting to a local exchange server, seems to lose connection and fails to authenticate/validate the certificates.

The Master program is connected to one room of machines, with the master in the same room (we have just this room set up as a test).

This problem doesn't occur when the Veyon Master application is closed, but within a few minutes of opening things start to go wrong.

**Comment by RandomArker** [comment]
Further investigation reveals that multiple high resolution screens in the room seem to be consuming a lot of network bandwidth. In another lab with the same number of computers and all resolutions below 1080p (max1440x900) and the issue doesn't seem to occur.

**Comment by tobydox** [comment]
Have you found a solution meanwhile? I'm afraid there's nothing we can do Veyon side except for raising the thumbnail update interval in the Master configuration page.
