### ISSUE TITLE
Veyon 4.4.2: locking only partially working on Kubuntu 20.04

### ISSUE THREAD

**Issue by chalmasr** [veyon/veyon#665]
When we try to lock a student's computer, no padlock appears. However, the **keyboard is locked** but **the mouse is not.**
This happens with versions 4.4.2 for Ubuntu 20.04 downloaded as deb package from veyon.io or build from sources downloaded from the same site.
The problem is not specific to version 4.4.2 but was already encountered with older versions of Veyon and Kubuntu (but we can't tell in which exact version it appeared).
It's interesting to mention that this problem does not happen with the version 4.3.1 included in Ubuntu repositories, but this old version has other problems, so we would like to upgrade to a newer one, which is not possible as long as this locking problem exists.

**Comment by Luckasas** [comment]
It also happens with 18.04 Ubuntu/Lubuntu system

**Comment by chalmasr** [comment]
I'm pleased to confirm that the problem is fixed in version 4.99.0-569-g85d3946b, built from the sources.
Congratulations for this nice job!

**Comment by tobydox** [comment]
@chalmasr thanks for testing and giving feedback!

The issue has been fixed in the latest 4.5.0 release as well.
