### ISSUE TITLE
InternetAccessControl & proxy

### ISSUE THREAD

**Issue by ljoets** [veyon/veyon#667]
Hello,
I have successfully tested internet blocking on my test lab, on which clients do not use a proxy.
In production, my clients access the Internet via a proxy, and Internet blocking doesn't seem to work, neither in routing mode nor in firewall mode.
Is this a known problem?
Is it supposed to work anyway?
Thanks

**Comment by ljoets** [comment]
Pour compléter, n'y a-t-il pas un problème de guillemets dans le json généré ?

Routing mode :
![image](https://user-images.githubusercontent.com/11474581/95294207-29c67580-0875-11eb-885e-2d2c2ab7c2e7.png)

Firewall mode:
![image](https://user-images.githubusercontent.com/11474581/95294219-2fbc5680-0875-11eb-9d95-59022ac78c02.png)

**Comment by tobydox** [comment]
Thank you for your feedback! Blocking a proxy is not yet supported but will be in the next release. You can download a preview of the add-ons installer at https://github.com/veyon/addons/releases/download/v4.4.2/veyon-addons-4.4.2.12-win64-setup.exe with an updated InternetAccessControl add-on which includes support for blocking traffic to certain servers (using the firewall backend).

**Comment by ljoets** [comment]
It works fine with this addon, and actived firewall.
Is it possible to block proxy using routing ? (I'm not a network expert !)

**Comment by tobydox** [comment]
Yes I think you can also block the proxy using the routing backend, checking *Add custom route to block internet*, enter the proxy IP address as destination and enter an invalid gateway (e.g. ``127.0.0.1``).
