### ISSUE TITLE
Screenshots not listed

### ISSUE THREAD

**Issue by ljoets** [veyon/veyon#668]
Hello,
Screenshots do not immediately appear in the list on the left.
To view them, you need to close and then re-open Veyon-Master.
My users use roaming profiles (W10).
Is this the reason for the problem?
Thanks

**Comment by tobydox** [comment]
Do you have a special directory configured for screenshots or do you use the default values?

**Comment by ljoets** [comment]
I use default directory but appdata is in the roaming profile.

**Comment by tobydox** [comment]
The issue will be fixed in the next 4.5.1 release. In the meantime you can use the intermediate build at https://github.com/veyon/veyon/releases/download/v4.5.0/veyon-4.5.0.12-win64-setup.exe which already contains this fix.
