### ISSUE TITLE
Black wallpaper when monitoring clients

### ISSUE THREAD

**Issue by ljoets** [veyon/veyon#669]
When veyon-master is launched on the teacher computer, the monitored students lose their wallpaper and the background of their desktop becomes black (w10x64). Is this the normal behavior, or is there a setting to keep the client's wallpaper display?
Thanks

**Comment by tobydox** [comment]
This is not the default behaviour. I suspect you have/had UltraVNC installed and configured it to hide the desktop wallpaper on connection. Can you verify this? If so, search for a registry value named ``RemoveWallpaper`` and remove it.

**Comment by tobydox** [comment]
According to https://github.com/veyon/veyon/blob/master/plugins/vncserver/ultravnc-builtin/BuiltinUltraVncServer.cpp#L105 we even override the setting explicitely. It's still possible an orphan INI file or registry key is being read.

**Comment by ljoets** [comment]
Ok, it's because of a parameter when deploying TighVNC : "SET_REMOVEWALLPAPER" is enabled by default.
So Veyon is not involved :-)

**Comment by tobydox** [comment]
Thanks for responding!
