### ISSUE TITLE
Option "hide local computer in computer room management" doesn't work on Veyon master windows10

### ISSUE THREAD

**Issue by orion777** [veyon/veyon#67]
I checked this option in Veyon configurator but local master screen computer is always visible in the master interface.
I entered computer name and adress IP of the local computer in the local data.

**Comment by orion777** [comment]
Any news about this issue?

**Comment by TheFireMind-Tech** [comment]
Tested this as-well with windows 10 64-bit and the feature doesn't seem to be functioning.

**Comment by tobydox** [comment]
There has been a fix (62ec4e19c0f5cef72c899100274b79b84a392238) which will be part of Veyon 4.0 RC3 which should also fix this issue :-)

**Comment by tobydox** [comment]
Fixed in 3.99.7.
