### ISSUE TITLE
problems with windows 10: desperate teacher :(

### ISSUE THREAD

**Issue by alexia74** [veyon/veyon#671]
hi, I'm a teacher. And I need this system for my lab...
But it seems that there are some problems with windows 10 and the last release.
There is a problem of authentication.
I watched several videos on youtube with previous releases and windows 10 and they worked..... So I have to switch off every pc every time :/
we don't have any server in the school

CAN i HAVE THE PREVIOUS RELEASE?
please help me

**Comment by SlrG** [comment]
Older releases are available here: https://github.com/veyon/veyon/releases

**Comment by alexia74** [comment]
> Older releases are available here: https://github.com/veyon/veyon/releases

I understood  the problem.
I have to login on the master pc with the same account of clients...
i didn't do that.
so I solved... and it works :)

**Comment by SlrG** [comment]
Great, I'm glad you got it working. :) As it is solved, you should propably close the issue?

**Comment by alexia74** [comment]
I'd like to know... I don't remember to have read this in the documentation. I know that many people have problems with windows 10...
perhaps I can suggest to insert this detail in the documentation...

**Comment by tobydox** [comment]
It's been in the docs already (see hint https://docs.veyon.io/en/latest/admin/configuration.html#overview) but as suggested I also added it to the section on logon authentication at https://docs.veyon.io/en/latest/admin/configuration.html#authentication-methods - thank you very much for your feedback!
