### ISSUE TITLE
preview reimplementation needed and remoteaccess opening always on 0,0 (main screen)

### ISSUE THREAD

**Issue by SlrG** [veyon/veyon#678]
Situation:
On our dual monitor teacher stations the main screen is connected to a projector and is used by the teacher to show the lesson contents as a presentation or directly work on something with the students. The veyon master window is placed on the expanded desktop on the secondary screen, to see what the students are doing, if someone has trouble and lags behind or has a problem and needs help to correct it.

Veyon or Windows remembers Veyons position on the secondary screen and always reopens it there, when closed and reopened which is good.

On iTalc it was possible to hold the left mouse button on a thumbnail preview and the teacher would get a large preview window of the students screen. This preview would open on the position of the master, in our situation the secondary screen, without interfering with the presentation on the main display, so the other students can keep working, without their view being interrupted. The teacher could then describe verbally to the student, what needs to be done, to fix a problem. Releasing the mouse button closed the preview automatically.

Problem:
The remoteaccess function is close, but it has some drawbacks.
- It always opens on 0,0 on the main monitor and interrupts the view of all students. The teacher then has to move the window manually to the secondary screen, out of the view of the other students.
- After explaining the problem, which is sometimes extremely quick, the teacher has to manually close the remoteaccess window.
- The position is not remembered, so this process has to be repeated every time a student has a question and needs help. This can often be in very short order, which makes it quite tedious.

Proposed solution:
- Make the remoteaccess window always appear on the same position of the master window and/or remember the position it was moved to and reopen there.
- Reimplement the quick preview when holding/releasing the left mouse button on a thumbnail preview.

Difficulties regarding quick preview:
In manual order mode, the thumbnail previews are draggable when holding the left mouse. This could be changed to require the ctrl key to be pressed in addition to holding the left mouse button when dragging. So holding only could still open a quick preview without interfering with the reordering functionality.

**Comment by SlrG** [comment]
@tobydox 
Could you maybe give me a hint on how to get an pointer to the masters main window, so I can get the position of the master window and use its top left corner as base for the remote access windows position?

It would then be possible to add an option to open the remote access window on the position of the master (e.g. secondary screen) if desired.

A quick way could be to read the position from the configuration which contains the stored master position, but this is probably not very elegant.

**Comment by tobydox** [comment]
You can retrieve the pointer to the Veyon Master window in plugins via

``` c++
auto master = VeyonCore::instance()->findChild<VeyonMasterInterface *>();
if( master )
{
    const auto windowPos = master->mainWindow()->pos();
    const auto screen = master->mainWindow()->screen();
}
```

For the remote access widget you'll likely have to call `widget->window()->setScreen(...)`.

**Comment by SlrG** [comment]
I made a bit of progress #687 and would like your input on how to name the new option and tooltip and where to place it.

At the moment it looks like this: 
![RAonMasterOption](https://user-images.githubusercontent.com/978967/99889394-f12c0100-2c54-11eb-9c00-8fa5a194bbbc.png)
The tooltip is:
Else it will open on the main screen always

Please tell me if you disagree with the translation or the placement and I'll change it.

**Comment by SlrG** [comment]
@tobydox 
Continuing the work mentioned above (please have a look and also comment on that):

I extended the remoteaccess plugin with a preview feature and the master with a left mouse press and hold detection. If the feature is assigned to the left press and hold in the configurator, the preview window opens (or other selected feature gets executed).

What I am missing to submit another pull request, is it automatically closing when the mouse button is released. A signal should already be emitted. I'm having trouble to connect to it from the plugin. Please see my previewwindow branch [here](https://github.com/veyon/veyon/compare/master...SlrG:previewwindow).

The whitespace is not yet fixed (working with QtCreator in stock settings, creates other whitespace as you have in your project). 
My problems are in the file plugins/remoteaccess/RemoteAccessWidget.cpp line 39 and 284, 285 where I try to connect back to the new signal from the ComputerMonitoringWidget. Sadly it does not work and I get a linker error.

`/home/michael/Devel/veyon/plugins/remoteaccess/RemoteAccessWidget.cpp:285: undefined reference to ComputerMonitoringWidget::mousePressAndHoldRelease()
collect2: error: ld returned 1 exit status`

Maybe you can put me on the right track? Thank you very much for your help!

**Comment by tobydox** [comment]
Thank you very much for your input and proposals. It looks like you're making good progress and managed to dive into the code base of Veyon successfully ;-) While I like the new option for configuring the placement of the remote access window, I think the approach for the mouse press-and-hold feature is not optimal for two reasons: first it almost duplicates what we have with the new spotlight feature already (which can be used easily via middle click). Secondly – and that's the reason for your linker error – it introduces a dependency of a plugin on the Veyon Master binary which is bad from an architectural point of view. So instead of adding new complexity I'd suggest to improve the spotlight feature. There could be an option (e.g. next to the "Realtime update" button) to open the panel/splitter automatically when adding computers to it via middle click and closing it automatically as soon as all computers have been removed from it. Another big advantage: it does not introduce the establishment of a new connection (which always is connected with some delays and potential notifications client-side) but shows everything in realtime instantly.

**Comment by SlrG** [comment]
Thank you for responding. I'll have a look at the spotlight feature. What I have seen of it until know makes it seem very different.

I'm glad you like the new placement option. :+1: I'll provide a rebased pull request for it, so you can pull it in without conflicts. Though I'm still debating with myself if the wording of the tooltip can be improved.

**Comment by SlrG** [comment]
Had a deeper look into the spotlight feature. I can see it's merits and that it will be useful for some people but if I'm not doing something completely wrong, it is not what I and the other teachers on my school want and had in iTalc. 

We are doing a lot of "Office" things with our students and especially in Excel/LO Calc it is crucial to get a full screen preview, so the teacher can read the formula, a student is working on and help to fix it. Having the spotlight panel/splitter open, will always reduce the screen size available for the students screens below, while still never providing a real full screen preview. Buying larger resolution screens for the teacher is not really an option as we have no budget of our own.

You are right that it can be improved by automatically opening/closing the panel on double click/when the last computer is removed and I would be willing to try and help you work on that, if you would like. 

But I still think we need the fullscreen preview back. Having it react on press and hold is much easier than to having to right click and move down to open remote view I think. If you find it redundant to have a third feature for the remote access plugin, this is understandable however I wanted to hide the toolbar button for the preview and thought this would be the cleanest way to do that. The feature can be removed however and the admin would need to assign the remote view to the left press if needed.

They delay for the new connection is a problem I can't prevent. It is the same as opening remote view or remote control however. So if users find the delay disturbing, and don't need a fullscreen view, they can indeed use the spotlight instead. This does not invalidate the options in my opinion however.

So there are three questions:

**Question 1:**
Is the left press and hold itself a thing you don't want to merge? (The admin can assign whatever feature is needed to it, so it can still be useful even if it doesn't open a preview.) If it is, this will kill the whole feature.

**Question 2:**
Is the preview feature itself a thing you don't want to merge? (Does it really hurt to have it there? It is hidden from the main menu and context menu.) If it is, I will remove it.

**Question 3:**
It should be possible to close the preview from the master directly without having the preview waiting for the signal from the master and closing itself. That should prevent the backwards dependency. Would it be acceptable if I got it working that way?

**Comment by SlrG** [comment]
I found a way to detect and close the correct window by checking the window title. Already open view or control windows are left untouched. Only the newly opened preview window is closed, when the left press is released.

If this is acceptable I could change the preview features title from remote access to remote preview. At the moment it checks for the name of the currently selected computer which works, but is maybe not fully fail safe.

**Comment by tobydox** [comment]
Regarding your questions: it's not a feature which I don't want to merge in general :-) It's the rather complex approach which I'm not completely convinced of. IMHO this should be an integrated lightweight feature of the Master application only without touching plugins and without adding configuration options. Instead the `ComputerMonitoringWidget` class should directly create and destroy e.g. a `ComputerZoomWidget` (a lightweight version of `RemoteAccessWidget` living in `master/src/`) instances. Once finished, we should verify the usability so the press-and-hold mechanism does not conflict with the workflow to rearrange computers. If it works fine there should be no need for involving modifiers (such as ctrl) which wouldn't be very user-friendly either. What do you think about the implementation proposal?

**Comment by SlrG** [comment]
Sounds fine for me. The problem is, if I'll be able to do this. :) Changing how existing plugins work, is probably easier than this new approach. But I'll look into it. Sadly my free time to work on this will soon decline due to work circumstances.

Regarding the press and hold, it works without a modifier and should not conflict with rearrangement or selection functionality already. I tried to test all scenarios I could think of and in my tests it worked without problems. (On linux mint - Without a windows build I can't test it there, but because of qt it should too in theory).

**Comment by tobydox** [comment]
It shouldn't be more complicated than what you did already ;-) Basically just strip down `RemoteAccessWidget` or look at the `DemoClient` class and create/destroy it the way you would trigger the existing feature start/stop.

**Comment by SlrG** [comment]
Okay. My new take on this is #698 . I hope I was able to implement it as requested.
