### ISSUE TITLE
option to choose the position of the user and pc name on the thumbnail previews

### ISSUE THREAD

**Issue by SlrG** [veyon/veyon#679]
Maybe not really necessary, but nice to have, would be an option to choose the position of the user and pc name on the thumbnail previews. On iTalc it was above the previews, on Veyon it is below. At the moment the pc name is displayed in the remoteaccess windows title (which is above the screen content) it would be nice if it could be displayed above the thumbnails, too.

Also it would be nice if the user name would be displayed in the window title, too.

**Comment by tobydox** [comment]
I think it's good practice to show labels below icons in general, no matter whether tool buttons, file browsers in icon view mode or thumbnails in Veyon. We should therefore keep the current mode, also since QListView only supports displaying labels below icons ;-)
