### ISSUE TITLE
Good news!!

### ISSUE THREAD

**Issue by jamj2000** [veyon/veyon#68]
Hello everyone,

I've been testing veyon in several linux distros.

There are 2 issues  ( #14 and #56 ) that happen in systems with Qt libs < 5.7.1  (Ubuntu < 17.04 and LinuxMint 18). Maybe Qt libs has some bug that affects some widgets' display.

It works fine (issues #14 and #56 don't appear) in distros with **Qt libs >= 5.7.1** (**Ubuntu >= 17.04 and Debian 9**) .

**Comment by tobydox** [comment]
Do you use the latest version from Git? If so, it should work properly with Qt 5.5. If not, which specific issues still do not work?

**Comment by orion777** [comment]
I can confirm that issues #14 and #56 were resolved with latest version from Git. I have tested on Linuxmint18 and it works like a charm now. 
Just download the latest version, compil the sources and you will have the Veyon installation updated and working fine.

**Comment by tobydox** [comment]
Ok perfect - thank you very much for all your testing efforts! :+1:

**Comment by jamj2000** [comment]
OK, I'll continue testing.  Thanks !!
