### ISSUE TITLE
veyon-master: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by herumasadi** [veyon/veyon#680]
i installed veyon smoothly.
Then I tried running veyon by clicking the icon but it didn't work. so I run through the terminal and the following error code comes out.

`veyon-master: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory`

what can i do so that veyon can run on my device. I'm using MX Linux

**Comment by SlrG** [comment]
Google says: https://www.linuxquestions.org/questions/antix-mx-linux-127/error-loading-libjpeg-so-8-for-a-game-4175681095/

**Comment by tobydox** [comment]
@SlrG  thanks - yes probably a package with libjpeg.so.8 is missing. Alternatively try rebuilding Veyon from source so it links against the correct libraries available in your distribution.

**Comment by herumasadi** [comment]
I'm sorry, I just found out that MX Linux uses base debian 10 (Debian Buster). This problem was resolved after I updated & upgraded the system and downloaded the veyon buster version.

Thank you for the response.
Regards
