### ISSUE TITLE
Mass Logon not working?

### ISSUE THREAD

**Issue by RustyAlgorithm** [veyon/veyon#683]
The mass log on feature fails to even enter the credentials in to our machines we have a user agreement screen before the user enters their credentials (Win10)I was wondering if this is the reason?

**Comment by tobydox** [comment]
Yes this is likely the reason. If you have a legal message configured, you can configure Veyon to close this message before logging on. Open Veyon Configurator, switch to advanced view via the menu, go to the *Windows* tab and enable the *Confirm legal notice (message displayed before user logs in)* option. Afterwards save the configuration and deploy it to your clients.
