### ISSUE TITLE
Question about security

### ISSUE THREAD

**Issue by ysalmon** [veyon/veyon#684]
Hi,
we have been using Veyon in computer labs running Linux and authentication is done with LDAP, restricting the use of Veyon to members of the "Teachers" group.
Now a colleague is reporting that one student experienced text appearing for no explainable reason in his (python) console.
I am investigating on that. A possible cause would be a malicious use of Veyon remote control capabilities.

It might be the case that somebody got access to a teacher's LDAP credentials. I will be looking into the logs for suspicious ldap solicitations.

My question is about clarifying the points about (ldap) authentication in the docs. A prompt appears when opening Veyon master.
However, how is the connection between the monitored machines and the master machine secured ?
Is it possible for somebody with LAN access to, without using Veyon master, interfere with the veyon service on the monitored machines ?

**Comment by tobydox** [comment]
Even though most of the traffic is unencrypted, all kind of credentials are always exchanged encrypted (via one-time RSA keys), so it's unlikely someone stole the credentials via Veyon connections unless someone successfully performed a man-in-the-middle attack via ARP spoofing or similar to intercept the complete traffic including the key exchange.
