### ISSUE TITLE
Installing on Raspberry Pi OS (Buster)

### ISSUE THREAD

**Issue by jonwitts** [veyon/veyon#686]
Hi all,

I am trying to get the latest version of Veyon installed on my Raspberry Pi to test classroom management of my RPi computers running on our PiServer implementation. I first tried to install the stock Veyon package from Debian but that appeared broken and I didn't have access to the veyon-cli program after installing so removed it.

I have added the PPA to my Raspberry Pi by adding the following to my sources.list:
    deb http://ppa.launchpad.net/veyon/stable/ubuntu bionic main
and then imported the PPA signing key with:
   apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 4B776B9B1C1938F18C023C8C49ABD150D5D0DCC6

After an apt-update I am then able to install the latest version of Veyon - however I get a package dependency error when trying...
#apt install veyon
....
Some packages could not be installed...

The following packages have unmet dependencies:
veyon: Depends: libprocps6 but it is not installable

An apt-search libprocps returns the libprocps7 is available but not 6...

How do I get the latest version of Veyon installed on a Raspberry Pi?

**Comment by tobydox** [comment]
Indeed Ubuntu Bionic and Debian Buster seem to be incompatible in regards to certain libraries :-( I guess you'll have to build the binary packages on your own. See https://github.com/veyon/veyon#veyon-on-linux for instructions (install dependencies, run cmake and run "make package" which will produce a DEB file).
