### ISSUE TITLE
So I'd like to know about Android Version

### ISSUE THREAD

**Issue by henrycoding** [veyon/veyon#694]
I found that one issuse methon the android version,
and I think it's a very good idea to support android and VR teching in veyon, it's very fantastic!

So I'd like to know when will the android version be release, or can we participate in the development of android version?

Best wishes !

**Comment by tobydox** [comment]
Thanks for your question! It's planned to release Veyon 5 with a very basic android version later this year.

**Comment by tylla** [comment]
Are there any news on this?
