### ISSUE TITLE
(on RDP-Session) Veyon-Server.exe closes when RDP is minimized

### ISSUE THREAD

**Issue by RealFilmKuh** [veyon/veyon#699]
Hello everyone,

we have a problem with Veyon and RDP-Sessions. When the RDP-Session is minimized by User on a Client-PC, then 
the veyon-server.exe is closed on the Client-PC so that the lecturer cannot see anything on the Veyon-Master/ User cant see no longer a demo. The veyon-service is no longer runs on the Client-PC.

The User can start the service again with veyon-server.exe, and everything works again (until RDP-Session is minimized again).

Our Settings are:
- all of the PC's runs Veyon Version 4.5.1.0
- Multi session mode
- built in VNC Server (Ultra VNC)
  - Enable Desktop Duplication Engine on Windows 8 and newer (is on)

If we turn "Enable Desktop Duplication Engine on Windows 8 and newer" off, then Veyon-Service is not closed on Client-PC (RDP-Session), but everything is very slowly.

Does anyone know a solution for this bug/ error?

thx

**Comment by tobydox** [comment]
It might be related to https://support.smartbear.com/testcomplete/docs/testing-with/running/via-rdp/in-minimized-window.html so can you try the proposed solution?

**Comment by RealFilmKuh** [comment]
The behavior of the UltraVNC has changed from Veyon version 4.3.4 to Veyon version 4.5.1, so that with Veyon 4.5.1 access from the master to the Veyon client is completely terminated, with Veyon version 4.3.4 it was maintained.

Your solution helped, thanks!

**Comment by tobydox** [comment]
Thank you for the feedback! Also don't forget to update to 4.5.2 for even better Windows 10 compatibility.
