### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by jamj2000** [veyon/veyon#7]
Hello Tobias,

what's the way you are intend to translate veyon to other languages?

In **core/resources**, there are 2 files :    

* _lang_.ts  (e.g.  es.ts :es:)
* veyon.ts

Do you use transifex? How is it works?
Or, 
can it be translate in the old way, with Qt Linguist?

Thanks for your time.
Great work! :clap:

**Comment by tobydox** [comment]
Hi,

yes we use Transifex for easy translation, see https://github.com/veyon/veyon/wiki/Creating-or-improving-translations for some basic information.

In case you're familiar with Qt Linguist you can also run "make es.ts" in a build tree and edit the updated file es.ts in core/resources. You can then commit and send a PR. At the same time please register at Transifex so you can update the according resources for your language.

Toby
