### ISSUE TITLE
veyon configurators advanced view of service configuration page too big for small screen resolutions

### ISSUE THREAD

**Issue by SlrG** [veyon/veyon#700]
I have a screen resolution of 1366x768 on my development system. I know this is extremely small. When using veyon-configurator and enabling the advanced view of the service configuration page the reset and apply button vanish behind the taskbar.

Using tab and and enter or moving the taskbar still helps to apply the changed settings, but I still wanted to report the problem. Maybe it can be solved by adding a scrollbar if the window gets to big for the screens resolution.

**Comment by GitHub-ITGuy** [comment]
I use a smallish Lenovo laptop with the same resolution and have not experienced this issue.  Is it possible you could have some kind of screen or window magnification/scaling enabled?

**Comment by SlrG** [comment]
Yes, I'm sure. :) Can you recheck if you tried with enabled advanced view and the service configuration page? All three conditions (resolution, mode and page) have to be met, for the issue to surface.

**Comment by GitHub-ITGuy** [comment]
![GitHub01](https://user-images.githubusercontent.com/76734341/103303751-cca21200-49d4-11eb-802d-f05b6497b2cc.png)

![GitHub02](https://user-images.githubusercontent.com/76734341/103303766-d7f53d80-49d4-11eb-80bb-9bfbc0600574.png)

**Comment by SlrG** [comment]
I see. So on windows it works. I have an ubuntu system with mostly stock settings and there it does not. So it might be an ubuntu specific problem on low resolution systems. 
![Bildschirmfoto vom 2020-12-29 19-02-54](https://user-images.githubusercontent.com/978967/103304426-e9583d00-4a08-11eb-9038-bfbee5384695.png)

**Comment by GitHub-ITGuy** [comment]
Apologies, I had assumed you were using Windows.

**Comment by SlrG** [comment]
No problem. You wanted to help, that's all that matters. My description of the problem was obviously lacking which OS I'm using, as we see now it is  an important information in this case.

**Comment by tobydox** [comment]
It's not OS related - once you select a VNC server you'll notice the VNC server settings will be missing at the bottom. So we indeed need to embed configuration pages into a `QScrollArea`.

**Comment by GitHub-ITGuy** [comment]
Maximizing the window is workable in Windows 10.

![GitHub04](https://user-images.githubusercontent.com/76734341/103347736-d2940380-4a65-11eb-800a-1cc06fcd35a3.png)
