### ISSUE TITLE
Feature Request (WebAPI): Fetch status of all features in one call

### ISSUE THREAD

**Issue by SamuelYaron** [veyon/veyon#703]
You can query the status of a feature by calling **GET** */api/v1/feature/<FEATURE-UID>*.

If you are interested in the status of all features that means a lot of queries. It would be great if you could provide an endpoint to query the status of all features.
Maybe it could be integrated in **GET** */api/v1/feature - Get available features*?

**Comment by tobydox** [comment]
The integration into the existing `GET /api/v1/feature` API call should not be a problem and thus be part of the 4.5.3 release.

**Comment by tobydox** [comment]
Implemented in 4.5.3.
