### ISSUE TITLE
hide the veyon icon

### ISSUE THREAD

**Issue by Eliasssaber** [veyon/veyon#704]
Hello, I want to hide the "**veyron**" icon in the taskbar (in users' computers).

Help me @tobydox 
Thank you.

**Comment by SlrG** [comment]
Google "veyon hide tray icon" click first [link](https://docs.veyon.io/en/latest/admin/reference.html), search hide or click [here](https://docs.veyon.io/en/latest/admin/reference.html#refservicegeneral). Start veyon-configurator, click view and enable advanced. Go to the service tab and enable hide tray icon. Done.

**Comment by Eliasssaber** [comment]
Good answer. @SlrG 
thank you so much.
