### ISSUE TITLE
Tree view for places/pc menu

### ISSUE THREAD

**Issue by wall1y** [veyon/veyon#705]
Hello. Sorry for my poor english. Can we get a tree view for nestesd room like an OU view in Active Directory?
Now it is just list of OU.  Where parent and child OU are mixed and parent OU include all cumputers from its childrens OU.
Or maybe I misconfigured something?

**Comment by tobydox** [comment]
This is supported by the commercial LDAP Pro add-on ;-) Contact us via sales@veyon.io to get a demo license for it.

**Comment by wall1y** [comment]
> This is supported by the commercial LDAP Pro add-on ;-) Contact us via [sales@veyon.io](mailto:sales@veyon.io) to get a demo license for it.
Oh, I see. Thanks.

**Comment by tobydox** [comment]
You're welcome :-)
