### ISSUE TITLE
problems with login (of the pc of students)

### ISSUE THREAD

**Issue by alexia74** [veyon/veyon#709]
hi, I'm using veyon and it make easyer life in my lab 
I've still a problem.
I have got 27 pc and all works: for example shut down or share a link or file.
But I can't log in the 27 pc. It can be very usefull for me because I teach to young children... so they sometimes cannot digit the password :D
It says password is not correct... but it is the same of my system. it is correct.

how can I solve?
it can be useful also to switch on the pc... but  how can it works if the pc is off (there is not energy)?

thanks

**Comment by SlrG** [comment]
If you correctly setup [authentication](https://docs.veyon.io/en/latest/admin/configuration.html#authentication) you should be able to  remotecontrol a single system and log it in from the teacher system. You could even log in all systems simultaneously if the password is the same on all systems. Please read the manual on how to setup it all.

Starting the systems will obviously not work, if the power is completely switched of as you already noted. Most systems today support a "powered" down state, where the ethernet adapter is left running. This is used by veyon to start the systems using something called Wake On Lan. (The BIOS of your systems needs to support this. Most probably do today.) Please research a bit online on how to set ip up and the veyon manual on how to use it in class.

**Comment by alexia74** [comment]
Hi, I can do anything... remote control, send link and file, do presentations and so on. I tested before to use it.
But I have a problem with login to the pc.

**"You could even log in all systems simultaneously if the password is the same on all systems"**
yes, I know... but I'm writing here because it doesn't work for me.

There is the button login to all pc. I want to put the password to all... 
I see that the system put the password to the pc... but it says is not correct (on their pc). But it is.
It is the same password.

There are problems in the input? there are letters and numbers... 
I use logon authentication not Public-Key-Cryptography,

the other one is not a big problem... i was courious. Luckly the children can switch off... but it could be useful to login.




> If you correctly setup [authentication](https://docs.veyon.io/en/latest/admin/configuration.html#authentication) you should be able to remotecontrol a single system and log it in from the teacher system. You could even log in all systems simultaneously if the password is the same on all systems. Please read the manual on how to setup it all.
> 
> Starting the systems will obviously not work, if the power is completely switched of as you already noted. Most systems today support a "powered" down state, where the ethernet adapter is left running. This is used by veyon to start the systems using something called Wake On Lan. (The BIOS of your systems needs to support this. Most probably do today.) Please research a bit online on how to set ip up and the veyon manual on how to use it in class.

**Comment by alexia74** [comment]
perhaps I have to add a rules on the pcs?

"The rules can be configured through the Veyon Configurator on the configuration page Access control in section Access control rules. The rules list is empty by default. In this case, all access attempts are denied since there is no rule that explicitly allows access. This means that at least one rule must be defined that allows access under certain conditions."

it is strange, because I can manage all... but not login.

**Comment by SlrG** [comment]
I'm sorry I misunderstood your first question. I should have read it more carefully.

What is the language you are speaking/the computers are setup to use? What happens if you remote control a student pc, open a text editing program and type the password into it through the remote control from your teacher pc? Does it get displayed correctly? I'm guessing there is maybe a special char, that is not correctly transferred and might cause the problem.

I don't think access rules would be able to improve the situation if don't have them setup yet. I think it should work without them, first.

**Comment by alexia74** [comment]
no problem :)
language: italian
the password is composed by a name (caps lock on the first letter) and 4 numbers
there are not special characters.
I tried to write it on a text and it was correct. 
it can be the caps lock... of the first letter, but it is a simple password...
I can try to change the password on a pc...  to test what happens.







> I'm sorry I misunderstood your first question. I should have read it more carefully.
> 
> What is the language you are speaking/the computers are setup to use? What happens if you remote control a student pc, open a text editing program and type the password into it through the remote control from your teacher pc? Does it get displayed correctly? I'm guessing there is maybe a special char, that is not correctly transferred and might cause the problem.
> 
> I don't think access rules would be able to improve the situation if you don't have them setup yet. I think it should work without them, first.

**Comment by alexia74** [comment]
I think it is the only thing that doesn't work :D
but it would be great if it works... as they are 27 pc and I work with very young children (6 years old), that cannot digit the password :)

**Comment by tobydox** [comment]
Are you trying to use the "Login user" feature? If so, please make sure the Windows login settings are configured correctly, see https://docs.veyon.io/en/latest/admin/platform-notes.html#user-login for details.

**Comment by alexia74** [comment]
> Are you trying to use the "Login user" feature? If so, please make sure the Windows login settings are configured correctly, see https://docs.veyon.io/en/latest/admin/platform-notes.html#user-login for details.

hi tobias
yes, i use login user.
I try to login to all pc but it says password incorrect on all pcs (I whatch them on my screen).
this is the only problem I have at the moment (solved the previous).
It would be comfortable as I teacth to 16-20 little children of 6 that cannod digit the password :dagger: 

This:
"in general when using the user log in feature make sure to enable the Interactive logon: Do not display last user name group policy."
has to be done on veyon configurator?
thanks

**Comment by SlrG** [comment]
@alexia74 
No, this is not a veyon, but an windows setting. If you look in the veyon manual topic which is linke above, there are two links that describe how to use a group policy to do this. If it works afterwards, perfect.

If not, please note, that someone reports problems and a solution [here](https://social.technet.microsoft.com/Forums/windows/en-US/d475aea0-aa3b-4013-b4f3-015b2f3d8455/windows-10-education-1903-clear-last-logged-in-user-bug?forum=win10itprosetup#a020f903-b1b4-4cce-afa0-25aef23974a4). His link to the newer admx templates is broken, so [here](https://www.microsoft.com/en-US/download/details.aspx?id=58495) is a working one.

**Comment by GitHub-ITGuy** [comment]
Not using Configurator, this settings change would be done through Windows group policy at the student computers.

Log in at a student computer, open a command prompt with admin level access (search CMD, right-click Command Prompt to ‘Run as administrator’) then enter GPEDIT.MSC to start the Local Group Policy Editor.

Under **Computer Configuration** expand **Windows Settings** \ **Security Settings** \ **Local Policies** then click **Security Options**.  Scroll through the list of policies on the right until you come to

**Interactive logon: Don’t display last signed-in**

Double click this policy, select Enabled then click OK.

When the computer is restarted the lock screen will appear.  Press the Spacebar or Enter to clear the lock screen and display the logon screen.

The logon screen should now show two blank input fields, User name and Password.

Try again from Veyon Master to log in to that computer, if successful repeat this policy settings change at each of the remaining student computers.

**Comment by alexia74** [comment]
thanks, yes I search on the net, then.. I saw it was windows configuration.
I didn't remembrer this... perhaps because at home I use linux :dagger: 
oh... so I have to set this on the 27 pcs  :/
I'll try on one pc and then the other if it works.

I'll try when I'll go to the lab for maintanance.
thanks very much.





> Not using Configurator, this settings change would be done through Windows group policy at the student computers.
> 
> Log in at a student computer, open a command prompt with admin level access (search CMD, right-click Command Prompt to ‘Run as administrator’) then enter GPEDIT.MSC to start the Local Group Policy Editor.
> 
> Under **Computer Configuration** expand **Windows Settings** \ **Security Settings** \ **Local Policies** then click **Security Options**. Scroll through the list of policies on the right until you come to
> 
> **Interactive logon: Don’t display last signed-in**
> 
> Double click this policy, select Enabled then click OK.
> 
> When the computer is restarted the lock screen will appear. Press the Spacebar or Enter to clear the lock screen and display the logon screen.
> 
> The logon screen should now show two blank input fields, User name and Password.
> 
> Try again from Veyon Master to log in to that computer, if successful repeat this policy settings change at each of the remaining student computers.

**Comment by SlrG** [comment]
@alexia74 
It depends how your lab is setup. If each pc is an individual installation, then yes, you will have to do it on each of them if it works on the first one. 

If the PCs are part of an active directory you might be able to deploy the gpo from the server. Or if the PCs are synced using some kind of imaging and deployment software it might be enough to change the template pc and replicate it to the others.

**Comment by alexia74** [comment]
unfortunately there is not a server....




> @alexia74
> It depends how your lab is setup. If each pc is an individual installation, then yes, you will have to do it on each of them if it works on the first one.
> 
> If the PCs are part of an active directory you might be able to deploy the gpo from the server. Or if the PCs are synced using some kind of imaging and deployment software it might be enough to change the template pc and replicate it to the others.

**Comment by SlrG** [comment]
Then sadly it's a manual process. 

@tobydox: Maybe sometime in the future it will be possible to use veyon to remote control (identical) PCs simultaneously. That way it would be possible to manipulate all of them at once from the teacher station. Would be an nice feature request if it is not one already.

**Comment by alexia74** [comment]
i tried this morning
it doesn't work. 

I look only one input

So have I to install the admx template?



> @alexia74
> No, this is not a veyon, but a windows setting. If you look in the veyon manual topic which is linke above, there are two links that describe how to use a group policy to do this. If it works afterwards, perfect.
> 
> If not, please note, that someone reports problems and a solution [here](https://social.technet.microsoft.com/Forums/windows/en-US/d475aea0-aa3b-4013-b4f3-015b2f3d8455/windows-10-education-1903-clear-last-logged-in-user-bug?forum=win10itprosetup#a020f903-b1b4-4cce-afa0-25aef23974a4). His link to the newer admx templates is broken, so [here](https://www.microsoft.com/en-US/download/details.aspx?id=58495) is a working one.

**Comment by GitHub-ITGuy** [comment]
That particular step is necessary but may not be the entire solution.

ADMX files cannot be used since your computers are not part of a domain.  In the second case ADMX files are Windows version specific and use, if not correctly version matched, may lead to undesired results.

Open Veyon Configurator in Advanced view, select the Windows category and confirm in the General section that ‘Enable SAS generation by software (Ctrl-Alt-Del)’ is checkmarked.  That option may or may not need to be checkmarked.  Try a remote login to the student computer after applying this setting both checked and unchecked.

Another possibility is that your logons are not using local computer accounts but instead use Microsoft specific web accounts.  I have no specific solution for that particular circumstance.

There is a third possibility, a second group policy which applies specifically to non-domain computers that may interfere with the “Don’t display last signed-in” policy; “Sign-in and lock last interactive user automatically after a restart” may need to be disabled.

GPEDIT.MSC

Computer Configuration / Administrative Templates / Windows Components / Windows Logon Options

The need to disable this second policy is determined by whether the Windows Logon screen shows the ‘Other user’ (Altro utente) account name above the User name input field.  What text is displayed directly above the User name field?

A fourth possibility is that your computers are configured for passwordless sign-ins such as using Windows Hello Face or a PIN.

**Comment by alexia74** [comment]
Another possibility is that your logons are not using local computer accounts but instead use Microsoft specific web accounts. I have no specific solution for that particular circumstance.
**---> no, there are not microsoft accounts on them. I'm pretty sure. They had to have outlook accounts.**

A fourth possibility is that your computers are configured for passwordless sign-ins such as using Windows Hello Face or a PIN.
**--> no pin no passwordless. I said there is user and password before ;) When I log in it says it is not correct.**

anyone has configured other policies.
I configured all the net because the last teacher did't do a lot on it
But I'll check next week.

to see altro utente (other user), I have to click on altro utente...

I have user and password... and stop.
(there are 2 account on the pcs, but they are both administrator)

**Comment by GitHub-ITGuy** [comment]
> to see altro utente (other user), I have to click on altro utente...
> 

I see altro utente without clicking altro utente.

Criteri Computer locale -> Configurazione computer -> Impostazioni di Windows -> Impostazioni sicurezza -> Criteri locali -> Opzioni di sicurezza

Double-click;

Accesso interattivo: non visualizzare l'ultimo nome utente

or

Accesso interattivo: Non visualizzare l'ultimo accesso

(Prima di Windows 10 versione 1703, questa impostazione di criterio è denominata 
accesso interattivo: non visualizzare l'ultimo nome utente.)

Choose Attivato then OK, restart the computer.

![GitHub_Altro_01](https://user-images.githubusercontent.com/76734341/106491717-25a60f80-6485-11eb-900c-cc74cc4605e6.png)

**Comment by alexia74** [comment]
i'll try today at school.
I did it from cmd. 

I'lll try also in this way.
I'll let you know :dagger: 


> > to see altro utente (other user), I have to click on altro utente...
> 
> I see altro utente without clicking altro utente.
> 
> Criteri Computer locale -> Configurazione computer -> Impostazioni di Windows -> Impostazioni sicurezza -> Criteri locali -> Opzioni di sicurezza
> 
> Double-click;
> 
> Accesso interattivo: non visualizzare l'ultimo nome utente
> 
> or
> 
> Accesso interattivo: Non visualizzare l'ultimo accesso
> 
> (Prima di Windows 10 versione 1703, questa impostazione di criterio è denominata
> accesso interattivo: non visualizzare l'ultimo nome utente.)
> 
> Choose Attivato then OK, restart the computer.
> 
> ![GitHub_Altro_01](https://user-images.githubusercontent.com/76734341/106491717-25a60f80-6485-11eb-900c-cc74cc4605e6.png)

**Comment by Mitko939** [comment]
> > to see altro utente (other user), I have to click on altro utente...
> 
> I see altro utente without clicking altro utente.
> 
> Criteri Computer locale -> Configurazione computer -> Impostazioni di Windows -> Impostazioni sicurezza -> Criteri locali -> Opzioni di sicurezza
> 
> Double-click;
> 
> Accesso interattivo: non visualizzare l'ultimo nome utente
> 
> or
> 
> Accesso interattivo: Non visualizzare l'ultimo accesso
> 
> (Prima di Windows 10 versione 1703, questa impostazione di criterio è denominata
> accesso interattivo: non visualizzare l'ultimo nome utente.)
> 
> Choose Attivato then OK, restart the computer.
> 
> ![GitHub_Altro_01](https://user-images.githubusercontent.com/76734341/106491717-25a60f80-6485-11eb-900c-cc74cc4605e6.png)

I had the same problem as alexia74 and solved as GitHub-ITGuy said. Nice work (Y)

**Comment by csnnan** [comment]
Type password both in user and pass, it work!!
