### ISSUE TITLE
Local computer never hides with RC3

### ISSUE THREAD

**Issue by patdu59** [veyon/veyon#71]
Hi,
I'm trying the new release but I'm facing a problem/bug that I didn't have before.
Even if I want the local computer to hide, it is visible in Veyon Master (see the screenshots)
![veyon 1](https://user-images.githubusercontent.com/30406004/28716013-32fd6bd0-739b-11e7-8555-25f0f25b52a1.jpg)
![veyon 2](https://user-images.githubusercontent.com/30406004/28716021-3b78359c-739b-11e7-991e-b56489da9cc2.jpg)

Concerning the release, the auto size is just great !
Just to be sure : with the option "enforce selected mode for client computers", for example if I lock a PC, whatever a student does, his computer will always be locked, even if he tries to restart his PC ?

Thanks :-)

**Comment by tobydox** [comment]
What did hostname(s) did you enter in local data page? If you use IP addresses here Veyon won't hide the computer as it excludes hosts by name.

**Comment by patdu59** [comment]
Hi,
I didn't change anything (compared to RC2)
I just updated Veyon and now the local PC is not hidden anymore (while it was in RC2)
In local data page, I put PORTABLE / 192.168.0.18

**Comment by tobydox** [comment]
Please use PORTABLE as host name instead of the IP address. RC3 matches the host address against localhost name instead of the display name column ;-)

**Comment by patdu59** [comment]
Here are the two situations : 

Situation 1
![veyon avec ip](https://user-images.githubusercontent.com/30406004/28721742-b2802828-73b1-11e7-87a2-00bfdb434b49.jpg)
In that case, I see the 2 PCs with Veyon Master

Situation 2
![veyon sans ip](https://user-images.githubusercontent.com/30406004/28721774-c8980e28-73b1-11e7-9a3a-08d9cd774131.jpg)
In that case, there is nothing in Veyon Master
![veyon sans ip master vide](https://user-images.githubusercontent.com/30406004/28721798-dc21f044-73b1-11e7-9f92-aafff96d0d18.jpg)

**Comment by patdu59** [comment]
Hi again,
I finally understood what you meant :)
I put PORTABLE in the column where I should have the IP address and it works. Isn't it strange ? :-)

**Comment by tobydox** [comment]
No it's the way it's intended to work. I'll however extend the mechanism to also match local IP addresses (like we do for room detection already).
