### ISSUE TITLE
 connect remotely

### ISSUE THREAD

**Issue by GCAtorres** [veyon/veyon#711]
Hello, when trying to connect remotely with a computer it is not possible, but if I see the computers in the console, when they log in if it is possible to perform the remote control and manage it, how can this problem be solved.

**Comment by RealFilmKuh** [comment]
try to deactivate the button "on startup" in the Veyon configuration on Client Computer.

**Comment by tobydox** [comment]
Thank you very much for your bug report. The issues have been fixed in the 4.6 branch and will be fixed in the upcoming 4.6.0 release.
