### ISSUE TITLE
Black Screen / Unable to connect with 4 Monitos

### ISSUE THREAD

**Issue by rootbear75** [veyon/veyon#712]
We get this error in veyonmaster.log when trying to access a computer with 4 monitors set up in a 2x2 configuration while logged in.
When they log out it connects fine, and I'm able to see the login screen, no issues.
`2021-01-28T14:59:08.297: [WARN] setGeometry: Unable to set geometry 3844x2160+405-937 (frame: 3860x2199+397-968) on QWidgetWindow/"RemoteAccessWidgetClassWindow" on "\\.\DISPLAY4". Resulting geometry: 3844x2141+405-937 (frame: 3860x2180+397-968) margins: 8, 31, 8, 8)`

When trying to access my localhost with the master program, i get 
`2021-01-28T14:42:30.247: [WARN] setGeometry: Unable to set geometry 1920x1080+16-1057 (frame: 1936x1119+8-1088) on QWidgetWindow/"RemoteAccessWidgetClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1858x1057+16-1057 (frame: 1874x1096+8-1088) margins: 8, 31, 8, 8)`

All of our call center users utilize 4 monitors.

Version 4.5.2

Any help would be appreciated.

**Comment by tobydox** [comment]
Does this still happen with 4.7.1?

**Comment by rootbear75** [comment]
> 

I no longer work at the company that wanted me to implement this, so no idea.
