### ISSUE TITLE
Ubuntu 20.04 - Veyon Server Unreachable or Not Running

### ISSUE THREAD

**Issue by coryarobbins** [veyon/veyon#717]
I'm using the PPA to install Veyon on Ubuntu 20.04.  I've installed on multiple machines, and some VMs, but when I look at the clients in the master, they all show as a yellow/orange screen with status of "Veyon Server Unreachable or Not Running."    I've looked at the logs that have been set to debug, but it shows a successful start of the server on port 11100 as well as the successful authentications from the keys.  No errors are listed.

If I do the local telnet command, `telnet localhost 11100`, I get a connection refused message even though the ports are listed as the defaults in the configurator and the logs clearly say the server is started on that port.  UFW is disabled.

Any ideas what I am missing?

**Comment by tobydox** [comment]
Thank you very much for your bug report! Can you verify that a) you're running X11 sessions (i.e. no Wayland sessions since they're not supported by Veyon) and b) multi session mode is disabled in the Service configuration page?

**Comment by tobydox** [comment]
Additionally, can you please try the latest version available in our PPA (4.5.3-2)? It contains additional fixes (concerning session management) compared to the official 4.5.3 release.

**Comment by tobydox** [comment]
The latest 4.5.4 release improves service and server management and should fix this issue (as long as X11 sessions are used).

**Comment by maxmasetti** [comment]
hi,
I have the same problem with Ubuntu 22.04. Updated from ubuntu 20 where everything worked fine to 22.04 and no way to get it work. Disabled wayland and running in X11, setup the keys, users and groups. No, no way. I only can see the pc is on but not reachable.

thx

max

**Comment by BestITTeacher** [comment]
I have the same problem. I installed Veyon on Ubuntu 22.04 and I get "Veyon Server Unreachable or Not Running." message from my Windows Veyon Master. If I do telnet localhost 11100, I get a connection refused message. UFW is disabled. Could you please help me somehow?
