### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by Kurt-FIT** [veyon/veyon#72]
Hello. Very impressed with Veyon. Thank-you. We are looking at using this program in meetings and training where individuals can present to a large monitor in a conference or training room... and at same time to individual PC's in front of people.
We are seeing that if someone is a Master and has a screen resolution of 1366x768 (a notebook).... and they Demo to a screen that is 1920x1080... the viewed Demo is not upscaled or fitted to the entirety of the 1920x1080 screen. There is black space below and right of the fullscreen or maximized window. Is the any way to fill the entire screen? We have not found any configuration that seems to affect this. Are we missing something or is this a planned future enhancement etc. Thanks.

**Comment by tobydox** [comment]
There's currently no scaling for performance reasons (scaling full screen images 10-20 times a second is quite CPU intensive). This might change once we switch to Qt Quick which OpenGL-based and thus GPU accelerated ;-) However this won't happen before Veyon 5.
