### ISSUE TITLE
Bug on multi-sessions on Linux since 4.4.1

### ISSUE THREAD

**Issue by pruje** [veyon/veyon#720]
Since Veyon 4.4.1, we have a major bug on Linux. Here is the situation:

Client setup:
- Linux Fedora 32 with lightdm + gnome3
- RDP server installed (xrdp)
- Veyon 4.4.0 with multi-session option enabled

Since COVID, our students can connect to PCs locally or remotely by RDP (with only 1 RDP session max). So we have configured Veyon master to monitor clients with creating 2 entries for each PC:
- first entry with default port 11100
- 2nd entry with port 11101

With Veyon 4.4.0 on clients, we could monitor both local sessions (on first entry) and remote sessions (on 2nd entry).

Since 4.4.1 to latest 4.5.3 (on the clients), here are the issues:

1. no session: lightdm display on the default entry, orange icon on 2nd. Everything is normal.
2. student opens a local session: default entry prints student username, but displays a black screen. No monitoring. 2nd entry has orange icon (which is normal).
3. student opens a RDP remote session: 2nd entry has still orange icon. No monitoring.

**Comment by tobydox** [comment]
Thank you very much for the detailed bug report! Indeed we had some changes regarding session management in 4.4.1. While investigating the issue, I already found and fixed some bugs which might be related to the behavior you described. I uploaded intermediate builds for [FC32](https://github.com/veyon/veyon/releases/download/v4.5.3/veyon-4.5.3.6.fc32.x86_64.rpm) / [FC33](https://github.com/veyon/veyon/releases/download/v4.5.3/veyon-4.5.3.6.fc32.x86_64.rpm) which include these fixes. Could you please try them and report if it changes the behavior? If not, can you please set the Veyon log level to *Debug*, restart the computer, try to login and afterwards attach `/tmp/VeyonServ*.log`?

**Comment by tobydox** [comment]
Thank you very much for the detailed bug report! Indeed we had some changes regarding session management in 4.4.1. While investigating the issue, I already found and fixed some bugs which might be related to the behavior you described. I uploaded intermediate builds for [FC32](https://github.com/veyon/veyon/releases/download/v4.5.3/veyon-4.5.3.6.fc32.x86_64.rpm) / [FC33](https://github.com/veyon/veyon/releases/download/v4.5.3/veyon-4.5.3.6.fc32.x86_64.rpm) which include these fixes. Could you please try them and report if it changes the behavior? If not, can you please set the Veyon log level to *Debug*, restart the computer, try to login and afterwards attach `/tmp/VeyonServ*.log`?

**Comment by tobydox** [comment]
(updates files re-uploaded at 10:43 CET)

**Comment by pruje** [comment]
Thank you so much for the quick answer!
One of the issue is resolved: we can see local sessions now. But we still cannot see remote RDP sessions.
Here are the logs when opening a RDP session:

VeyonServer.log:
```
2021-03-04T11:35:12.096: [INFO] ComputerControlServer: Access control successful for "::ffff:100.64.59.19" "user1"
```

VeyonService.log:
```
2021-03-04T11:40:28.236: [INFO] LinuxServiceCore::startServer(): Starting server for new x11 session "/org/freedesktop/login1/session/c3" with ID 0 at seat "/org/freedesktop/login1/seat/seat0"
2021-03-04T11:40:54.892: [INFO] LinuxServiceCore::startServer(): Starting server for new x11 session "/org/freedesktop/login1/session/c4" with ID 1 at seat "/"
```

I tried to put `Debug` or `5` in LogLevel, restarted the service, but it seems logs are not really in a debug mode. I don't know if it's normal.

**Comment by tobydox** [comment]
I'm glad local sessions work now. I'm sure we'll get RDP sessions running as well ;-)

Can you additionally please enable the (advanced) option *Write to logging system of operating system*? This should make the output of the Veyon Server instances be visible in the journal of the `veyon` systemd service. After enabling this option, please reboot, try again and paste the output of `journalctl -u veyon`.

**Comment by tobydox** [comment]
There's an xrdp-specific issue I'm currently working on. Expect a solution tomorrow :-)

**Comment by tobydox** [comment]
New builds with many fixes and improvements regarding xrdp and systemd-logind are available here: [FC32](https://github.com/veyon/veyon/releases/download/v4.5.3/veyon-4.5.3.14.fc32.x86_64.rpm) / [FC33](https://github.com/veyon/veyon/releases/download/v4.5.3/veyon-4.5.3.14.fc32.x86_64.rpm)

**Comment by pruje** [comment]
Bugs are fixed. Thank you so much for your awesome job!

**Comment by tobydox** [comment]
Perfect! Thank you for reporting and testing! And yes, as a paying customer you can expect support like this ;-)
