### ISSUE TITLE
Bug in connect feature on Linux with lightdm

### ISSUE THREAD

**Issue by pruje** [veyon/veyon#721]
When using "log in" feature, clients using Linux with lightdm (tested on Fedora) are not connecting.

Instead of log in, the DM opens session choice menu (GNOME, KDE, etc.) as you can see in this screenshot:

![lightdm_veyon](https://user-images.githubusercontent.com/11392009/110294776-9befe180-7ff0-11eb-96f9-541915abedef.png)

**Comment by tobydox** [comment]
How does your lightdm login screen look like? Does it show both username and password input fields which can be switched via tab? The current code for perfoming a logon is quite simple and does not recognize DM-specifics:

https://github.com/veyon/veyon/blob/4.5/plugins/platform/linux/LinuxUserFunctions.cpp#L288

**Comment by pruje** [comment]
No, it has:
- step 1: username + press enter
- step 2: password + press enter
That's why it doesn't work

**Comment by pruje** [comment]
I'm currently looking for how to customize lightdm to show the 2 fields in the same page.

It would be better than adding DM-specific source code juste for this case.

**Comment by tobydox** [comment]
Yes I was already thinking about a generic solution where one could manually configure a complete key sequence with placeholders for username and password.

**Comment by tobydox** [comment]
The latest 4.5.4 release implements configurable user login key sequences:

![linux-user-login](https://user-images.githubusercontent.com/3300739/110917350-b936ef80-8311-11eb-93f5-32bf0089b801.png)

Any of the X11 keycodes without the `XK_` prefix can be used (see e.g. https://github.com/veyon/libvncserver/blob/master/rfb/keysym.h for available keycodes)
