### ISSUE TITLE
Windows Veyon Service

### ISSUE THREAD

**Issue by SICTech** [veyon/veyon#727]
I have found that running the Veyon Service as an Automatic (Delayed Start) more reliable than just the default setting. This works very well on both old and new machines.

Could an option be added to the installer to apply this setting automatically without having to manually change it on every machine?

**Comment by RealFilmKuh** [comment]
What do you mean with "more reliable" ?

what problems do you have exactly?

**Comment by SICTech** [comment]
Sorry for not being clear, we have found that the Veyon service set to start automatic(default) randomly does not start on multiple machines. By changing the startup to Delayed, we have found that less or no machines have this issue. This is happens more on older machines. This has been an issue for as long as i remember with Veyon not so much with Italc. I have tested both the 32bit and 64bit version and we still get the service randomly not starting. It would be nice if the master console could restart \ start the service remotely on machines would be nice too.

**Comment by tobydox** [comment]
In Veyon 4.6.0 we added more service dependencies to the Veyon Service which might fix the problem. If you want to set this option for all your computers automatically, you could call

`sc config VeyonService start=delayed-auto`

in your deployment scripts or configure a suitable GPO.

**Comment by SICTech** [comment]
Thanks for this, I have already started deploying using a script using this method and works well. Unfortunatly we still get the odd random machine not starting the service, but a lot less than without the delay. I look forward to using 4.6.0 to see if there is further improvments.
