### ISSUE TITLE
Windows dependencies

### ISSUE THREAD

**Issue by LinkKung** [veyon/veyon#728]
I saw the installation method of Linux dependencies provided by you. Could you help me to provide windows dependencies? Thank you very much！

**Comment by tobydox** [comment]
There are no dependencies - simply run the installer and it will install everything required.

**Comment by LinkKung** [comment]
Sorry, I mean, I don't directly use the installation package for installation. I want to compile the whole project on the windows platform, but I find that I lack a lot of dependencies. I don't know if you can help provide dependency packages on windows like Linux.
![微信图片_20210331144030](https://user-images.githubusercontent.com/55228982/113101333-2bbf2f00-922f-11eb-8c77-4e6925f5b907.png)

**Comment by tobydox** [comment]
I'm sorry, building Veyon for Windows is a process restricted to OEM partners and well known Open Source contributors (there has been massive abuse of the possibility to whitelabel and sell the customized software for Windows in the past). So if you need a specific change or want us to build an installer for you, feel free to contact us via support@veyon.io
