### ISSUE TITLE
Slow displaying images from clent!

### ISSUE THREAD

**Issue by hopla1234** [veyon/veyon#73]
hi all,
sorry to sound so not positive, but i have been testing veyon already multiple times, but my impression so far is not so good about it. My question is »Why is Veyon so slow when displays an images from clent (delay time)? 

thanks,
Primus

**Comment by patdu59** [comment]
hi,
There was an option to change the delay in iTalc, as far as the display was concerned.
Maybe that they will implement that in Veyon :)

**Comment by tobydox** [comment]
What do you mean by slow? Update requests are sent to all clients every second so you should see updates almost every second. If you have delays, something is not ok. What bandwidth is available in your network? What CPUs and OS do you have?

**Comment by leszek12** [comment]
Hi I have also the same problem with vayon. I have wireless network with 20 laptops speed ac. I dont know what settings i must choose to remove delays.

**Comment by tobydox** [comment]
Can you quantify what delays you have?

**Comment by leszek12** [comment]
I can say that I am not able to use the program normally. I am still waiting for the program's reactions. It's very frustrating. I came back to version 2. It is more reactive. Although after some time it is frozen.

**Comment by tobydox** [comment]
So the program hangs? If so, when does it hang? What happens if you monitor just 2 or 3 clients? What is the CPU load while running Veyon Master?

**Comment by leszek12** [comment]
As for Veyon it is possible to work. But once I turn on one computer (via Master Veyon) I have to wait for about 1 minute to the response. No matter how many computers are hooked up. Is the effect affected by the installed TightVnc? 

I have enough powerful i7-4770 processor so I do not feel the increased demand.
I have only installed a standard Microsoft anti-virus program.

**Comment by tobydox** [comment]
So there's a delay between computer being powered up and being displayed in Veyon Master? This can happen if the host is down initially and Veyon tries to connect. If the host is down, the connect function of the operating system can block for a long time until it times out with "host not reachable". On the other hand you should see client computers immediately if you start Veyon Master if all clients are powered on already. Is this true?

**Comment by tobydox** [comment]
Closing this due to missing feedback - feel free to test upcoming RC and give more feedback again ;-)
