### ISSUE TITLE
Configurator crash using LDAP

### ISSUE THREAD

**Issue by mavhc** [veyon/veyon#734]
Installed 4.5.6

1. Open Configurator on Windows 10
2. Accept UAC prompt
3. LDAP Basic
4. Enter server name
5. Use bind credentials
6. Enter domain\username and password for new user created for veyon to use
7. Base DN, Fixed base DN, Browse
8. DC=local appears, click arrow (about 1 second wait for response)
9. DC=domain appears, click arrow (not responding, about 25 seconds later the window vanishes)

VeyonConfigurator.log is empty (if deleted before starting)

**Comment by tobydox** [comment]
Did this work in previous releases, e.g. 4.5.5?

**Comment by Fehler12** [comment]
Hi, in #737 we identified an issue with a new version of LDAP-lib. Does it make sense if you try the posted version from tobydox as well? This migt also resolve your issue?

**Comment by mavhc** [comment]
With 4.5.6.3 and Encryption Protocol set to None it works.

With it set to SSL and any combination of "TLS certificate verification" I get a blank Browse LDAP window.

With it set to TLS I get a blank Browse LDAP window except when verification is set to Never

Would be useful to feed back any errors to the user.

Does not crash any more though.

**Comment by tobydox** [comment]
Crash fixed in Veyon 4.5.7.
