### ISSUE TITLE
Provide RDP session on the same port as local one for Windows10 (single session licensed)

### ISSUE THREAD

**Issue by denis-b** [veyon/veyon#735]
Microsoft Windows 10  License allows only one session, local or RDP.  Provided that it should be much more simpler to always serve veyon session on the same static port 11000 regardless of connexion type and without the need of multi-session setting.

The main use case is a classroom, with computers accessed locally and others remotely from students devices, who may switch to local computer. With this setup, Sessions on conputers accessed remoteley are never detected from veyon master, even in multi-session mode, as we are using ldap filters for defining classrooms, and there is no way to choose the port.

Network Discovery plugin may provide a workaround, but as only single sessions can be made on computers, it is definitely not worth using it.

**Comment by denis-b** [comment]
In fact it looks like a bug: When multi-session is not active,  If an active user session (console/RDP)  exists, it should be proposed on port 11100, not the winlogon.exe one.
Unfortunately, I'm not able to compile Veyon for Windows, so it is difficult for me to submit a clean and tested patch.

**Comment by tobydox** [comment]
Indeed the behavior in single session mode is arguable when focusing on actual active sessions only, not stations/physical displays. However the description (**Single session mode (create server instance for local/physical session only)**) is clear here. In multi session mode it was a design decision to always expose the console session on the first port, see the description of c8a7832e8c0ef59e6ba24eddfe7ff4dccd7d2813 for details. So the behavior regarding the console session intentionally is identical in both modes.

A possible solution could be to add a third mode ("[User|Primary|Active] session mode") and rename Single session mode to "Local session mode". What do you think about it?

**Comment by denis-b** [comment]
Hello, you are perfectly right,  allowing three choices  is the good solution : 
- local session mode, (formerly single session)
- multi session mode,
- active session mode (logon, local and remote always on first port) 

I'm not very efficient in QT/C++ programming, but I can help for testing builds in our SambaEdu deployments (more than 300 schools in France)

**Comment by denis-b** [comment]
Hello, any news about this issue ? For us it's a real problem, as it makes Veyon completely unuseable if some computers in the classroom are accessed from guacamole/rdp. I had to hack logon scripts to kill veyon processes but it is totally unreliable.

**Comment by tobydox** [comment]
An installer for testing is available at https://github.com/veyon/veyon/releases/download/v4.5.7/veyon-4.5.7.52-win64-setup.exe - the  active session mode (currently implemented as draft internally only) is active when enabling multi session mode and setting the maximum session count to `1`.

**Comment by denis-b** [comment]
Thanks very much, I will try it and and report here the result.

**Comment by denis-b** [comment]
Thanks very much, I installed it, but now veyon-service is not starting anymore. tried to find logs, but I found nothing related in journals.

**Comment by denis-b** [comment]
Ok it is working with other computers ! 
for us it's perfect.

**Comment by TomRicci** [comment]
Hi,
I don't know if it is still officially supported but it seems that this version 4.5.7.52 doesn't work with the active session mode on Windows 7,  (the exact same configuration is working on Windows 10 perfectly, many thanks for that).

The service doesn't start, when I manually try I get : "Error 1075: The dependency service does not exist or has been marked for deletion".

**Comment by tobydox** [comment]
Thank you four the feedback! The 4.x snapshot builds also include 6a520f67f7dce36b4f860278d0d3123aa5e6fbdf which adds more service dependencies. Can you verify that both `LSM` and `LanmanWorkstation` exist on your Windows 7 computer and are enabled?

**Comment by TomRicci** [comment]
`LanmanWorkstation` exist, is enabled and runing fine. `LSM.exe` is a running process running, but there doesn't seems to be any service by that name. Anything I can test ?

**Comment by TomRicci** [comment]
Hi, it's know working fine, thank you very much! Take care.

**Comment by tobydox** [comment]
Implemented in the 4.6.0 release.
