### ISSUE TITLE
Veyon Master crashes on LDAP-query with version 4.5.6

### ISSUE THREAD

**Issue by Fehler12** [veyon/veyon#737]
Hi,

today I wanted to update veyon from version 4.5.2 to 4.5.6.
On the master console PC I noticed that veyon keeps crashing after the update with the very same config.
The error message is:
"Runtime Error!
Program c:\Program Files\Veyon\veyon-master.exe

This application has requested the Runtime to terminate in an unusual way.
Please contact the application's support team for more information"

The Windows Error log says:
"Name der fehlerhaften Anwendung: veyon-master.exe, Version: 4.5.6.0, Zeitstempel: 0x00000000
Name des fehlerhaften Moduls: libldap.dll, Version: 0.0.0.0, Zeitstempel: 0x00000000
Ausnahmecode: 0x40000015
Fehleroffset: 0x0000000000037536
ID des fehlerhaften Prozesses: 0x14d8
Startzeit der fehlerhaften Anwendung: 0x01d771c41312ae61
Pfad der fehlerhaften Anwendung: C:\Program Files\Veyon\veyon-master.exe
Pfad des fehlerhaften Moduls: C:\Program Files\Veyon\libldap.dll
Berichtskennung: 2602530a-6f88-4c33-81c5-6f7ad43edd56
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: "

Following I tried to replace the libladp.dll from the veyon 4.5.2 installation into the current 4.5.6 installation and the error is gone and veyon is working again.
Are there any ways to further troubleshoot this?
The VeyonLog at %TEMP% is empty when the application crashes.

System information:
Windows Server 2016 (build 14393.4467) 64bit, Veyon 4.5.6 64 Bit installation.

I've configured LDAP queries (Windows AD) for room information and using cert-based auth.

**Comment by Fehler12** [comment]
Add: this might be the same issue as #734 . But for me the configurator crashes instantly when clicking the check computer tree button within the ldap basic settings. The basic DC check on the first tab works for me.

**Comment by Fehler12** [comment]
Add2: this issue does NOT exist with a Win10 Machine with nearly identical config (there are some other certs for connection authentication and a filter for filtering on a particular room).

**Comment by tobydox** [comment]
Thank you for your bug report! Unfortunately I can't reproduce the issue here but likely it's caused by the update of the OpenLDAP library (from 2.4.58 to 2.5.4+) in Veyon 4.5.6. I uploaded a new build at https://github.com/veyon/veyon/releases/download/v4.5.6/veyon-4.5.6.2-win64-setup.exe which contains a version of libldap.dll with the latest bug fixes from the official 2.5.x branch – may be the crash is fixed. If not, we'll revert to OpenLDAP 2.4 in Veyon 4.5.7. One more question: does the crash also happen when disabling encryption/TLS?

**Comment by Fehler12** [comment]
Hi,

the 4.5.6.2 built does not work either, sorry! TLS was never enabled nor configured.
However I've found maybe an error which causes the crash: 
If I leave all of the marked fields empty the crash occurs. If I enter a vaule in the field computer-tree the new version works as expected:
![image](https://user-images.githubusercontent.com/53938045/125132463-a3410c00-e104-11eb-90b5-fbe9934c5ff4.png)

Is it possible that the new version is not able to work if there is no OU value in the field computer-tree?

The reason for leaving the fields empty on the Server machine is that the Server should access all possible machines. The Win10 machines should only access the rooms they are in.

**Comment by tobydox** [comment]
Thanks for sharing the interesting observations! Can you post screenshots of the other LDAP configuration pages?

**Comment by Fehler12** [comment]
Sure:
![image](https://user-images.githubusercontent.com/53938045/125294582-aca8bf00-e324-11eb-9e2d-45d656fad364.png)
![image](https://user-images.githubusercontent.com/53938045/125294646-baf6db00-e324-11eb-85ea-5608abf0eafb.png)

I've only changed the domain-name to a universal one.

Sorry that I did not check this initially!

**Comment by tobydox** [comment]
Thanks for the feedback. I still can't reproduce a crash so we'll downgrade to OpenLDAP 2.4 in the next release. In the meantime you can test the installer at https://github.com/veyon/veyon/releases/download/v4.5.6/veyon-4.5.6.3-win64-setup.exe which already contains the downloaded LDAP library.

**Comment by Fehler12** [comment]
Hi, sorry for my delayed reply! I can confirm that the most recent veyon-version with the downgraded LDAP-lib works in my described scenario! Thank you for the solution.
