### ISSUE TITLE
[ERR] MainWindow: failed to initialize credentials

### ISSUE THREAD

**Issue by WhoIsLTD** [veyon/veyon#738]
![image](https://user-images.githubusercontent.com/41822445/128005301-533e46a4-c7e2-4b43-a7d2-a8a64d83f377.png)
why i cant open veyon-master ui

**Comment by tobydox** [comment]
You're probably using a build based on the master branch which is the development version. Please use the 4.5 branch and/or the official binaries. Otherwise make sure you enabled at least one authentication mechanism.

**Comment by WhoIsLTD** [comment]
> Có thể bạn đang sử dụng một bản dựng dựa trên nhánh chính là phiên bản phát triển. Vui lòng sử dụng nhánh 4.5 và / hoặc các mã nhị phân chính thức. Nếu không, hãy đảm bảo rằng bạn đã bật ít nhất một cơ chế xác thực.

![image](https://user-images.githubusercontent.com/41822445/128288901-5902adc4-1b64-432e-b827-4a45422c80e2.png)
but i have an error with Qt5HttpServer. Do you know how to install it? :(

**Comment by tobydox** [comment]
This is not an error but just a warning - if you checked out including submodules, the bundled qhttpserver library will be used.

**Comment by WhoIsLTD** [comment]
> This is not an error but just a warning - if you checked out including submodules, the bundled qhttpserver library will be used.

```
CMake Error: File /home/pumpkinduke/veyon-4.5/3rdparty/kldap/src/kldap_config.h.cmake does not exist.
CMake Error at plugins/ldap/kldap/CMakeLists.txt:21 (configure_file):
```
  configure_file Problem configuring file
what about these 2 errors?

**Comment by tobydox** [comment]
You didn't checkout all submodules properly. Please make make sure to clone and afterwards run "git submodule update --init --recursive".

**Comment by WhoIsLTD** [comment]
> You didn't checkout all submodules properly. Please make make sure to clone and afterwards run `git submodule update --init --recursive`.

oh this work for me
thank you, i miss --recursive when i clone :D
