### ISSUE TITLE
veyon-server doesn't start on login-screen

### ISSUE THREAD

**Issue by mathiasrettich** [veyon/veyon#739]
Hi, everyone,
the current version 4.5.7 of veyon is running on my ubuntu 20.04 client. X11 (not Wayland) runs as the display manager.
A systemctl status veyon.service as root on the Ubuntu client delivers:

```
root@lz-r99:~# systemctl status veyon.service 
● veyon.service - Veyon Service
     Loaded: loaded (/lib/systemd/system/veyon.service; enabled; vendor preset:>
     Active: active (running) since Sat 2021-08-07 09:59:42 CEST; 13min ago
       Docs: man:veyon-service(1)
   Main PID: 40772 (veyon-service)
      Tasks: 28 (limit: 9495)
     Memory: 64.7M
     CGroup: /system.slice/veyon.service
             ├─40772 /usr/bin/veyon-service
             ├─41151 /usr/bin/veyon-server
             └─41152 /usr/bin/veyon-worker {8e997d84-ebb9-430f-8f72-d45d9821963>

Aug 07 09:59:42 lz-r99 systemd[1]: Started Veyon Service.
Aug 07 09:59:46 lz-r99 veyon-service[40772]: 2021-08-07T09:59:46.632: [WARN] Li>
Aug 07 09:59:49 lz-r99 veyon-service[40772]: 2021-08-07T09:59:49.648: [WARN] QP>
```

So everything is as it should be.
As soon as the user logs out, the login screen is no longer visible on the teacher's computer. A systemctl status veyon.service as root on the Ubuntu client delivers:

```
root@lz-r99:~# systemctl status veyon.service 
● veyon.service - Veyon Service
     Loaded: loaded (/lib/systemd/system/veyon.service; enabled; vendor preset:>
     Active: active (running) since Sat 2021-08-07 09:59:42 CEST; 20min ago
       Docs: man:veyon-service(1)
   Main PID: 40772 (veyon-service)
      Tasks: 4 (limit: 9495)
     Memory: 3.9M
     CGroup: /system.slice/veyon.service
             └─40772 /usr/bin/veyon-service

Aug 07 09:59:42 lz-r99 systemd[1]: Started Veyon Service.
Aug 07 09:59:46 lz-r99 veyon-service[40772]: 2021-08-07T09:59:46.632: [WARN] Li>
Aug 07 09:59:49 lz-r99 veyon-service[40772]: 2021-08-07T09:59:49.648: [WARN] QP>
```
A veyon-server start as root on the Ubuntu client delivers:

```
root@lz-r99:~# veyon-server start
2021-08-07T10:23:21.701: [ERR] VncServer: no VNC server plugins found!
KLDAP: connection closed!
```

If a user now logs in, his screen is visible again on the teacher's computer.

Greeting,
Mathias

**Comment by mathiasrettich** [comment]
perhaps the following observation will help.
I installed veyon 4.5.7-2 on two computers (ubuntu 20.04).
The built-in VNC server delivers the screen image for one or two seconds after starting veyon-master.
The problem occurs when starting veyon-master and not when starting the vnc-server.

**Comment by tobydox** [comment]
As discussed in the community forum, the service-related issues have been fixed in the 4.6 branch which will be released as 4.6.0 soon.

**Comment by yeji0407** [comment]
same problem!
Can you tell me the commit id that fixed this problem?
Thank you so much!

**Comment by tobydox** [comment]
It's a whole series of commits so simply check out the 4.6 branch and build it.
