### ISSUE TITLE
press and hold feature broken on windows

### ISSUE THREAD

**Issue by SlrG** [veyon/veyon#740]
Sadly I noticed just now, that the press and hold feature (#698) doesn't seem to work on Windows 10. I don't have a Windows 7 available to test. Looking through the code it is mostly qt based, so I don't really understand why it's not working. As we have windows 10 based teacher PCs in our school I really would like to get it working on windows, too.

Can you maybe have a look at the code again, if there are any obvious problems which would break it working on windows?

Cross developing on linux makes it hard to debug this problem, as it's not possible to set breakpoints and step through the code on a windows machine. Do you have any ideas if and how I could circumvent/solve that or do you have a windows development environment, where you can test it?

**Comment by tobydox** [comment]
Thank you again for your contribution. This feature is only part of the development branch that's why you can't find it in current releases (for Windows). It definitely will be part of a possible 4.6.x series and/or Veyon 5 later this year.

**Comment by tobydox** [comment]
FYI: it just landed in the 4.6 branch which will be released as 4.6.0 soon.

**Comment by SlrG** [comment]
Cool. Thank you very much. :+1:  I'll install that ASAP after it is released.

**Comment by SlrG** [comment]
We have just installed 4.6. Sadly the feature is not working correctly. There is a short "flash" when holding the mouse button on a student pc thumbnail (so it tries to do something), but the preview window does not open correctly or closes itself extremely quick without the user releasing the mouse button. Do you have an idea how I can debug the problem?

Also a setting to open the preview,  remote view or control maximised by default would be great, as we have one room with dual monitor student systems now and its tedious to always having to click to view both screens at once. If you want I could probably implement the latter myself and send you a PR.
