### ISSUE TITLE
veyon dosent install on unbuntu 18.04

### ISSUE THREAD

**Issue by johnmccauley1718** [veyon/veyon#741]
after completing download tried installing with software installer, get error:
sorry something went wrong:
E: encounteres a section with no package: header

Tried another package installer, get error:
dependency is not satisfiable: libprocps4

Any other methods I can try to get veyon installed?

**Comment by tobydox** [comment]
Did you use the right package, i.e. the one for Ubuntu 18.04? libprocps4 is part of Ubuntu 16.04 so I guess you used that package. Consider using our PPA at https://launchpad.net/~veyon/+archive/ubuntu/stable to obtain the latest stable version of Veyon for your Ubuntu computer(s).
