### ISSUE TITLE
请问支持arm处理器的Linux系统运行吗

### ISSUE THREAD

**Issue by amosniu** [veyon/veyon#744]
电脑是arm架构的处理器，运行Linux系统，包管理器是apt，请问能运行吗？或是源代码能够打包成支持该架构的可执行程序吗

**Comment by tobydox** [comment]
Unfortunately we don't speak Chinese so please submit a new bug in English. Regarding arm support: our official PPA https://launchpad.net/~veyon/+archive/ubuntu/stable also contains arm packages of Veyon for Ubuntu.
