### ISSUE TITLE
Display hostname in tooltip

### ISSUE THREAD

**Issue by scls19fr** [veyon/veyon#745]
Hello,

Currenty Hostname is display bottom screen (next to user name)... but not in tooltip

![Veyon-Hostname-missing](https://user-images.githubusercontent.com/109167/132309007-d9d6dd4c-71bf-4c9b-beff-97af698c4f21.png)

Unfortunately some user name are quite long and so hostname can't be displayed.

Displaying hostname in tooltip could be a nice improvement

Kind regards

**Comment by tobydox** [comment]
Thanks for the suggestion! Change 99b80a00071448fa641811f27aa9f5044136d6b5 will be part of the upcoming 4.5.8 release.
