### ISSUE TITLE
Got signal 11 when launching veyon master

### ISSUE THREAD

**Issue by fweng322** [veyon/veyon#748]
Version 4.5.7
upgraded from old installations

After upgrading, all the clients were disconnected and could not connect anymore
when running veyon-service under command line, service started successfully (log before line 12), but when launching veyon master it shows the following error:

https://pastebin.com/ea2NbiQ1

Had no idea about how to dig further.

**Comment by tobydox** [comment]
Which platform/version are you using?

**Comment by fweng322** [comment]
> Which platform/version are you using?

Both server and clients are running on kubuntu 18.04.

I also tried to (dist-)upgrade from 18.04 to 20.04, but still got signal 11 on server when running veyon-master.

**Comment by tobydox** [comment]
Ok, can you try to install https://github.com/veyon/veyon/releases/download/v4.5.7/veyon_4.5.7-50-ubuntu-focal_amd64.deb on the Kubuntu 20.04 computer? It contains many bug fixes regardig the server/service.

**Comment by fweng322** [comment]
> Ok, can you try to install https://github.com/veyon/veyon/releases/download/v4.5.7/veyon_4.5.7-50-ubuntu-focal_amd64.deb on the Kubuntu 20.04 computer? It contains many bug fixes regardig the server/service.

Thanks, will try it some time later.

**Comment by fweng322** [comment]
> Ok, can you try to install https://github.com/veyon/veyon/releases/download/v4.5.7/veyon_4.5.7-50-ubuntu-focal_amd64.deb on the Kubuntu 20.04 computer? It contains many bug fixes regardig the server/service.

This version works.

Actually when updating it to clients, the veyon-master in server side could successfully see all the clients.

Thanks for your work.
