### ISSUE TITLE
Demo screen very slow on client sides

### ISSUE THREAD

**Issue by fweng322** [veyon/veyon#749]
Version 4.5.7-50 downloaded from github
OS: Kubuntu 20.04 (upgraded from 18.04)
Server vnc set to internal x11vnc, with option -ncache_cr (also tried with -ncache 10 too)

When demo from server, the client got the screen after nearly 10 seconds, and when clicking something on server the clients would take more than 10 seconds to refresh 1 frame too.

Have already checked the internal network environment.  All the clients are running under 1G ethernet.

The server CPU Intel i7-8700 12 cores and has 16GB ram.

Wondering if it is vnc's problem.

**Comment by fweng322** [comment]
Additional info:  I just finished a mass deployment of hard drive images to 29 clients in this environment in 20 minutes, so I'm pretty sure that the network speed is not an issue.

**Comment by tobydox** [comment]
Indeed this sounds like a VNC problem. 1G network should be fine. One possibility for debugging is to set the log level to "Debug" and enable the "Write to logging system of operating system" option (switch to advanced view). Then you should see and extract the output of x11vnc in `journalctl -u veyon` on the broadcasting computer. May be there are some hints about the bad performance.

**Comment by okulegitimci** [comment]
you should also check the "key frame interval" settings with veyon configurator... it is better to keep that value not too small ... mine is "10 s" and I don't have showing vidoes ...

**Comment by candiedoperation** [comment]
**Difficult to Grab your Computer** when you want to View Screens in your Computer Lab?

Monitoring Center is an **Android / iOS Application for Veyon**. It is a free and open source software for monitoring and controlling computers across multiple platforms. It supports you in teaching in digital learning environments, performing virtual trainings and Monitoring Devices in Computer Laboratories. Learn more About Veyon at https://veyon.io

Get the Source code of Monitoring Center at https://github.com/candiedoperation/Monitoring-Center/
Become my Patron at https://patreon.com/atheesh

Screenshots of the App -
|![Screenshot_1637053110](https://user-images.githubusercontent.com/47198395/141977770-fec81e6e-fc6c-4f07-a491-dcfebd52dc6c.png)|![Screenshot_1637061267](https://user-images.githubusercontent.com/47198395/141977781-df24cb23-3740-4221-924f-66bef4f3c90e.png)|
|---|---|

**Comment by tobydox** [comment]
Closed via 37011a580b66b85f93ecc40530d8917000897374
