### ISSUE TITLE
请问是否有arm架构的deb安装包

### ISSUE THREAD

**Issue by amosniu** [veyon/veyon#750]
请问是否有arm架构的deb安装包

**Comment by tobydox** [comment]
Thank you for your bug report. First of all: please write in English next time so everyone can participate properly. According to online translation, you're searching for a DEB file for ARM. There are some for Ubuntu at https://launchpad.net/~veyon/+archive/ubuntu/stable - alternatively build DEB packages on your own as described in the README.md file.
