### ISSUE TITLE
veyon-cli service restart vs veyon-configurator apply button

### ISSUE THREAD

**Issue by brunovila** [veyon/veyon#751]
I am using veyon 4.5.7 and I have to reload the config from a json file in many computers.

After import the config using _veyon-cli  config load file.json_ I tried to apply the configuration with _veyon-cli service restart_, but none is happening.  I tried:
- Restart service with _veyon-cli service restart_
- Restart the veyon windows service
- Restart service with _veyon-cli service restart_, and restart the veyon windows service
- Restart the computer

None of these work; all computers remain in red color.

But if I open the veyon-configurator window, and press the apply button without changing anything, It works fine!!!

Why it is diferent from the previous commands?  I don't want to open the veyon-configurator in every computer (they are about 300)
What am I doing wrong?

**Comment by tobydox** [comment]
Thank you for your bug report. This is an interesting issue which needs to be fixed. Are you running "veyon-cli" with admin privileges? Also do you use the `import` command (you wrote about `load` which does not exist ;-) Can you try to run `veyon-cli config export foo.json` after import and look if the two JSON files are identical? Also run the export again with another filename after pressing "Apply" in Veyon Configurator just to see if anything changed in the config.

**Comment by tobydox** [comment]
BTW do you have access control configured? If so, how?

**Comment by brunovila** [comment]
I am using Windows and access control configured buy public/private key and it works fine.
I tried this:
`veyon-cli config import file.json`
`veuon-cli service restart`

I cannot view the client on the veyon-master
Then tried to load fille.json with the veyon-configurator app, and press the apply button. It works fine
After that, I tried
`veyon-cli config export anotherfile.json`
Then I compare both files and they are the same.

By the end, I tried to restart the service with command line (after pressed the apply button)
`veyon-cli service restart`
And it works fine

But if I try to load the file exported before, or the file exported with the veyon-configurator app from the command line it does not work anymore.
`veyon-cli config import anotherfile.json`
`veuon-cli service restart`

**Comment by tobydox** [comment]
After reviewing your description again, I think I found the problem. You must not restart the service immediately after importing the configuration since ``veyon-cli config import`` already restarts the service. I guess invoking ``veyon-cli service restart`` immediately afterwards fails since the service is still starting up and so something gets messed up when telling Windows or the service to restart again. Can you verify that ``veyon-cli config import`` is sufficient?
