### ISSUE TITLE
veyon troubles with MATE Desktop Ubuntu  20.04

### ISSUE THREAD

**Issue by rrignier** [veyon/veyon#754]
Hello, I tried to setup Veyon-server on an ubuntu 20.04 machine by using keys pair authentication.
- Veyon-service is 4.31
- Veyon master is 4.5.7 on Windows 10

This seems working OK as I get on master, Ubuntu's  Login screen with lightdm as connected user. But as soon as I connect with a local user,, The remote screen turns Orange. If I manually restart veyon-service, I can see the machine's display back on the master.

Host log is full of messages like thie one (every second);
`. veyon-service[3473]: 2021-09-23T15:26:17.724: [WARN] LinuxServiceCore: Environment for session "/org/freedesktop/login1/session/c2" not yet available - retrying in 1000 msecs`

What could I do for Troublshoot ?

Thank you for help.

**Comment by tobydox** [comment]
Please use the latest 4.6.0 Linux packages which should solve most of the server/service-related problems on Linux.
