### ISSUE TITLE
Veyon 4.6.0 - Search Case Sensitive

### ISSUE THREAD

**Issue by pauloboc** [veyon/veyon#755]
Hello,
I'm testing the version 4.6.0
It's very good, is too fast to connect remotely.

The search is differentiating between uppercase and lowercase now, is this an error?

Example:
Computer named "Mac001"

```
Searching for: Mac001.... Ok
Searching for: MAC001.... No result
Searching for: mac001.... No result
```

**Comment by tobydox** [comment]
Thank you for testing and reporting this bug. Indeed this is an issue in Qt 5.12 which has been revealed now since we're using newer API calls (which are compatible with Qt 6 already) in Veyon 4.6.0. This will be fixed in Veyon 4.6.1.
