### ISSUE TITLE
Veuyon-worker problem in ubuntu 20.04

### ISSUE THREAD

**Issue by brunovila** [veyon/veyon#758]
I have computers with ubuntu 20.04 in which I have installed veyon 4.6.0 via ppa repository, and key based auth.
When user logs in, I can see the screen in master only 2 or 3 seconds.  After that, the veyon-worker process ends and I cannot see the computer desktop anymore

But if I install the veyon 4.4.6 from the package listed in the download page for ubuntu 20.04, it works fine, and the veyon-worker does nont end, and I can see the computer desktop.

Are the ppa version and the web version of the veyon different?

**Comment by tobydox** [comment]
Indeed there's a binary compatibility problem in the PPA packages causing the server to crash. The packages from veyon.io are built using a different mechanism and therefore are not affected by this issue. Thank you very much for spotting this issue! Updated packages with proper bug fixes (6eff0918482d7db122c711c298f5eebb3f2e3674, 37f76ae2934067e226697ee59b43ffdda411ccf2) are currently in the build queue and will be available soon.
