### ISSUE TITLE
No ACL Domain Groups listing

### ISSUE THREAD

**Issue by SICTech** [veyon/veyon#76]
I have used Italc for several years now using ACL authentication as a method of access control. I have never required direct LDAP\AD. Would it be possible for the Access control area to show Domain Security Groups like it did in previously in Italc.

**Comment by tobydox** [comment]
This is currently not implemented but I'll mark this as a feature request to also include domain groups in the group list. Alternatively you can/should configure LDAP/AD integration which also allows you to fetch all computer data from AD so you don't have to manage all computers separately in Veyon Configurator. Once LDAP/AD integration is setup you can use LDAP/AD groups for access control groups and access control rules.

**Comment by SICTech** [comment]
Thanks for your quick response, I wish is could use LDAP/AD but our network security team would prevent it. I will stick with Italc3 and keep watching the Veyon project for this possible enhancement. On another note a great feature that was included in another commercial product was the ability to block individual computers internet access without having to implement a screen lock. A simple proxy setting switch is most likely how it can be achieved.
