### ISSUE TITLE
plugins/WebAPI missing in master branch?

### ISSUE THREAD

**Issue by candiedoperation** [veyon/veyon#765]
I'm unable to locate the WebAPI plugin in Veyon's master branch. @tobydox could you please tell whether the plugin code has been written somewhere else or if WebAPI support is to be dropped in future releases?

P.S: I've posted this question here in the issue tab as I could not find any other place to do so.

**Comment by tobydox** [comment]
The WebAPI plugin has not yet been ported to the refactored (modularized) authentication layer, that's why it's not included in the master branch at the moment. It's not planned to drop it.

**Comment by candiedoperation** [comment]
@tobydox, I actually have been working on an Android/iOS App for Veyon and would like to discuss about it with you. There has been a good progress in the App's repository at https://github.com/candiedoperation/Monitoring-Center/
