### ISSUE TITLE
Veyon WebAPI fails to authenticate due to UpperCase Headers

### ISSUE THREAD

**Issue by candiedoperation** [veyon/veyon#767]
Thank you for your great service veyon!

Below are the W3C Guidelines for HTTP Headers
https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2
https://www.rfc-editor.org/rfc/rfc7230#appendix-A.2

For Further Reference visit https://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive

HTTP Headers are Case Insensitive. Maximum HTTP Libraries in
JavaScript (XHR, Axios, fetch) convert HTTP Headers' to Lowercase
and Veyon fails to authenticate as the below code (before this edit)
returns QStringLiteral("Connection-Uid") instead of all lowercase
QStringLiteral("connection-uid")

This issue in Veyon was discovered during development of an Android/iOS
Client for Veyon at https://github.com/candiedoperation/Monitoring-Center

Further Information can be found in https://github.com/veyon/veyon/issues/765#issuecomment-958891312

**Comment by tobydox** [comment]
Thank you for identifying and reporting this issue! Indeed this required a fix to properly implement case insensitive header field lookups. Just changing to lower case would break existing applications which send requests with upper case characters. Interesting project BTW!
