### ISSUE TITLE
support for LDAPS or StartTLS

### ISSUE THREAD

**Issue by andreasmalta** [veyon/veyon#77]
whats the recommended practice to encrypt ldap traffic please, just specifying port 636 didn't seem to work...

**Comment by tobydox** [comment]
It's currently not supported but we'll work on it so it might be part of the 4.1.x series.

**Comment by tobydox** [comment]
Implemented via 775aba20a96c7de13cd3fb0378bf58b49f5f0b17,  cbfff4bcd20f7ed0941dd702440f990ba1ab9710 and ce8819db50106683ae060b6008e3d3c727550727 so it will be part of Veyon 4.1.
