### ISSUE TITLE
multiple computers selected, cannot be opened at once

### ISSUE THREAD

**Issue by CoodyCZ** [veyon/veyon#770]
When I select multiple computers, this amount cannot be opened at once. I have to request a remote connection for each computer separately.

Is there an option or would it not be possible to add a feature that would allow you to select multiple computers and access them remotely with one click?

At this moment woks it so, that a popup will pop up on me stating that I can enter the ip address or hostname for a specific computer ...

**Comment by candiedoperation** [comment]
**Difficult to Grab your Computer** when you want to View Screens in your Computer Lab?

Monitoring Center is an **Android / iOS Application for Veyon**. It is a free and open source software for monitoring and controlling computers across multiple platforms. It supports you in teaching in digital learning environments, performing virtual trainings and Monitoring Devices in Computer Laboratories. Learn more About Veyon at https://veyon.io

Get the Source code of Monitoring Center at https://github.com/candiedoperation/Monitoring-Center/
Become my Patron at https://patreon.com/atheesh

Screenshots of the App -
|![Screenshot_1637053110](https://user-images.githubusercontent.com/47198395/141977770-fec81e6e-fc6c-4f07-a491-dcfebd52dc6c.png)|![Screenshot_1637061267](https://user-images.githubusercontent.com/47198395/141977781-df24cb23-3740-4221-924f-66bef4f3c90e.png)|
|---|---|
