### ISSUE TITLE
Password changed, cannot connect

### ISSUE THREAD

**Issue by makgab** [veyon/veyon#771]
Hi,
Our Environment: Veyon 4.4

 We changed the password on the students pc and we cannot connect to the PCs. Authentication error.
What may it be?

**Comment by candiedoperation** [comment]
Hello @makgab, It is better to use Key File Authentication method in Veyon instead of the Username and Password Authentication. On changing the password, I have noticed that, the authentication fails if the student and teacher computers do not have the same username and password.

**Comment by tobydox** [comment]
Indeed the password has to match on all computers. That's why it's recommended to either join all computers to a domain and use domain users or use key file authentication.

**Comment by makgab** [comment]
> Hello @makgab, It is better to use Key File Authentication method in Veyon instead of the Username and Password Authentication. On changing the password, I have noticed that, the authentication fails if the student and teacher computers do not have the same username and password.

Thanks! It was the reason! :) The master PC had the old password.
