### ISSUE TITLE
unsafe actions confirmation shows always "ALL" computers

### ISSUE THREAD

**Issue by SlrG** [veyon/veyon#774]
It's probably some kind of regression. The confirmation dialogue for unsafe actions (e.g. reboot, shutdown or logoff) always shows the text: "Do you really want to reboot **ALL** computers?" It happens no matter how many computers are selected for the desired context menu action. 

The expected behaviour would be the ALL showing only when an icon bar action is clicked or all computers are selected.

Otherwise it should display "Do you really want to reboot the selected computers?"

**Comment by candiedoperation** [comment]
**Difficult to Grab your Computer** when you want to View Screens in your Computer Lab?

Monitoring Center is an **Android / iOS Application for Veyon**. It is a free and open source software for monitoring and controlling computers across multiple platforms. It supports you in teaching in digital learning environments, performing virtual trainings and Monitoring Devices in Computer Laboratories. Learn more About Veyon at https://veyon.io

Get the Source code of Monitoring Center at https://github.com/candiedoperation/Monitoring-Center/
Become my Patron at https://patreon.com/atheesh

Screenshots of the App -
|![Screenshot_1637053110](https://user-images.githubusercontent.com/47198395/141977770-fec81e6e-fc6c-4f07-a491-dcfebd52dc6c.png)|![Screenshot_1637061267](https://user-images.githubusercontent.com/47198395/141977781-df24cb23-3740-4221-924f-66bef4f3c90e.png)|
|---|---|
