### ISSUE TITLE
press and hold feature not working correctly on windows

### ISSUE THREAD

**Issue by SlrG** [veyon/veyon#775]
We have just installed 4.6 on our schools windows 10 PC's. Sadly the feature is not working correctly.

There is a short "flash" when holding the mouse button on a student PC thumbnail (so it tries to do something), but the preview window does not open correctly or closes itself extremely quick without the user releasing the mouse button.

Do you have an idea how I can debug the problem?

On my linux testing system it works without problems.

**Comment by candiedoperation** [comment]
**Difficult to Grab your Computer** when you want to View Screens in your Computer Lab?

Monitoring Center is an **Android / iOS Application for Veyon**. It is a free and open source software for monitoring and controlling computers across multiple platforms. It supports you in teaching in digital learning environments, performing virtual trainings and Monitoring Devices in Computer Laboratories. Learn more About Veyon at https://veyon.io

Get the Source code of Monitoring Center at https://github.com/candiedoperation/Monitoring-Center/
Become my Patron at https://patreon.com/atheesh

Screenshots of the App -
|![Screenshot_1637053110](https://user-images.githubusercontent.com/47198395/141977770-fec81e6e-fc6c-4f07-a491-dcfebd52dc6c.png)|![Screenshot_1637061267](https://user-images.githubusercontent.com/47198395/141977781-df24cb23-3740-4221-924f-66bef4f3c90e.png)|
|---|---|

**Comment by tobydox** [comment]
It looks like on Windows `QWidget::mouseReleaseEvent()` is called as soon as a window loses focus. So we need a different approach for detecting the mouse release event...

**Comment by SlrG** [comment]
I'll have a look at it. Sadly its hard to test without the possibility to build a windows version.

**Comment by SlrG** [comment]
@tobydox 
I wrote a PM in our forum chat from January. Please check it out. :)

**Comment by SlrG** [comment]
With the merge of the fix, this issue is now closed.
