### ISSUE TITLE
Login when Duo is present 

### ISSUE THREAD

**Issue by mpn-peter-smith** [veyon/veyon#777]
Logging a user in remotely when the Duo client is installed causes the screen to be black. The only way to do anything it to press CTRL ALT DEL which shows the Lock Screen again. This behaviour persists even if the users account is set to bypass MFA. Looking to see if there is a feature to allow the Duo pop up to display to allow remote login when Duo is installed on the target machine.

**Comment by candiedoperation** [comment]
**Difficult to Grab your Computer** when you want to View Screens in your Computer Lab?

Monitoring Center is an **Android / iOS Application for Veyon**. It is a free and open source software for monitoring and controlling computers across multiple platforms. It supports you in teaching in digital learning environments, performing virtual trainings and Monitoring Devices in Computer Laboratories. Learn more About Veyon at https://veyon.io

Get the Source code of Monitoring Center at https://github.com/candiedoperation/Monitoring-Center/
Become my Patron at https://patreon.com/atheesh

Screenshots of the App -
|![Screenshot_1637053110](https://user-images.githubusercontent.com/47198395/141977770-fec81e6e-fc6c-4f07-a491-dcfebd52dc6c.png)|![Screenshot_1637061267](https://user-images.githubusercontent.com/47198395/141977781-df24cb23-3740-4221-924f-66bef4f3c90e.png)|
|---|---|

**Comment by tobydox** [comment]
Thank you very much for your post! The remote login feature assumes a certain standard behavior of the Windows login screen. If it's changed e.g. by 3rdparty components, there's no way for Veyon to detect and handle this. Unfortunately we can't add support for such special cases.
