### ISSUE TITLE
RPM release

### ISSUE THREAD

**Issue by grkeller** [veyon/veyon#78]
Hello,

I wanted to try out veyon on CentOS 7.3 and I see you are currently running automated builds for this platform but it seems you don't publish the rpms. Is this something that you could consider for the next release?

Thanks!
Graziano

**Comment by tobydox** [comment]
The built binaries will be available with every upcoming release so it's just a question of days until we release the last RC (3.99.8). You should then be able to use the RPMs. For CentOS some extra dependencies such as GCC 6 runtime and Qt 5 from EPEL are required.

**Comment by grkeller** [comment]
Great news! I'm looking forward to test this out.

Thanks a lot for all the hard work on veyon and for making it open source!

Best,
Graziano

**Comment by pauloboc** [comment]
Do not forget the ".deb"

Looking forward to next time.
I have over 80 machines to install and test!

:)

**Comment by tobydox** [comment]
Veyon 4.0.0 has been released including binary packages for major Linux distributions :-)
