### ISSUE TITLE
Event 1000, Application Error

### ISSUE THREAD

**Issue by PappBence** [veyon/veyon#784]
After update to 4.7, I get a lots of error in Event Viewer:

Faulting application name: veyon-server.exe, version: 4.7.0.0, time stamp: 0x00000000
Faulting module name: Qt5Core.dll, version: 5.12.12.0, time stamp: 0x00000000
Exception code: 0xc0000602
Fault offset: 0x0000000000011ab1
Faulting process id: 0xde8
Faulting application start time: 0x01d7ec3bb68589e4
Faulting application path: C:\Program Files\Veyon\veyon-server.exe
Faulting module path: C:\Program Files\Veyon\Qt5Core.dll
Report Id: b09ec3d3-30e0-476f-bbbd-f2a877a77da2
Faulting package full name: %14
Faulting package-relative application ID: %15

Win 10 x64bit

**Comment by PappBence** [comment]
Any news?

**Comment by tobydox** [comment]
Not yet but we'll provide an update for testing at the beginning of next year.

**Comment by PappBence** [comment]
Not fixed in version 4.7.1

**Comment by PappBence** [comment]
Any news about it, can we help somehow? Thanks

**Comment by tobydox** [comment]
Do you have a special multi monitor setup? What graphics cards are you using? Is it a virtual machine?

**Comment by PappBence** [comment]
Not virtual machine, single 1 PC 1 Monitor setup. Before 4.7 version I didn't see this error.

**Comment by PappBence** [comment]
My bad, sorry. We use ESET Endpoint solutions in the school, and same HIPS rules block veyon-server.exe and veyon-service.exe process, because want to access other processes (explorer, winlogon). I whitelisted veyon and now error went away. The ticket can be closed. Thank you.
