### ISSUE TITLE
rdp when user disconnected

### ISSUE THREAD

**Issue by fabio1999ita** [veyon/veyon#789]
is possible watch screen if user is disconnected from rdp but its user is logged?

**Comment by tobydox** [comment]
First I'd recommend a recent thread in our community forum: https://veyon.nodebb.com/topic/2340/rdp-connections Does it answer your question?

**Comment by fabio1999ita** [comment]
i can see screen if rdp is on, but if rdp is off so session is disconnected no

**Comment by fabio1999ita** [comment]
so is there a way or not?

**Comment by tobydox** [comment]
I just tried to change the code such that it treats disconnected sessions as active sessions, i.e. starts a Veyon Server instance but obviously the server or the built-in VNC server is not able to access the disconnected session (likely blocked by the Windows API). So the short answer unfortunately is no :-(
