### ISSUE TITLE
Manjaro Linux (Arch) - Insufficient Privileges

### ISSUE THREAD

**Issue by mscdaddy30** [veyon/veyon#791]
I downloaded and created Veyon 4.7.0 (stable) on my Manjaro Linux system. I used the make install command at the end. When I run the veyon-configurator app from KDE Plasma I get an error saying the application has insufficient privilege. Then another error about not being able to write backend configuration files. I have tried running it with kdesu, but does not seem to fix it. I also noticed it installed in /usr/local/bin instead of /usr/bin/; not sure if this matters or not. Please advise on how to fix this issue.  Thank you in advance.

Richard Beale
Computer Science Principles Teacher
Pioneer Technology and Arts Academy

**Comment by tobydox** [comment]
I guess you built it from source? If so, please pass -DCMAKE_INSTALL_PREFIX=/usr to cmake so it gets installed in /usr. Then it should also install the PolicyKit file (io.veyon.veyon-configurator.policy) at the proper location so pkexec & friends should invoke the program with the proper permissions.

**Comment by mscdaddy30** [comment]
> I guess you built it from source? If so, please pass -DCMAKE_INSTALL_PREFIX=/usr to cmake so it gets installed in /usr. Then it should also install the PolicyKit file (io.veyon.veyon-configurator.policy) at the proper location so pkexec & friends should invoke the program with the proper permissions.

This flag did it.  I apologize. I am relatively new to Linux and since I was not on Debian or RedHat (examples in the instructions) I did not think it applied to my circumstances.  Thank you for your help!

**Comment by mscdaddy30** [comment]
Issue resolved
