### ISSUE TITLE
remote view or control windows opens two times for each screen

### ISSUE THREAD

**Issue by SlrG** [veyon/veyon#793]
When selecting one student screen for remote view or control by double clicking (and having the feature assigned to the double click) or right clicking or choosing the feature in the menu, the selected screen opens two times.

Selecting more than one screen will open each of them two times.

**Comment by bonez565** [comment]
Can confirm this on my devices as well.

**Comment by tobydox** [comment]
Oops, looks like we did non resolve a cherry picking conflict properly and left an old line of code so the remote access window gets open twice...

**Comment by tobydox** [comment]
New builds including the immediate bug fix are now officially available for download. Users of Veyon 4.7.1.0 should update to 4.7.1.3.
