### ISSUE TITLE
Veyon Master unintentionally modifies clipboard content of currently logged on user

### ISSUE THREAD

**Issue by MJakubec** [veyon/veyon#801]
When the Veyon Master application is open on a teacher's computer with several currently used classroom computers selected in its main window, a clipboard content of student users is periodically transferred into the clipboard of a teacher. When the Veyon Master is closed, the problem goes away. After you open the Veyon Master application again, the problem manifests again. Veyon version 4.7.1 installed on both the teacher and all student computers.

**Comment by SlrG** [comment]
Is it really when only the master is open or does it happen while a remote control window is open? In the first case its a bug, in the latter case its a new feature, not a bug.

**Comment by MJakubec** [comment]
> Is it really when only the master is open or does it happen while a remote control window is open? In the first case its a bug, in the latter case its a new feature, not a bug.

It is the first case, there were no explicit connections to student computers at all.

**Comment by SlrG** [comment]
Okay. Thanks for reporting. I'm sure @tobydox will have a look.
