### ISSUE TITLE
Add a security policy

### ISSUE THREAD

**Issue by JamieSlome** [veyon/veyon#805]
Hey there!

I belong to an open source security research community, and a member (@ysf) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by tobydox** [comment]
Thank you very much for your recommendations! Indeed we were lacking a security policy. I have just added an initial version via 65be60c2761aaeeeb16835a038faaa7270368cb0.

**Comment by JamieSlome** [comment]
@tobydox - amazing, appreciate your time!

We will send an e-mail over to you shortly. In the meantime, you can view the report directly here:

https://huntr.dev/bounties/4ea303f8-4ba5-4a2e-bbc4-44dd2a365e61/

It is private and only accessible to maintainers with repository write permissions! 👍
