### ISSUE TITLE
Build package to Ubuntu 22.04 (Jammy Jellyfish).

### ISSUE THREAD

**Issue by pauloboc** [veyon/veyon#809]
Canonical’s latest iteration to the Ubuntu operating system is Ubuntu 22.04 Jammy Jellyfish. 

Ubuntu 22.04 release date was April 21, 2022. This is an LTS (long term support) release.

Thanks

**Comment by tobydox** [comment]
Thanks for the reminder. Official Ubuntu 22.04 packages will be shipped with the next 4.7.4 release. Until then you can use our PPA where I just uploaded 4.7.3 for Ubuntu 22.04.
