### ISSUE TITLE
WOL Doesn,t work

### ISSUE THREAD

**Issue by FCarrascoV** [veyon/veyon#81]
I installed Veyon to monitor computers in a lab. These computers have the WOL feature enabled in the BIOS, and it worked commanded from Veyon Master, but from one moment to another stopped working, ie, the computers no longer start with the command executed from Veyon Master, but if they do with other WOL software.
The devices are configured with fixed IP (reserved in the router) and their respective MAC address. Please, I need your guidance to solve this.

**Comment by tobydox** [comment]
Has the version of Veyon changed? Are all MAC addresses set in the local data configuration on the Master computer?

**Comment by FCarrascoV** [comment]
I thought it was the software version. When I started using Veyon, I installed version 3.99.6 and everything worked fine, then when version 3.99.7 was released, it stopped working. I changed the version of the Master and all computers to version 3.99.7, but WOL still does not work. All MAC addresses are configured on the Master computer. Attachment configuration file.

{
    "AccessControl": {
        "AuthorizedUserGroups": [
        ]
    },
    "Authentication": {
        "KeyAuthenticationEnabled": "true",
        "LogonAuthenticationEnabled": "false",
        "PrivateKeyBaseDir": "$GLOBALAPPDATA\\keys\\private",
        "PublicKeyBaseDir": "$GLOBALAPPDATA\\keys\\public"
    },
    "Demo": {
        "FramebufferUpdateInterval": 100,
        "KeyFrameInterval": 10,
        "MemoryLimit": 128
    },
    "Directories": {
        "Screenshots": "$APPDATA\\Screenshots",
        "UserConfiguration": "$APPDATA\\Config"
    },
    "ExternalVncServer": {
        "ServerPort": 5900
    },
    "LDAP": {
        "ServerHost": "",
        "ServerPort": 389,
        "UseBindCredentials": "true"
    },
    "LocalData": {
        "NetworkObjects": {
            "JsonStoreArray": [
                {
                    "Name": "Sala de Computación",
                    "Type": 2,
                    "Uid": "{0b935231-657d-457c-82e5-cccad9121dc8}"
                },
                {
                    "HostAddress": "192.168.0.101",
                    "MacAddress": "C4:34:6B:82:40:85",
                    "Name": "PC01",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{6ccaec70-6690-4f64-98a9-afd924069b0d}"
                },
                {
                    "HostAddress": "192.168.0.102",
                    "MacAddress": "C4:34:6B:82:26:C7",
                    "Name": "PC02",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{8ee71942-e4dd-4c0d-bf3f-1a45deabfa2e}"
                },
                {
                    "HostAddress": "192.168.0.103",
                    "MacAddress": "C4:34:6B:82:24:8D",
                    "Name": "PC03",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{a14dd387-f379-4c5d-9134-2a1a698e5ccc}"
                },
                {
                    "HostAddress": "192.168.0.104",
                    "MacAddress": "C4:34:6B:82:25:6C",
                    "Name": "PC04",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{c29fd2c4-16a3-4b5b-b0df-e2eed7350859}"
                },
                {
                    "HostAddress": "192.168.0.105",
                    "MacAddress": "C4:34:6B:82:27:72",
                    "Name": "PC05",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{72286e94-7d78-4e8e-9648-1a809443e547}"
                },
                {
                    "HostAddress": "192.168.0.106",
                    "MacAddress": "C4:34:6B:82:25:B5",
                    "Name": "PC06",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{ff811f83-c6f7-4c1c-9b0d-381e032b7338}"
                },
                {
                    "HostAddress": "192.168.0.107",
                    "MacAddress": "C4:34:6B:82:26:0A",
                    "Name": "PC07",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{0a441ad8-e08d-4087-be15-0d645046c8de}"
                },
                {
                    "HostAddress": "192.168.0.108",
                    "MacAddress": "C4:34:6B:82:60:DD",
                    "Name": "PC08",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{4352ed3d-649e-4b42-a729-3b539d0c456b}"
                },
                {
                    "HostAddress": "192.168.0.109",
                    "MacAddress": "C4:34:6B:82:59:2B",
                    "Name": "PC09",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{904ea2e3-a189-4017-bd94-87949748dc8d}"
                },
                {
                    "HostAddress": "192.168.0.110",
                    "MacAddress": "C4:34:6B:82:28:1F",
                    "Name": "PC10",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{f6d1438f-6c7f-49a1-8d44-cfd35557b32b}"
                },
                {
                    "HostAddress": "192.168.0.111",
                    "MacAddress": "C4:34:6B:82:28:31",
                    "Name": "PC11",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{d9f7e699-02e6-4c70-962f-b9c0baaa4f9a}"
                },
                {
                    "HostAddress": "192.168.0.112",
                    "MacAddress": "C4:34:6B:82:26:1B",
                    "Name": "PC12",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{f411ec6c-e0d6-45ac-9c1d-4e7e5262ae72}"
                },
                {
                    "HostAddress": "192.168.0.113",
                    "MacAddress": "C4:34:6B:82:26:8D",
                    "Name": "PC13",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{26dce5da-f785-4537-b29d-5bcb662e6838}"
                },
                {
                    "HostAddress": "192.168.0.114",
                    "MacAddress": "C4:34:6B:82:32:E5",
                    "Name": "PC14",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{a927c5ec-67ed-42d5-a952-67c4a5511607}"
                },
                {
                    "HostAddress": "192.168.0.115",
                    "MacAddress": "C4:34:6B:82:28:24",
                    "Name": "PC15",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{e53aef4c-ed70-4505-8ff9-543a607e5fee}"
                },
                {
                    "HostAddress": "192.168.0.116",
                    "MacAddress": "C4:34:6B:82:3A:A4",
                    "Name": "PC16",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{41de6f78-0661-4b7e-b481-6ad37630c1d2}"
                },
                {
                    "HostAddress": "192.168.0.117",
                    "MacAddress": "C4:34:6B:82:32:D8",
                    "Name": "PC17",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{70475862-08e3-41d9-9b64-4f8966b9647c}"
                },
                {
                    "HostAddress": "192.168.0.118",
                    "MacAddress": "C4:34:6B:82:27:12",
                    "Name": "PC18",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{cd47ea63-6762-47e3-96ee-a724c99a7b59}"
                },
                {
                    "HostAddress": "192.168.0.119",
                    "MacAddress": "C4:34:6B:82:24:50",
                    "Name": "PC19",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{0aadf611-1601-47c2-8299-76213535244c}"
                },
                {
                    "HostAddress": "192.168.0.120",
                    "MacAddress": "C4:34:6B:82:25:A1",
                    "Name": "PC20",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{0a0b81e8-7b0a-4de0-8002-531bf8a61460}"
                },
                {
                    "HostAddress": "192.168.0.121",
                    "MacAddress": "C4:34:6B:82:26:0F",
                    "Name": "PC21",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{4e8e4999-29ab-44fe-a624-65d152f1bf58}"
                },
                {
                    "HostAddress": "192.168.0.122",
                    "MacAddress": "C4:34:6B:82:27:17",
                    "Name": "PC22",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{fee0b3fd-a47e-48e1-b779-da5bfb71afb0}"
                },
                {
                    "HostAddress": "192.168.0.123",
                    "MacAddress": "C4:34:6B:82:25:B6",
                    "Name": "PC23",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{c9e7a4ba-af57-4191-8d42-d1e05906f0a3}"
                },
                {
                    "HostAddress": "192.168.0.124",
                    "MacAddress": "C4:34:6B:82:26:7D",
                    "Name": "PC24",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{5909a9d5-7dd7-47bd-b828-41280f7db184}"
                },
                {
                    "HostAddress": "192.168.0.125",
                    "MacAddress": "C4:34:6B:82:3E:91",
                    "Name": "PC25",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{754dfcfd-1176-4c35-90ef-780f4bf1ceac}"
                },
                {
                    "HostAddress": "192.168.0.126",
                    "MacAddress": "C4:34:6B:82:25:20",
                    "Name": "PC26",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{d49f0b9d-6371-4082-a2f6-e81945702f1d}"
                },
                {
                    "HostAddress": "192.168.0.127",
                    "MacAddress": "C4:34:6B:82:26:90",
                    "Name": "PC27",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{11d832c5-e30f-43d0-9d6d-0ae532ea2f4c}"
                },
                {
                    "HostAddress": "192.168.0.128",
                    "MacAddress": "C4:34:6B:82:24:66",
                    "Name": "PC28",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{bc9c20b0-f546-4656-9387-61ebd1035fe1}"
                },
                {
                    "HostAddress": "192.168.0.129",
                    "MacAddress": "C4:34:6B:82:24:97",
                    "Name": "PC29",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{1c8ea0e4-57a3-446f-a3b2-76d3150895e1}"
                },
                {
                    "HostAddress": "192.168.0.130",
                    "MacAddress": "C4:34:6B:82:28:88",
                    "Name": "PC30",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{d18a82b2-df14-4bc7-80e6-a56b9fca0a70}"
                },
                {
                    "HostAddress": "192.168.0.131",
                    "MacAddress": "C4:34:6B:82:3A:14",
                    "Name": "PC31",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{06ffd482-b1d4-408d-b472-f87949f36dd9}"
                },
                {
                    "HostAddress": "192.168.0.132",
                    "MacAddress": "C4:34:6B:82:40:59",
                    "Name": "PC32",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{4767fdad-8b5a-490f-a1bb-81999a6ff144}"
                },
                {
                    "HostAddress": "192.168.0.133",
                    "MacAddress": "C4:34:6B:82:31:4D",
                    "Name": "PC33",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{cf94e446-2534-47a3-a9e5-c443a7000ff4}"
                },
                {
                    "HostAddress": "192.168.0.134",
                    "MacAddress": "C4:34:6B:81:DD:A9",
                    "Name": "PC34",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{b840b978-4a24-4fbb-a3e3-4f7e0277c249}"
                },
                {
                    "HostAddress": "192.168.0.135",
                    "MacAddress": "C4:34:6B:82:31:A3",
                    "Name": "PC35",
                    "ParentUid": "{0b935231-657d-457c-82e5-cccad9121dc8}",
                    "Type": 3,
                    "Uid": "{26aa5cbb-6ee4-4612-8fea-16f2c85ddab3}"
                }
            ]
        }
    },
    "Logging": {
        "LogFileDirectory": "$TEMP",
        "LogFileRotationCount": 10,
        "LogFileRotationEnabled": "false",
        "LogFileSizeLimit": 100,
        "LogFileSizeLimitEnabled": "false",
        "LogLevel": 4,
        "LogToStdErr": "true",
        "LogToWindowsEventLog": "false"
    },
    "Master": {
        "ComputerDoubleClickFeature": "{ca00ad68-1709-4abe-85e2-48dff6ccf8a2}"
    },
    "Network": {
        "DemoServerPort": 11400,
        "FeatureWorkerManagerPort": 11300,
        "FirewallExceptionEnabled": "1",
        "PrimaryServicePort": 11100,
        "VncServerPort": 11200
    },
    "NetworkObjectDirectory": {
        "Plugin": "{14bacaaa-ebe5-449c-b881-5b382f952571}",
        "UpdateInterval": 60
    },
    "Service": {
        "Arguments": "",
        "Autostart": "true",
        "HideTrayIcon": "false",
        "SoftwareSASEnabled": "1"
    },
    "UI": {
        "ApplicationName": "",
        "EnableHighDPIScaling": "true",
        "Language": "Spanish - español de España (es_ES)"
    },
    "UltraVNC": {
        "CaptureLayeredWindows": "true",
        "Configured": "true",
        "LowAccuracy": "true",
        "PollFullScreen": "true"
    },
    "VncServer": {
        "Plugin": "{39d7a07f-94db-4912-aa1a-c4df8aee3879}"
    }
}

**Comment by tobydox** [comment]
The configuration looks fine. Did you install any operating system updates or changed/updated your network firewall? Did you change the switch/router configuration? I'm asking because nothing WOL-related has changed between 3.99.6 and 3.99.7. Can you set log level to "debug", clear config files and wake computers via Master? Afterwards look at the VeyonMaster.log file for suspicious messages.

**Comment by tobydox** [comment]
Closing due to missing feedback - request to reopen if necessary :-)

**Comment by FCarrascoV** [comment]
Ok. Thanks
