### ISSUE TITLE
linux: Open website doesn't work on KDE

### ISSUE THREAD

**Issue by Blarse** [veyon/veyon#817]
This is because the Veyon server starts separately from the KDE session, and its environment does not have the KDE_SESSION_VERSION variable, which is used in the xdg-open script.

I propose to set XDG_CURRENT_DESKTOP to X-Generic

**Comment by tobydox** [comment]
Actually Veyon Service tries to fetch all environment variables from the session processes (by traversing all processes starting from the session leader) but obviously it's missing some parts. Can you verify the contents of `/proc/<veyon-server-PID>/environ`? Would manually setting `XDG_CURRENT_DESKTOP` to `X-Generic` help to workaround this issue?

**Comment by Blarse** [comment]
> Actually Veyon Service tries to fetch all environment variables from the session processes (by traversing all processes starting from the session leader) but obviously it's missing some parts.

I see, but this only happens if KDE session starts after veyon is started (on the boot).
`cat "/proc/$(pidof veyon-server)/environ" | tr '\0' '\n' | grep -i KDE`:
```
KDE_APPLICATIONS_AS_SCOPE=1
KDE_FULL_SESSION=true
KDE_SESSION_UID=500
KDE_SESSION_VERSION=5
XDG_CONFIG_DIRS=/home/test/.config/kdedefaults:/etc/kf5/xdg:/etc/xdg
XDG_CURRENT_DESKTOP=KDE
XDG_SESSION_DESKTOP=KDE
```
And after `systemctl restart veyon.service`:
```
XDG_CURRENT_DESKTOP=KDE
XDG_SESSION_DESKTOP=KDE
```


> Would manually setting `XDG_CURRENT_DESKTOP` to `X-Generic` help to workaround this issue?

Adding `setenv("XDG_CURRENT_DESKTOP", "X-Generic", 1);` to LinuxPlatformPlugin() constructor helped though.

**Comment by Blarse** [comment]
ping

**Comment by tobydox** [comment]
I'll deal with it as soon as I return from vacation in July ;-)

**Comment by tobydox** [comment]
I hope this workaround covers your case and fixes the issue for you. Any feedback is welcome :-)
