### ISSUE TITLE
Incorrect behavior on two-monitors hw config on windows when primary screen is on the right

### ISSUE THREAD

**Issue by ilya84** [veyon/veyon#818]
Hello! I want to suggest a fix on situation described in header.

**Config locale (master):** Win10, two monitors in different resolutions, primary 1680x1050, secondary: 1366x768 (TV); secondary monitor stands on the left from primary, and tuned in OS in that position.
**Config remote (server):** Win10, (so as upper), primary 1980x1050, secondary 1280x1024 (old 17"); monitors stands and tuned as on master

When I connect to that config and select "All Screens" view, all right and no problems appears. But only I choose primary (right) screen of remote connection, I get... this:
![veyon2scrnbug](https://user-images.githubusercontent.com/11805368/173511701-ea9682f9-2ad9-4b20-b51d-fdd5714cf754.png)

Selecting secondary screen shows darkness.

On Windows OS upper left conner of primary screen always have zero coordinates. And if secondary screen locates to the left (or upper), then it has negative X and/or Y. RemoteViewWidget counts coordinates from zero (cause it is QWidget), and content on "negative space" cuts. Veyon knows about it and place content of widget from zero coordinates. But viewports for screens stays on their places, on negative coords.

So my fix calculates min x and y coordinates for all remote screens for RemoteViewWidget and corrects update procedure with this values. It changes only RemoteViewWidget.cpp in about 15 lines. I can just copy-paste patch here, but maybe PR?

RemoteAccessWidget.cpp; from line 286:
```
		menu->addSeparator();

		int min_x, min_y; bool init_mins=false;
		for (const auto& screen : screens)
		{
			if (!init_mins) {
				min_x=screen.geometry.x();
				min_y=screen.geometry.y();
				init_mins=true;
			}
			if (screen.geometry.x() < min_x) min_x=screen.geometry.x();
			if (screen.geometry.y() < min_y) min_y=screen.geometry.y();
		}

		for (const auto& screen : screens)
		{
			const auto action = menu->addAction(screen.name, this, [=]() {
				QRect real_geometry = screen.geometry;
				real_geometry.moveTo(screen.geometry.x()-min_x,screen.geometry.y()-min_y);
				m_parent->vncView()->setViewport(real_geometry);
			});
			action->setCheckable(true);
```

**Comment by tobydox** [comment]
Thank you very much for reporting this issue and a solution! I will have a look at it and adopt the code according to your proposal. Alternatively, please adopt our coding style (i.e. `minX` instead of `min_x` and `auto realGeometry` instead of `QRect real_geometry` etc.) and send a PR if you like.

**Comment by ilya84** [comment]
Understand, great thanks :) but my PR will cooked in some days. My fighting with git goes on...

**Comment by ilya84** [comment]
ouppss :)
awaited for button jump, but itself :-]

**Comment by ilya84** [comment]
Is there anything I need to do in this situation?
