### ISSUE TITLE
Dual screen doesn't show

### ISSUE THREAD

**Issue by benoitfouc** [veyon/veyon#82]
Hi, if the client have 2 screens or more, we see only the principal screen, we can't see the other.
An idea ?

Friendly

**Comment by davidlig** [comment]
+1 

I'm interested too, italc did not either.

**Comment by jimmy5678** [comment]
I programmed it to work on duel screens using dfmirage to view both screens and tweaked a few files to run. dfmirage works better then mv2 driver (allows aero to work correctly and does not change screens background or size of screen on client/student end )works on windows 7 and windows 10 for sure. I'm not sure how to submit the changes for review.

**Comment by tobydox** [comment]
I'll add an option to make internal UltraVNC transmit both screens :-)

@jimmy5678 contributions are welcome, feel free to submit a pull request for review.

**Comment by davidlig** [comment]
Thanks!!!

**Comment by benoitfouc** [comment]
Thank a lot !
The update is automatic for the client ?
