### ISSUE TITLE
Wake on LAN not working and lacking information

### ISSUE THREAD

**Issue by tylla** [veyon/veyon#840]
I'm running Veyon 4.1.7 (Win10/Linux master with Win10 clients) and I'm having two problems using the WakeOnLAN feature.

1. What format is awaited by Veyon for the MAC address? There is no mention about the format of the MAC address, whether it should be colon-, hyphen-separated or concatenated.
2. I tried all three possibilities anyway and none of them worked. All this while trying to wake the same machines with an alternate program (Depicus' [WoL GUI](https://www.depicus.com/wake-on-lan/wake-on-lan-gui)) worked perfectly every time.

The first I suppose could be simply solved, and the documentation should be extended as well with the proper information.

The second one needs some extra craft.
Where should I look or what other information should I provide to be able to troubleshoot this problem?

**Comment by tylla** [comment]
Meanwhile I have updated to 4.8.2 and in parallel I figured out the needed format: it needs to be concatenated.
This should be updated in the docs to be easily found by newbies.

**Comment by tobydox** [comment]
Thank you for your submission! However I really wonder why MAC addresses only work on concatenated format. According to https://github.com/veyon/veyon/blob/master/plugins/powercontrol/PowerControlFeaturePlugin.cpp#L356 any delimiters should work since they are removed internally anyway. Can you retry your tests with 4.8.2 and with various delimiters?

**Comment by tylla** [comment]
Well it seems that in the last more than a year this changed (or I had some other strange issues back in the days when I reported the issue).
Now I have double checked (I planned this the other day as well, but now I had some time), and all variations (concatenated, colon and dash separated) work as should.

So I would say this ticket should advance to the topic of "include the MAC address formatting information in the docs", so that when someone gets some doubts, s/he should be assured that if it does not work, it's not the formatting that gets in the way.

Can we contribute to the docs, or we have to wait until someone with the proper rights does these changes to it?
