### ISSUE TITLE
Security: passwords saved is plaintext

### ISSUE THREAD

**Issue by ideamk** [veyon/veyon#87]
If use external vnc-server plugin, password saved on cleartext
**Registry path**: HKEY_LOCAL_MACHINE\SOFTWARE\Veyon Solutions\Veyon\ExternalVncServer
**Keyname**: Password

If use LDAP bind, password also saved on cleartext
**Registry path**: HKEY_LOCAL_MACHINE\SOFTWARE\Veyon Solutions\Veyon\LDAP
**Keyname**: BindPassword

**Version**: 3.99.7

**Comment by tobydox** [comment]
This is still on my TODO list so thanks for reporting this here to prioritize it.

**Comment by tobydox** [comment]
Fixed via 4b6bd4a37731a518921119b9773ad878e3bf204e and 7014d7e0f0b6191631d762436d9d3920a6d8d802 and will be part of Veyon 4.1.
