### ISSUE TITLE
Veyon 4.7.5 is reported infected with Gen:Trojan.Heur.FU.eI3@aGFEPZdi by Bitdefender on Windows

### ISSUE THREAD

**Issue by yanottamao** [veyon/veyon#871]
Veyon 4.7.5 Windows setup file is reported infected with Gen:Trojan.Heur.FU.eI3@aGFEPZdi by Bitdefender on Windows, is this a false positive?

![image](https://user-images.githubusercontent.com/22324216/221780135-3ac8974d-aac6-4c9b-ab70-8e0aa3fb5af5.png)

On the same system, Veyon 4.7.20 setup file is reported clean

**Comment by tobydox** [comment]
I'm sure this is a false positive. Our installers are built in a clean Linux-based CI environment so we can guarantee that the files which you can download at https://github.com/veyon/veyon/releases/ do not contain any trojans, virusses or malware.
