### ISSUE TITLE
See how long a user has been logged in

### ISSUE THREAD

**Issue by paul-pascual** [veyon/veyon#876]
Hi,
I have a suggestion for veyon.
I need to be able to rotate the students in my computer room every 30 minutes. But for now, I use a spreadsheet with the arrival time and a formula calculating the exit time.
I would like to have this directly in veyon next to the user name for example.

Thanks in advance :)

**Comment by tobydox** [comment]
Thanks for the suggestion. This is a duplicate of #821 and is going to be implemented in the upcoming 4.8.0 release.

**Comment by paul-pascual** [comment]
Thank you !
I'm sorry for the duplicate :/

**Comment by tobydox** [comment]
Don't worry, it's just for documentation purposes so we keep track of duplicates ;-)

**Comment by paul-pascual** [comment]
Other question, when version 4.8 is released ?

**Comment by tobydox** [comment]
This month ;-)

**Comment by paul-pascual** [comment]
Thank you :)

**Comment by paul-pascual** [comment]
Hi,
Hi have updated all my pcs but but i don’t see how to display the connection time :/
