### ISSUE TITLE
Veyon

### ISSUE THREAD

**Issue by staceypillage** [veyon/veyon#88]
Hello, I may be missing something very obvious, but after installing Veyon. I can't add classrooms or computers.
I click on computer rooms at the bottom left which opens the tall list box, but I can't see how to add items.
iTalc allowed entry with a right click in the Room/Computer box.
Am I missing something very basic ?

I can click on Remote View or Remote Control icons; add an IP and connect OK.

**Comment by tobydox** [comment]
We moved this (administrative) functionality to the Veyon Configurator tool. This means you will have to add rooms and computers in the "Local data" configuration page in the Veyon Configurator. This way Veyon Master is an even more simple to use program which only offers features used by end users (such as teachers).

**Comment by staceypillage** [comment]
Hello, thank you for the reply.
I really should look harder !
Thank you onceagain.
Regards

Peter Morrison

ICT Technician

Rothesay Joint Campus

________________________________________
