### ISSUE TITLE
Point d'entrée CreateEventW introuvable dans api-ms-win-core-synch-l1-2-0.dll

### ISSUE THREAD

**Issue by SebCanet** [veyon/veyon#883]
Bonjour,
je viens d'installer la v4.8.0 mais elle ne se lance pas avec l'erreur contenue dans le titre, c'est sur un Windows 7x64.
Merci d'avance.

**Comment by tobydox** [comment]
Thank you for your report! However we're sorry but Veyon doesn't support Windows 7 any longer since it's End-Of-Life anyway. You can continue using previous releases of Veyon.

**Comment by SebCanet** [comment]
This is a real shame for Windows 7 users....
So you should write it on your website on download page.
Thanks.

**Comment by tobydox** [comment]
I can understand but I guess you also don't receive any Windows updates, don't you?

**Comment by SebCanet** [comment]
I don't see the connection at all....
Anyway, thanks for updating the download page, and thanks for this great tool.
