### ISSUE TITLE
Veyon 4.8.0 no longer works on Windows 7

### ISSUE THREAD

**Issue by niltwill** [veyon/veyon#884]
The Qt update from 5.12 to 6.5 also means that Veyon is no longer usable on Windows 7 (and 8.x). Because the last Qt version these OSes can use is 5.x, 6.x dropped support for them. It will keep erroring out that the "CreateEventW" entry point cannot be found in DLL (api-ms-win-core-synch-l1-2-0.dll). I tested this with Windows 7 on two computers and the error is the same. Hitting repeatedly ok on this error message can install Veyon, but it will not be usable.

So if you don't use Windows 10 or Windows 11, do not update to 4.8.0, keep it at 4.7.5. That's the last usable version for these legacy operating systems.

@tobydox I opened this issue because you should warn users about this, otherwise they'll face a nasty surprise at installation. (Not sure how many users use these legacy OSes, but still). It would be good to notify users that due to Qt 6, Veyon no longer works on Windows 7 and 8 (beyond 4.7.5).

**Comment by tobydox** [comment]
Thank you for pointing out this issue! We added a note on our download page so Windows 7 users are able to switch to 4.7.5 easily.
