### ISSUE TITLE
Installer fails with error 0xc000007b if mandatory ASLR is enabled

### ISSUE THREAD

**Issue by damiel-gc** [veyon/veyon#885]
The Veyon installer for Windows fails like this with error 0xc000007b if mandatory ASLR is enabled:
![veyon-setup](https://github.com/veyon/veyon/assets/133098543/5452e33b-f335-4864-9475-5b709c373c25)
The current version 4.8.0.4 shows the same problem, while 4.7.4.0 worked fine for me.

Mandatory ASLR is an optional security feature in Windows that can be enabled in the Windows Security app under "App & browser control", or through group policy.

I managed to work around the problem by including an exception for the Veyon installer in the MitigationPolicy.xml I am distributing through group policy. It looks like this (the Veyon installer is the only application where I have ever seen this problem):
```
<?xml version="1.0" encoding="UTF-8"?>
<MitigationPolicy>
  <SystemConfig>
    <ASLR ForceRelocateImages="true" RequireInfo="false" />
  </SystemConfig>
  <AppConfig Executable="veyon-4.8.0.4-win64-setup.exe">
    <ASLR ForceRelocateImages="false" />
  </AppConfig>
</MitigationPolicy>
```
In addition to fixing the problem, it would be good, if the Veyon installer is compiled in a way that ASLR is always enabled (e. g. with /dynamicbase). An even better solution would be to replace the EXE installer with aa proper Windows Installer MSI package that also allows easy deployment by group policy.

**Comment by tobydox** [comment]
4.8.1 has been released. Can you please try the latest installers?

**Comment by damiel-gc** [comment]
4.8.1 works for me with mandatory ASLR! That's great, thank you very much for the fix.

**Comment by tobydox** [comment]
Thanks for the feedback!
