### ISSUE TITLE
veyon-cli feature error on 4.8.0 and 4.7.5

### ISSUE THREAD

**Issue by wnmail** [veyon/veyon#887]
I made an error following the official example：

veyon-cli.exe feature help start 

PS C:\Program Files\Veyon> .\veyon-cli.exe feature start 192.168.100.110 TextMessage "{\\"text\\":\\"Test message\\"}"
[ERROR] Error parsing the JSON-encoded arguments: unterminated object
[ERROR] Invalid arguments given

PS C:\Program Files\Veyon> .\veyon-cli.exe feature start 192.168.100.110 da9ca56a-b2ad-4fff-8f8a-929b2927b442 "{\\"applications\\":\\"notepad\\"}"
[ERROR] Error parsing the JSON-encoded arguments: unterminated object
[ERROR] Invalid arguments given

**Comment by hoeppnerf** [comment]
I second this issue. 

I'm trying to do the following:

PS C:\Program Files\Veyon> $jsoninput = '{ "Username": "test.schueler01", "Password": "testtest" }'
PS C:\Program Files\Veyon> $jsoninput | ConvertFrom-Json

Username    Password
--------    --------
test.schueler01 testtest

PS C:\Program Files\Veyon> .\veyon-cli.exe feature start R00601 UserLogin $jsoninput
[FEHLER] Fehler beim Parsen der JSON-kodierten Argumente: Nicht abgeschlossenes Objekt
[FEHLER] Ungültige Argumente angegeben

**Comment by tobydox** [comment]
This seems to be a PowerShell-specific escaping issue. When issueing

`veyon-cli feature start 127.0.0.1 TextMessage '{\"text\": \"Test message\"}'`

everything works.
