### ISSUE TITLE
api-ms-win-core-synch-l1-2-0.dll can not be located

### ISSUE THREAD

**Issue by iliaskessaris** [veyon/veyon#888]
While I am trying to install veyon 4.8.0.4 as Master on a server with server 2008 (64 bit version) windows, the following message appears at various stages of the installation:
"The procedure entry point CreateEventW could not be located in the dynamic link library api-ms-win-core-synch-l1-2.0.dll".
The strange thing is that the api-ms-win-core-synch-l1-2.0.dll exists in both C:\Windows\SysWOW64 and C:\Windows\System32 folders as it should be.
The 32 bit version of the file has 11512 bytes (SysWOW64 folder) size and 64 bite version 12024 (system32 folder)
![problem](https://github.com/veyon/veyon/assets/19271392/28fbddcf-32c3-41c0-ae89-97a0e4564399)

**Comment by tobydox** [comment]
Veyon 4.8 does not support Windows 7 / Server 2008 any longer since they are not End-Of-Life/Service anyway. Please use/downgrade to Veyon 4.7.x or upgrade to a newer version of Windows. I'm sorry that we can't help here any further.

**Comment by iliaskessaris** [comment]
Thank you for your immediate response. I have already done. However I was hoping for a solution for veyon 4.8.
