### ISSUE TITLE
Failed readproc.h build on arch linux

### ISSUE THREAD

**Issue by swhaat** [veyon/veyon#893]
Current Arch linux fails to build veyon 4.8.1, on either QT5 or QT6, with the error:

```
[ 63%] Building CXX object plugins/powercontrol/CMakeFiles/powercontrol.dir/Unity/unity_0_cxx.cxx.o
In file included from /build/veyon/src/build/plugins/platform/linux/CMakeFiles/linux-platform.dir/Unity/unity_0_cxx.cxx:13:
/build/veyon/src/veyon/plugins/platform/linux/LinuxServerProcess.cpp:28:10: fatal error: proc/readproc.h: No such file or directory
   28 | #include <proc/readproc.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [plugins/platform/linux/CMakeFiles/linux-platform.dir/build.make:111: plugins/platform/linux/CMakeFiles/linux-platform.dir/Unity/unity_0_cxx.cxx.o] Error 
```
Thanks for any suggestions..

**Comment by tobydox** [comment]
Do you have development packages of libprocps or libproc2 installed?

**Comment by swhaat** [comment]
It uses [procps-ng](https://archlinux.org/packages/core/x86_64/procps-ng) which i thought would include the libs.. 
Turns out it doesnt, the libs are at [libprocps](https://archlinux.org/packages/extra/x86_64/libprocps/), and it builds with no problems.. 
Thanks
