### ISSUE TITLE
Veyon Links not working - Veyon installers for Windows via veyon.io downloads page

### ISSUE THREAD

**Issue by SolarPH** [veyon/veyon#894]
The Veyon Download Page doesn't direct me to the latest release downloadable file (veyon 4.8.1 for Windows 64bit and 32bit as this report is being written). However, I can navigate my way to it via the Github Hyperlink for Veyon 4.7.5.

Can this be fixed for future users?

**Comment by tobydox** [comment]
Thank you very much for reporting the broken links! I just fixed them.
