### ISSUE TITLE
Veyon doesn't work on Windows Login Screen and Close all applications

### ISSUE THREAD

**Issue by pedrostorti** [veyon/veyon#9]
Hello.

In testing with Veyon, I realized that the software does not perform on-screen monitoring of Windows users.

In iTALC this function worked, where it could perform the remote access by iTALC itself and logged in to the PCs.

Would it be possible to create a closed applications function to close all programs on the monitored stations?

Thanks if you can help.

**Comment by pedrostorti** [comment]
I've done the verification, and the function is working.
I think it was my mistake.

**Comment by tobydox** [comment]
Thanks for the feedback anyways!

**Comment by pedrostorti** [comment]
Would it be possible to create a closed applications function to close all programs on the monitored stations?
