### ISSUE TITLE
Configurator Crash - 4.8.2

### ISSUE THREAD

**Issue by PappBence** [veyon/veyon#901]
I updated from 4.7.3 to 4.8.2, and configurator crash when click to Access control.
If I first click LDAP Basic settings and then Access control everything OK.

LDAP settings configured and working fine.
With downgrade to 4.7.3, it's not happening.

Windows 10 Enterprise 22H2 64-bit

Faulting application name: veyon-configurator.exe, version: 4.8.2.0, time stamp: 0x64da2c44
Faulting module name: ntdll.dll, version: 10.0.19041.2788, time stamp: 0x2f715b17
Exception code: 0xc00000fd
Fault offset: 0x000000000002aa2c
Faulting process id: 0x2f20
Faulting application start time: 0x01d9e3e4b75e1e96
Faulting application path: C:\Program Files\Veyon\veyon-configurator.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 30eb0857-8c4c-4355-abd4-8f3e02923dc4
Faulting package full name: 
Faulting package-relative application ID: 

Faulting application name: veyon-configurator.exe, version: 4.8.2.0, time stamp: 0x64da2c44
Faulting module name: Qt6Core.dll, version: 6.5.3.0, time stamp: 0x64da2c43
Exception code: 0xc00000fd
Fault offset: 0x00000000000f75b7
Faulting process id: 0x1acc
Faulting application start time: 0x01d9e3e7b24aaaff
Faulting application path: C:\Program Files\Veyon\veyon-configurator.exe
Faulting module path: C:\Program Files\Veyon\Qt6Core.dll
Report Id: 6c7f24b1-86f6-42e0-aaf8-0fca26d6ee9a
Faulting package full name: 
Faulting package-relative application ID:

**Comment by tobydox** [comment]
Confirming. Will be fixed in 4.8.3.
