### ISSUE TITLE
Automatische Client Installation mit Intune

### ISSUE THREAD

**Issue by schuladmin** [veyon/veyon#915]
Hallo, ich brauche Hilfe bei der Ausrollung von Veyon über Microsoft Intune. 
Leider funktioniert die automatische Übernahme der Konfiguration (Schlüsselauthentifizierung) nicht wie in der Dokumentation beschrieben ... - am Client kommt das immer als Anmeldeauthentifizierung an - und somit ist kein Zugriff möglich (Rechner wird rot angezeigt). Wenn ich händisch die Konfiguration und den public-Schlüssel importiere, dann funktioniert es ... ist aber keine Option ...
Ich bräuchte eine klare Anleitung, wie die automatische Übertragung der Konfiguration und des Schlüssels über Intune funktioniert ... ich teste schon Tage herum und kommen nicht weiter
Bitte um Hilfe!

**Comment by OCA-it** [comment]
Hallo Schuladmin,

hast du auch on-prem Server?
Wir verteilen Veyon via Intune und die JSON-Konfiguration zusätzlich via GPO.

Der Intune-Installationsbefehl sieht für den Service (Schüler) wie folgt aus:
veyon-4.8.2.0-win64-setup.exe /S /NoMaster /ApplyConfig=\\DOMAIN\NETLOGON\tools\veyon.json

Bei uns war das Problem, dass sich nicht jedes Gerät die Konfiguration gezogen hatte und wir zudem in der Testphase diverse Änderungen in der Konfiguration vorgenommen haben.

Daher haben wir eine zusätzliche GPO aktiviert:
Geplante Aufgabe > Jede Stunde > Programm starten
Programm: C:\Program Files\Veyon\veyon-cli.exe
Argument: config import "\\DOMAIN\NETLOGON\tools\veyon.json"

Seit dem haben wir keine Probleme mehr.

VG
Niko

**Comment by tobydox** [comment]
It's important to know that authentication keys are not part of the configuration since they are not stored in the platform-specific configuration store (i.e. Windows registry etc.) but in separate files. Therefore they have to be imported separately. This can be automated as well via `veyon-cli authkeys import ...` – see https://docs.veyon.io/en/latest/admin/cli.html#authentication-key-management (or German version at https://docs.veyon.io/de/latest/admin/cli.html#authentication-key-management) for details

**Comment by schuladmin** [comment]
Danke für eure Tipps! 
@OCA-it Meine Schülergeräte sind nur im AzureAD und nicht im lokalen AD eingebunden - daher sind GPOs (soweit ich das durchblicke, bin Anfängerin) keine Möglichkeit. Auf die Idee mit der seperaten Ausrollung der Konfiguration und des Schüssels bin ich schon gekommen, weiß aber nicht, wie die dann in Veyon automatisch importiert werden kann...
@tobydox Ja, diese Beiträge in der Dokumentation hab ich schon mehrfach gelesen, fange aber leider nichts damit an, da fehlt mir als Anfängerin das Hintergrundwissen ...

**Comment by OCA-it** [comment]
Entschuldige die späte Rückmeldung.
Ich habe ein gutes Video für dich gefunden: https://www.youtube.com/watch?v=k8WQbjlajlQ

Anhand dieser Anleitung könntest du die Konfigurationsdatei auf die Geräte verteilen.
Das Script aus dem Video müsstest du entsprechend anpassen und die Konfigurationsdatei und Authkeys noch beifügen.
Ebenso müsstest du das Script um die CLI-Befehle erweitern > Siehe den Beitrag von tobydox.

Alternativ könntest du auch nach der Videoanleitung die Dateien verteilen und mit einer geplanten Aufgabe arbeiten, welche z.B. bei jedem Start eines Gerätes die CLI-Befehle ausführt.

LG
Niko

**Comment by schuladmin** [comment]
Vielen lieben Dank!

**Comment by schuladmin** [comment]
Hallo nochmals,
ich habe mich in letzter Zeit ein wenig mit Powershell beschäftigt, da ich nur von früher ein paar alte DOS-Befehle kenne und sonst mit dem Skripten blank bin ...
Jetzt komme ich zu meinem Problem zurück und komme trotzdem nicht weiter: Wenn ich versuche veyon-cli zu öffnen, ploppt nur ganz kurz das schwarze Fenster auf und das war's. Wie soll ich mit veyon-cli arbeiten, wenn ich da gar nicht reinkomme?  
Oder muss ich da ein PowerShell-Skript schreiben?
Leider steht das in der Hilfe so, als ob das sonnenklar wäre. Ist es für mich nicht ...
Bitte um Hilfe! Danke!
lg Schuladmin

**Comment by SlrG** [comment]
veyon-cli (cli = command-line-interface) ist ein Kommandozeilentool bzw. unter Windows auch Eingabeaufforderungstool. Es funktioniert, wie die von Dir benannten alten DOS-Befehle, nur auf der Kommandozeile und indem Du ihm entsprechende Befehlsparameter mitgibst. Klickst Du es einfach nur doppelt an, weiß es nicht was es eigentlich tun soll und schließt sich sofort wieder.

Um eine Kommandozeile zu starten bitte cmd.exe öffnen (einfach Windows-Taste einmal drücken und cmd eingeben, dann sucht Windows nach dem Programm). Das Programm muss u. U. als Administrator gestartet werden, damit veyon-cli Zugriff auf alle nötigen Registry Schlüssel hat. Es öffnet sich ein schwarzes Fenster, indem Du dann Kommandozeilenbefehle und auch veyon-cli benutzen kannst.

Dazu zuerst mit ```cd "\Program Files\Veyon``` in den Ordner wechseln, wo Veyon und damit veyon-cli installiert ist (der Befehl kann je nach Installationspfad bei Dir auch anders aussehen!) oder das Veyon Verzeichnis zum Pfad hinzufügen.

Die Powershell ist auch ein Kommandozeilenfenster und müsste eigentlich ebenfalls funktionieren. Auch dort in den Pfad wechseln und dann veyon-cli verwenden.

Skripte lassen sich sowohl als BAT-Dateien, als auch als Powershell Skripte erstellen. Dazu bitte die entsprechenden Suchbegriffe in eine Suchmaschine Deiner Wahl eingeben.

Leider wirst Du Dich im Rahmen Deiner Arbeit als Schuladmin ausführlich in solche Betriebssystemgrundlagen einarbeiten müssen.

**Comment by schuladmin** [comment]
Danke, bin schon am Tüfteln und Testen! Danke nochmals!

**Comment by schuladmin** [comment]
Danke nochmals, SirG!
Deine Hinweise haben mich auf die richtige Fährte geführt! Ich hab es geschafft - bis auf eine gefühlte Kleinigkeit, da hab ich noch eine Frage:
Ich möchte Veyon ja via Intune verteilen. Verteilung des Clients war kein Problem. Verteilung des Schlüssels läuft seit heute auch. Auch die Konfiguration konnte ich heute endlich via Intune importieren lassen - nur da bekomme ich von Intune eine Fehlermeldung, weil die Erkennungsregel nicht passt. 
Jetzt meine Frage: Wird die Konfigurationsdatei irgendwo im System abgelegt? Ich konnte sie nicht finden. Oder werden beim Import der Konfiguration nur die Infos eingespielt? Ich bräuchte zur Definition der Erkennungsregel eine Datei, die sich ändert ... hab aber im System nichts gefunden... (Ich habe absichtlich den Config-Import von der Client-Installation getrennt, da ich sicher immer wieder die Konfiguration ändern muss, z.B. wenn neue Schüler (mit ihren Rechnern) dazukommen. Jetzt will Intune natürlich auch eine eigene Erkennungsregel, ob die Config-Installation geklappt hat ...)
Hat jemand eine Idee?
lg Schuladmin

**Comment by SlrG** [comment]
@schuladmin 
Ich helfe gerne, wenn ich kann. Leider habe ich von Intune keine Ahnung. Aber: Die Veyon Konfiguration für den Service befindet sich in der Registry. Der Pfad müsste glaube ich `HKEY_LOCAL_MACHINE\SOFTWARE\Veyon Solutions\Veyon\` sein.  Laut google kennt Intune auch Erkennungsregeln für die Registry. Theoretisch sollte es damit funktionieren?!

Die Konfiguration für den Master ist eine Datei. Sie liegt im '\Users\XYZ\Appdata/Roaming/Veyon` Verzeichnis des jeweiligen Benutzers.

**Comment by schuladmin** [comment]
@SirG
Danke, ja Intune bietet da auch eine Erkennungsregel für die Registry an. Das werde ich bei Gelegenheit einmal probieren, muss mich da aber erst einmal ein wenig einlesen. Bei der Registry kenn ich mich überhaupt nicht aus (man muss nicht alles selber machen, mein Techniker braucht ja auch Arbeit ;-)). Ich lasse beim Import der Konfiguration bis dahin einfach ein leeres Textfile in den Schlüssel-Ordner mitkopieren, das dient dann als Erkennungs-File. Ist zwar nicht elegant, aber funkioniert ;-) Die Master-Config-Datei hab ich schon gefunden, die wird auf den Lehrerrechnern ihren Dienst machen ... Herzlichen Dank nochmals für deine Tipps! 
lg Schuladmin

**Comment by schuladmin** [comment]
Update: Mittlerweile habe ich die Probleme gelöst: Die automatisierte Installation via Intune auf meine Rechner in der Testumgebung funktioniert - Veyon läuft einwandfrei, alles bestens.
Was war das Problem? In Intune kann man die Installation systembezogen oder userbezogen durchführen. Bis jetzt haben alle meine Apps, die ich systembezogen installieren ließ, funktioniert - nur Veyon braucht die userbezogene Variante! Wenn man das weiß, geht das in null komma nichts!
ABER: Leider bringe ich so nur die Veyon Version 4.7.5 zum Laufen. Sobald ich die 4.8.3 installieren möchte, geht gar nichts - rote Bildschirme ...

**Comment by schuladmin** [comment]
Update: Nach den Sommerferien wollte ich alles auf meine Schülerrechner ausrollen - und es klappt wieder nicht! ich bin echt ratlos. Hab nichts verändert ...
