### ISSUE TITLE
no access to ubuntu 22.04 joined in samba ad dc with sssd

### ISSUE THREAD

**Issue by stephanmartin** [veyon/veyon#918]
Hi everybody,
I have a domain based on a samba ad dc server
I joined ubuntu 22.04 workstations to the domain with sssd but I can't access these with master veyon on a windows 10 computer.
I think I have to use a custom Pam service to authenticate the users but I don't know what to do.

**Comment by stephanmartin** [comment]
I answer myself : it's not a problem of custom pam service.
The problem is wayland : I deactivate it and now veyon master can access the ubuntu workstations

**Comment by tobydox** [comment]
Thanks for reporting back!
