### ISSUE TITLE
Students can get around lock command

### ISSUE THREAD

**Issue by bridgec** [veyon/veyon#92]
If you send a lock command to a student PC the padlock appears onscreen.
The student is able to press the windows key to bring up the start menu, and even then close the lock app(right clicking the app on the task bar and close).

**Comment by tobydox** [comment]
Did you reboot the computer after installing Veyon? Because a key interception driver is installed which so far worked on all installations with Windows 7 to 10.

**Comment by bridgec** [comment]
Yes rebooted the PC after installation.  Student computer is windows 10.

**Comment by ideamk** [comment]
![screenshot](https://user-images.githubusercontent.com/7419359/29743372-225649de-8aaa-11e7-96ee-31461782f1cb.png)
Windows 10 Pro 1607, Alt+Tab, Ctrl+Esc, Win-key, Ctrl+Alt+Del is work, Task manager is run, taskbar work, lock app close easily. Domain user, not admin privileges.
Veyon compile from source, version 3.99.7.24 both service and master interface, rebooted the PC after installation.

**Comment by Treeek** [comment]
Hello there,
I think what could be the problem is that InputDeviceBlocker is using the "interception.h" header, I can't find it on the core/include/ folder.  
Is the interception.h file imported as a default library?

**Comment by tobydox** [comment]
Did you try the official Windows installers, i.e. not compiled from source on your own?

**Comment by ideamk** [comment]
@tobydox i tried clean install official (from "releases" page) windows installers (3.99.7.0), and got these problem again.

**Comment by binhuo** [comment]
I have the same problem, have you found a solution?

**Comment by shadowserge** [comment]
Just wanted to add that my students have found that the special shortcut keys in the keyboard still work after being locked. i.e. pressing the calculator, home, or mail buttons opens an instance of the corresponding apps. The keyboard and mouse remain locked, but it still provides enough of a distraction.

This is on version 4.0.1, Windows 10 and logitech k200 keyboards

**Comment by bacsom** [comment]
It is the way since iTalc :-( Our workaround for CTRL-ALT-DEL is to disable the taskmanager and other options from the lock screen. This way the students can't run or shutdown programs.

**Comment by tobydox** [comment]
Thank you all for your feedback! Recent versions of Veyon should properly lock keyboards (we have a fix regarding special keys such as calculator in 4.0.2). If you have special keyboards with special drivers and/or software (e.g. Logitech) which is directly talking with the hardware (i.e. bypassing the input device driver) I'm afraid there's nothing we can do about it :-/
