### ISSUE TITLE
Benachrichtigung bei Fernzugriff anzeigen - lässt sich nicht ausschalten

### ISSUE THREAD

**Issue by schuladmin** [veyon/veyon#925]
Hallo,
ich habe in meiner Testumgebung Veyon 4.8.2 installiert, läuft alles soweit gut. Wenn ich mit dem Master auf meine Testgeräte zugreife ("Beobachten"), erscheint am Client die Meldung, dass derzeit ein Fernzugriff stattfindet.
Also habe ich den entsprechenden Haken im Configurator auf meinem Master-Rechner rausgenommen (und auch "anwenden" gedrückt), die Konfiguration nochmals exportiert und auf den Clients importiert. Die Konfiguration ist auf den Clients richtig angekommen (im Configurator am Client ist der Haken auch weg).  Aber sobald ich mit dem Master den Client beobachte, erscheint die Meldung trotzdem...
Hab ich da was übersehen?
lg Schuladmin

**Comment by SlrG** [comment]
@schuladmin 
Hast Du den Veyon Dienst nach der Konfigurationsänderung neu gestartet? Der Configurator macht das automatisch. veyon-cli aber, glaube ich, nicht. Dort musst Du erst noch ein `"C:\Program Files\Veyon\veyon-cli.exe" service restart` hinterher schieben.

**Comment by schuladmin** [comment]
Danke für den Tipp. Nein, ich hab den Dienst nicht extra neu gestartet. Heute nach dem Hochfahren passt es aber, d.h. der "Neustart" des Dienstes im Rahmen des Hochfahrens hat anscheinend ausgereicht ;-)
Danke!
