### ISSUE TITLE
Does not compile on ubuntu 16.04 (Mate)

### ISSUE THREAD

**Issue by lebowski42** [veyon/veyon#93]
Hi,

i try to install veyon on Ubuntu 16.04 Mate. I did:

`apt-get -y install g++ make cmake qtbase5-dev qtbase5-dev-tools qttools5-dev qttools5-dev-tools xorg-dev libxtst-dev libjpeg-turbo8-dev zlib1g-dev libssl-dev libpam0g-dev liblzo2-dev libqca2-dev libqca-qt5-2-dev libldap2-dev libsasl2-dev`

and then 

`cd /opt/veyon &&
mkdir build &&
cd build &&
cmake .. &&
make -j4
`

Then i get this output and error

> Veyon build summary
> --------------------
> * Version                     : 3.99.7.0 (3.99.7)
> * Install prefix              : /usr/local
> * Build type                  : relwithdebinfo
> * Platform                    : x86_64 (x86_64-linux-gnu)
> * Compile flags               :  -Wall  (CXX:  -Wall -fno-exceptions -std=c++11 )
> 
> -- Configuring done
> CMake Error at core/CMakeLists.txt:73 (ADD_LIBRARY):
>   Cannot find source file:
> 
>     /opt/veyon/3rdparty/libvncserver/libvncclient/cursor.c
> 
>   Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
>   .hxx .in .txx
> 
> 
> CMake Error at cmake/modules/BuildPlugin.cmake:23 (ADD_LIBRARY):
>   Cannot find source file:
> 
>     /opt/veyon/3rdparty/kldap/src/ber.cpp
> 
>   Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
>   .hxx .in .txx
> Call Stack (most recent call first):
>   plugins/ldap/CMakeLists.txt:39 (BUILD_PLUGIN)
> 
> 
> CMake Error at cmake/modules/BuildPlugin.cmake:23 (ADD_LIBRARY):
>   Cannot find source file:
> 
>     /opt/veyon/3rdparty/x11vnc/src/appshare.c
> 
>   Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
>   .hxx .in .txx
> Call Stack (most recent call first):
>   plugins/vncserver/x11vnc-builtin/CMakeLists.txt:36 (BUILD_PLUGIN)
> 
> 
> CMake Error: CMake can not determine linker language for target: veyon-core
> CMake Error: Cannot determine link language for target "veyon-core".
> CMake Error: CMake can not determine linker language for target: ldap
> CMake Error: Cannot determine link language for target "ldap".
> CMake Error: CMake can not determine linker language for target: builtin-x11vnc-server
> CMake Error: Cannot determine link language for target "builtin-x11vnc-server".
> -- Generating done
> -- Build files have been written to: /opt/veyon/build
> Scanning dependencies of target he.qm
> Scanning dependencies of target zh_CN.qm
> Scanning dependencies of target es_ES.qm
> Scanning dependencies of target fr.qm
> [  1%] Generating ../core/resources/zh_CN.qm
> [  1%] Generating ../core/resources/es_ES.qm
> [  1%] Generating ../core/resources/fr.qm
> [  1%] Generating ../core/resources/he.qm
> Updating '/opt/veyon/core/resources/he.qm'...
> Updating '/opt/veyon/core/resources/zh_CN.qm'...
>     Generated 198 translation(s) (198 finished and 0 unfinished)
>     Ignored 382 untranslated source text(s)
>     Generated 209 translation(s) (27 finished and 182 unfinished)
>     Ignored 220 untranslated source text(s)
> Updating '/opt/veyon/core/resources/es_ES.qm'...
>     Generated 638 translation(s) (638 finished and 0 unfinished)
> Updating '/opt/veyon/core/resources/fr.qm'...
>     Generated 626 translation(s) (626 finished and 0 unfinished)
> [  1%] Built target zh_CN.qm
> [  1%] Built target he.qm
> [  1%] Built target es_ES.qm
> Scanning dependencies of target mn.qm
> [  1%] Built target fr.qm
> Scanning dependencies of target fi.qm
> [  2%] Generating ../core/resources/mn.qm
> [  3%] Generating ../core/resources/fi.qm
> Scanning dependencies of target pl.qm
> Scanning dependencies of target ru.qm
> Updating '/opt/veyon/core/resources/mn.qm'...
>     Generated 424 translation(s) (424 finished and 0 unfinished)
> Updating '/opt/veyon/core/resources/fi.qm'...
>     Generated 184 translation(s) (13 finished and 171 unfinished)
>     Ignored 245 untranslated source text(s)
> [  4%] Generating ../core/resources/pl.qm
> [  4%] Built target mn.qm
> [  4%] Generating ../core/resources/ru.qm
> Updating '/opt/veyon/core/resources/pl.qm'...
>     Generated 188 translation(s) (13 finished and 175 unfinished)
>     Ignored 241 untranslated source text(s)
> Updating '/opt/veyon/core/resources/ru.qm'...
> [  4%] Built target fi.qm
>     Generated 424 translation(s) (424 finished and 0 unfinished)
> [  4%] Built target pl.qm
> Scanning dependencies of target pt_BR.qm
> [  4%] Built target ru.qm
> Scanning dependencies of target ar.qm
> Scanning dependencies of target veyon.qm
> [  4%] Generating ../core/resources/pt_BR.qm
> [  4%] Generating ../core/resources/ar.qm
> [  4%] Generating ../core/resources/veyon.qm
> Updating '/opt/veyon/core/resources/pt_BR.qm'...
>     Generated 256 translation(s) (256 finished and 0 unfinished)
>     Ignored 347 untranslated source text(s)
> Updating '/opt/veyon/core/resources/ar.qm'...
>     Generated 402 translation(s) (401 finished and 1 unfinished)
>     Ignored 27 untranslated source text(s)
> Updating '/opt/veyon/core/resources/veyon.qm'...
>     Generated 0 translation(s) (0 finished and 0 unfinished)
>     Ignored 660 untranslated source text(s)
> Scanning dependencies of target ko_KR.qm
> [  4%] Built target pt_BR.qm
> [  4%] Built target ar.qm
> [  4%] Built target veyon.qm
> [  4%] Generating ../core/resources/ko_KR.qm
> Scanning dependencies of target cs.qm
> Updating '/opt/veyon/core/resources/ko_KR.qm'...
>     Generated 638 translation(s) (638 finished and 0 unfinished)
> Scanning dependencies of target uk.qm
> [  4%] Generating ../core/resources/cs.qm
> Scanning dependencies of target it_IT.qm
> [  4%] Built target ko_KR.qm
> Updating '/opt/veyon/core/resources/cs.qm'...
> [  4%] Generating ../core/resources/uk.qm
>     Generated 638 translation(s) (638 finished and 0 unfinished)
> [  4%] Generating ../core/resources/it_IT.qm
> Updating '/opt/veyon/core/resources/uk.qm'...
> [  4%] Built target cs.qm
>     Generated 638 translation(s) (638 finished and 0 unfinished)
> Scanning dependencies of target sv.qm
> Updating '/opt/veyon/core/resources/it_IT.qm'...
>     Generated 254 translation(s) (254 finished and 0 unfinished)
>     Ignored 349 untranslated source text(s)
> [  4%] Built target uk.qm
> [  4%] Built target it_IT.qm
> Scanning dependencies of target hu.qm
> [  4%] Generating ../core/resources/sv.qm
> Updating '/opt/veyon/core/resources/sv.qm'...
>     Generated 332 translation(s) (265 finished and 67 unfinished)
>     Ignored 97 untranslated source text(s)
> Scanning dependencies of target ja_JP.qm
> Scanning dependencies of target tr.qm
> [  5%] Generating ../core/resources/hu.qm
> [  5%] Built target sv.qm
> Updating '/opt/veyon/core/resources/hu.qm'...
>     Generated 398 translation(s) (52 finished and 346 unfinished)
>     Ignored 31 untranslated source text(s)
> [  5%] Generating ../core/resources/ja_JP.qm
> [  5%] Generating ../core/resources/tr.qm
> Updating '/opt/veyon/core/resources/ja_JP.qm'...
>     Generated 90 translation(s) (90 finished and 0 unfinished)
>     Ignored 334 untranslated source text(s)
> [  5%] Built target hu.qm
> Scanning dependencies of target bb.qm
> Updating '/opt/veyon/core/resources/tr.qm'...
>     Generated 349 translation(s) (349 finished and 0 unfinished)
>     Ignored 277 untranslated source text(s)
> [  5%] Built target ja_JP.qm
> Scanning dependencies of target pt_PT.qm
> [  5%] Generating ../core/resources/bb.qm
> [  5%] Built target tr.qm
> Updating '/opt/veyon/core/resources/bb.qm'...
>     Generated 400 translation(s) (286 finished and 114 unfinished)
>     Ignored 29 untranslated source text(s)
> Scanning dependencies of target de_DE.qm
> [  6%] Generating ../core/resources/pt_PT.qm
> [  6%] Built target bb.qm
> Updating '/opt/veyon/core/resources/pt_PT.qm'...
>     Generated 209 translation(s) (71 finished and 138 unfinished)
>     Ignored 220 untranslated source text(s)
> [  6%] Generating ../core/resources/de_DE.qm
> Scanning dependencies of target nn.qm
> Scanning dependencies of target zh_TW.qm
> Updating '/opt/veyon/core/resources/de_DE.qm'...
> [  6%] Built target pt_PT.qm
>     Generated 660 translation(s) (660 finished and 0 unfinished)
> [  7%] Generating ../core/resources/zh_TW.qm
> [  7%] Built target de_DE.qm
> [  7%] Generating ../core/resources/nn.qm
> Updating '/opt/veyon/core/resources/zh_TW.qm'...
> Scanning dependencies of target lt.qm
>     Generated 638 translation(s) (638 finished and 0 unfinished)
> Updating '/opt/veyon/core/resources/nn.qm'...
>     Generated 161 translation(s) (12 finished and 149 unfinished)
>     Ignored 268 untranslated source text(s)
> Scanning dependencies of target sk.qm
> [  7%] Built target zh_TW.qm
> [  7%] Generating ../core/resources/lt.qm
> [  8%] Generating ../core/resources/sk.qm
> Updating '/opt/veyon/core/resources/lt.qm'...
> [  8%] Built target nn.qm
> Scanning dependencies of target el.qm
>     Generated 424 translation(s) (424 finished and 0 unfinished)
> Updating '/opt/veyon/core/resources/sk.qm'...
>     Generated 189 translation(s) (13 finished and 176 unfinished)
>     Ignored 240 untranslated source text(s)
> [  8%] Built target lt.qm
> Scanning dependencies of target nl.qm
> [  8%] Generating ../core/resources/el.qm
> [  8%] Built target sk.qm
> [  8%] Generating ../core/resources/nl.qm
> Updating '/opt/veyon/core/resources/el.qm'...
>     Generated 196 translation(s) (13 finished and 183 unfinished)
>     Ignored 233 untranslated source text(s)
> Scanning dependencies of target sl.qm
> Scanning dependencies of target ca_ES.qm
> Updating '/opt/veyon/core/resources/nl.qm'...
>     Generated 404 translation(s) (404 finished and 0 unfinished)
>     Ignored 25 untranslated source text(s)
> [  8%] Built target el.qm
> [  8%] Generating ../core/resources/ca_ES.qm
> [  8%] Generating ../core/resources/sl.qm
> [  8%] Built target nl.qm
> Updating '/opt/veyon/core/resources/ca_ES.qm'...
>     Generated 424 translation(s) (424 finished and 0 unfinished)
> Scanning dependencies of target veyon-auth-helper
> Scanning dependencies of target kldap_MOC
> make[2]: *** No rule to make target '../3rdparty/kldap/src/ldapsearch.h', needed by 'plugins/ldap/__/__/3rdparty/kldap/src/moc_ldapsearch.cpp'.  Stop.
> CMakeFiles/Makefile2:2923: recipe for target 'plugins/ldap/CMakeFiles/kldap_MOC.dir/all' failed
> make[1]: *** [plugins/ldap/CMakeFiles/kldap_MOC.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> Updating '/opt/veyon/core/resources/sl.qm'...
>     Generated 424 translation(s) (424 finished and 0 unfinished)
> [  8%] Built target ca_ES.qm
> [  8%] Built target sl.qm
> [  9%] Building CXX object service/helpers/CMakeFiles/veyon-auth-helper.dir/VeyonAuthHelper.cpp.o
> [  9%] Linking CXX executable veyon-auth-helper
> [  9%] Built target veyon-auth-helper
> Makefile:149: recipe for target 'all' failed
> make: *** [all] Error 2
>

**Comment by tobydox** [comment]
You forgot to initialize/update external submodule repositories. Please clone the repository again and then type

    cd veyon
    git submodule update --init

(as described in the README ;-)
