### ISSUE TITLE
Replace Comma with Semicolon

### ISSUE THREAD

**Issue by michihuf** [veyon/veyon#939]
![Screenshot 2024-02-22 235844](https://github.com/veyon/veyon/assets/2346087/fd30baaa-d159-4838-a9ab-db24e67c6c9d)

This Comma marked in the screenshot took me some hours, please change to Semicolon.

BTW Veyon 4.8.3 works awesome, thanks!

**Comment by tobydox** [comment]
Thanks for reporting the inconsistent example! The fix will be included in Veyon 4.8.4.
