### ISSUE TITLE
Can't access https://anongit.kde.org/kldap.git

### ISSUE THREAD

**Issue by lebowski42** [veyon/veyon#94]
Maybe this not an issue for this project. But trying to update the submodlues, i can't access

https://anongit.kde.org/kldap.git/

Maybe this is temporary or is there another repo to use.

**Comment by tobydox** [comment]
This seems to be a temporary issue as the URL is officially listed at https://cgit.kde.org/kldap.git/

**Comment by lebowski42** [comment]
Still not working. Is there a fork of kldap?

**Comment by tobydox** [comment]
Cloning works here. Do you still have problems?

**Comment by lebowski42** [comment]
I still get an error:
`
/opt/veyon# git submodule update --init
Cloning into '3rdparty/kldap'...
fatal: unable to connect to anongit.kde.org:
anongit.kde.org: Name or service not known

fatal: clone of 'git://anongit.kde.org/kldap.git' into submodule path '3rdparty/kldap' failed
`

**Comment by tobydox** [comment]
Something must be wrong with your DNS setup. The host anongit.kde.org resolves properly here (159.203.184.29) and also https://mxtoolbox.com/SuperTool.aspx?action=a%3aanongit.kde.org&run=toolpage indicates no problems.

Starting with the next release candidate DEB packages for Debian 9 and Ubuntu 16.04+ will be available for download.
