### ISSUE TITLE
Screen recording

### ISSUE THREAD

**Issue by blonkm** [veyon/veyon#947]
It would be nice to have a way to record the screen(s) to a video file. If anyone knows a way to do this let me know.
I could use the game bar recorder, but it requires me to start it on every screen, and the files go to the student's pc. 
If I screen record the overview screen on my own pc the text is not readable.

**Comment by mrjarbenne** [comment]
You might want to check out this ScreenRecorder Addon. Looks like it does exactly what you need: 

https://veyon.io/en/addons/#screenrecorder

**Comment by tobydox** [comment]
As mentioned by @mrjarbenne the requested feature is available in the commercial ScreenRecorder add-on.

**Comment by blonkm** [comment]
> It would be nice to have a way to record the screen(s) to a video file. If anyone knows a way to do this let me know. I could use the game bar recorder, but it requires me to start it on every screen, and the files go to the student's pc. If I screen record the overview screen on my own pc the text is not readable.

After considerable experimentation, I have a manual solution now. I use ffmpeg on a shared drive, and a VBScript file that I start using 'Start Application' in Veyon. This starts a recording. Some notes: using mp4 the file will corrupt when ended prematurely (since it needs a moov atom at the end), so I am recording to avi. I use 1fps, which keeps the file at about 60MB per hour. I don't know how well the add-on works, but we are planning on buying that as well.
