### ISSUE TITLE
CLI - Config import impossible !!

### ISSUE THREAD

**Issue by sa3D0UD** [veyon/veyon#948]
Hi,

When I try to import a JSON configuration file (previously exported) by CLI, I get the following error : 

veyon-cli config import veyon-config-26042024.json
[ERROR] The configuration is not writable. Please check your permissions !

Can you help me, please ?

Thank's.

OS used : Ubuntu 22.04

**Comment by tobydox** [comment]
This looks like a permission problem. Are you running the import command with root/administrative privileges?
