### ISSUE TITLE
client thumbnails not showing on Veyon Master

### ISSUE THREAD

**Issue by lincdeckard** [veyon/veyon#95]
Hello,

I've just migrated 5 classrooms from iTalc to Veyon and everything seems to be working fine apart from the client thumbnails not showing up on the teacher's master window. 

The computers are on an AD running windows 10pro x64 as well as the teacher's machine and my admin's machine which monitors both teachers and students. 

The admin machine does not display thumbnails as well. I'm using Veyon through Logon auth method. 

Any tips on what might be the issue? 

Cheers

![image](https://user-images.githubusercontent.com/31446430/29829932-9f702b26-8cd8-11e7-9822-474d2ccf3ae4.png)

**Comment by ideamk** [comment]
Workaround: in Veyon Configurator uncheck option in section Master: "Automatically adjust computer thumbnail size at start"

**Comment by lincdeckard** [comment]
@ideamk Thank you! That solved the issue.

Cheers!

**Comment by ideamk** [comment]
@tobydox is bug likely due to thumbnail size ajust before open main window master-interface, and retrieve incorrect window-size for calculate thumbnail size.
