### ISSUE TITLE
Import der Konfiguration - Probleme bei der automatisierten Installation via Intune

### ISSUE THREAD

**Issue by schuladmin** [veyon/veyon#957]
Hallo,
ich versuche Veyon via Intune auf die Schüler-Rechner zu verteilen. Die Installation des Clients via Intune funtioniert prinzipiell. Aber ein Problem in zweierlei Ausführung taucht auf:

1. In meiner Testumgebung habe ich zwei Rechner, bei denen nach der automatisierten Installation der Dienst nicht läuft und auch nicht händisch im Konfigurator eingeschaltet werden kann. Fehlermeldung: Die Autostart-Einstellung für den Veyon-Dienst konnte nicht geändert werden. Bei diesen beiden Geräten funktioniert auch nicht der automatisierte Import der Konfiguration bzw. des Schlüssels. Händischer Import von Konfiguration und Schlüssel funktioniert. Das Problem bleibt aber, dass der Dienst nicht startet / gestartet werden kann. Erst wenn ich den Client händisch installiere, passt alles. Auch der Dienst läuft und der Master hat Zugriff.

2. Bei den zwei anderen Rechnern kommt die Konfiguration und auch der Schlüssel automatisiert im Configurator an, ich kann alles sehen, alles ist so eingestellt, wie es sein soll. Aber der Master sieht nur 2 rote Bildschirme. Nur wenn ich den Client händisch installiere, hat der Master Zugriff. 

Damit das überhaupt läuft, muss auch der Master händisch installiert werden (ist kein Problem, hab nur 12 Rechner, die Master werden). Aber 170 Clients sollten schon automatisiert gehen. Übrigens: Ich habe mich auch mit verschiedenen Veyon-Versionen gespielt: Mit 4.7.5. bekomm ich das händisch zum Laufen, mit den 4.8.-Versionen geht leider gar nichts :-(

Also scheint es irgendeinen Unterschied zu geben, dass die automatisierte Installation nicht ident mit der händischen ist. Obwohl das selbe Installationsfile verwendet wird. 

Bitte, weiß jemand Rat?

**Comment by schuladmin** [comment]
Update: Mittlerweile habe ich die Probleme gelöst: Die automatisierte Installation via Intune auf meine Rechner in der Testumgebung funktioniert - Veyon läuft einwandfrei, alles bestens. 
Was war das Problem? In Intune kann man die Installation systembezogen oder userbezogen durchführen. Bis jetzt haben alle meine Apps, die ich systembezogen installieren ließ, funktioniert - nur Veyon braucht die userbezogene Variante! Wenn man das weiß, geht das in null komma nichts!
ABER: Leider bringe ich so nur die Veyon Version 4.7.5 zum Laufen. Sobald ich die 4.8.3 installieren möchte, geht gar nichts - rote Bildschirme ...
Weiß jemand,woran das liegen könnte, dass die aktuellen Versionen sich da anders verhalten?

**Comment by schuladmin** [comment]
Update: Nach den Sommerferien wollte ich die funktionierende Version auf weitere Rechner ausrollen - und es funktioniert wieder nicht, obwohl ich nichts verändert habe ... ich bin echt ratlos ...
Ausrollung des Masters und des Clients bzw. auch der Schlüssel funktioniert klaglos. Das funzt. Nur die Ausrollung der **Konfiguration macht Probleme**:
Wenn ich die Konfiguration im Configurator importiere, passt alles. 
Wenn ich mein Script, das ich über Intune ausrollen will, über die Kommandozeile laufen lasse (Admin-Rechte), passt auch alles. 
Kommandozeile ohne Admin-Rechte geht nicht, obwohl der User Admin ist.
Die Installation über Intune sollte lt. Microsoft auch immer Admin-Rechte haben.
Mein Script (als Batch-Datei) schaut so aus:

cd C:\Program Files\Veyon
veyon-wcli config import MyConfig.json

Intune meldet, dass es installiert wurde, wenn ich in den Configurator schaue, hat sich aber genau gar nichts verändert...
Ich hab in der Zwischenzeit die Konfiguration schon zurückgesetzt, alles deinstalliert, Registrierungsschlüssel gelöscht ... nichts nützt! Auch bei frisch aufgesetzten Rechnern dasselbe Ergebnis... - der Import funktioniert nicht.
Hat jemand eine Idee, wo mein Fehler stecken könnte?
Bitte dringend um Hilfe!

**Comment by tobydox** [comment]
Passt evtl. der Pfad zur JSON-Datei nicht (Thema Platzhaltervariablen wie %cd% etc.?) oder ist die Datei nicht lesbar? Macht es einen Unterschied, wenn man "veyon-cli" statt "veyon-wcli" verwendet?

**Comment by schuladmin** [comment]
Pfad ist in Ordnung. cli oder wcli macht keinen Unterschied. Via Befehlszeile klappt der Import. Via Intune klappt der Import derzeit bei manchen Geräten, bei manchen nicht ... ist für mich nicht greifbar ... habe das alles mit V4.7.5 getestet, da ich die 4.8 nicht zum Laufen gebracht habe. Habe gerade die neue 4.9 entdeckt und versuche es nun damit.
Erste Erkenntnis mit 4.9: Auf einem Rechner funktioniert die Ablösung (automatische Deinstallation der 4.7.5, automatische Installation der 4.9) incl Import von Schlüssel und Koniguration via Intune - auf dem Rechner hat zuvor das alles auch mit V4.7.5 geklappt.
Bei zwei Rechnern, wo es vorher schon nur zum Teil geklappt hat, war auch die Ablösung ein Problem: Configurator konnte nicht gestartet werden, Fehlermeldungen ... Deinstallation war auch erst möglich, als ich über die Dienste den Veyon-Dienst beendet habe. Erneute Installation und Import der Schlüssel und Konfiguration via Intune, hat geklappt, Konfiguration und Schlüssel scheinen im Konfigurator richtig auf. Im Master gibt's aber nur rote Bildschirme ... (so wie damals bei 4.8. ...)
ICh versuche es ein andermal nochmals ...

**Comment by schuladmin** [comment]
Update: Nachdem ich auch V4.9. in der Testumgebung nicht stabil zum Laufen bekommen habe, habe ich die Konfiguration zurückgesetzt und eine neue Konfigurationsdatei erstellt (auf die Idee hätte ich schon früher kommen können) - und siehe da: Auf einmal scheint es zu klappen! Es sieht so aus, als ob die Konfigurationsdatei, mit der ich lange gearbeitet habe, defekt war. Es scheint, als ob das der Grund war, warum es mal funktioniert hat und dann wieder nicht oder nur bei manchen Rechnern. 
Verteilung über Intune klappt reibungslos, Konfiguration wird korrekt übernommen.
Am Montag wird in der Schule getestet und hoffentlich danach gleich auf eine Testklasse ausgerollt. Ich bin jetzt wirklich guter Dinge, dass ich's geschafft habe ;-) - ich werde berichten!

**Comment by schuladmin** [comment]
Update: Es hat geklappt! Veyon 4.9. läuft in beiden Klassen, die ich gestern getestet habe. Endlich! Auf die Idee mit der neuen Konfigutaionsdatei hätte ich schon viel früher kommen können ... hatte aber Scheu, alle bereits angelegten Schüler nochmals anlegen zu müssen... hab's jetzt mit einer CSV gelöst, geht ratzfatz!
Fazit:
In meinem Setting (170 BYOD-Schülerrechner, Win11,  WLAN, nicht in der Domain, nur in Intune) rolle ich über Intune den Client (bzw. Master) getrennt vom Key und wieder separat die Konfiguration aus (Systembezogene Installation). So kann ich auf etwaige Änderungen bei den Schülern (Abgang, Neuzugang) besser reagieren. Die CSV mit den Standorten und Computern via Kommandozeile (siehe Handbuch - veyon-cli networkobjects import) in die Konfiguration einspielen, Konfiguration neu ausrollen. Somit bleibt der Aufwand bei Schüleränderungen überschaubar.
Ich möchte mich herzlich bedanken für die Tipps, die ich hier im Forum erhalten habe. Ich habe sehr viel gelernt. Danke an die Menschen, die Veyon entwickeln und den Schulen zur Verfügung stellen. Ein wertvolles Tool - und seit Jahren in einem anderen Setting - EDV-Räume, in der Domain, Anmeldeauthentifizierung, LAN, Win10 - bereits lange Zeit im Einsatz! Danke!
