### ISSUE TITLE
Translation of the authentication window in the Veyon Configurator

### ISSUE THREAD

**Issue by rautyrauty** [veyon/veyon#967]
https://app.transifex.com/veyon-solutions/veyon/viewstrings/#ru/$/170622386?q=text%3A'is+required'
https://github.com/veyon/veyon/blob/master/configurator/data/io.veyon.veyon-configurator.policy.in
There is no way to translate this window:
![изображение](https://github.com/user-attachments/assets/eebae661-b4c4-4036-aa2d-44476e3d30e9)
Please fix it or tell me how to do it (an example of commit will be enough).

**Comment by tobydox** [comment]
Indeed the language specific messages were missing in the PolicyKit file. Please see https://github.com/veyon/veyon/commit/60cd6867a3d99e6b6e4c8c9c353cd8762f483159 for details on how to add translations. The same applies to the desktop files (`veyon-master.desktop.in` and `veyon-configurator.desktop.in`)
