### ISSUE TITLE
Students can stop the Veyon service

### ISSUE THREAD

**Issue by karamazov451** [veyon/veyon#97]
Students can stop the Veyon service on the Configurator window: Service -> Stop Service.

**Comment by tobydox** [comment]
Only if they have administrative privileges. Please check the settings/privileges of your student accounts ;-)

**Comment by neahstupid** [comment]
How tf do i remove veyron from my computer

**Comment by acromata** [comment]
My man based

**Comment by MrBeam89** [comment]
> How tf do i remove veyron from my computer

That's the neat part : **You can't**

**Comment by massblabla** [comment]
> > How tf do i remove veyron from my computer
> 
> That's the neat part : **You can't**

I saw "Uninstall Veyon" when I'm searching Veyon on the Windows search bar. I'm a student.

**Comment by MrBeam89** [comment]
> > > How tf do i remove veyron from my computer
> > 
> > 
> > That's the neat part : **You can't**
> 
> I saw "Uninstall Veyon" when I'm searching Veyon on the Windows search bar. I'm a student. Didn't tried that yet, scared.

The system may be misconfigured, but even if you tried to open the uninstaller, it would probably ask you for administrator privileges or straight up say you don't have authorized access. I haven't tried this, and you probably shouldn't.

**Comment by massblabla** [comment]
I messed up

Pada Sen, 14 Okt 2024 pukul 05.19 MrBeam89 ***@***.***>
menulis:

**Comment by JuanKW** [comment]
What if the student already have admin privilege? how to just use password instead in order to manage the veyon

**Comment by drakoisback** [comment]
Try to end task the process it works i try it
