### ISSUE TITLE
I can not unlock an individual computer

### ISSUE THREAD

**Issue by mrkaban** [veyon/veyon#98]
Hello, I can not unlock an individual computer. If you select a specific computer and click the lock, it will be successfully blocked, but the unlock option does not appear when you click it again. The problem can be circumvented if you lock the entire class and then unlock the entire class.

**Comment by tobydox** [comment]
With latest version (3.99.7 or newer) you should be able to unlock individual computers by right click. The "Lock computer" item in the context menu should be to "Unlock computer" for locked computers.
