### ISSUE TITLE
Installation problem (No administrator permissions)

### ISSUE THREAD

**Issue by abdallahlisserbtssiolla** [veyon/veyon#985]
Good evening,
I will explain my problem to you.
Unfortunately, I no longer have permissions on my computer and I would like to install veyon but it is impossible. Unfortunately I can't reset the computer, I tried everything bios, settings, remove bios. If you have a way without administrator permissions I'm interested and I really need it please

**Comment by tobydox** [comment]
Installation is possible with Admin privileges only, I'm sorry :-)
