### ISSUE TITLE
Linux Mint Installation Instructions

### ISSUE THREAD

**Issue by lavos3rd** [veyon/veyon#99]
Sorry for asking a stupid question here, I'm kind of stuck in this part:
> Setup a Veyon client
> ......
> 1. Add the appropriate command ("veyon-service &") to /etc/X11/xinit/xinitrc
> ......

could you guys elaborate?
For Information Purposes
Planned Server: Windows 10 and/or Linux Mint 18.1
Clients: Linux Mint 18.1

**Comment by tobydox** [comment]
It's about adding veyon-service to session autostart but not as usual using XDG autostart file because it should run as root so users can't kill it. Did you manage to make it run properly as root?

**Comment by orion777** [comment]
I added veyon-service in autostart (add usr/local/bin/veyon-service to parameters>session and starting)
It works perfectly. Veyon-service run each time a session is starting.

**Comment by lavos3rd** [comment]
@tobydox Sorry for the late reply: Yes, I have managed to run it properly as root, if I manually run the client program.

@orion777 I'm still a newbie in Linux Mint, thanks for this info

**Comment by tobydox** [comment]
Sorry for the late reply. Did you get it work in the meanwhile? You can also checkout Veyon 4.1 which has full systemd support and should resolve such issues on Linux.
